force-app/main/default/objects/Bundle_Product__c/Bundle_Product__c.object-meta.xml
<CustomObject>
    <label>Bundle Product</label>
    <nameField>
        <label>Bundle Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundle Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Product__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Type__c</field>
            <operation>equals</operation>
            <value>Bundle</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Products (Bundle)</relationshipLabel>
    <relationshipName>Bundle_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bundle_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.TI_Id__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Products</relationshipLabel>
    <relationshipName>Bundle_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <inlineHelpText>Date of last enrollment as related to campaign</inlineHelpText>
    <label>Enrollment Date</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Campaign.Project_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cvent_Registration_Log__c/Cvent_Registration_Log__c.object-meta.xml
<CustomObject>
    <label>Cvent Registration Log</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Cvent Registration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Registration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cvent_Registration_Log__c/fields/Retrieved__c.field-meta.xml
<CustomField>
    <fullName>Retrieved__c</fullName>
    <label>Retrieved</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <inlineHelpText>Completion for Elearning, ILT</inlineHelpText>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <label>Enrollment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Is_free__c.field-meta.xml
<CustomField>
    <fullName>Is_free__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/isBootcampbundle__c.field-meta.xml
<CustomField>
    <fullName>isBootcampbundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isBootcampbundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Enrollments (Collection)</relationshipLabel>
    <relationshipName>Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edx</fullName>
            </value>
            <value>
                <fullName>Panorama</fullName>
            </value>
            <value>
                <fullName>SugarCRM</fullName>
            </value>
            <value>
                <fullName>TI</fullName>
            </value>
            <value>
                <fullName>TI SCORM</fullName>
            </value>
            <value>
                <fullName>TI Panorama</fullName>
            </value>
            <value>
                <fullName>TI Other</fullName>
            </value>
            <value>
                <fullName>TI Purchase</fullName>
            </value>
            <value>
                <fullName>QuickStart</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Cvent_Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Event_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Id of the corresponding Cvent Event record</description>
    <externalId>true</externalId>
    <inlineHelpText>The Id of the corresponding Cvent Event record</inlineHelpText>
    <label>Cvent Event Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Event&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Source_Detail_p__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Detail_p__c</fullName>
    <label>Lead Source Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Email Marketing</fullName>
            </value>
            <value>
                <fullName>Organic Search</fullName>
            </value>
            <value>
                <fullName>Google Ads</fullName>
            </value>
            <value>
                <fullName>Bing</fullName>
            </value>
            <value>
                <fullName>Meta</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Reddit</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Drift</fullName>
            </value>
            <value>
                <fullName>HubSpot</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Whitepaper</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Experience</fullName>
            </value>
            <value>
                <fullName>In-person Event</fullName>
            </value>
            <value>
                <fullName>Virtual Event</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Direct Traffic</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Edx</fullName>
            </value>
            <value>
                <fullName>Cvent</fullName>
            </value>
            <value>
                <fullName>LF Auth0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Bootcamp_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Bootcamp_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bootcamp Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/TI_Id__c.field-meta.xml
<CustomField>
    <fullName>TI_Id__c</fullName>
    <externalId>true</externalId>
    <label>TI Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Course</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>E-Learning</fullName>
            </value>
            <value>
                <fullName>Instructor-Led</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AI, ML, Data &amp; Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud, Containers &amp; Virtualization</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps, CI/CD &amp; Site Reliability</fullName>
    </customValue>
    <customValue>
        <fullName>IoT &amp; Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>Linux Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Networking &amp; Edge</fullName>
    </customValue>
    <customValue>
        <fullName>Open Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source &amp; Compliance Best Practices</fullName>
    </customValue>
    <customValue>
        <fullName>Privacy &amp; Security</fullName>
    </customValue>
    <customValue>
        <fullName>Quantum Computing</fullName>
    </customValue>
    <customValue>
        <fullName>Safety-Critical Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>System Administration</fullName>
    </customValue>
    <customValue>
        <fullName>System Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Visual Effects</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Application Development</fullName>
    </customValue>
    <customValue>
        <fullName>Cybersecurity</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
        <isActive>false</isActive>
        <label>Security</label>
    </customValue>
    <customValue>
        <fullName>Node.js Development</fullName>
        <isActive>false</isActive>
        <label>Node.js Development</label>
    </customValue>
    <customValue>
        <fullName>Open Source Best Practices</fullName>
        <isActive>false</isActive>
        <label>Open Source Best Practices</label>
    </customValue>
    <customValue>
        <fullName>Application Development</fullName>
        <isActive>false</isActive>
        <label>Application Development</label>
    </customValue>
    <description>Technology categories used by training, events, and projects across the LF.  Note that forms in Cvent need to be updated for any label change needed in this value set.</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_Utility.cls
//Test class for UtilityClass
@isTest
public class Test_Utility{
    @testsetup
    public static void createData(){
        Account account = new Account(Name = 'Acme, Inc.');
        insert account;
        Contact contact = new Contact(FirstName = 'Robin', LastName = 'Koehler', AccountId = account.Id);
        insert contact;
        Lead lead = new Lead();
        lead.LastName = 'Test Lead';
        lead.Email = 'testEmail@test.com';
        insert lead;

        Product2 parentProduct = new Product2(Name = 'Test Training Parent Product', productcode = 'parent', isActive = true, Type__c = 'Bundle');
        insert parentProduct;

        Product2 product = new Product2(Name = 'TestP', productcode = 'campaign', isActive = true, TI_Id__c = 'TestTiid');
        insert product;

        Bundle_Product__c bundleProduct = new Bundle_Product__c(Bundle__c = parentProduct.Id, Product__c = product.Id);
        insert bundleProduct;

        Campaign parentCampaign = new Campaign(Name = 'Training Bootcamp 2020', IsActive = TRUE, startDate = System.today() - 1, endDate = System.today() + 30, Product__c = 'Test Training Parent Product');
        insert parentCampaign;
        System.debug('parentCampaign ' + parentCampaign);

        Campaign campaign = new Campaign(Name = 'Test campaign', IsActive = TRUE, ParentId = parentCampaign.id, Type = 'Training');
        insert campaign;

        Enrollment__c enrollment = new Enrollment__c();
        enrollment.Name = 'Test enrollment';
        enrollment.Contact_Name__c = contact.Id;
        enrollment.Product_Name__c = product.Id;
        enrollment.Parent_Product__c = parentProduct.Id;
        enrollment.Is_free__c = true;
        enrollment.Source__c = 'SugarCRM';
        enrollment.Completion_Date__c = System.today() - 1;
        enrollment.isBootcampbundle__c = true;
        enrollment.Enrollment_Date__c = System.today();
        insert enrollment;

        parentProduct.Bootcamp_Campaign__c = true;
        update parentProduct;

        Cvent_Integration__c cventIntegration = TestDataUtils.createCventIntegrationSetting(true);

        
    }

    /*
	 Test Method batch
	 */
	@IsTest
	static void batchDataTest(){
        Project__c project = TestDataUtils.createProject(true, 'The Linux Foundation', 'Event', 'Directed Fund', 'Planned');
		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		Database.executeBatch(new GetEventFromCvent());
		Test.stopTest();
		System.assertEquals(1, [SELECT Id
		                        FROM Event__c
		                        WHERE Cvent_Event_Id__c != null].size(), 'There must be an event');
	}

    @IsTest
	static void getRenewalCloseDate_Test(){

		Utility util = new Utility();
        util.getRenewalCloseDate(Date.newInstance(2021, 11, 18),30);
        util.getRenewalCloseDate(Date.newInstance(2021, 12, 18),30);
        util.getRenewalCloseDate(Date.newInstance(2021, 01, 18),30);



		/* System.assertEquals(1, [SELECT Id
		                        FROM Event__c
		                        WHERE Cvent_Event_Id__c != null].size(), 'There must be an event'); */
	}

    //Test Method for addCampaignMember()
    @isTest
    public static void testData(){
        Campaign campaign = [SELECT Id, Name
                             FROM Campaign
                             WHERE Parent.Name = 'Training Bootcamp 2020'];
        Test.startTest();
        Database.executeBatch(new EnrollmentToCampaignMemberBatch('Test Training Parent Product'));
        Test.stopTest();
        System.assertEquals('Sent', [SELECT id, Status
                                     FROM CampaignMember
                                     WHERE CampaignId = :campaign.Id][0].Status);
    }

    /*
	 Test Method for RetrieveRegistrationsFromCventBatch
	 */
	@isTest
	static void RetrieveRegistrationsFromCventBatchTest(){
		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(true, 'TestSearchId45768', 'Registration');
		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		Database.executeBatch(new RetrieveRegistrationsFromCventBatch());
		Test.stopTest();
		System.assertEquals(1, [SELECT Id
		                        FROM Cvent_Registration_Log__c
		                        WHERE Retrieved__c != null].size(), 'There must be a record');
	}

    @isTest
    public static void getEmailAddresses_Test(){
        User user = TestFactory.getUser();
        Group newGroup = new Group();
        newGroup.Name = 'Test Group';
        newGroup.DeveloperName = 'Test_Group';
        insert newGroup;
        GroupMember newMember = new GroupMember();
        newMember.GroupId = newGroup.Id;
        newMember.UserOrGroupId = user.Id;
        insert newMember;
        List<String> returnAddress = Utility.getEmailAddresses('Test_Group');
        System.assertEquals('standarduser123@testorg.com', returnAddress.get(0), 'Email Address must be standarduser123@testorg.com');
    }

    //Test method for getDependentPicklistValues() and getPickListValuesIntoList()
    @isTest
    public static void general_testMethod(){
        List<String> leadSourcePickListValues = Utility.getPickListValuesIntoList('Lead', 'LeadSource');
        System.assertNotEquals(null, leadSourcePickListValues.size(), 'List must not be null');
        Lead lead = new Lead();
        lead.LastName = 'Lead source test';
        lead.Email = 'test@lead.com';
        insert lead;
        Map<String, List<String>> dependentPicklistValuesMap = Utility.getDependentPicklistValues(SObjectType.Lead, 'LeadSource', 'Lead_Source_Detail_p__c');

    }

    //Test method for updateLeadTechnology()
    @isTest
    public static void updateLeadTechnology_testMethod(){
        List<String> sObjectTechnology = new List<String>{ 'Application Development', 'Blockchain' };
        List<String> strlstLead = new List<String>{ 'System Administration' };
        Lead lead = new Lead();
        lead.LastName = 'Lead source test';
        lead.Email = 'test@lead.com';
        lead.Technology__c = 'System Administration';
        insert lead;
        List<Lead> leadList = Utility.updateLeadTechnology(lead, sObjectTechnology, strlstLead);
        System.assertEquals(true, leadList.get(0).Technology__c.contains('Application Development'), 'Technology of lead must contains Application Development');
    }

    //Test method for updateTechnologyOnContact()
    @isTest
    public static void updateTechnologyOnContact_testMethod(){
        List<String> sObjectTechnology = new List<String>{ 'Application Development', 'Blockchain' };
        List<String> strlstContact = new List<String>{ 'System Administration' };
        Contact contact = new Contact();
        contact.LastName = 'Contact test';
        contact.Email = 'test@contact.com';
        contact.Technology__c = 'System Administration';
        insert contact;
        List<Contact> contactList = Utility.updateTechnologyOnContact(contact, sObjectTechnology, strlstContact);
        System.assertEquals(true, contactList.get(0).Technology__c.contains('Application Development'), 'Technology of contact must contains Application Development');
    }

    //Test method for getFieldNames()
    @isTest
    public static void getFieldNames_testMethod(){
        Utility mergeUtility = new Utility();
        Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Contact.fields.getMap();
        Map<String, Object> returnedMap = mergeUtility.getFieldNames(schemaFieldMap);
        System.assertNotEquals(null, returnedMap);
        /* Map<String, Object> returnMap = mergeUtility.getFieldNames(schemaFieldMap);
         System.assertEquals(true,returnMap.containsKey('CheckboxFields'),'Must must contains CheckboxFields as a key');
         System.assertEquals(true,returnMap.containsKey('FieldNames'),'Must must contains FieldNames as a key'); */
    }

    @isTest
    public static void getLinuxFoundationId_test(){
        Project__c prjLf = new Project__c(Name = 'The Linux Foundation', Status__c = 'Planned', Category__c = 'Directed Fund', Subsidiary_ID__c = 8);
        prjLf.slug__c = 'testlf';
        insert prjLf;
        System.assertEquals(prjLf.Id, Utility.linuxFoundationId, 'Id must match');
        System.assertNotEquals(null, Utility.corporateRecordTypeId, 'Id must not be null');
    }
}