force-app/main/default/objects/Bundle_Product__c/Bundle_Product__c.object-meta.xml
<CustomObject>
    <label>Bundle Product</label>
    <nameField>
        <label>Bundle Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundle Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Product__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Type__c</field>
            <operation>equals</operation>
            <value>Bundle</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Products (Bundle)</relationshipLabel>
    <relationshipName>Bundle_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bundle_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.TI_Id__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Products</relationshipLabel>
    <relationshipName>Bundle_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>false</active>
    <businessProcess>Training</businessProcess>
    <description>Record type for training opportunities</description>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Bill_From__c.field-meta.xml
<CustomField>
    <fullName>Bill_From__c</fullName>
    <label>Bill From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Billfrom_ID__c.field-meta.xml
<CustomField>
    <fullName>Billfrom_ID__c</fullName>
    <label>Billfrom ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Product (Billing Contact)</relationshipLabel>
    <relationshipName>Opportunity_Product5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Text that will be displayed on invoice</description>
    <inlineHelpText>Text that will be displayed on invoice</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Standard Memberships will auto-populate date.</description>
    <inlineHelpText>Standard Memberships will auto-populate date.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Deferred_Revenue_Account__c</fullName>
    <label>NetSuite Deferred Revenue Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Department__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Department__c</fullName>
    <label>NetSuite Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Income_GL_Account__c</fullName>
    <label>NetSuite Income GL Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Revenue_Schedule__c</fullName>
    <label>NetSuite Revenue Schedule</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Skip_NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>Skip_NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, the Purchase History that is created from this line item will not be sent to NetSuite. You probably don&apos;t want this.</description>
    <inlineHelpText>When selected, the Purchase History that is created from this line item will not be sent to NetSuite. You probably don&apos;t want this.</inlineHelpText>
    <label>Skip NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Required</inlineHelpText>
    <label>Start Date*</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Trainings__c.field-meta.xml
<CustomField>
    <fullName>Trainings__c</fullName>
    <label>Training</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
            <value>
                <fullName>01241000001E0UhAAK</fullName>
                <isActive>false</isActive>
                <label>01241000001E0UhAAK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Corporate_Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Product_Description__c</fullName>
    <label>Corporate Product Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NetSuite_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Revenue_Schedule__c</fullName>
    <label>NetSuite Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Revenue_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Course</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>E-Learning</fullName>
            </value>
            <value>
                <fullName>Instructor-Led</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Netsuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>NS Item ID</inlineHelpText>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
            <value>
                <fullName>Straight Line</fullName>
                <isActive>false</isActive>
                <label>Straight Line</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Deferred_Revenue_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>284</fullName>
        <label>Deferred Revenue : Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>282</fullName>
        <label>Deferred Revenue : Deferred Revenue - Membership</label>
    </customValue>
    <customValue>
        <fullName>4494</fullName>
        <label>Deferred Revenue : Deferred Revenue - Directed Funds</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Other</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Membership</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Membership</label>
    </customValue>
    <masterLabel>NetSuite Deferred Revenue Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NetSuite_Revenue_Schedule.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6</fullName>
        <label>Straight Line</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>Directed Fund</label>
    </customValue>
    <customValue>
        <fullName>7164</fullName>
        <label>CP Services</label>
    </customValue>
    <masterLabel>NetSuite Revenue Schedule</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddSubscriptionController.cls
public class AddSubscriptionController {
    
    @AuraEnabled
    public static void addSubscriptionProducts(Integer noOfCertification,Decimal OppAmount,Id opportunityID,List<NewOpportunityProductController.ProductDetailsWrapper> prodDetailWrapper,String selectedCategory/*,Date endDate*/){
        Decimal CertificationAmount = 0;
        Decimal ELearningAmount =0;
        Decimal InstructorLedAmount =0;
        Integer quantity = 1;
        Integer eLearningQuantity = 1;
        if(selectedCategory == 'Subscription'){
            CertificationAmount = 200*noOfCertification ;
            quantity = noOfCertification;
            ELearningAmount = OppAmount-CertificationAmount;
        }
        system.debug('SelectedCategory=>' + selectedCategory);
        Map<Id,Set<String>> productCategoryByBundle = new Map<Id,Set<String>>();
        Opportunity opp = [SELECT Id,CloseDate,Billing_Contact__c FROM Opportunity WHERE ID=:opportunityID];
        List<OpportunityLineItem> items = new List<OpportunityLineItem>();
        Map<String,Product_Details__c> productDetailsByName =productDetailHelper(prodDetailWrapper);
        if(selectedCategory == 'Bundle'){
            productCategoryByBundle = checkBundleProducts(prodDetailWrapper);
        }
        System.debug('productDetailsByName' + productCategoryByBundle);
        String parentId = ''; 
        String parentName = '';
        Boolean IsFutureProductAdded = false;
        for(NewOpportunityProductController.ProductDetailsWrapper wrapper : prodDetailWrapper){
            if(wrapper.selected){
                //Added by priyesh @cloudroute to check whether Future Training product is added
                IsFutureProductAdded = wrapper.productName.contains('Future') && !IsFutureProductAdded ? true : false;

                parentId =wrapper.productID;
                parentName=wrapper.productName;
                items.add(oppLineItemHelper(opp,productDetailsByName.get(wrapper.productName),0,wrapper.productName,1,'',true/*,endDate*/));
            }
        }
        System.debug('Parent=>'+ parentId);
        if(selectedCategory == 'Bundle'){
            Set<String> productTypes = productCategoryByBundle.containskey((Id)parentId) ? productCategoryByBundle.get((Id)parentId) : new Set<String>();
            System.debug('Product Types=>'+ productTypes);
            System.debug('IsFutureProductAdded: ' + IsFutureProductAdded);
            //Added by priyesh @cloudroute to divide amount by 3 if Future Training product is added
            if(IsFutureProductAdded){
                CertificationAmount =  OppAmount/3;
                ELearningAmount = OppAmount/3;
                InstructorLedAmount = OppAmount/3;
            }else if(productTypes.contains('Certification') && productTypes.contains('E-Learning') ){
                CertificationAmount =  OppAmount/2;
                ELearningAmount = OppAmount/2;
            }else if(productTypes.contains('Certification')){
                CertificationAmount =  OppAmount;
            }else if(productTypes.contains('E-Learning')){
                ELearningAmount = OppAmount;
            }else{
                CertificationAmount =  OppAmount/2;
                ELearningAmount = OppAmount/2; 
            }
        }
        if(selectedCategory == 'Subscription' || CertificationAmount !=0){
            OpportunityLineItem oppLineItem = oppLineItemHelper(opp,productDetailsByName.get('Certification'),CertificationAmount,'Certification',quantity,parentId,false/*,endDate*/);
            if(selectedCategory == 'Bundle'){
                oppLineItem.description__c =productDetailsByName.get(parentName).Products__r.Corporate_Product_Description__c;
            }
            items.add(oppLineItem);
        }
        if(selectedCategory == 'Subscription' || ELearningAmount !=0){
             OpportunityLineItem oppLineItem = oppLineItemHelper(opp,productDetailsByName.get('E-Learning'),ELearningAmount,'E-Learning',eLearningQuantity,parentId,false/*,endDate*/);
            if(selectedCategory == 'Bundle'){
                oppLineItem.description__c =productDetailsByName.get(parentName).Products__r.Corporate_Product_Description__c;
            }
            items.add(oppLineItem);
        }
        //Added by priyesh @cloudroute to add the Instructor-Led product if Future Training is added
        if(IsFutureProductAdded && selectedCategory == 'Bundle' && InstructorLedAmount !=0){
             OpportunityLineItem oppLineItem = oppLineItemHelper(opp,productDetailsByName.get('Instructor-Led'),InstructorLedAmount,'Instructor-Led',quantity,parentId,false/*,endDate*/);
            oppLineItem.description__c =productDetailsByName.get(parentName).Products__r.Corporate_Product_Description__c;
            System.debug('oppLineItem for Future prod IL: ' + oppLineItem);
            items.add(oppLineItem);
        }
        insert items;
        
    }    
    
    //this checks what type of products does bundle has
    private static  Map<Id,Set<String>> checkBundleProducts(List<NewOpportunityProductController.ProductDetailsWrapper> prodDetailWrapper){
        Set<Id> bundleIds = new Set<Id>();
        for(NewOpportunityProductController.ProductDetailsWrapper wrapper : prodDetailWrapper){
            System.debug('wrapper: ' + wrapper);
            if(wrapper.selected){
                bundleIds.add(wrapper.productID);
            }
        }
        Map<Id,Set<String>> productCategoryByBundle = new Map<Id,Set<String>>();
        System.debug('bundleIds: ' + bundleIds);
        for(Bundle_Product__c bundleProduct : [SELECT Id,Product__c,Product__r.Type__c,Bundle__c FROM Bundle_Product__c WHERE Bundle__c=:bundleIds]){
            System.debug('bundleProduct: ' + bundleProduct);
            if(!productCategoryByBundle.containsKey(bundleProduct.Bundle__c)){
                productCategoryByBundle.put(bundleProduct.Bundle__c,new Set<String>());
            }
            productCategoryByBundle.get(bundleProduct.Bundle__c).add(bundleProduct.Product__r.Type__c);
        }
        return productCategoryByBundle;
    }
    
    private static Map<String,Product_Details__c> productDetailHelper( List<NewOpportunityProductController.ProductDetailsWrapper> prodDetailWrapper){
        Set<Id> trainingIDs = new Set<Id>();
        Set<Id> productIds = new Set<Id>();
        Map<String,Product_Details__c> productDetailsByName = new Map<String,Product_Details__c>();
        for(NewOpportunityProductController.ProductDetailsWrapper wrapper : prodDetailWrapper){
            System.debug('wrapper PD: ' + wrapper);
            if(wrapper.selected){
                trainingIDs.add(wrapper.trainingID);
                productIds.add(wrapper.productDetailID);
            }
        }        
        if(!trainingIDs.isEmpty()){
            productDetailsByName =getProductDetails(trainingIDs,productIds);
        }
        return productDetailsByName;
    }
    
     private static Map<String,Product_Details__c> getProductDetails(Set<Id> trainingId,Set<Id> productDetailID){
        Map<String,Product_Details__c> productDetailsByName = new Map<String,Product_Details__c>();
        List<Product_Details__c> productDetails = [SELECT ID,Training__c,Training__r.Name,Products__c,Products__r.Name,
                                                   Products__r.Corporate_Product_Description__c,Description__c,
                                                   NetSuite_Class__c,NS_Department__c,NS_Income_GL_Account__c,NS_Deferred_Revenue_Account__c,
                                                   NS_Revenue_Schedule__c,Netsuite_ID__c,Price__c FROM Product_Details__c
                                                   WHERE Training__c =:trainingId AND (ID IN:productDetailID OR Products__r.Name IN ('E-Learning','Certification','Instructor-Led'))];
        for(Product_Details__c prodDetail : productDetails){
            System.debug('prodDetail: ' + prodDetail);
            productDetailsByName.put(prodDetail.Products__r.Name,prodDetail);
        }
        
        return productDetailsByName;
    }
    
    private static OpportunityLineItem oppLineItemHelper(Opportunity opp,Product_Details__c productDetail,Decimal Amount,String productName,Integer quantity,String prodDetail,Boolean skip/*,Date endDate*/){
        System.debug('productName: ' + productName);
        System.debug('productDetail: ' + productDetail);
        OpportunityLineItem oppLineItem = new OpportunityLineItem();
        oppLineItem.Opportunityid = opp.Id;
        oppLineItem.TotalPrice = Amount;
        oppLineItem.Quantity = quantity;
        oppLineItem.Billing_Contact__c = opp.Billing_Contact__c;
        oppLineItem.PricebookEntryId = [SELECT ID FROM PriceBookEntry WHERE PRODuct2.Name = :productName LIMIT 1].ID;
        oppLineItem.Product_Details__c = productDetail.Id;
        oppLineItem.description__c =productDetail.Description__c;        
        oppLineItem.NetSuite_Class__c =productDetail.NetSuite_Class__c;
        oppLineItem.NetSuite_Department__c =productDetail.NS_Department__c;
        oppLineItem.NetSuite_ID__c =productDetail.Netsuite_ID__c;
        oppLineItem.NetSuite_Income_GL_Account__c = productDetail.NS_Income_GL_Account__c;
        oppLineItem.NetSuite_Revenue_Schedule__c = productDetail.NS_Revenue_Schedule__c;
        oppLineItem.NetSuite_Deferred_Revenue_Account__c = productDetail.NS_Deferred_Revenue_Account__c;
        oppLineItem.Training__c = productDetail.Training__c;
        oppLineItem.Bill_From__c = 'The Linux Foundation';
        oppLineItem.Billfrom_ID__c = Utility.linuxFoundationId;
        oppLineItem.Trainings__c = productDetail.Training__r.name;
        //oppLineItem.Start_Date__c = opp.CloseDate;
        //oppLineItem.End_Date__c = endDate;
        oppLineItem.Skip_NetSuite_Sync__c = skip;
        oppLineItem.Type__c = 'Training';
        if(String.isNotBlank(prodDetail))
            oppLineItem.Parent_Product__c = prodDetail;

        System.debug('oppLineItem: ' + oppLineItem);
        return oppLineItem;
    }
    
}