force-app/main/default/objects/Campaign/fields/Add_to_Subscription_Center__c.field-meta.xml
<CustomField>
    <fullName>Add_to_Subscription_Center__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is created for Marketing Cloud.</description>
    <inlineHelpText>If this field is Checked, Campaign will show up in Subscription Center Marketing Cloud</inlineHelpText>
    <label>Add to Subscription Center</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Finos_Hubspot__c.field-meta.xml
<CustomField>
    <fullName>Finos_Hubspot__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finos Hubspot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Hubspot__c.field-meta.xml
<CustomField>
    <fullName>Hubspot__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hubspot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/HubSpot__c.field-meta.xml
<CustomField>
    <fullName>HubSpot__c</fullName>
    <formula>Campaign.Hubspot__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HubSpot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Campaign.Project_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Finos_Hubspot__c.field-meta.xml
<CustomField>
    <fullName>Finos_Hubspot__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finos Hubspot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Hubspot__c.field-meta.xml
<CustomField>
    <fullName>Hubspot__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hubspot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AI, ML, Data &amp; Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud, Containers &amp; Virtualization</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps, CI/CD &amp; Site Reliability</fullName>
    </customValue>
    <customValue>
        <fullName>IoT &amp; Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>Linux Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Networking &amp; Edge</fullName>
    </customValue>
    <customValue>
        <fullName>Open Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source &amp; Compliance Best Practices</fullName>
    </customValue>
    <customValue>
        <fullName>Privacy &amp; Security</fullName>
    </customValue>
    <customValue>
        <fullName>Quantum Computing</fullName>
    </customValue>
    <customValue>
        <fullName>Safety-Critical Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>System Administration</fullName>
    </customValue>
    <customValue>
        <fullName>System Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Visual Effects</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Application Development</fullName>
    </customValue>
    <customValue>
        <fullName>Cybersecurity</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
        <isActive>false</isActive>
        <label>Security</label>
    </customValue>
    <customValue>
        <fullName>Node.js Development</fullName>
        <isActive>false</isActive>
        <label>Node.js Development</label>
    </customValue>
    <customValue>
        <fullName>Open Source Best Practices</fullName>
        <isActive>false</isActive>
        <label>Open Source Best Practices</label>
    </customValue>
    <customValue>
        <fullName>Application Development</fullName>
        <isActive>false</isActive>
        <label>Application Development</label>
    </customValue>
    <description>Technology categories used by training, events, and projects across the LF.  Note that forms in Cvent need to be updated for any label change needed in this value set.</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CampaignTriggerTest.cls
@isTest
public with sharing class CampaignTriggerTest {
   
    @testSetup static void setup() {
 	
        Account acc1 = new Account(Name = 'Test account' , website = 'testing123.com');
        insert acc1;
            
        Project__c project= new Project__c(Name='TestProject', Category__c = 'Directed fund', Slug__c = 'testproject');
        insert project;
            
        Campaign C1 = new Campaign();
            C1.Name ='Test Subscription Center';
            C1.Description ='Test for Email Opt Out';
            C1.Project__c = project.Id;
            C1.Type ='Subscription Center';
            C1.Status ='In Progress';
            C1.StartDate = Date.today();
            C1.IsActive = true;
            C1.Add_to_Subscription_Center__c = true;
            C1.Technology__c ='System Administration';
            insert C1;
            
            CampaignMemberStatus ms1= new CampaignMemberStatus();
            ms1.CampaignId = C1.Id;
            ms1.Label = 'Subscribed';
            ms1.SortOrder = 3;
            insert ms1;
            
            CampaignMemberStatus ms2 = new CampaignMemberStatus();
            ms2.CampaignId = C1.Id;
            ms2.Label = 'Unsubscribed';
            ms2.SortOrder = 4;
            insert ms2;
                
            List<Lead> leadListToInsert = new List<Lead>();
             Lead lead1 = new Lead();
             lead1.LastName = 'Lead Opt Out Check';
             lead1.Email = 'testOptOut@lead1.com';
             lead1.Country= 'India';
             leadListToInsert.add(lead1);
            
             Lead lead2 = new Lead();
             lead2.LastName = 'Lead Opt Out Check2';
             lead2.Email = 'testOptOut@lead2.com';
             lead2.Country= 'India';
             leadListToInsert.add(lead2);

             insert leadListToInsert;

             List<contact> contactListToInsert = new List<contact>();
             Contact contact1 = new Contact();
             contact1.LastName ='Contact Opt Out Check';
             contact1.Email ='testOptOut@contact1.com';
             contact1.AccountId = acc1.Id;
             contactListToInsert.add(contact1);  
            
             Contact contact2 = new Contact();
             contact2.LastName ='Contact Opt Out Check2';
             contact2.Email ='testOptOut@contact2.com';
             contact2.AccountId = acc1.Id;
             contactListToInsert.add(contact2);
             
             insert contactListToInsert;
            
            List<campaignMember> lstCM = new List<CampaignMember>();
            CampaignMember CM1 = new CampaignMember();
            CM1.CampaignID = C1.Id;
            CM1.LeadId = lead1.Id;
            CM1.Status = 'Subscribed';
            lstCm.add(CM1);
            
            CampaignMember CM2 = new CampaignMember();
            CM2.CampaignID = C1.Id;
            CM2.ContactId = contact1.Id;
            CM2.Status = 'Subscribed';
            lstCM.add(CM2);

            CampaignMember CM5 = new CampaignMember();
            CM5.CampaignID = C1.Id;
            CM5.LeadId = lead2.Id;
            CM5.Status = 'Unsubscribed';
            lstCm.add(CM5);
            
            CampaignMember CM6 = new CampaignMember();
            CM6.CampaignID = C1.Id;
            CM6.ContactId = contact2.Id;
            CM6.Status = 'Unsubscribed';
            lstCM.add(CM6);
            
            insert lstCM;
            
         }

    @isTest
    public static void checkHubSpot_Test(){
       Test.startTest();
        Campaign campaign =[SELECT Id FROM Campaign LIMIT 1];
        campaign.Hubspot__c = true;
        Campaign.Finos_Hubspot__c = true;
        update campaign;
        List<Campaignmember> cmMmberList = [SELECT Id FROM CampaignMember WHERE CampaignId=: campaign.Id 
        AND campaign.Hubspot__c = true AND campaign.Finos_Hubspot__c = true];
        system.assertequals(4,cmMmberList.size());
        Test.stopTest();
    }
}