force-app/main/default/objects/Campaign/fields/Add_to_Subscription_Center__c.field-meta.xml
<CustomField>
    <fullName>Add_to_Subscription_Center__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is created for Marketing Cloud.</description>
    <inlineHelpText>If this field is Checked, Campaign will show up in Subscription Center Marketing Cloud</inlineHelpText>
    <label>Add to Subscription Center</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Campaign.Project_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A one-sentence description of the project, which will be used for external facing (i.e. landscape graphic or a website list of LF projects) descriptions of projects.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Consumer Electronics</fullName>
            </value>
            <value>
                <fullName>Cross-Industry</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Climate</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health Care</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
            <value>
                <fullName>Motion Pictures</fullName>
            </value>
            <value>
                <fullName>Non-profit Organizations</fullName>
            </value>
            <value>
                <fullName>Pharmaceuticals</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Public Health &amp; Disaster Response</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Indicates if the project has Membership, Crowdfunding (e.g. LFX Funding), or both. Note that a project may have membership requirements that do not have any fees or funding associated with them. In that case, &apos;Membership&apos; is still selected for this field.</inlineHelpText>
    <label>Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Crowdfunding</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Parent_Entity_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Parent_Entity_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Incorporated Entity or Series LLC that is the legal parent of the project.</inlineHelpText>
    <label>Legal Parent</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Child Projects of Legal Entity</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Incorporated Entity, Series LLC, or Subproject with which this project is associated. For example, a Series LLC entity may have a legal parent of LF Projects, LLC, but be associated with the parent project LF AI Foundation.</inlineHelpText>
    <label>Parent Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Child Projects</relationshipLabel>
    <relationshipName>Child_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Entity_Name__c</fullName>
    <inlineHelpText>The legal name of the entity or formal Subproject name.</inlineHelpText>
    <label>Formal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <inlineHelpText>The &quot;Prospect&quot; stage is reserved for non-LF projects, e.g. some Community Bridge projects.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Formation - Exploratory</fullName>
            </value>
            <value>
                <fullName>Formation - Engaged</fullName>
            </value>
            <value>
                <fullName>Formation - Confidential</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Formation - On Hold</fullName>
            </value>
            <value>
                <fullName>Formation - Disengaged</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Actively Engaged</fullName>
                <isActive>false</isActive>
                <label>Actively Engaged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Technical_Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Technical_Activity_Type__c</fullName>
    <label>Technical Activity Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Source Software</fullName>
            </value>
            <value>
                <fullName>Open Standard / Specification</fullName>
            </value>
            <value>
                <fullName>Open Hardware</fullName>
            </value>
            <value>
                <fullName>Open Data</fullName>
            </value>
            <value>
                <fullName>Open Governance Network</fullName>
            </value>
            <value>
                <fullName>Community Initiative</fullName>
            </value>
            <value>
                <fullName>Peer Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AI, ML, Data &amp; Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud, Containers &amp; Virtualization</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps, CI/CD &amp; Site Reliability</fullName>
    </customValue>
    <customValue>
        <fullName>IoT &amp; Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>Linux Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Networking &amp; Edge</fullName>
    </customValue>
    <customValue>
        <fullName>Open Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source &amp; Compliance Best Practices</fullName>
    </customValue>
    <customValue>
        <fullName>Privacy &amp; Security</fullName>
    </customValue>
    <customValue>
        <fullName>Quantum Computing</fullName>
    </customValue>
    <customValue>
        <fullName>Safety-Critical Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>System Administration</fullName>
    </customValue>
    <customValue>
        <fullName>System Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Visual Effects</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Application Development</fullName>
    </customValue>
    <customValue>
        <fullName>Cybersecurity</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
        <isActive>false</isActive>
        <label>Security</label>
    </customValue>
    <customValue>
        <fullName>Node.js Development</fullName>
        <isActive>false</isActive>
        <label>Node.js Development</label>
    </customValue>
    <customValue>
        <fullName>Open Source Best Practices</fullName>
        <isActive>false</isActive>
        <label>Open Source Best Practices</label>
    </customValue>
    <customValue>
        <fullName>Application Development</fullName>
        <isActive>false</isActive>
        <label>Application Development</label>
    </customValue>
    <description>Technology categories used by training, events, and projects across the LF.  Note that forms in Cvent need to be updated for any label change needed in this value set.</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Chart_LeadSubmissionControllerTest.cls
@IsTest
private class Chart_LeadSubmissionControllerTest {
    @TestSetup
    static void testSetup(){
        Project__c parentProj = new Project__c(Name = 'Parent project', slug__c = 'parent');
        insert parentProj;
        
        Project__c proj = new Project__c(Name = 'testProject1', Project_Status__c='Active', Category__c='Subproject');
        proj.Slug__c = 'testproj';
        proj.Funding__c = 'Unfunded';
        proj.Project_Entity_Name__c = 'The Linux Foundation';
        proj.Start_Date__c = system.today();
        proj.Industry__c = 'Non-profit Organizations';
        proj.Model__c = 'Alternate Funding';
        proj.Technology__c = 'Blockchain';
        proj.Technical_Activity_Type__c = 'Open Source Software';
        proj.Description__c = 'description';
        proj.Parent_Entity_Relationship__c = parentProj.Id;
        proj.Parent_Project__c = parentProj.Id;
        insert proj;
        Account account = new Account(Name = 'TestAbc');
        insert account;
        List<Lead> listOfLead = new List<Lead>();
        for (Integer i = 0; i < 2; i++) {
            String leadEmail = 'testlead' + i + '@gmail.com';
            Lead lead = new Lead(FirstName = 'Test', LastName = 'leadTest' + i, Company = 'TestLeadCompany' + i, Status = 'Unqualified', Email = leadEmail, LeadSource = 'Event');
            listOfLead.add(lead);
        }
        insert listOfLead;
        Campaign camp = new Campaign();
            camp.Name ='Test Subscription Center';
            camp.Description ='Test for Email Opt Out';
            camp.Project__c = proj.Id;
            camp.Type ='Subscription Center';
            camp.Status ='In Progress';
            camp.StartDate = Date.today();
            camp.IsActive = true;
            camp.Add_to_Subscription_Center__c = true;
	        camp.Technology__c ='System Administration';
            insert camp;
            List<CampaignMember> listOfcampMember = new List<CampaignMember>();
        for (Integer i = 0; i < 2; i++) {
            CampaignMember campMember = new CampaignMember();
            campMember.CampaignID = camp.Id;
            campMember.LeadId = listOfLead[i].Id;
            campMember.Status = 'Subscribed';
            listOfcampMember.add(campMember);
        }
        insert listOfcampMember;
    }
    
    @IsTest
    static void getSelectedProjectDetailsTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];
        Project__c result = Chart_LeadSubmissionController.getSelectedProjectDetails(proj.Id);
        System.assertEquals(proj.Id, result.Id);
        
    }

    @IsTest
     static void getLeadDetailsTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];   
        List<String> leadSource = new List<String>{'Event'};  
        List<String> selectedDates=new List<String>{'2021-02-22', '2021-03-22'};
        String result = Chart_LeadSubmissionController.getLeadDetails(proj.Id, leadSource, '', 'between', selectedDates);
        System.assertNotEquals(null, result);  
    }

    @IsTest
     static void getLeadDetailsLessThanTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];   
        List<String> leadSource = new List<String>{'Event'};  
        List<String> selectedDates=new List<String>{'2021-02-22', '2021-03-22'};
        String result = Chart_LeadSubmissionController.getLeadDetails(proj.id, leadSource, '', 'lessThanEqual', selectedDates);
        System.assertNotEquals(null, result);
     }

     @IsTest
     static void getLeadDetailsGreaterThanTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];   
        List<String> leadSource = new List<String>{'Event'};  
        List<String> selectedDates=new List<String>{'2021-02-22', '2021-03-22'};
        String result = Chart_LeadSubmissionController.getLeadDetails(proj.id, leadSource, '', 'greaterThanEqual', selectedDates);
        System.assertNotEquals(null, result);
     }

     @IsTest
     static void getLeadDetailsEqualsLessTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];   
        List<String> leadSource = new List<String>{'Event'};  
        List<String> selectedDates=new List<String>{'2021-02-22', '2021-03-22'};
        String result = Chart_LeadSubmissionController.getLeadDetails(proj.id, leadSource, '', 'equalLessThan', selectedDates);
        System.assertNotEquals(null, result);
     }

     @IsTest
     static void getLeadDetailsEqualsTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];   
        List<String> leadSource = new List<String>{'Event'};  
        List<String> selectedDates=new List<String>{'2021-02-22', '2021-03-22'};
        String result = Chart_LeadSubmissionController.getLeadDetails(proj.id, leadSource, '', 'equal', selectedDates);
        System.assertEquals(null, result);
     }

    @IsTest
     static void getLeadTableDetailsTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];
        List<String> selectedDates=new List<String>{'THIS_YEAR'};
        List<String> leadSource = new List<String>{'Event'};  
        Chart_LeadSubmissionController.ReturnLeadWrapper result = Chart_LeadSubmissionController.getLeadTableDetails(proj.id, leadSource, null, 'equal', selectedDates, '', 'Event', 'equal', false, false);
        System.assertEquals(2, result.leadWrapper.size());
     }

     @IsTest
     static void getLeadTableDetailsGTTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];
        List<String> selectedDates=new List<String>{'THIS_Year'};
        List<String> leadSource = new List<String>{'Event'};  
        Chart_LeadSubmissionController.ReturnLeadWrapper result = Chart_LeadSubmissionController.getLeadTableDetails(proj.id, leadSource, null, 'equalLessThan', selectedDates, '', '["Event"]', 'greaterThanEqual', true, true);
        System.assertEquals(2, result.leadWrapper.size());
     }

     @IsTest
     static void getLeadTableDetailsLTTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];
        List<String> selectedDates=new List<String>{'2021-02-22', '2021-03-22'};
        List<String> leadSource = new List<String>{'Event'};  
            Chart_LeadSubmissionController.ReturnLeadWrapper result = Chart_LeadSubmissionController.getLeadTableDetails(proj.id, leadSource, '"march"', 'lessThanEqual', selectedDates, null, 'Event', 'lessThanEqual', false, false);
        System.assertEquals(0, result.leadWrapper.size());
     }

     @IsTest
     static void getLeadTableDetailsEqualsLessTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];
        List<String> selectedDates=new List<String>{'2021-02-22', '2021-03-22'};
        List<String> leadSource = new List<String>{'Event'};  
        Chart_LeadSubmissionController.ReturnLeadWrapper result = Chart_LeadSubmissionController.getLeadTableDetails(proj.id, leadSource, null, 'between', selectedDates, null, 'Event', 'equalLessThan', false, false);
        System.assertEquals(0, result.leadWrapper.size());
     }     
   
     @IsTest
     static void getLeadTableDetailsFQTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];
        List<String> selectedDates=new List<String>{'THIS_Fiscal_Quarter'};
        List<String> leadSource = new List<String>{'Event'};  
        Chart_LeadSubmissionController.ReturnLeadWrapper result = Chart_LeadSubmissionController.getLeadTableDetails(proj.id, leadSource, null, 'equalLessThan', selectedDates, '', '["Event"]', 'greaterThanEqual', true, true);
        System.assertEquals(2, result.leadWrapper.size());
     }

     @IsTest
     static void getLeadTableDetailsFYTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];
        List<String> selectedDates=new List<String>{'THIS_Fiscal_Year'};
        List<String> leadSource = new List<String>{'Event'};  
        Chart_LeadSubmissionController.ReturnLeadWrapper result = Chart_LeadSubmissionController.getLeadTableDetails(proj.id, leadSource, null, 'equalLessThan', selectedDates, '', '["Event"]', 'greaterThanEqual', true, true);
        System.assertEquals(2, result.leadWrapper.size());
     }

     @IsTest
     static void getLeadTableDetailsQuarterTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];
        List<String> selectedDates=new List<String>{'THIS_Quarter'};
        List<String> leadSource = new List<String>{'Event'};  
        Chart_LeadSubmissionController.ReturnLeadWrapper result = Chart_LeadSubmissionController.getLeadTableDetails(proj.id, leadSource, null, 'equalLessThan', selectedDates, '', '["Event"]', 'greaterThanEqual', true, true);
        System.assertEquals(2, result.leadWrapper.size());
     }

     @IsTest
     static void getLeadTableDetailsMonthTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];
        List<String> selectedDates=new List<String>{'THIS_Month'};
        List<String> leadSource = new List<String>{'Event'};  
        Chart_LeadSubmissionController.ReturnLeadWrapper result = Chart_LeadSubmissionController.getLeadTableDetails(proj.id, leadSource, null, 'equalLessThan', selectedDates, '', '["Event"]', 'greaterThanEqual', true, true);
        System.assertEquals(2, result.leadWrapper.size());
     }

     @IsTest
     static void getLeadTableDetailsDefaultTest(){
        Project__c proj = [SELECT Id FROM Project__c where slug__c = 'testproj'];
        List<String> selectedDates=new List<String>();
        List<String> leadSource = new List<String>{'Event'};  
        Chart_LeadSubmissionController.ReturnLeadWrapper result = Chart_LeadSubmissionController.getLeadTableDetails(proj.id, leadSource, null, '', selectedDates, '', '["Event"]', 'greaterThanEqual', true, true);
        System.assertEquals(2, result.leadWrapper.size());
     }

}