force-app/main/default/objects/Campaign/fields/Add_to_Subscription_Center__c.field-meta.xml
<CustomField>
    <fullName>Add_to_Subscription_Center__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is created for Marketing Cloud.</description>
    <inlineHelpText>If this field is Checked, Campaign will show up in Subscription Center Marketing Cloud</inlineHelpText>
    <label>Add to Subscription Center</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Thirdparty_Coupon__c.field-meta.xml
<CustomField>
    <fullName>Thirdparty_Coupon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Thirdparty Coupon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coupon_Code__c/Coupon_Code__c.object-meta.xml
<CustomObject>
    <label>Coupon Code</label>
    <nameField>
        <label>Coupon Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coupon Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon_Code__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Name</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Coupon Codes</relationshipLabel>
    <relationshipName>Coupon_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AI, ML, Data &amp; Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud, Containers &amp; Virtualization</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps, CI/CD &amp; Site Reliability</fullName>
    </customValue>
    <customValue>
        <fullName>IoT &amp; Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>Linux Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Networking &amp; Edge</fullName>
    </customValue>
    <customValue>
        <fullName>Open Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source &amp; Compliance Best Practices</fullName>
    </customValue>
    <customValue>
        <fullName>Privacy &amp; Security</fullName>
    </customValue>
    <customValue>
        <fullName>Quantum Computing</fullName>
    </customValue>
    <customValue>
        <fullName>Safety-Critical Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>System Administration</fullName>
    </customValue>
    <customValue>
        <fullName>System Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Visual Effects</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Application Development</fullName>
    </customValue>
    <customValue>
        <fullName>Cybersecurity</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
        <isActive>false</isActive>
        <label>Security</label>
    </customValue>
    <customValue>
        <fullName>Node.js Development</fullName>
        <isActive>false</isActive>
        <label>Node.js Development</label>
    </customValue>
    <customValue>
        <fullName>Open Source Best Practices</fullName>
        <isActive>false</isActive>
        <label>Open Source Best Practices</label>
    </customValue>
    <customValue>
        <fullName>Application Development</fullName>
        <isActive>false</isActive>
        <label>Application Development</label>
    </customValue>
    <description>Technology categories used by training, events, and projects across the LF.  Note that forms in Cvent need to be updated for any label change needed in this value set.</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CouponCodeTH_Test.cls
//Test Class For - CouponCodeTH Class
@isTest
public class CouponCodeTH_Test {
    
    //Method to create testdata
    @testSetup
    public static void createTestData(){
        //project
        Project__c project= new Project__c(Name='TestProject', Category__c = 'Directed fund', Slug__c='testproj');
        insert project;
        
        //campaign
        Campaign C1 = new Campaign();
        C1.Name ='Test Subscription Center';
        C1.Description ='Test for Email Opt Out';
        C1.Project__c = project.Id;
        C1.Type ='Subscription Center';
        C1.Status ='In Progress';
        C1.StartDate = Date.today();
        C1.IsActive = true;
        C1.Add_to_Subscription_Center__c = true;
        C1.Technology__c ='System Administration';
        insert C1;
        
        CampaignMemberStatus ms1= new CampaignMemberStatus();
        ms1.CampaignId = C1.Id;
        ms1.Label = 'Subscribed';
        ms1.SortOrder = 3;
        insert ms1;
        
        CampaignMemberStatus ms2 = new CampaignMemberStatus();
        ms2.CampaignId = C1.Id;
        ms2.Label = 'Unsubscribed';
        ms2.SortOrder = 4;
        insert ms2;
    }
    
    //Test Method for validateCouponCodeForDuplicate
    @isTest private static void validateCouponCodeForDuplicate_Test(){
        Campaign campaign = [SELECT Id FROM Campaign LIMIT 1];
        campaign.Thirdparty_Coupon__c = true;
        update campaign;
        
        List<Coupon_Code__c> couponCodeList = new List<Coupon_Code__c>();
        for(Integer i=0;i<=1;i++){
            Coupon_Code__c couponCode = new Coupon_Code__c(Name='TestCoupon123',
                                                           Expiration_Date__c=System.today()+1,
                                                           Campaign_Name__c=campaign.Id);
            couponCodeList.add(couponCode);
        }
        Test.startTest();
        try{
            Database.insert(couponCodeList,false);
        }catch(Exception e){
            
        }
        
        Test.StopTest();
        
        System.assertEquals(1,[SELECT Id FROM Coupon_Code__c 
                               WHERE Campaign_name__c=:campaign.Id].size());
    }
    
    /*Test Method for other methods of trigger handler class as there coverage is based on events 
     * and for now we only have before insert event for couponcode trigger hence covering the other methods in this way
    */
    @isTest
    public static void otherMethods_Test(){
        Map<id, SObject> newMap = new Map<id, SObject>();
        Map<id, SObject> oldMap = new Map<id, SObject>();
        CouponCodeTH.BeforeUpdate(newMap,oldMap);
        CouponCodeTH.BeforeDelete(oldMap);
        CouponCodeTH.AfterInsert(newMap);
        CouponCodeTH.AfterUpdate(newMap,oldMap);
        CouponCodeTH.AfterDelete(oldMap);
        CouponCodeTH.AfterUnDelete(newMap);
    }
    
}