force-app/main/default/objects/Campaign/fields/Do_Not_Include_in_Master_Subscriber_List__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Include_in_Master_Subscriber_List__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do Not Include in Master Subscriber List
Do_Not_Include_in_Master_Subscriber_List</description>
    <label>Do Not Include in Global Subscriber List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Do_Not_Include_in_Master_Subscriber_List__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Include_in_Master_Subscriber_List__c</fullName>
    <formula>Campaign.Do_Not_Include_in_Master_Subscriber_List__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Do Not Include in Master Subscriber List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Campaign.Project_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/MembersRolUpToSubsCampBatchTest.cls
@IsTest
private class MembersRolUpToSubsCampBatchTest{
	@TestSetup
	static void testSetup(){
		List<Campaign> listOfCampaign = new List<Campaign>();
		Project__c testProject = TestFactory.getProject();
        Account testAccount = TestFactory.getAccount();
		for (Integer i = 0; i <  = 5; i++){
			Campaign campaign = new Campaign(Name = 'Test Campaign', IsActive = true, Status = 'In Progress', Description = 'TestCampaign', Do_Not_Include_in_Master_Subscriber_List__c = false, Project__c = testProject.Id);
			if (i == 0){
				campaign.Type = 'Subscription Center';
			} else{
				campaign.Type = 'MixMax';
			}
			listOfCampaign.add(campaign);
		}
		insert listOfCampaign;
		List<CampaignMember> listOfCampaignMember = new List<CampaignMember>();
        List<Contact> listOfContact = new List<Contact>();
		for (Integer i = 0; i <= 5; i++) {
            Contact contact = new Contact();
            contact.AccountId = testAccount.Id;
            contact.LastName = 'Test ' + i;
            listOfContact.add(contact);
        }
        insert listOfContact;
		for (Integer i = 0; i <  = 5; i++){
			CampaignMember campaignMember = new CampaignMember();
			campaignMember.CampaignId = listOfCampaign[i].Id;
			campaignMember.ContactId = listOfContact[i].Id;
			listOfCampaignMember.add(campaignMember);
		}
		insert listOfCampaignMember;
	}

	@IsTest
	static void execeuteBatchTest(){
		Test.startTest();
        MembersRollUpToSubscriptionCampaignBatch schedule = new MembersRollUpToSubscriptionCampaignBatch();
		schedule.execute(null);
		Test.stopTest();
		System.assertEquals(6, [SELECT count()
		                        FROM CampaignMember
		                        WHERE Campaign.Type = 'Subscription Center']);
	}
}