force-app/main/default/objects/Account_And_Project__c/Account_And_Project__c.object-meta.xml
<CustomObject>
    <label>NetSuite ID</label>
    <nameField>
        <displayFormat>AP-{00}</displayFormat>
        <label>NetSuite ID AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NetSuite IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_And_Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_And_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_And_Project__c/fields/Netssuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netssuite_ID__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_And_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Account_And_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_And_Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</description>
    <inlineHelpText>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</inlineHelpText>
    <label>Billing Account Override</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_Error__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Error__c</fullName>
    <label>NetSuite Error</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Endpoints__c/Endpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Endpoints</label>
</CustomObject>

force-app/main/default/objects/Endpoints__c/fields/Nlauth_Account__c.field-meta.xml
<CustomField>
    <fullName>Nlauth_Account__c</fullName>
    <label>Nlauth_Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Netsuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_ID__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/Hotel_Commissions__c.object-meta.xml
<CustomObject>
    <description>Hotel Commissions are revenue transactions.These are the commissions which Linux Foundation receives from Hotel&apos;s when event registrant registers for an LF event and books the room to stay in and attend the event.</description>
    <label>Hotel Commissions</label>
    <nameField>
        <label>Hotel Commissions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotel Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel_Commissions__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hotel Commissions</relationshipLabel>
    <relationshipName>Hotel_Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Bill_to_Contact_2__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Contact 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hotel Commissions (Bill to Contact 2)</relationshipLabel>
    <relationshipName>Hotel_Commissions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Bill_to_Contact_3__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Contact_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Contact 3</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hotel Commissions (Bill to Contact 3)</relationshipLabel>
    <relationshipName>Hotel_Commissions2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Bill_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hotel Commissions</relationshipLabel>
    <relationshipName>Hotel_Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Hotel_Commission_Link__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Commission_Link__c</fullName>
    <formula>LEFT($Api.Partner_Server_URL_470, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_470))&amp;Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hotel Commission Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/NetSuite_Error__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Error__c</fullName>
    <label>NetSuite Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <label>NetSuite Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/NS_Invoice_Memo__c.field-meta.xml
<CustomField>
    <fullName>NS_Invoice_Memo__c</fullName>
    <label>NS Invoice Memo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>298217</fullName>
                <default>true</default>
                <label>Hotel Commission</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Salesorder_Number__c.field-meta.xml
<CustomField>
    <fullName>Salesorder_Number__c</fullName>
    <label>Salesorder Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Salesorder_Status__c.field-meta.xml
<CustomField>
    <fullName>Salesorder_Status__c</fullName>
    <label>Salesorder Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/SubsidiaryId__c.field-meta.xml
<CustomField>
    <fullName>SubsidiaryId__c</fullName>
    <defaultValue>Text(1)</defaultValue>
    <label>SubsidiaryId</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Sync_to_Netsuite__c.field-meta.xml
<CustomField>
    <fullName>Sync_to_Netsuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync to Netsuite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Events</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Training</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Training (Linux Labs)</label>
    </customValue>
    <masterLabel>NetSuite Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HotelCommissionSalesOrderHelper.cls
public class HotelCommissionSalesOrderHelper {
    public static Endpoints__c settings{
        get{
            if(settings == null){
                List<Endpoints__c> endPointObj = new List<Endpoints__c>([select name, endpoint__c, Password__c, User_Id__c, Nlauth_Account__c from Endpoints__c where name = 'For Other than Membership Asset']);         
                settings = endPointObj[0];
            }
            return settings;
        }
        set;
    }
    public Boolean createHotelCommissionSalesOrder(Id recordId){
        Boolean isSuccess = false;
        try{
            List<Endpoints__c> endPointObj = new List<Endpoints__c>([select name, endpoint__c, Password__c, User_Id__c, Nlauth_Account__c from Endpoints__c where name = 'For Other than Membership Asset']);         
            if(!endPointObj.IsEmpty()){
                Hotel_Commissions__c hotelCommissions = [SELECT ID,Bill_to_Account__c,Salesorder_Status__c,Salesorder_Number__c,
                                                         NetSuite_ID__c,NetSuite_Error__c,Sync_to_Netsuite__c
                                                         FROM Hotel_Commissions__c WHERE Id =: recordId];            
                String body = createSalesOrderJSON(recordId); // create json body 
                body = createAccountInNetSuite(body);// create account
                if(String.isNotEmpty(body)){
                    HttpResponse response = CallOutToNetSuiteForAsset.calloutToNetSuite(settings, 'POST', body); //creates sales order
                    if(response.getStatusCode() == 200 || response.getStatusCode() == 201) {
                        WrapperToGetSalesOrderData salesOrderWrapper = (WrapperToGetSalesOrderData)JSON.deserialize(response.getBody() , WrapperToGetSalesOrderData.class);
                        WrapperToGetSalesOrderData wrap = salesOrderWrapper;
                        hotelCommissions.NetSuite_ID__c = wrap.id;
                        hotelCommissions.Salesorder_Number__c = wrap.tranid;
                        hotelCommissions.NetSuite_Error__c ='';
                        hotelCommissions.Sync_to_Netsuite__c = true;
                        isSuccess = true;
                    }else{
                        //update error message
                        hotelCommissions.NetSuite_Error__c ='NetSuite Sync Failed to work for Hotel Commissions:' + response.getBody();
                    }
                    update hotelCommissions;
                    Map<String , Object> jsonBody = (Map<String , Object>)JSON.deserializeUntyped(body);
                    if(jsonBody.containsKey('entity')){                
                        Account_And_Project__c apa = new Account_And_Project__c();
                        apa.Account__c  = hotelCommissions.Bill_To_Account__c;
                        apa.Project__c =  [SELECT ID,NAME FROM Project__c WHERE NAME='The Linux Foundation'][0].Id;//harcode to linux foundation project
                        apa.Netssuite_ID__c = (String)jsonBody.get('entity');
                        upsert apa Netssuite_ID__c;
                    }
                }
            }
        }
        catch (Exception ex){
            
        }
        return isSuccess;
    }
    
    private String createAccountInNetSuite(String body){   
        List<Endpoints__c> endPointObj = new List<Endpoints__c>([select name, endpoint__c, Password__c, User_Id__c, Nlauth_Account__c from Endpoints__c where name = 'For Product Details']);         
        Map<String , Object> jsonBody = (Map<String , Object>)JSON.deserializeUntyped(body);
        if(jsonBody != null && jsonBody.containsKey('syncAccount')){
            String accountBodyInString = String.valueOf(jsonBody.get('syncAccount'));            
            HttpResponse response = CallOutToNetSuiteForAsset.calloutToNetSuite(endPointObj[0], 'POST', accountBodyInString);           
            if(response.getStatusCode() != 200){
                //there is an error creating account return blank account
                return '';
            }else{
                jsonBody.remove('syncAccount');                
                jsonBody.put('entity' , response.getBody().replaceAll('"' , ''));
                body = JSON.serialize(jsonBody);
            }
        }
        return body;        
    }
    
    
    public String createSalesOrderJSON(Id recordId) {       
        Hotel_Commissions__c hotelCommissions = [
            SELECT Id,NS_Department__c,Product__c,Product_Description__c, Bill_to_Contact__r.Email,
            Amount__c,Bill_To_Account__c,Bill_To_Account__r.Billingstreet,Bill_To_Account__r.Billingcity,
            Bill_To_Account__r.billingstate, Bill_To_Account__r.billingPostalCode, Bill_To_Account__r.billingCountry, Start_Date__c,End_Date__c,
            Bill_To_Account__r.Name,SubsidiaryId__c,NS_Invoice_Memo__c,Bill_to_Contact_2__c,Bill_to_Contact_2__r.Email,Bill_to_Contact_3__c,
            Bill_to_Contact_3__r.Email,Hotel_Commission_Link__c
            FROM Hotel_Commissions__c
            WHERE ID = :recordId
        ];
        
        List<Account_And_Project__c> accProList = [
            select id, Account__c, Project__c, Subsidiary_ID__c, Netssuite_ID__c
            from Account_And_Project__c
            where Account__c = :hotelCommissions.Bill_To_Account__c AND Project__r.Project_Code__c = 'LF'
        ];
        
        Map<String, Object> jsonMappingObject = new Map<String, Object>();
        
        
        jsonMappingObject.put('subsidiary',hotelCommissions.SubsidiaryId__c); // 1
        jsonMappingObject.put('Project_Code__c','LF'); // check if this is needed //LF
        jsonMappingObject.put('billaddress', getBillToAddress(hotelCommissions));
        jsonMappingObject.put('recordtype', 'salesorder');
        jsonMappingObject.put('custbody_primary_email', hotelCommissions.Bill_to_Contact__r.email);
        jsonMappingObject.put('department', hotelCommissions.NS_Department__c);
        jsonMappingObject.put('custbody_sugar_reference' , hotelCommissions.Hotel_Commission_Link__c);
        if(hotelCommissions.NS_Invoice_Memo__c != null){
            if(hotelCommissions.NS_Invoice_Memo__c.length() < 999){
                jsonMappingObject.put('memo' , hotelCommissions.NS_Invoice_Memo__c);
            }
        }
        if(hotelCommissions.Bill_to_Contact_2__c != null){
            jsonMappingObject.put('custbody_additional_email_1' , hotelCommissions.Bill_to_Contact_2__r.email);
        }
        if(hotelCommissions.Bill_to_Contact_3__c != null){
            jsonMappingObject.put('custbody_additional_email_2' , hotelCommissions.Bill_to_Contact_3__r.email);
        }
        if (!accProList.isEmpty()) {
            jsonMappingObject.put('entity', accProList[0].Netssuite_ID__c); // bill to account details
            String netsuiteBody = creatingMember(hotelCommissions, accProList[0].Netssuite_ID__c);
            jsonMappingObject.put('syncAccount', netsuiteBody);
        } else {
            String netsuiteBody = creatingMember(hotelCommissions, null);
            jsonMappingObject.put('syncAccount', netsuiteBody);
        }        
        jsonMappingObject.put('items', buildSalesItem(hotelCommissions));
        String jsonString = JSON.serialize(jsonMappingObject);        
        return jsonString;
    }
    
    public  string creatingMember(Hotel_Commissions__c hotelCommissions, String isEntityIdPresent) {
        Map<String, String> memberMapping = new Map<String, String>();
        if (isEntityIdPresent != null) {
            memberMapping.put('id', isEntityIdPresent);
        }
        memberMapping.put('companyname', hotelCommissions.Bill_To_Account__r.Name);
        String name = hotelCommissions.Bill_To_Account__r.Name + '-LF' ;
        if (name.length() > 80) {         
            name = hotelCommissions.Bill_To_Account__r.Name.substring(0, 70) + ' - LF';// + ems.Event__r.BillFromProject__r.project_code__c;
        }
        memberMapping.put('entityid', name);
        memberMapping.put('subsidiary', String.valueOf(hotelCommissions.SubsidiaryId__c));       
        memberMapping.put('recordtype', 'customer');
        memberMapping.put('url', null);
        memberMapping.put('phone', null);
        
        String billingStreet = hotelCommissions.Bill_To_Account__r.BillingStreet != null ? hotelCommissions.Bill_To_Account__r.BillingStreet : '';
        memberMapping.put('addr1',billingStreet);  
        
        String billingCity = hotelCommissions.Bill_To_Account__r.BillingCity != null ? hotelCommissions.Bill_To_Account__r.BillingCity : '';
        memberMapping.put('city',billingCity);  
        
        String billingPostalCode = hotelCommissions.Bill_To_Account__r.BillingPostalCode != null ? hotelCommissions.Bill_To_Account__r.BillingPostalCode : '';
        memberMapping.put('zip',billingPostalCode);  
        
        String billingState = hotelCommissions.Bill_To_Account__r.BillingState != null ? hotelCommissions.Bill_To_Account__r.BillingState : '';
        memberMapping.put('state',billingState);  
        
        String billingCountry = hotelCommissions.Bill_To_Account__r.billingCountry != null ? AssetToSalesOrderHelper.convertingCountry( hotelCommissions.Bill_To_Account__r.billingCountry, false) : '';
        memberMapping.put('country',billingCountry); 
        
        return JSON.serialize(memberMapping);
    }
    
    private List<Object> buildSalesItem(Hotel_Commissions__c hotelCommissions) {
        List<Object> itemList = new List<Object>();
        Map<String, Object> salesLineItem = new map<String, Object>();
        salesLineItem.put('item', hotelCommissions.Product__c);
        salesLineItem.put('price', 1);
        salesLineItem.put('description', hotelCommissions.Product_Description__c);
        salesLineItem.put('amount', hotelCommissions.Amount__c);
        salesLineItem.put('quantity', 1);        
        String startDate = hotelCommissions.Start_Date__c.month()  + '/'+ hotelCommissions.Start_Date__c.day() + '/' + hotelCommissions.Start_Date__c.year();
        String endDate = hotelCommissions.End_Date__c.month()  + '/'+ hotelCommissions.End_Date__c.day() + '/' + hotelCommissions.End_Date__c.year();
        salesLineItem.put('revrecstartdate', startDate);
        salesLineItem.put('revrecenddate', startDate);
        itemList.add(salesLineItem);
        return itemList;
        
    }
    
    private String getBillToAddress(Hotel_Commissions__c hotelCommissions) {
        String billToAddress = '';
        if (hotelCommissions.Bill_To_Account__c != null) {
            String convertedCountry = '', country = '';            
            convertedCountry = AssetToSalesOrderHelper.convertingCountry(hotelCommissions.Bill_To_Account__r.billingCountry, true);            
            if (convertedCountry != null) {
                country = convertedCountry.capitalize();
            }
            String street = hotelCommissions.Bill_To_Account__r.billingstreet != null ? hotelCommissions.Bill_To_Account__r.billingstreet : '' ;
            String city = hotelCommissions.Bill_To_Account__r.billingcity != null ? hotelCommissions.Bill_To_Account__r.billingcity : '' ;
            String state = hotelCommissions.Bill_To_Account__r.billingstate != null ? hotelCommissions.Bill_To_Account__r.billingstate : '' ;
            String Postalcode = hotelCommissions.Bill_To_Account__r.billingPostalCode != null ? hotelCommissions.Bill_To_Account__r.billingPostalCode : '' ;
            String checkCountry = country != null ? country : '' ;
            if (String.isNotEmpty(street)) {
                billToAddress = hotelCommissions.Bill_To_Account__r.Name + '\n' + street + '\n' + city + ' ' + state + ' ' + PostalCode + '\n' + checkCountry;
            }
        }       
        return billToAddress;
    }
}