force-app/main/default/objects/Account_And_Project__c/Account_And_Project__c.object-meta.xml
<CustomObject>
    <label>NetSuite ID</label>
    <nameField>
        <displayFormat>AP-{00}</displayFormat>
        <label>NetSuite ID AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NetSuite IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_And_Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_And_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_And_Project__c/fields/Netssuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netssuite_ID__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_And_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Account_And_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_And_Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bill_From__c.field-meta.xml
<CustomField>
    <fullName>Bill_From__c</fullName>
    <label>Bill From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</description>
    <inlineHelpText>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</inlineHelpText>
    <label>Billing Account Override</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_Error__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Error__c</fullName>
    <label>NetSuite Error</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/EMS__c/EMS__c.object-meta.xml
<CustomObject>
    <label>EMS</label>
    <nameField>
        <label>EMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS__c/fields/Bill_From__c.field-meta.xml
<CustomField>
    <fullName>Bill_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill From</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>EMS</relationshipLabel>
    <relationshipName>EMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EMS (Bill To Account)</relationshipLabel>
    <relationshipName>EMS1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>EMS</relationshipLabel>
    <relationshipName>EMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/EMS_Link__c.field-meta.xml
<CustomField>
    <fullName>EMS_Link__c</fullName>
    <formula>LEFT($Api.Partner_Server_URL_470, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_470))&amp;Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EMS Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>EMS</relationshipLabel>
    <relationshipName>EMS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Jobcode__c.field-meta.xml
<CustomField>
    <fullName>Jobcode__c</fullName>
    <label>Jobcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/NetSuite_Error__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Error__c</fullName>
    <label>NetSuite Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/NS_Class__c.field-meta.xml
<CustomField>
    <fullName>NS_Class__c</fullName>
    <defaultValue>&quot;3&quot;</defaultValue>
    <label>NS Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <defaultValue>&quot;2&quot;</defaultValue>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>22</fullName>
                <default>true</default>
                <label>Event Management Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Salesorder_Number__c.field-meta.xml
<CustomField>
    <fullName>Salesorder_Number__c</fullName>
    <label>Salesorder Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Sync_to_Netsuite__c.field-meta.xml
<CustomField>
    <fullName>Sync_to_Netsuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync to Netsuite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Endpoints__c/Endpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Endpoints</label>
</CustomObject>

force-app/main/default/objects/Endpoints__c/fields/Nlauth_Account__c.field-meta.xml
<CustomField>
    <fullName>Nlauth_Account__c</fullName>
    <label>Nlauth_Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Netsuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_ID__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A one-sentence description of the project, which will be used for external facing (i.e. landscape graphic or a website list of LF projects) descriptions of projects.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Events</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Training</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Training (Linux Labs)</label>
    </customValue>
    <masterLabel>NetSuite Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EMSSalesOrderHelper.cls
public class EMSSalesOrderHelper {    
    
    public static Endpoints__c settings{
        get{
            if(settings == null){
                List<Endpoints__c> endPointObj = new List<Endpoints__c>([select name, endpoint__c, Password__c, User_Id__c, Nlauth_Account__c from Endpoints__c where name = 'For Other than Membership Asset']);         
                settings = endPointObj[0];
            }
            return settings;
        }
        set;
    }

    public Boolean createEMSSalesOrder(Id recordId){
        Boolean isSuccess = false;
        try{
        List<Endpoints__c> endPointObj = new List<Endpoints__c>([select name, endpoint__c, Password__c, User_Id__c, Nlauth_Account__c from Endpoints__c where name = 'For Other than Membership Asset']);         
        if(!endPointObj.IsEmpty()){
            EMS__c ems = [SELECT ID,NetSuite_ID__c,Bill_To_Account__c,Salesorder_Number__c,Event__r.BillFromProject__c,NetSuite_Error__c FROM EMS__c WHERE Id =: recordId];            
            String body = createSalesOrderJSON(recordId); // create json body 
            body = createAccountInNetSuite(body);// create account
            if(String.isNotEmpty(body)){
                HttpResponse response = CallOutToNetSuiteForAsset.calloutToNetSuite(settings, 'POST', body); //creates sales order
                System.debug('Response ==>' + response.getBody());
                if(response.getStatusCode() == 200 || response.getStatusCode() == 201) {
                    WrapperToGetSalesOrderData salesOrderWrapper = (WrapperToGetSalesOrderData)JSON.deserialize(response.getBody() , WrapperToGetSalesOrderData.class);
                    WrapperToGetSalesOrderData wrap = salesOrderWrapper;
                    ems.NetSuite_ID__c = wrap.id;
                    ems.Salesorder_Number__c = wrap.tranid;
                    ems.NetSuite_Error__c ='';
                    ems.Sync_to_Netsuite__c = true;
                    isSuccess = true;
                }else{
                    //update error message
                    ems.NetSuite_Error__c ='NetSuite Sync Failed to work for EMS:' + response.getBody();
                }
                update ems;
                Map<String , Object> jsonBody = (Map<String , Object>)JSON.deserializeUntyped(body);
                if(jsonBody.containsKey('entity')){                
                    Account_And_Project__c apa = new Account_And_Project__c();
                    apa.Account__c  = ems.Bill_To_Account__c;
                    apa.Project__c =  ems.Event__r.BillFromProject__c;
                    apa.Netssuite_ID__c = (String)jsonBody.get('entity');
                    upsert apa Netssuite_ID__c;
                }

            }
        }
        }
        catch (Exception ex){
            
        }
        return isSuccess;
    }
    
    private String createAccountInNetSuite(String body){   
        List<Endpoints__c> endPointObj = new List<Endpoints__c>([select name, endpoint__c, Password__c, User_Id__c, Nlauth_Account__c from Endpoints__c where name = 'For Product Details']);         
        Map<String , Object> jsonBody = (Map<String , Object>)JSON.deserializeUntyped(body);
        if(jsonBody != null && jsonBody.containsKey('syncAccount')){
            String accountBodyInString = String.valueOf(jsonBody.get('syncAccount')); 
            system.debug('Account Body==>' +accountBodyInString);
            HttpResponse response = CallOutToNetSuiteForAsset.calloutToNetSuite(endPointObj[0], 'POST', accountBodyInString);           
            if(response.getStatusCode() != 200){
                //there is an error creating account return blank account
                return '';
            }else{
                jsonBody.remove('syncAccount');                
                jsonBody.put('entity' , response.getBody().replaceAll('"' , ''));
                body = JSON.serialize(jsonBody);
            }
        }
        
        return body;        
    }
    
    public String createSalesOrderJSON(Id recordId) {
        List<Object> mainJsonArray = new List<Object>();

        EMS__c ems = [
                SELECT Id,NS_Department__c,Product__c,Description__c, Contact__r.Email,NS_Class__c,
                        Amount__c,Bill_To_Account__c,Bill_To_Account__r.Billingstreet,Bill_To_Account__r.Billingcity,Bill_From__r.Project_Code__c,
                        Bill_To_Account__r.billingstate, Bill_To_Account__r.billingPostalCode, Bill_To_Account__r.billingCountry, StartDate__c,
                        Bill_To_Account__r.Name,Bill_From__r.Subsidiary_ID__c,Jobcode__c,EMS_Link__c
                FROM EMS__c
                WHERE ID = :recordId
        ];

        Map<String, Object> jsonMappingObject = new Map<String, Object>();
        List<Account_And_Project__c> accProList = [
                select id, Account__c, Project__c, Subsidiary_ID__c, Netssuite_ID__c
                from Account_And_Project__c
                where Account__c = :ems.Bill_To_Account__c AND Project__r.Project_Code__c = :ems.Bill_From__r.Project_Code__c
        ];

        jsonMappingObject.put('subsidiary',ems.Bill_From__r.Subsidiary_ID__c); // 1
        jsonMappingObject.put('Project_Code__c',ems.Bill_From__r.Project_Code__c); // check if this is needed //LF
        jsonMappingObject.put('billaddress', getBillToAddress(ems));
        jsonMappingObject.put('location' , ems.Jobcode__c);
        jsonMappingObject.put('class' , ems.NS_Class__c);
        jsonMappingObject.put('recordtype', 'salesorder');
        jsonMappingObject.put('department', ems.NS_Department__c);
        jsonMappingObject.put('custbody_primary_email', ems.Contact__r.email);
        jsonMappingObject.put('custbody_sugar_reference' , ems.EMS_Link__c);
       
        //accProList = new List<Account_And_Project__c>();//added to solve sync issue on sandox
        if (!accProList.isEmpty()) {
            jsonMappingObject.put('entity', accProList[0].Netssuite_ID__c); // bill to account details
            String netsuiteBody = creatingMember(ems, accProList[0].Netssuite_ID__c);
            jsonMappingObject.put('syncAccount', netsuiteBody);
        } else {
            String netsuiteBody = creatingMember(ems, null);
            jsonMappingObject.put('syncAccount', netsuiteBody);
        }        
        jsonMappingObject.put('items', buildSalesItem(ems));

        String jsonString = JSON.serialize(jsonMappingObject);       
        return jsonString;
    }



    public  string creatingMember(EMS__c ems, String isEntityIdPresent) {
        Map<String, String> memberMapping = new Map<String, String>();
        if (isEntityIdPresent != null) {
            memberMapping.put('id', isEntityIdPresent);
        }
        //ems.Event__r.BillFromProject__r.Project_Code__c;
        memberMapping.put('companyname', ems.Bill_To_Account__r.Name);
        String name = ems.Bill_To_Account__r.Name + '-LF' ;
        if (name.length() > 80) {         
            name = ems.Bill_To_Account__r.Name.substring(0, 70) + ' - LF';// + ems.Event__r.BillFromProject__r.project_code__c;
        }
        if (isEntityIdPresent == null){
            memberMapping.put('entityid', name);
        }
        
        memberMapping.put('subsidiary', String.valueOf(ems.Bill_From__r.Subsidiary_ID__c));       
        memberMapping.put('recordtype', 'customer');
        memberMapping.put('url', null);
        memberMapping.put('phone', null);
        
        String billingStreet = ems.Bill_To_Account__r.BillingStreet != null ? ems.Bill_To_Account__r.BillingStreet : '';
        memberMapping.put('addr1',billingStreet);  
        
        String billingCity = ems.Bill_To_Account__r.BillingCity != null ? ems.Bill_To_Account__r.BillingCity : '';
        memberMapping.put('city',billingCity);  
        
        String billingPostalCode = ems.Bill_To_Account__r.BillingPostalCode != null ? ems.Bill_To_Account__r.BillingPostalCode : '';
        memberMapping.put('zip',billingPostalCode);  
        
        String billingState = ems.Bill_To_Account__r.BillingState != null ? ems.Bill_To_Account__r.BillingState : '';
        memberMapping.put('state',billingState);  
        
        String billingCountry = ems.Bill_To_Account__r.billingCountry != null ? AssetToSalesOrderHelper.convertingCountry( ems.Bill_To_Account__r.billingCountry, false) : '';
        memberMapping.put('country',billingCountry); 
        
        return JSON.serialize(memberMapping);
    }

    private List<Object> buildSalesItem(EMS__c ems) {
        List<Object> itemList = new List<Object>();
        Map<String, Object> salesLineItem = new map<String, Object>();
        salesLineItem.put('item', ems.Product__c);
        salesLineItem.put('price', 1);
        salesLineItem.put('description', ems.Description__c);
        salesLineItem.put('amount', ems.Amount__c);
        salesLineItem.put('quantity', 1);
        salesLineItem.put('job',ems.Jobcode__c);
        String startDate = ems.StartDate__c.month()  + '/'+ ems.StartDate__c.day() + '/' + ems.StartDate__c.year(); 
        salesLineItem.put('revrecstartdate', startDate);
        salesLineItem.put('revrecenddate', startDate);
        itemList.add(salesLineItem);
        return itemList;
    }

    private String getBillToAddress(EMS__c ems) {
        String billToAddress = '';
        if (ems.Bill_To_Account__c != null) {
            String convertedCountry = '', country = '';            
            convertedCountry = AssetToSalesOrderHelper.convertingCountry(ems.Bill_To_Account__r.billingCountry, true);            
            if (convertedCountry != null) {
                country = convertedCountry.capitalize();
            }
            String street = ems.Bill_To_Account__r.billingstreet != null ? ems.Bill_To_Account__r.billingstreet : '' ;
            String city = ems.Bill_To_Account__r.billingcity != null ? ems.Bill_To_Account__r.billingcity : '' ;
            String state = ems.Bill_To_Account__r.billingstate != null ? ems.Bill_To_Account__r.billingstate : '' ;
            String Postalcode = ems.Bill_To_Account__r.billingPostalCode != null ? ems.Bill_To_Account__r.billingPostalCode : '' ;
            String checkCountry = country != null ? country : '' ;
            if (String.isNotEmpty(street)) {
                billToAddress = ems.Bill_To_Account__r.Name + '\n' + street + '\n' + city + ' ' + state + ' ' + PostalCode + '\n' + checkCountry;
            }
        }       
        return billToAddress;
    }
}