force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Manual_Status_Check__c.field-meta.xml
<CustomField>
    <fullName>Manual_Status_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchUpdateAccountPicklistTest.cls
@IsTest
public class BatchUpdateAccountPicklistTest {

    @IsTest
    static void UpdatePicklistSuccessTest() {
        //Id directedProjectId = [Select Id, Name From RecordType Where SobjectType = 'Project__c' and Name='Subproject'].Id;
        
        Project__c proj = new Project__c();
        proj.Name = 'testProject';
        proj.Category__c = 'Incorporated Entity';
        proj.Status__c = 'Planned';
        proj.Type__c = 'Membership';
        proj.Manual_Status_Check__c = false;
        proj.Slug__c = 'test_slug';
        insert proj;
        
        Project__c Proj1 = new Project__c();
        proj1.Category__c = 'Incorporated Entity';
        proj1.Status__c = 'Planned';
        proj1.Type__c = 'Membership';
        proj1.Manual_Status_Check__c = false;
        proj1.Name = 'testProject1';
        proj1.Slug__c = 'test_slug1';
        insert proj1;
        
        proj.Status__c = 'Active';
        proj.Manual_Status_Check__c = false;
        update proj;
        
        proj1.Status__c = 'Active';
        proj1.Manual_Status_Check__c = false;
        update proj1;
        
        
        Test.startTest();
        Test.setMock(WebServiceMock.class, new MetadataServiceTest.WebServiceMockImpl(true));
        BatchUpdateAccountPicklist picklistUpdate = new BatchUpdateAccountPicklist();
        Database.executeBatch(picklistUpdate);
        Test.stopTest();
        
        
    }

    @IsTest
    static void UpdatePicklistErrorTest() {
        //Id directedProjectId = [Select Id, Name From RecordType Where SobjectType = 'Project__c' and Name='Subproject'].Id;
        
        Project__c proj = new Project__c();
        proj.Name = 'testProject';
        proj.Category__c = 'Incorporated Entity';
        proj.Status__c = 'Planned';
        proj.Type__c = 'Membership';
        proj.Manual_Status_Check__c = false;
        proj.Slug__c = 'test_slug';
        insert proj;
        
        Project__c Proj1 = new Project__c();
        proj1.Category__c = 'Incorporated Entity';
        proj1.Status__c = 'Planned';
        proj1.Type__c = 'Membership';
        proj1.Manual_Status_Check__c = false;
        proj1.Name = 'testProject1';
        proj1.Slug__c = 'test_slug1';
        insert proj1;
        
        proj.Status__c = 'Active';
        proj.Manual_Status_Check__c = false;
        update proj;
        
        proj1.Status__c = 'Active';
        proj1.Manual_Status_Check__c = false;
        update proj1;
        
        Test.setMock(WebServiceMock.class, new MetadataServiceTest.WebServiceMockImpl(false));
        try{
            Test.startTest();
            BatchUpdateAccountPicklist picklistUpdate = new BatchUpdateAccountPicklist();
            Database.executeBatch(picklistUpdate);
            
            Test.stopTest();
        }catch(Exception e){
            
        }
        
    }
    
}