force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectBenchmarkInput__c/ProjectBenchmarkInput__c.object-meta.xml
<CustomObject>
    <description>Defines multiplier for input into a Projects Scorecard</description>
    <label>Project Benchmark Input</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Benchmark Inputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/BenchmarkInputType__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkInputType__c</fullName>
    <description>The Type of Input used for the Benchmark</description>
    <inlineHelpText>The Type of Input used for the Benchmark</inlineHelpText>
    <label>Benchmark Input Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BenchmarkInputType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Project Benchmark Input Types Related To</description>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Project__c.Project_Status__c</field>
            <operation>equals</operation>
            <value>Formation - Engaged, Formation - Confidential, Active</value>
        </filterItems>
        <infoMessage>Project Stage must be Formation - Engaged, Formation - Confidential or Active</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Benchmark Inputs</relationshipLabel>
    <relationshipName>ProjectBenchmarkInputsProject</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/BenchmarkInputType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PersonOrgCertCnt</fullName>
        <label>Associated Person Certifications</label>
    </customValue>
    <customValue>
        <fullName>BoardMeetingAttendCnt</fullName>
        <label>Board Meetings Attended</label>
    </customValue>
    <customValue>
        <fullName>CodeCommitCnt</fullName>
        <label>Code Commits</label>
    </customValue>
    <customValue>
        <fullName>EvntAttendCnt</fullName>
        <label>Event Attendence</label>
    </customValue>
    <customValue>
        <fullName>ForumContribCnt</fullName>
        <label>Forum Contributions</label>
    </customValue>
    <customValue>
        <fullName>QBRAttendCnt</fullName>
        <label>QBR Attendence</label>
    </customValue>
    <customValue>
        <fullName>TrainingCmpltCnt</fullName>
        <label>Training Completed</label>
    </customValue>
    <masterLabel>Benchmark Input Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectBenchmarkInputTriggerHandler.cls
/**
ProjectBenchmarkInput trigger handler
@author (c) Idea Science  2023
*
* History
* *******
* Date       By             Ticket      Change
* *********  *************  **********  **************************************
* 17FEB2023	 Craig Jackson	LF240-271   Initial Version
*/
public with sharing class ProjectBenchmarkInputTriggerHandler implements ITriggerHandler {

    public void beforeDelete(Map<Id, SObject> oldMap) {
        return;
    }

    //This method will handle before insert method
    public void beforeInsert(List<SObject> newItems) {
        createName((List<ProjectBenchmarkInput__c>) newItems);
    }

    public void beforeUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        List<ProjectBenchmarkInput__c> recLst = new List<ProjectBenchmarkInput__c>();

        // Check if Project and/or Membership Level has changed
        for (Id recId : newMap.keySet()) {
            ProjectBenchmarkInput__c newRec = (ProjectBenchmarkInput__c) newMap.get(recId);
            ProjectBenchmarkInput__c oldRec = (ProjectBenchmarkInput__c) oldMap.get(recId);
            if ((newRec.Project__c            != oldRec.Project__c) || 
                (newRec.BenchmarkInputType__c != oldRec.BenchmarkInputType__c)|| 
                (newRec.Name                  != oldRec.Name)) {
                recLst.add(newRec);
            }

            if (recLst.size() > 0) {
                createName(recLst);
            }
        }
        return;
    }

    public void afterInsert(Map<Id, SObject> newMap) {
        return;
    }

    public void afterUpdate(Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        return;
    }

    public void afterDelete(Map<Id, SObject> oldMap) {
        return;
    }

    public void afterUndelete(Map<Id, SObject> newMap) {
        return;
    }

    public Boolean isDisabled() {
        return false;
    }

    /*
    ** createName - Update the name as Project Name - Membership Level
    */
    private static void createName(List<ProjectBenchmarkInput__c> newItems){
        List<Id> projectIds = new List<Id>();

        // Get List of Projects
        for(ProjectBenchmarkInput__c prgMemBMark : newItems){
            if (!projectIds.contains(prgMemBMark.Project__c)) {
                projectIds.add(prgMemBMark.Project__c);
            }
        }

        // Select Projects
        Map<Id, Project__c> prjIdMap = new Map<Id, Project__c>([SELECT Id, Name FROM Project__c WHERE Id IN :projectIds]);

        // Build Name field
        for(ProjectBenchmarkInput__c prgMemBMark : newItems) {
            prgMemBMark.Name = prjIdMap.get(prgMemBMark.Project__c).Name + ' - ' + prgMemBMark.BenchmarkInputType__c;
        }
    }
}