force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectBenchmarkInput__c/ProjectBenchmarkInput__c.object-meta.xml
<CustomObject>
    <description>Defines multiplier for input into a Projects Scorecard</description>
    <label>Project Benchmark Input</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Benchmark Inputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/BenchmarkInputType__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkInputType__c</fullName>
    <description>The Type of Input used for the Benchmark</description>
    <inlineHelpText>The Type of Input used for the Benchmark</inlineHelpText>
    <label>Benchmark Input Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BenchmarkInputType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Project Benchmark Input Types Related To</description>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Project__c.Project_Status__c</field>
            <operation>equals</operation>
            <value>Formation - Engaged, Formation - Confidential, Active</value>
        </filterItems>
        <infoMessage>Project Stage must be Formation - Engaged, Formation - Confidential or Active</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Benchmark Inputs</relationshipLabel>
    <relationshipName>ProjectBenchmarkInputsProject</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/ProjectMembershipBenchmark__c.object-meta.xml
<CustomObject>
    <label>Project Membership Benchmark</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Membership Benchmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Project Stage must be Formation - Engaged, Formation - Confidential or Active</errorMessage>
        <filterItems>
            <field>Project__c.Project_Status__c</field>
            <operation>equals</operation>
            <value>Formation - Engaged, Formation - Confidential, Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Membership Benchmarks</relationshipLabel>
    <relationshipName>ProjectMembershipBenchmarks_Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/BenchmarkInputType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PersonOrgCertCnt</fullName>
        <label>Associated Person Certifications</label>
    </customValue>
    <customValue>
        <fullName>BoardMeetingAttendCnt</fullName>
        <label>Board Meetings Attended</label>
    </customValue>
    <customValue>
        <fullName>CodeCommitCnt</fullName>
        <label>Code Commits</label>
    </customValue>
    <customValue>
        <fullName>EvntAttendCnt</fullName>
        <label>Event Attendence</label>
    </customValue>
    <customValue>
        <fullName>ForumContribCnt</fullName>
        <label>Forum Contributions</label>
    </customValue>
    <customValue>
        <fullName>QBRAttendCnt</fullName>
        <label>QBR Attendence</label>
    </customValue>
    <customValue>
        <fullName>TrainingCmpltCnt</fullName>
        <label>Training Completed</label>
    </customValue>
    <masterLabel>Benchmark Input Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectBenchmarkInputTriggerHandler_Test.cls
/**
ProjectBenchmarkInput trigger handler Test Coverage
@author (c) Idea Science  2023
*
* History
* *******
* Date       By             Ticket      Change
* *********  *************  **********  **************************************
* 21FEB2023  Craig Jackson  LF240-271   Initial Version
*/
@isTest
public class ProjectBenchmarkInputTriggerHandler_Test {

    //
    // Test Happy Path for Insert
    // Expect Name to be changed and Benchmark Input Records to be created
    //
    @isTest
    static void insertHappyPath() {
        Schema.DescribeFieldResult fieldResult = ProjectBenchmarkInput__c.BenchmarkInputType__c.getDescribe();
        List<Schema.PicklistEntry> ple         = fieldResult.getPicklistValues();
        String projectName  = 'PBI Test';
        String inputType    = ple[0].getValue();
        String expectedName = projectName + ' - ' + inputType;
        Project__c prj      = TestDataFactory.getProject(projectName, true);

        // Setup ProjectMembershipBenchmark__c
        ProjectBenchmarkInput__c pbi = TestDataFactory.getProjectBenchmarkInput(prj, inputType, false);

        // Insert ProjectMembershipBenchmark__c
        Test.startTest();
        insert pbi;
        Test.stopTest();

        // Assert Record created and Name changed
        List<ProjectBenchmarkInput__c> actualLst = [SELECT Id, Name FROM ProjectBenchmarkInput__c];
        Assert.isTrue(actualLst.size() == 1, 'Expected 1 ProjectMembershipBenchmark__c record to be found');
        Assert.areEqual(expectedName, actualLst[0].name);
    }

    //
    // Test Happy Path for Update
    // Expect Name to be changed and no extra Benchmark Input Records to be created
    //
    @isTest
    static void updateHappyPath() {
        Schema.DescribeFieldResult fieldResult = ProjectBenchmarkInput__c.BenchmarkInputType__c.getDescribe();
        List<Schema.PicklistEntry> ple         = fieldResult.getPicklistValues();
        String projectName  = 'PBI Test';
        String inputType    = ple[0].getValue();
        String expectedName = projectName + ' - ' + inputType;
        Project__c prj      = TestDataFactory.getProject(projectName, true);

        // Setup ProjectBenchmarkInput__c
        ProjectBenchmarkInput__c pbi = TestDataFactory.getProjectBenchmarkInput(prj, inputType, false);
        insert pbi;

        // Assert Record created and Name changed
        List<ProjectBenchmarkInput__c> actualLst = [SELECT Id, Name FROM ProjectBenchmarkInput__c];
        Assert.isTrue(actualLst.size()==1, 'Expected 1 ProjectBenchmarkInput__c record to be found');
        Assert.areEqual(expectedName, actualLst[0].name);

        // Update Name
        pbi.Name = 'Changed';

        // Update ProjectMembershipBenchmark__c
        Test.startTest();
        update pbi;
        Test.stopTest();

        // Assert Record Name updated
        List<ProjectBenchmarkInput__c> actualLst2 = [SELECT Id, Name FROM ProjectBenchmarkInput__c];
        Assert.isTrue(actualLst2.size() == 1, 'Expected 1 ProjectBenchmarkInput__c record to be found');
        Assert.areEqual(expectedName, actualLst2[0].name);
    }

    //
    // Test Happy Path for Delete
    // No extra coding exists for delete and undelete so just for code coverage
    //
    @isTest
    static void deleteHappyPath() {
        Schema.DescribeFieldResult fieldResult = ProjectBenchmarkInput__c.BenchmarkInputType__c.getDescribe();
        List<Schema.PicklistEntry> ple         = fieldResult.getPicklistValues();
        String projectName  = 'PBI Test';
        String inputType    = ple[0].getValue();
        Project__c prj      = TestDataFactory.getProject(projectName, true);

        // Setup ProjectBenchmarkInput__c
        ProjectBenchmarkInput__c pbi = TestDataFactory.getProjectBenchmarkInput(prj, inputType, true);

        // Assert Record created and Name changed
        List<ProjectBenchmarkInput__c> actualLst = [SELECT Id, Name FROM ProjectBenchmarkInput__c];
        Assert.isTrue(actualLst.size()==1, 'Expected 1 ProjectBenchmarkInput__c record to be found');

        // Delete ProjectBenchmarkInput__c
        Test.startTest();
        delete pbi;

        // Assert Record Deleted
        List<ProjectBenchmarkInput__c> actualLst2 = [SELECT Id, Name FROM ProjectBenchmarkInput__c];
        Assert.isTrue(actualLst2.size()==0, 'Expected 0 ProjectBenchmarkInput__c record to be found');

        // Undelete ProjectBenchmarkInput__c
        undelete pbi;
        Test.stopTest();

        // Assert Record Undeleted
        List<ProjectBenchmarkInput__c> actualLst3 = [SELECT Id, Name FROM ProjectBenchmarkInput__c];
        Assert.isTrue(actualLst3.size() == 1, 'Expected 1 ProjectBenchmarkInput__c record to be found');
    }

    //
    // Should not be able to create multiple records with the same Project/Membership combination
    // Expect Exception to be thrown
    //
    @isTest
    static void insertDuplicateCheck() {
        Schema.DescribeFieldResult fieldResult = ProjectBenchmarkInput__c.BenchmarkInputType__c.getDescribe();
        List<Schema.PicklistEntry> ple         = fieldResult.getPicklistValues();
        String projectName  = 'PBI Test';
        String inputType    = ple[0].getValue();
        Project__c prj      = TestDataFactory.getProject(projectName, true);

        // Setup ProjectBenchmarkInput__c
        ProjectBenchmarkInput__c pbi     = TestDataFactory.getProjectBenchmarkInput(prj, inputType, false);
        ProjectBenchmarkInput__c pbiDupe = TestDataFactory.getProjectBenchmarkInput(prj, inputType, false);
        insert pbi;

        // Attempt to insert duplicate ProjectMembershipBenchmark__c
        Test.startTest();
        try {
            insert pbiDupe;
            Assert.fail('Expected Duplicate Reocrd to thrown an Exception');
        } catch (Exception ex) {
            Assert.areEqual(ex.getTypeName(), 'System.DmlException', 'Expected DmlException to be thrown');
        }
        Test.stopTest();

    }
}