force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Assignment_Agreement_URL__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Agreement_URL__c</fullName>
    <description>This field is applicable to Incorporated Entities, Subprojects, Series LLCs, and Unofficial Subprojects. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Assignment Agreement Link field on page layouts instead.)</description>
    <label>Assignment Agreement File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Dissolution_Document_URL__c.field-meta.xml
<CustomField>
    <fullName>Dissolution_Document_URL__c</fullName>
    <label>Dissolution Document File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Governance_Document_URL__c.field-meta.xml
<CustomField>
    <fullName>Governance_Document_URL__c</fullName>
    <description>This field is only applicable to Incorporated Entities. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Governance Document Link field on page layouts instead.)</description>
    <label>Governance Document File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/MasterServiceAgreementURL__c.field-meta.xml
<CustomField>
    <fullName>MasterServiceAgreementURL__c</fullName>
    <description>This field is only applicable to Incorporated Entities. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Management Services Agreement Link field on page layouts instead.)</description>
    <label>Management Services Agreement File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Entity_Dissolution_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Entity_Dissolution_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was terminated.  For Incorporated Entities, the date the project dissolution was accepted by the Secretary of State. For Subprojects, the date the project was deemed no longer in operation.</inlineHelpText>
    <label>Dissolution/End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Entity_Formation_Document__c.field-meta.xml
<CustomField>
    <fullName>Project_Entity_Formation_Document__c</fullName>
    <description>This field is only applicable to Incorporated Entities. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Incorporation Document Link field on page layouts instead.)</description>
    <label>Incorporation Document File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Entity_MSA_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Entity_MSA_Date__c</fullName>
    <description>This field is only applicable to Incorporated Entities.</description>
    <inlineHelpText>Date that the management services agreement takes effect.</inlineHelpText>
    <label>Management Services Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <inlineHelpText>The &quot;Prospect&quot; stage is reserved for non-LF projects, e.g. some Community Bridge projects.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Formation - Exploratory</fullName>
            </value>
            <value>
                <fullName>Formation - Engaged</fullName>
            </value>
            <value>
                <fullName>Formation - Confidential</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Formation - On Hold</fullName>
            </value>
            <value>
                <fullName>Formation - Disengaged</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Actively Engaged</fullName>
                <isActive>false</isActive>
                <label>Actively Engaged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Series_Agreement_URL__c.field-meta.xml
<CustomField>
    <fullName>Series_Agreement_URL__c</fullName>
    <description>This field is only applicable to Series LLCs. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Series Agreement Link field on page layouts instead.)</description>
    <label>Series Agreement File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProjectFileUploadControllerTest.cls
@isTest
private class ProjectFileUploadControllerTest {

	@isTest static void testSeriesAgreementUpload() {
        //prep data
        Id fileID = createFile();
        Id projID = TestDataUtils.createSeriesLLC();
        Date seriesAgreementDate = Date.newInstance(2000, 12, 31);
        
        //run method
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'series', seriesAgreementDate);
        
        //query updated Project and verify results
        Project__c updatedSeriesLLC = new Project__c();
        updatedSeriesLLC = [SELECT Series_Agreement_URL__c, Start_Date__c
                            FROM Project__c
                            WHERE Id = :projID];
        System.assertEquals(getFileURL(fileID), updatedSeriesLLC.Series_Agreement_URL__c);
        System.assertEquals(seriesAgreementDate, updatedSeriesLLC.Start_Date__c);
	}
    
    @isTest static void testAssignmentAgreementUpload() {
        //prep data
        Id fileID = createFile();
        Id projID = TestDataUtils.createSeriesLLC();
        
        //run method
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'assignment', null);
        
        //query updated Project and verify results
        Project__c updatedSeriesLLC = new Project__c();
        updatedSeriesLLC = [SELECT Assignment_Agreement_URL__c
                            FROM Project__c
                            WHERE Id = :projID];
        System.assertEquals(getFileURL(fileID), updatedSeriesLLC.Assignment_Agreement_URL__c);
	}
    
    @isTest static void testIncorporationDocumentUpload() {
        //prep data
        Id fileID = createFile();
        Id projID = createIncorporatedProject();
        Date incorporationDocumentDate = Date.newInstance(2000, 12, 31);
        
        //run method
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'incorporation', incorporationDocumentDate);
        
        //query updated Project and verify results
        Project__c updatedInc = new Project__c();
        updatedInc = [SELECT Project_Entity_Formation_Document__c, Start_Date__c
                      FROM Project__c
                      WHERE Id = :projID];
        System.assertEquals(getFileURL(fileID), updatedInc.Project_Entity_Formation_Document__c);
        System.assertEquals(incorporationDocumentDate, updatedInc.Start_Date__c);
	}
    
    @isTest static void testMSAUpload() {
        //prep data
        Id fileID = createFile();
        Id projID = createIncorporatedProject();
        Date msaDate = Date.newInstance(2000, 12, 31);
        
        //run method
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'msa', msaDate);
        
        //query updated Project and verify results
        Project__c updatedInc = new Project__c();
        updatedInc = [SELECT MasterServiceAgreementURL__c, Project_Entity_MSA_Date__c
                      FROM Project__c
                      WHERE Id = :projID];
        System.assertEquals(getFileURL(fileID), updatedInc.MasterServiceAgreementURL__c);
        System.assertEquals(msaDate, updatedInc.Project_Entity_MSA_Date__c);
	}
    
    @isTest static void testGovernanceDocumentUpload() {
        //prep data
        Id fileID = createFile();
        Id projID = createIncorporatedProject();
        
        //run method
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'governance', null);
        
        //query updated Project and verify results
        Project__c updatedInc = new Project__c();
        updatedInc = [SELECT Governance_Document_URL__c
                      FROM Project__c
                      WHERE Id = :projID];
        System.assertEquals(getFileURL(fileID), updatedInc.Governance_Document_URL__c);
	}
    
    @isTest static void testDissolutionDocumentUpload() {
        //prep data
        Id fileID = createFile();
        Id projID = createIncorporatedProject();
        Date dissolutionDocumentDate = Date.newInstance(2000, 12, 31);
        
        //run method
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'dissolution', dissolutionDocumentDate);
        
        //query updated Project and verify results
        Project__c updatedInc = new Project__c();
        updatedInc = [SELECT Dissolution_Document_URL__c, Project_Entity_Dissolution_Date__c
                      FROM Project__c
                      WHERE Id = :projID];
        System.assertEquals(getFileURL(fileID), updatedInc.Dissolution_Document_URL__c);
        System.assertEquals(dissolutionDocumentDate, updatedInc.Project_Entity_Dissolution_Date__c);
	}
    
    @isTest static void testPreventingUserAccess(){
        //create a standard user
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User u = new User();
        u.Alias = 'standUsr';
        u.Email='test@linuxfoundation.org';
        u.EmailEncodingKey='UTF-8';
        u.LastName='Testing';
        u.LanguageLocaleKey='en_US';
        u.LocaleSidKey='en_US';
        u.ProfileId = p.Id;
        u.TimeZoneSidKey='America/Los_Angeles';
        u.UserName='test@linuxfoundation.org';
        insert u;
        
        //create some project
        Id projectID = TestDataUtils.createSeriesLLC();
        
        //get standard user's edit access to that project
        Boolean result;
        System.runAs(u){
            result = ProjectFileUploadController.getUserEditAccess(projectID);
        }
        
        //verify standard user does not have access to use the file uploader
        System.assertEquals(false, result);
    }
    
    private static ID createFile(){
        //create new Content Version
        ContentVersion cv = new ContentVersion();
        cv.VersionData = Blob.valueOf('Test Content Data');
        cv.Title = 'test file';
        cv.PathOnClient = 'test.pdf';
        insert cv;
        
        //query new Content Version to get ContentDocumentId from it
        ContentVersion uploadedFile = new ContentVersion();
        uploadedFile = [SELECT ContentDocumentId
                        FROM ContentVersion
                        WHERE Id = :cv.Id];
        
        return uploadedFile.ContentDocumentId;
    }
    
    private static Id createIncorporatedProject(){
        Project__c inc = new Project__c();
        inc.Name = 'Test Inc';
        inc.Project_Status__c = 'Formation - Exploratory';
        inc.Category__c = 'Incorporated Project';
        inc.Slug__c = 'test-inc';
        insert inc;
        return inc.Id;
    }
    
    private static String getFileURL(ID fileID){
        //return URL of newly created file
        String baseURL = System.Url.getOrgDomainUrl().toExternalForm();
        return baseURL + '/lightning/r/ContentDocument/' + fileID + '/view';
    }

}