force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectBenchmarkInput__c/ProjectBenchmarkInput__c.object-meta.xml
<CustomObject>
    <description>Defines multiplier for input into a Projects Scorecard</description>
    <label>Project Benchmark Input</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Benchmark Inputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/BenchmarkInputType__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkInputType__c</fullName>
    <description>The Type of Input used for the Benchmark</description>
    <inlineHelpText>The Type of Input used for the Benchmark</inlineHelpText>
    <label>Benchmark Input Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BenchmarkInputType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Project Benchmark Input Types Related To</description>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Project__c.Project_Status__c</field>
            <operation>equals</operation>
            <value>Formation - Engaged, Formation - Confidential, Active</value>
        </filterItems>
        <infoMessage>Project Stage must be Formation - Engaged, Formation - Confidential or Active</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Benchmark Inputs</relationshipLabel>
    <relationshipName>ProjectBenchmarkInputsProject</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/ScoreMultiplier__c.field-meta.xml
<CustomField>
    <fullName>ScoreMultiplier__c</fullName>
    <description>The count will be multipled by this value when used in the benchmark</description>
    <inlineHelpText>The count will be multipled by this value when used in the benchmark</inlineHelpText>
    <label>Score Multiplier</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/UseInEvntBenchmark__c.field-meta.xml
<CustomField>
    <fullName>UseInEvntBenchmark__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use Input when calculating the Event Benchmark</description>
    <inlineHelpText>Use Input when calculating the Event Benchmark</inlineHelpText>
    <label>Use In Evnt Benchmark</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/UseInMemberBenchmark__c.field-meta.xml
<CustomField>
    <fullName>UseInMemberBenchmark__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use Input when calculating the Membership Benchmark</description>
    <inlineHelpText>Use Input when calculating the Membership Benchmark</inlineHelpText>
    <label>Use In Member Benchmark</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/UseInTandCBenchmark__c.field-meta.xml
<CustomField>
    <fullName>UseInTandCBenchmark__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use Input when calculating the Training and Certification Benchmark</description>
    <inlineHelpText>Use Input when calculating the Training and Certification Benchmark</inlineHelpText>
    <label>Use In Training and Cert Benchmark</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/ProjectMembershipBenchmark__c.object-meta.xml
<CustomObject>
    <label>Project Membership Benchmark</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Membership Benchmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/EventBenchmark__c.field-meta.xml
<CustomField>
    <fullName>EventBenchmark__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Event Benchmark Value Expected to be reached for the Project/Membership Level</description>
    <inlineHelpText>The Event Benchmark Value Expected to be reached for the Project/Membership Level</inlineHelpText>
    <label>Event Benchmark</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/EventMaxValue__c.field-meta.xml
<CustomField>
    <fullName>EventMaxValue__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Max Expected Event Benchmark Value Expected to enable progress bar to be displayed</description>
    <inlineHelpText>The Max Expected Event Benchmark Value Expected to enable progress bar to be displayed</inlineHelpText>
    <label>Event Max Value</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/MembershipBenchmark__c.field-meta.xml
<CustomField>
    <fullName>MembershipBenchmark__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Membership Benchmark Value Expected to be reached for the Project/Membership Level</description>
    <inlineHelpText>The Membership Benchmark Value Expected to be reached for the Project/Membership Level</inlineHelpText>
    <label>Membership Benchmark</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/MembershipLevel__c.field-meta.xml
<CustomField>
    <fullName>MembershipLevel__c</fullName>
    <description>The Project Membership Level</description>
    <inlineHelpText>The Project Membership Level</inlineHelpText>
    <label>Membership Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/MembershipMaxValue__c.field-meta.xml
<CustomField>
    <fullName>MembershipMaxValue__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Max Expected Membership Benchmark Value Expected to enable progress bar to be displayed</description>
    <inlineHelpText>The Max Expected Membership Benchmark Value Expected to enable progress bar to be displayed</inlineHelpText>
    <label>Membership Max Value</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Project Stage must be Formation - Engaged, Formation - Confidential or Active</errorMessage>
        <filterItems>
            <field>Project__c.Project_Status__c</field>
            <operation>equals</operation>
            <value>Formation - Engaged, Formation - Confidential, Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Membership Benchmarks</relationshipLabel>
    <relationshipName>ProjectMembershipBenchmarks_Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/TandCBenchmark__c.field-meta.xml
<CustomField>
    <fullName>TandCBenchmark__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Training and Certification Benchmark Value Expected to be reached for the Project/Membership Level</description>
    <inlineHelpText>The Training and Certification Benchmark Value Expected to be reached for the Project/Membership Level</inlineHelpText>
    <label>Training and Certification Benchmark</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/TandCMaxValue__c.field-meta.xml
<CustomField>
    <fullName>TandCMaxValue__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The Max Training and Certification Membership Benchmark Value Expected to enable progress bar to be displayed</description>
    <inlineHelpText>The Max Training and Certification Membership Benchmark Value Expected to enable progress bar to be displayed</inlineHelpText>
    <label>Training and Certification Max Value</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/BenchmarkInputType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PersonOrgCertCnt</fullName>
        <label>Associated Person Certifications</label>
    </customValue>
    <customValue>
        <fullName>BoardMeetingAttendCnt</fullName>
        <label>Board Meetings Attended</label>
    </customValue>
    <customValue>
        <fullName>CodeCommitCnt</fullName>
        <label>Code Commits</label>
    </customValue>
    <customValue>
        <fullName>EvntAttendCnt</fullName>
        <label>Event Attendence</label>
    </customValue>
    <customValue>
        <fullName>ForumContribCnt</fullName>
        <label>Forum Contributions</label>
    </customValue>
    <customValue>
        <fullName>QBRAttendCnt</fullName>
        <label>QBR Attendence</label>
    </customValue>
    <customValue>
        <fullName>TrainingCmpltCnt</fullName>
        <label>Training Completed</label>
    </customValue>
    <masterLabel>Benchmark Input Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SalesInsightController.cls
/**
LWC Controller for SalesInsight Components
@author (c) Idea Science  2023
*
* History
* *******
* Date       By             Ticket      Change
* *********  *************  **********  **************************************
* 23FEB2023  Craig Jackson  LF240-269   Initial Version
*/
public with sharing class SalesInsightController {

    //
    // hasConfig
    // Checks if a Sales Insight Configuration exists for a project
    //
    @AuraEnabled(cacheable=false)
    public static Boolean hasConfig(Id projectId) {
        // Look for ProjectMembershipBenchmark__c records for the Project
        List<ProjectMembershipBenchmark__c> pmbLst = [SELECT Id FROM ProjectMembershipBenchmark__c WHERE project__c = :projectId];

        // Select true/false depending if records found
        return(pmbLst.size() > 0);
    }

    //
    // getConfiguredProjectLst
    // Returns Unique list  of projects that currently have a benchmark configuration
    // First Map will be None
    //
    @AuraEnabled(cacheable=false)
    public static List<Project__c> getConfiguredProjectLst() {
        // Initialise map
        List<Project__c> prjLst = new List<Project__c>();

        // Put in the No Project records
        prjLst.add(new Project__c(id=null, Name='--None--'));

        // Get unique list of Projects using Group By
        for (AggregateResult ar : [SELECT Project__c, Project__r.Name ProjectName FROM ProjectMembershipBenchmark__c GROUP BY Project__c, Project__r.Name ORDER BY Project__r.Name]) {
            prjLst.add(new Project__c(id=(Id)ar.get('Project__c'), Name=(String)ar.get('ProjectName')));
        }

        // Return Map
        return(prjLst);
    }

    //
    // createSalesInsigtConfigForProject
    // Creates a Sales Insight Configuration for a project from 
    //
    @AuraEnabled(cacheable=false)
    public static void createSalesInsigtConfigForProject(Id projectId, Boolean overwriteExistingConfig, Id cloneFromProjectId) {

        // Make sure valid Project Passed
        List<Project__c> prjLst = [SELECT Id FROM Project__c WHERE Id = :projectId];
        if (prjLst.size() == 0) {
            throw new AuraHandledException('Project Does Not Exist');
        }

        // Look for Existing ProjectBenchmarkInputs__c Entries
        List<ProjectBenchmarkInput__c> pbiLst = [SELECT Id FROM ProjectBenchmarkInput__c WHERE project__c = :projectId];
        if (pbiLst.size() > 0) {
            if (overwriteExistingConfig) {
                delete pbiLst;
            } else {
                throw new AuraHandledException('Project Benchmark Input Records Already Exist for the Project');
            }
        }

        // Look for Existing ProjectMembershipBenchmark__c Entries
        List<ProjectMembershipBenchmark__c> pmbLst = [SELECT Id FROM ProjectMembershipBenchmark__c WHERE project__c = :projectId];
        if (pmbLst.size() > 0) {
            if (overwriteExistingConfig) {
                delete pmbLst;
            } else {
                throw new AuraHandledException('Project Membership Benchmark Records Already Exist for the Project');
            }
        }

        // Create Configuration
        if (cloneFromProjectId == null) {
            // Create Configuration using Metadata
            createConfigUsingMetadata(projectId);
        } else {
            // Clone Configuration
            createConfigUsingExisting(projectId, cloneFromProjectId);
        }
    }

    //
    // Helper Functions
    //

    //
    // createConfigUsingMetadata
    // Creates a Sales Insight Configuration for a project from MEtadata
    //
    private static void createConfigUsingMetadata(Id projectId) {

        // Create the ProjectMembershipBenchmark__c records
        // and the ProjectMembershipBenchmark__c trigger will create the Inputs

        // Get List of MembershipLevel__c Picklists
        Schema.DescribeFieldResult fieldResult = ProjectMembershipBenchmark__c.MembershipLevel__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

        // Add an entry for each MembershipLevel__c picklist value
        List<ProjectMembershipBenchmark__c> prjMBLst = new List<ProjectMembershipBenchmark__c>();
        for (Schema.PicklistEntry pickListVal : ple) {
            ProjectMembershipBenchmark__c prjMB = new ProjectMembershipBenchmark__c (
                Name = 'Will Be Overwriten'
                , Project__c             = projectId
                , MembershipLevel__c     = pickListVal.getValue()
                , EventBenchmark__c      = 50
                , EventMaxValue__c       = 100
                , MembershipBenchmark__c = 50
                , MembershipMaxValue__c  = 100
                , TandCBenchmark__c      = 50
                , TandCMaxValue__c       = 100
            );
            prjMBLst.add(prjMB);
        }

        // Add Project Benchmark Inputs
        if (prjMBLst.size() > 0) {
            insert prjMBLst;
        }
    }

    //
    // createConfigUsingMetadata
    // Creates a Sales Insight Configuration for a project from MEtadata
    //
    private static void createConfigUsingExisting(Id projectId, Id fromProjectId) {

        // Start with ProjectBenchmarkInputs
        List<ProjectBenchmarkInput__c> pbiLst = new List<ProjectBenchmarkInput__c>();
        for (ProjectBenchmarkInput__c pbiFrom : [SELECT Project__c
                                                        , BenchmarkInputType__c
                                                        , ScoreMultiplier__c
                                                        , UseInEvntBenchmark__c
                                                        , UseInMemberBenchmark__c
                                                        , UseInTandCBenchmark__c
                                                 FROM ProjectBenchmarkInput__c 
                                                 WHERE Project__c = :fromProjectId]) {
            ProjectBenchmarkInput__c pbiTo = new ProjectBenchmarkInput__c (
                Name                      = 'Project - ' + pbiFrom.BenchmarkInputType__c
                , Project__c              = projectId
                , BenchmarkInputType__c   = pbiFrom.BenchmarkInputType__c
                , ScoreMultiplier__c      = pbiFrom.ScoreMultiplier__c
                , UseInEvntBenchmark__c   = pbiFrom.UseInEvntBenchmark__c
                , UseInMemberBenchmark__c = pbiFrom.UseInMemberBenchmark__c
                , UseInTandCBenchmark__c  = pbiFrom.UseInTandCBenchmark__c
            );
            pbiLst.add(pbiTo);
        }

        // Add Project Benchmark Inputs
        if (pbiLst.size() > 0) {
            insert pbiLst;
        } else {
            throw new AuraHandledException('From Project does not have any Project Membership Benchmark Records');
        }

        // Add an entry for each BenchmarkInputType picklist
        List<ProjectMembershipBenchmark__c> pmbLst = new List<ProjectMembershipBenchmark__c>();
        for (ProjectMembershipBenchmark__c pmbFrom : [SELECT Project__c
                                                            , MembershipLevel__c
                                                            , EventBenchmark__c
                                                            , EventMaxValue__c
                                                            , MembershipBenchmark__c
                                                            , MembershipMaxValue__c
                                                            , TandCBenchmark__c
                                                            , TandCMaxValue__c
                                                      FROM ProjectMembershipBenchmark__c 
                                                      WHERE Project__c = :fromProjectId]) {
            ProjectMembershipBenchmark__c pmbTo = new ProjectMembershipBenchmark__c (
                Name                     = 'Project - ' + pmbFrom.MembershipLevel__c
                , Project__c             = projectId
                , MembershipLevel__c     = pmbFrom.MembershipLevel__c
                , EventBenchmark__c      = pmbFrom.EventBenchmark__c
                , EventMaxValue__c       = pmbFrom.EventMaxValue__c
                , MembershipBenchmark__c = pmbFrom.MembershipBenchmark__c
                , MembershipMaxValue__c  = pmbFrom.MembershipMaxValue__c
                , TandCBenchmark__c      = pmbFrom.TandCBenchmark__c
                , TandCMaxValue__c       = pmbFrom.TandCMaxValue__c
            );
            pmbLst.add(pmbTo);
        }

        // Add Project Benchmark Inputs
        if (pmbLst.size() > 0) {
            insert pmbLst;
        }
    }
}