force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Certification_ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>Certification_ExpirationDate__c</fullName>
    <label>Certification ExpirationDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <inlineHelpText>Completion for Elearning, ILT</inlineHelpText>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Exam_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Exam_Expiration_Date__c</fullName>
    <label>Exam Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <inlineHelpText>Expirationfor Elearning</inlineHelpText>
    <label>ExpirationDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Enrolled - Update status for , Course_purchase and when enrollment date is added
Started - Update status for Course_start and when start date is added
Completed -Update status for Course_complete and completed date is added
Expired - If complete date is null and Expired date is in past
Revoked - update for revoke_access
Not started - multiple enrollments when there is an record already with above statuses enrolled, started</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Not started</fullName>
            </value>
            <value>
                <fullName>Not Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchEnrollmentUpdateStatus.cls
public class BatchEnrollmentUpdateStatus implements Database.Batchable<sObject>,Schedulable {
    String query;
    public void execute(SchedulableContext sc){
        Database.executeBatch(new BatchEnrollmentUpdateStatus());
    }
    
    public BatchEnrollmentUpdateStatus(){
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        this.query ='SELECT Id,Status__c,Completion_Date__c,Start_Date__c,Exam_Expiration_Date__c,ExpirationDate__c,Certification_ExpirationDate__c FROM Enrollment__c WHERE (Status__c=\'Enrolled\' AND Start_Date__c !=null AND Start_Date__c <= Today)'+
            ' OR (Status__c=\'Started\' AND Completion_Date__c != null AND Completion_Date__c <= Today) OR'+
            ' ((Exam_Expiration_Date__c!= null OR ExpirationDate__c != null OR Certification_ExpirationDate__c !=null) AND (Exam_Expiration_Date__c <=Today OR ExpirationDate__c =Today OR Certification_ExpirationDate__c<=Today)'+
            ' AND Completion_Date__c = null AND Status__c NOT IN(\'Revoked\',\'Expired\',\'Not Certified\'))';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<Enrollment__c> enrollments){
        List<Enrollment__c> enrollmentToBeUpdated = new List<Enrollment__c>();
        for(Enrollment__c enrollment : enrollments){
            if(enrollment.Status__c == 'Enrolled'&& enrollment.Start_Date__c !=null && enrollment.Start_Date__c <= Date.today()){
                enrollment.Status__c = 'Started';
            }            
            if(enrollment.Status__c =='Started' && enrollment.Completion_Date__c != null && enrollment.Completion_Date__c <=  Date.today()){
                 enrollment.Status__c = 'Completed';
            }
            if(enrollment.Status__c !='Revoked' && enrollment.Status__c != 'Not Started' && enrollment.Completion_Date__c == null &&
               ((enrollment.Certification_ExpirationDate__c== null && (enrollment.Exam_Expiration_Date__c <=Date.today() || enrollment.ExpirationDate__c <= date.today()))
               || enrollment.Certification_ExpirationDate__c <= Date.today())){
                   enrollment.Status__c = 'Expired';
               }
            enrollmentToBeUpdated.add(enrollment);
        }
        
        if(!enrollmentToBeUpdated.IsEmpty()){
            update enrollmentToBeUpdated;
        }
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
}