force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <inlineHelpText>Expirationfor Elearning</inlineHelpText>
    <label>ExpirationDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Is_free__c.field-meta.xml
<CustomField>
    <fullName>Is_free__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/isBootcampbundle__c.field-meta.xml
<CustomField>
    <fullName>isBootcampbundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isBootcampbundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edx</fullName>
            </value>
            <value>
                <fullName>Panorama</fullName>
            </value>
            <value>
                <fullName>SugarCRM</fullName>
            </value>
            <value>
                <fullName>TI</fullName>
            </value>
            <value>
                <fullName>TI SCORM</fullName>
            </value>
            <value>
                <fullName>TI Panorama</fullName>
            </value>
            <value>
                <fullName>TI Other</fullName>
            </value>
            <value>
                <fullName>TI Purchase</fullName>
            </value>
            <value>
                <fullName>QuickStart</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignMemberExpirationBatchTest.cls
@isTest
public class CampaignMemberExpirationBatchTest {
    @isTest
    public static void upsertCampaignMember(){
        Account account = new Account (Name = 'Acme, Inc.');
        insert account;
        system.debug('Inserted Account, ID: ' + account.id);
        
        Contact contact = new Contact(
            FirstName = 'Robin',
            LastName = 'Koehler',
            AccountId = account.Id
        );
        insert contact;   
        
        Product2 product = new Product2(Name = 'TestP', productcode = 'campaign', isActive = true);
        insert product;
        
        Enrollment__c enrollment = new Enrollment__c();
        enrollment.Name = 'Test enrollment';
        enrollment.Contact_Name__c = contact.Id;
        enrollment.Product_Name__c = product.Id;
        enrollment.Is_free__c = true;
        enrollment.Source__c ='SugarCRM';
        enrollment.Amount__c  = 100;
        enrollment.ExpirationDate__c = System.today()-1;
        enrollment.isBootcampbundle__c = true;
        insert enrollment;
        
        Campaign parentCampaign = new Campaign(
            Name = 'LF Training Bootcamp June 2020',
            IsActive = TRUE
        );            
        insert parentCampaign;
        
        
        Campaign campaign = new Campaign(
            Name = 'Test campaign',
            IsActive = TRUE,
            ParentId = parentCampaign.id
        );            
        insert campaign;
        
        List<Campaign> campaigns = [SELECT Id,Name FROM Campaign WHERE Parent.Name='LF Training Bootcamp June 2020' ];
        System.debug('campaigns'+campaigns);
        CampaignMember member = new CampaignMember(
            ContactId = contact.Id,
            Status = 'sent',
            CampaignId = campaign.Id
        ); 
        insert member;
        CampaignMemberStatus newStatus = new CampaignMemberStatus(
            CampaignID=campaign.id,
            Label='Expired',
            IsDefault=false,
            HasResponded=false,
            SortOrder=3
        );

insert newStatus;
        Test.startTest();
        Database.executeBatch(new CampaignMemberExpirationBatch());
        Test.stopTest();
        
        System.assertEquals('Expired', [SELECT id,Status FROM CampaignMember WHERE CampaignId =: campaign.Id][0].Status);
    }
}