force-app/main/default/objects/Alternate_Email__c/Alternate_Email__c.object-meta.xml
<CustomObject>
    <label>Alternate Email</label>
    <nameField>
        <displayFormat>AE-{000}</displayFormat>
        <label>Alternate Email ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternate Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alternate_Email__c/fields/Alternate_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email_Address__c</fullName>
    <externalId>true</externalId>
    <label>Alternate Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>EndTime</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Meeting_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Attendees__c</fullName>
    <description>Meeting Attendees Count</description>
    <inlineHelpText>Meeting Attendees Count</inlineHelpText>
    <label>Meeting Attendees</label>
    <summaryForeignKey>Meeting_Attendees__c.Meeting__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Meeting_Detail__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Detail__c</fullName>
    <label>Meeting Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>StartTime</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>End</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please select meeting type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meeting</fullName>
                <default>true</default>
                <label>Meeting</label>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Meeting_Attendees__c/Meeting_Attendees__c.object-meta.xml
<CustomObject>
    <label>Meeting Attendees</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Meeting Attendee</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting_Attendees__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Alternate Email</label>
    <referenceTo>Alternate_Email__c</referenceTo>
    <relationshipLabel>Meeting Attendees</relationshipLabel>
    <relationshipName>Meeting_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting_Attendees__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Meeting Attendees</relationshipLabel>
    <relationshipName>Meeting_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting_Attendees__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Meeting Attendees</relationshipLabel>
    <relationshipName>Meeting_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Meeting_Attendees__c/fields/Meeting__c.field-meta.xml
<CustomField>
    <fullName>Meeting__c</fullName>
    <label>Meeting</label>
    <referenceTo>Meeting__c</referenceTo>
    <relationshipLabel>Meeting Attendees</relationshipLabel>
    <relationshipName>Meeting_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Meeting_Attendees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Denied</fullName>
                <isActive>false</isActive>
                <label>Denied</label>
            </value>
            <value>
                <fullName>Invited</fullName>
                <isActive>false</isActive>
                <label>Invited</label>
            </value>
            <value>
                <fullName>Pending for approval</fullName>
                <isActive>false</isActive>
                <label>Pending for approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TuxRewardsCampaignData__c/TuxRewardsCampaignData__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Tux Rewards Campaign Data</label>
</CustomObject>

force-app/main/default/objects/TuxRewardsCampaignData__c/fields/Campaign_ID__c.field-meta.xml
<CustomField>
    <fullName>Campaign_ID__c</fullName>
    <label>Campaign ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MeetingAttendeeTriggerHandlerTest.cls
@isTest
public class MeetingAttendeeTriggerHandlerTest {
    
    public static testmethod void TestDataSetup(){        
        Meeting__c objMeeting = new Meeting__c(
            Name='Test Meeting',
            Subject__c='Test Subject',
            Meeting_Detail__c='Discussion',
            StartDate__c=Date.today(),
            EndDate__c=Date.today(),
            Type__c ='Webinar',
            StartTime__c=Time.newInstance(18, 30, 2, 00),
            EndTime__c=Time.newInstance(19, 30, 2, 00));
        insert objMeeting;
        
        Alternate_Email__c objAlEmail = new Alternate_Email__c(
        Alternate_Email_Address__c ='abc@sforce.com'
        );
        insert objAlEmail;
        
        Meeting_Attendees__c objMeetingAttendees = new Meeting_Attendees__c(
            Meeting__c =objMeeting.id,
             Contact__c = TestFactory.getContact().id ,
            Alternate_Email__c = objAlEmail.id);
           
        insert objMeetingAttendees;
		System.assertEquals(1,[SELECT count() FROM CampaignMember WHERE ContactID =:objMeetingAttendees.Contact__c ]  );      
       
    }
    public static testmethod void TestDataSetup1(){
       
        Meeting__c objMeeting = new Meeting__c(
            Name='Test Meeting',
            Subject__c='Test Subject',
            Meeting_Detail__c='Discussion',
            StartDate__c=Date.today()-10,
            EndDate__c=Date.today()-7,
            Type__c ='Webinar',
            StartTime__c=Time.newInstance(18, 30, 2, 00),
            EndTime__c=Time.newInstance(19, 30, 2, 00));
        insert objMeeting;
        
        Alternate_Email__c objAlEmail = new Alternate_Email__c(
        Alternate_Email_Address__c ='abc@sforce.com'
        );
        insert objAlEmail;
        
        Meeting_Attendees__c objMeetingAttendees = new Meeting_Attendees__c(
            Meeting__c =objMeeting.id,
            Contact__c = TestFactory.getContact().id ,
            Alternate_Email__c = objAlEmail.id,
            Status__c = 'Registered');  
        insert objMeetingAttendees;
    
        objMeetingAttendees.Status__c = 'Attended';
        update objMeetingAttendees;
       	System.assertEquals(1,[SELECT count() FROM CampaignMember WHERE ContactID =:objMeetingAttendees.Contact__c AND Status='Attended' ]  );      

    }
    
    public static testmethod void TestDataSetup2(){      
        Meeting__c objMeeting = new Meeting__c(
            Name='Test Meeting',
            Subject__c='Test Subject',
            Meeting_Detail__c='Discussion',
            StartDate__c=Date.today()-10,
            EndDate__c=Date.today()-7,
            Type__c ='Webinar',
            StartTime__c=Time.newInstance(18, 30, 2, 00),
            EndTime__c=Time.newInstance(19, 30, 2, 00));
        	insert objMeeting;        
        
		Campaign camp=[Select Id From Campaign Where Name =: objMeeting.Name];
        TuxRewardsCampaignData__c tux = new TuxRewardsCampaignData__c(Name='campaign_name',Campaign_ID__c =objMeeting.Id);
        insert tux;
        delete camp;
        
        Alternate_Email__c objAlEmail = new Alternate_Email__c(
        Alternate_Email_Address__c ='abc@sforce.com'
        );
        insert objAlEmail;
        
        Meeting_Attendees__c objMeetingAttendees = new Meeting_Attendees__c(
            Meeting__c =objMeeting.id,
            Lead__c = TestFactory.getLead().id ,
            Alternate_Email__c = objAlEmail.id);
           
        insert objMeetingAttendees;
        System.assertEquals(1,[SELECT count() FROM CampaignMember WHERE LeadId =:objMeetingAttendees.Lead__c ]  ); 
        delete objMeetingAttendees;

    
    }
}