force-app/main/default/objects/Alternate_Email__c/Alternate_Email__c.object-meta.xml
<CustomObject>
    <label>Alternate Email</label>
    <nameField>
        <displayFormat>AE-{000}</displayFormat>
        <label>Alternate Email ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternate Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alternate_Email__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Alternate Emails</relationshipLabel>
    <relationshipName>Alternate_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alternate_Email__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Alternate Emails</relationshipLabel>
    <relationshipName>Alternate_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateAlternateEmailBatchTest.cls
@IsTest
public class CreateAlternateEmailBatchTest {
    @isTest public static void testInsertContact() 
    {
        List<Contact> lstContact= new List<Contact>();
        for(Integer i=0 ;i <200;i++)
        {
            Contact contact = new Contact();
            contact.lastName ='Name'+i;
            lstContact.add(contact);
        }
        
        insert lstContact;
        
        List<Alternate_Email__c> alternateEmails = [SELECT Id FROM ALternate_Email__c WHERE Contact_Name__c IN: lstContact];
        delete alternateEmails;
        Test.startTest();
        
        CreateAlternateEmailBatch jobObject = new CreateAlternateEmailBatch('Contact');
        DataBase.executeBatch(jobObject); 
        
        Test.stopTest();
    }
    
    @isTest 
    public static void testInsertlead() 
    {
        
        Lead lead = new lead();
        lead.lastName ='Name';
        lead.Email = 'testlead@noreply.com';
        insert lead;
        
        Test.startTest();
        
        List<Alternate_Email__c> alternateEmails = [SELECT Id FROM ALternate_Email__c WHERE Lead_Name__c =: lead.Id];
        delete alternateEmails;
        
        CreateAlternateEmailBatch jobObject = new CreateAlternateEmailBatch('Lead');
        DataBase.executeBatch(jobObject); 
        
        Test.stopTest();
    }
}