force-app/main/default/objects/Alternate_Email__c/Alternate_Email__c.object-meta.xml
<CustomObject>
    <label>Alternate Email</label>
    <nameField>
        <displayFormat>AE-{000}</displayFormat>
        <label>Alternate Email ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternate Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alternate_Email__c/fields/Alternate_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email_Address__c</fullName>
    <externalId>true</externalId>
    <label>Alternate Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Alternate_Email__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Alternate Emails</relationshipLabel>
    <relationshipName>Alternate_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alternate_Email__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Alternate Emails</relationshipLabel>
    <relationshipName>Alternate_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alternate_Email__c/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreateAlternateEmailBatch.cls
public class CreateAlternateEmailBatch implements Database.Batchable<sObject> ,Schedulable {
    public String objectName;
    public String fieldName;
    public String andClause;
    public CreateAlternateEmailBatch(String objectName){
        this.objectName = objectName;
        if(objectName == 'Lead'){
            fieldName = 'Lead_Name__c';
            andClause = 'AND IsConverted = false AND Email != null';
        }
        else If(objectName == 'Contact'){
            fieldName = 'Contact_Name__c';
            andClause = 'AND Email != null';
        }
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        String query = 'SELECT Id,Email FROM ' + objectName + ' WHERE Id NOT IN (SELECT ' + fieldName + ' FROM Alternate_Email__c )' + andClause;
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope)
    {
        List<Alternate_Email__c> alternateEmailList = new List<Alternate_Email__c>();
        for(sObject obj: scope)
        {
            if((String)obj.get('Email') != ''){
                ALternate_Email__c alternateEmail = new Alternate_Email__c();
                alternateEmail.Alternate_Email_Address__c = (String)obj.get('Email');
                alternateEmail.put(fieldName,(String)obj.get('Id'));
                alternateEmail.Primary_Email__c = True;
                alternateEmail.Active__c = True;
                alternateEmailList.add(alternateEmail);
            }
        }
        Database.SaveResult[] resultList = Database.insert(alternateEmailList,false);
        for(Database.SaveResult result : resultList){
            if (result.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully inserted  ' + result.getId());
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : result.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                }
            }
        }
        
    }
    public void execute(SchedulableContext sc)
    {
        CreateAlternateEmailBatch alternateEmailbatch = new CreateAlternateEmailBatch(objectName);
        database.executebatch(alternateEmailbatch);
    }
    
    public void finish(Database.BatchableContext bc)
    {
        
    }
}