force-app/main/default/objects/Travel_Fund_Request__c/Travel_Fund_Request__c.object-meta.xml
<CustomObject>
    <label>Travel Fund Request</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Fund Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting Approval</fullName>
            </value>
            <value>
                <fullName>Request Approved - Waiting For Expense Report</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Expense Report Received - Waiting Final Approval</fullName>
            </value>
            <value>
                <fullName>Problem With Expense Report</fullName>
            </value>
            <value>
                <fullName>Expense Report Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Transferred to Another Event</fullName>
            </value>
            <value>
                <fullName>Unable to Use Funds</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>ExpenseReportWaitingFinal</fullName>
                <isActive>false</isActive>
                <label>ExpenseReportWaitingFinal</label>
            </value>
            <value>
                <fullName>InitialApproval</fullName>
                <isActive>false</isActive>
                <label>InitialApproval</label>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
                <isActive>false</isActive>
                <label>Partially Approved</label>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
                <isActive>false</isActive>
                <label>Partially Paid</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request_Line_Item__c/Travel_Fund_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Travel Fund Request Line Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Fund Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel_Fund_Request_Line_Item__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request_Line_Item__c/fields/Travel_Fund_Request__c.field-meta.xml
<CustomField>
    <fullName>Travel_Fund_Request__c</fullName>
    <label>Travel Fund Request</label>
    <referenceTo>Travel_Fund_Request__c</referenceTo>
    <relationshipLabel>Travel Fund Request Line Items</relationshipLabel>
    <relationshipName>Travel_Fund_Request_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TravelFundLineItemHandler.cls
public class TravelFundLineItemHandler {

    public void afterInsert(Map<id,Travel_Fund_Request_Line_Item__c> oldMap,Map<id,Travel_Fund_Request_Line_Item__c> newMap){
        insertUpdateMeth(null,newMap);
    }
    
    public void afterUpdate(Map<id,Travel_Fund_Request_Line_Item__c> oldMap,Map<id,Travel_Fund_Request_Line_Item__c> newMap){
        insertUpdateMeth(oldMap,newMap);
    }
    
    public void insertUpdateMeth(Map<id,Travel_Fund_Request_Line_Item__c> oldMap,Map<id,Travel_Fund_Request_Line_Item__c> newMap){
        set<id> fundRequestLineId = new set<id>();
        for(Travel_Fund_Request_Line_Item__c fundRequest : newMap.values()){
        if(fundRequest.Line_Status__c != null && (oldMap == null || (oldMap != null && fundRequest.Line_Status__c != oldMap.get(fundRequest.Id).Line_Status__c ))){
            fundRequestLineId.add(fundRequest.Travel_Fund_Request__c);
        }
        }
        travelLineItemUpdate(fundRequestLineId);
    }
    public void onAfterDelete(Map<id,Travel_Fund_Request_Line_Item__c> oldMap){
        set<id> fundRequestLineId = new set<id>();
        for(Travel_Fund_Request_Line_Item__c fundRequest : oldMap.values()){
            fundRequestLineId.add(fundRequest.Travel_Fund_Request__c);
        }
            travelLineItemUpdate(fundRequestLineId);
    }
    
    public void travelLineItemUpdate(set<id> fundRequestIds){
        List<Travel_Fund_Request__c> fundRequestList = [select id ,(select id,Line_Status__c,Travel_Fund_Request__c from Travel_Fund_Request_Line_Items__r) from Travel_Fund_Request__c where id in:fundRequestIds ] ;
        list<Travel_Fund_Request__c> updateValueFundRequest = new list<Travel_Fund_Request__c>();
        
        for(Travel_Fund_Request__c travelFundRequest : fundRequestList){
            if(checkRejectedStatus(travelFundRequest.Travel_Fund_Request_Line_Items__r))
            {
                travelFundRequest.Status__c = 'Rejected';
                updateValueFundRequest.add(travelFundRequest);
            }else if(checkPartiallyApprovedStatus(travelFundRequest.Travel_Fund_Request_Line_Items__r)){
                travelFundRequest.Status__c = 'Partially Approved';
                updateValueFundRequest.add(travelFundRequest);
            }
            
        }
        system.debug('@@data@@@ ' +updateValueFundRequest);
        if(updateValueFundRequest.size() > 0){
            update updateValueFundRequest;
        }
    }
    
    private boolean checkRejectedStatus(List<Travel_Fund_Request_Line_Item__c> fundRequestLineItem){
        boolean isRejected = true;
        for(Travel_Fund_Request_Line_Item__c item : fundRequestLineItem){
            if(item.Line_Status__c != 'Rejected')
            {
                isRejected = false;
                break;
            }
        }
        return isRejected;
    }
    
    private boolean checkPartiallyApprovedStatus(List<Travel_Fund_Request_Line_Item__c> fundRequestLineItem){
        boolean partiallyApproved = true;
        Integer approvedCount = 0;
        Integer rejectedCount = 0;
        for(Travel_Fund_Request_Line_Item__c item : fundRequestLineItem){
            system.debug('Line status ' + item.Line_Status__c);
            if(item.Line_Status__c != 'Rejected' && item.Line_Status__c != 'Approved')
            {
                partiallyApproved = false;
                break;
            }else
            {
                if(item.Line_Status__c == 'Rejected')
                    rejectedCount +=1;
                else if(item.Line_Status__c == 'Approved')
                    approvedCount +=1;
            }
        }
        system.debug('Partially Approved ' + partiallyApproved);
         system.debug('Rejected Count ' + rejectedCount);
        if(rejectedCount <= 0) //if no rejected
             partiallyApproved = false;
        return partiallyApproved;
    }
}