force-app/main/default/objects/Asset/fields/Annual_Full_Price__c.field-meta.xml
<CustomField>
    <fullName>Annual_Full_Price__c</fullName>
    <inlineHelpText>Annual amount for Membership. Full price of Sponsorship Level for Event.</inlineHelpText>
    <label>Annual/Full Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Deferred_Revenue_Account__c</fullName>
    <label>NetSuite Deferred Revenue Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_Department__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Department__c</fullName>
    <label>NetSuite Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Income_GL_Account__c</fullName>
    <label>NetSuite Income GL Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Revenue_Schedule__c</fullName>
    <label>NetSuite Revenue Schedule</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Number_of_Years_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_Required__c</fullName>
    <label>Number of Years Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <description>Prorate - Will prorate after the required number of years have been met. Standard.
Nonprorate - 12 month renewal on the 1st of the month. 
Annual - Anniversary - 12 month renewal based on anniversary date (not the 1st).</description>
    <inlineHelpText>Prorate - Will prorate after the required number of years have been met. Standard.
Nonprorate - 12 month renewal on the 1st of the month. 
Annual - Anniversary - 12 month renewal based on anniversary date (not the 1st).</inlineHelpText>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prorate</fullName>
            </value>
            <value>
                <fullName>Non-Prorate</fullName>
            </value>
            <value>
                <fullName>Calendar Year</fullName>
                <label>Annual - Anniversary</label>
            </value>
            <value>
                <fullName>Renewable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Tax_Class__c.field-meta.xml
<CustomField>
    <fullName>Tax_Class__c</fullName>
    <label>Tax Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Asset__c.field-meta.xml
<CustomField>
    <fullName>Parent_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Bypass_Validation__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field allows the ChangeProductUtil class to bypass a validation rule on this object.  Anytime you run a report on this field, it should be FALSE for *all* records.  This field should not be included on any page layouts; it should only be set by Apex.</description>
    <label>Bypass Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/End_Tier__c.field-meta.xml
<CustomField>
    <fullName>End_Tier__c</fullName>
    <label>End Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Deferred_Revenue_Account__c</fullName>
    <label>NetSuite Deferred Revenue Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Department__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Department__c</fullName>
    <label>NetSuite Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Income_GL_Account__c</fullName>
    <label>NetSuite Income GL Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Revenue_Schedule__c</fullName>
    <label>NetSuite Revenue Schedule</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Number_of_Years_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_Required__c</fullName>
    <label>Number of Years Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prorate</fullName>
            </value>
            <value>
                <fullName>Non-Prorate</fullName>
            </value>
            <value>
                <fullName>Calendar Year</fullName>
            </value>
            <value>
                <fullName>Renewable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Start_Tier__c.field-meta.xml
<CustomField>
    <fullName>Start_Tier__c</fullName>
    <label>Start Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Tax_Class__c.field-meta.xml
<CustomField>
    <fullName>Tax_Class__c</fullName>
    <label>Tax Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/End_Tier__c.field-meta.xml
<CustomField>
    <fullName>End_Tier__c</fullName>
    <label>End Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Netsuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>NS Item ID</inlineHelpText>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
            <value>
                <fullName>Straight Line</fullName>
                <isActive>false</isActive>
                <label>Straight Line</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Number_Of_Years_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Years_Required__c</fullName>
    <label>Number Of Years Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Number_Of_Years_Required</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prorate</fullName>
            </value>
            <value>
                <fullName>Non-Prorate</fullName>
            </value>
            <value>
                <fullName>Calendar Year</fullName>
            </value>
            <value>
                <fullName>Renewable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Start_Tier__c.field-meta.xml
<CustomField>
    <fullName>Start_Tier__c</fullName>
    <label>Start Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Tax_Class__c.field-meta.xml
<CustomField>
    <fullName>Tax_Class__c</fullName>
    <defaultValue>&quot;T1&quot;</defaultValue>
    <label>Tax Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Project_Role__c/Project_Role__c.object-meta.xml
<CustomObject>
    <label>Membership Roles</label>
    <nameField>
        <displayFormat>PR{000}</displayFormat>
        <label>Role AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Role__c/fields/Parent_Asset__c.field-meta.xml
<CustomField>
    <fullName>Parent_Asset__c</fullName>
    <formula>Opportunity__r.Parent_Asset__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Asset</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Deferred_Revenue_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>284</fullName>
        <label>Deferred Revenue : Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>282</fullName>
        <label>Deferred Revenue : Deferred Revenue - Membership</label>
    </customValue>
    <customValue>
        <fullName>4494</fullName>
        <label>Deferred Revenue : Deferred Revenue - Directed Funds</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Other</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Membership</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Membership</label>
    </customValue>
    <masterLabel>NetSuite Deferred Revenue Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Number_Of_Years_Required.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <default>true</default>
        <label>1</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <masterLabel>Number Of Years Required</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ChangeProductUtil.cls
public with sharing class ChangeProductUtil {
    
    //expects the ID of the OLI that needs to be updated, along with the ID of the Product Detail
    //that the OLI should be updated to
    @AuraEnabled
    public static void changeProductDetailOnOLI(Map<Id, Product_Details__c> oliIDToProdDetail, Map<Id, OpportunityLineItem> oliIdToOli){

        //TODO: bulkify method to accept a map of OLI IDs to PD IDs (instead of one of each)
        map<String, OpportunityLineItem> upsertOlis = new Map<String, OpportunityLineItem>();
        List<OpportunityLineItem> deleteOlis = new List<OpportunityLineItem>();
        Set<String> oliIDStrings = new Set<String>();
        Map<Id, Opportunity> updateOpp = new Map<Id, Opportunity>();

        System.debug('oliIDToProdDetail--'+oliIDToProdDetail);

        for(Id oliId : oliIDToProdDetail.keySet()){
            System.debug('oliId--'+oliID);
            OpportunityLineItem oli = oliIdToOli.get(oliId);
            Product_Details__c pd = oliIDToProdDetail.get(oliId);

            System.debug('pd--'+pd);
            System.debug('oli--'+oli);
            //check if new Product Detail is the same Product as old Product Detail
            Boolean noProductChange = false;
            if(oli.Product2Id == pd.Products__c){
                noProductChange = true;
            }

            //if there's no product change (i.e. there's only a Product Detail change),
            //update the existing OLI
            if(noProductChange){
                System.debug('no product change');

                //updates from Product Detail
                oli.Product_Details__c = pd.Id;
                oli.Start_Tier__c = pd.Start_Tier__c;
                oli.End_Tier__c = pd.End_Tier__c;
                oli.Tier__c = pd.Tier__c;
                oli.Number_of_Years_Required__c = Integer.valueOf(pd.Number_Of_Years_Required__c);
                oli.Renewal_Type__c = pd.Renewal_Type__c;
                oli.NetSuite_Class__c = pd.NetSuite_Class__c;
                oli.NetSuite_Department__c = pd.NS_Department__c;
                oli.NetSuite_Deferred_Revenue_Account__c = pd.NS_Deferred_Revenue_Account__c;
                oli.NetSuite_Income_GL_Account__c = pd.NS_Income_GL_Account__c;
                oli.NetSuite_Revenue_Schedule__c = pd.NS_Revenue_Schedule__c;
                oli.NetSuite_ID__c = pd.Netsuite_ID__c;
                oli.Tax_Class__c = pd.Tax_Class__c;
                oli.UnitPrice = pd.Price__c;

                //update checkbox that will ensure the "Restrict_Discount_And_SP_Membership_Prod"
                //validation rule doesn't cause an error
                oli.Bypass_Validation__c = true;

                String uniqueId = oli.OpportunityId+' '+oli.Projects__c;
                upsertOlis.put(uniqueId, oli);

                //if there IS a product change, clone the existing OLI, modify the clone,
                //insert the clone, then delete the existing OLI -- necessary because
                //SFDC doesn't allow changes to the Product2Id on an existing OLI
            }else{
                System.debug('product change');
                OpportunityLineItem clonedOLI = oli.clone(false, false, false, false);
                
                //updates from Product Detail
                clonedOLI.Product2Id = pd.Products__c;
                clonedOLI.Product_Details__c = pd.Id;
                clonedOLI.Start_Tier__c = pd.Start_Tier__c;
                clonedOLI.End_Tier__c = pd.End_Tier__c;
                clonedOLI.Tier__c = pd.Tier__c;
                clonedOLI.Number_of_Years_Required__c = Integer.valueOf(pd.Number_Of_Years_Required__c);
                clonedOLI.Renewal_Type__c = pd.Renewal_Type__c;
                clonedOLI.NetSuite_Class__c = pd.NetSuite_Class__c;
                clonedOLI.NetSuite_Department__c = pd.NS_Department__c;
                clonedOLI.NetSuite_Deferred_Revenue_Account__c = pd.NS_Deferred_Revenue_Account__c;
                clonedOLI.NetSuite_Income_GL_Account__c = pd.NS_Income_GL_Account__c;
                clonedOLI.NetSuite_Revenue_Schedule__c = pd.NS_Revenue_Schedule__c;
                clonedOLI.NetSuite_ID__c = pd.Netsuite_ID__c;
                clonedOLI.Tax_Class__c = pd.Tax_Class__c;
                clonedOLI.UnitPrice = pd.Price__c;

                //update checkbox that will ensure the "Restrict_Discount_And_SP_Membership_Prod"
                //validation rule doesn't cause an error
                clonedOLI.Bypass_Validation__c = true;

                System.debug('clonedOLI '+clonedOLI);
                String uniqueId = oli.OpportunityId+' '+oli.Projects__c;
                upsertOlis.put(uniqueId, clonedOLI);

                //get 15-digit and 18-digit String versions of oliID, needed for the next query
                String eighteenDigitID = (String)oli.Id;
                oliIDStrings.add(eighteenDigitID);
                String fifteenDigitID = eighteenDigitID.substring(0, 15);
                oliIDStrings.add(fifteenDigitID);

                
                //delete the original OLI
                deleteOlis.add(oli);
            }

            //get the Opportunity to see if its Type needs to be updated
            Opportunity opp = new Opportunity();

            //only need to proceed with checking if the Opp's Type needs to be updated if this is a renewal
            //or if the Opp's Type is blank (edge case)
            if(oli.Opportunity.Type == null ||
            ( oli.Opportunity.Type.indexOf('Renewal') != -1 && oli.Opportunity.Parent_Asset__r.Annual_Full_Price__c != null) ){
                
                //check to see if the full price of the new Product Detail selected is
                //greater than, less than, or equal to the full price of the Parent Asset,
                //and set Type of this Opp accordingly
                String newType = '';
                if(pd.Price__c > oli.Opportunity.Parent_Asset__r.Annual_Full_Price__c){
                    newType += 'Renewal - Upgrade';
                }else if(pd.Price__c < oli.Opportunity.Parent_Asset__r.Annual_Full_Price__c){
                    newType += 'Renewal - Downgrade';
                }else if(pd.Price__c == oli.Opportunity.Parent_Asset__r.Annual_Full_Price__c){
                    newType += 'Renewal';
                }

                //if newType doesn't match the Opp's current Type, update Opp
                if(newType != '' && newType != oli.Opportunity.Type){
                    opp.Id = oli.OpportunityId;
                    opp.Type = newType;
                    updateOpp.put(oli.OpportunityId, opp);
                }

            }
        }

        

        if(!upsertOlis.values().isEmpty()){
            upsert upsertOlis.values();
        }
        
        if(!updateOpp.values().isEmpty()){
            update updateOpp.values();
        }

        if(!oliIDStrings.isEmpty()){
            //query any Membership Roles attached to the existing OLI
            List<Project_Role__c> membershipRoles = new List<Project_Role__c>();
            membershipRoles = [SELECT Opportunity_Line_Item__c
                            FROM Project_Role__c
                            WHERE Opportunity_Line_Item__c IN :oliIDStrings
                            ];
            
            //update Membership Roles attached to the existing OLI to now be attached
            //to the cloned OLI
            if(membershipRoles.size() > 0){
                System.debug('membership roles found to be moved to new OLI');
                for(Project_Role__c mr : membershipRoles){
                    if(oliIdToOli.containsKey(mr.Opportunity_Line_Item__c)){
                        OpportunityLineItem oli = oliIdToOli.get(mr.Opportunity_Line_Item__c);
                        String uniqueId = oli.OpportunityId+' '+oli.Projects__c;
                        if(upsertOlis.containsKey(uniqueId)){
                            mr.Opportunity_Line_Item__c = upsertOlis.get(uniqueId).Id;
                        }
                    }
                }
                update membershipRoles;
            }
        }

        if(!deleteOlis.isEmpty()){
            delete deleteOlis;
        }

    }
}