force-app/main/default/objects/Asset/fields/Annual_Full_Price__c.field-meta.xml
<CustomField>
    <fullName>Annual_Full_Price__c</fullName>
    <inlineHelpText>Annual amount for Membership. Full price of Sponsorship Level for Event.</inlineHelpText>
    <label>Annual/Full Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto-Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acquired</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Perceived Value</fullName>
            </value>
            <value>
                <fullName>Out of Business</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Reissued</fullName>
            </value>
            <value>
                <fullName>Non payment</fullName>
                <label>Non Payment</label>
            </value>
            <value>
                <fullName>Org Change/Lost Champion or Funding</fullName>
            </value>
            <value>
                <fullName>No Engagement</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <formula>IF(NOT(ISBLANK(Projects__c)),HYPERLINK(&quot;/&quot;+Projects__c,Projects__r.Name,&quot;_top&quot;), 
IF(NOT(ISBLANK(Event__c)),HYPERLINK(&quot;/&quot;+Event__c,Event__r.Name,&quot;_top&quot;),IF(NOT(ISBLANK(Training__c)),HYPERLINK(&quot;/&quot;+Training__c,Training__r.Name,&quot;_top&quot;),&quot;&quot;)) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Corporate_Email__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Email__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporate Email</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select the Alternate Email record which is associated with this Contact record only</errorMessage>
        <filterItems>
            <field>Alternate_Email__c.Contact_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Alternate_Email__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Manager (without subordinates)</fullName>
            </value>
            <value>
                <fullName>Manager (with subordinates)</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Owner/Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Firm Acquired</fullName>
            </value>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>No Budget / Lost Funding</fullName>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
            </value>
            <value>
                <fullName>No Engagement</fullName>
            </value>
            <value>
                <fullName>Non payment</fullName>
            </value>
            <value>
                <fullName>Org Change/Lost Champion or Funding</fullName>
            </value>
            <value>
                <fullName>Perceived Value</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Reissued</fullName>
            </value>
            <value>
                <fullName>Solution Fit</fullName>
            </value>
            <value>
                <fullName>SPAM Opportunity</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/AgreementDate__c.field-meta.xml
<CustomField>
    <fullName>AgreementDate__c</fullName>
    <inlineHelpText>Countersigned date of agreement (manually set by membership sales)</inlineHelpText>
    <label>Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <formula>IF(NOT(ISBLANK(Projects__c)),HYPERLINK(&quot;/&quot;+Projects__c,Projects__r.Name,&quot;_top&quot;), 
IF(NOT(ISBLANK(Event__c)),HYPERLINK(&quot;/&quot;+Event__c,Event__r.Name,&quot;_top&quot;),IF(NOT(ISBLANK(Training__c)),HYPERLINK(&quot;/&quot;+Training__c,Training__r.Name,&quot;_top&quot;),&quot;&quot;)) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Program_Manager__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If Program Manager is non-LF employee. Create contact and add</inlineHelpText>
    <label>Program Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/Project_Role__c.object-meta.xml
<CustomObject>
    <label>Membership Roles</label>
    <nameField>
        <displayFormat>PR{000}</displayFormat>
        <label>Role AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Role__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Membership Roles</relationshipLabel>
    <relationshipName>Project_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <formula>Asset__r.MC_Cancellation_Reason__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cancellation Reason</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Project_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Corporate_Email__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Email__c</fullName>
    <formula>Alternate_Email__r.Alternate_Email_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Corporate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Project_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Voting Contact means this is the person at the company that has the right to vote in the project’s membership elections for their member class.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Representative/Voting Contact</fullName>
                <label>Voting Contact</label>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Legal Contact</fullName>
            </value>
            <value>
                <fullName>Event Sponsorship</fullName>
            </value>
            <value>
                <fullName>PO Contact</fullName>
            </value>
            <value>
                <fullName>Press Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projects</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <formula>IF(NOT(ISBLANK(Projects__c)),HYPERLINK(&quot;/&quot;+Projects__c,Projects__r.Name,&quot;_top&quot;), 
IF(NOT(ISBLANK(Event__c)),HYPERLINK(&quot;/&quot;+Event__c,Event__r.Name,&quot;_top&quot;),IF(NOT(ISBLANK(Training__c)),HYPERLINK(&quot;/&quot;+Training__c,Training__r.Name,&quot;_top&quot;),&quot;&quot;)) 
)</formula>
    <label>Related To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CancelMembershipReport.cls
public class CancelMembershipReport {
    static List<Asset> lstCancelledMembership ;
    static List<OpportunityLineItem> lstOLI ;
    Public List<String> selectedFieldsList {get;set;}
    static map<Id,OppAssetWrapper> mapOppAssetWrapper = new map<Id,OppAssetWrapper>();
    public Date startDate {get;set;}
    public Date EndDate {get;set;}
    public string projectName {get;set;}
    static set<Id> ids = new set<Id>();
    
    public List<OppAssetWrapper> lstwrap{get;set;}
    public CancelMembershipReport(){
        
        projectName = '';
        getAsset();
        
    }
    public class OppAssetWrapper{
        Public String Account{get;set;}
        Public id AccountId;
        Public String Country{get;set;}
        Public String Product {get;set;}
        Public string Canceldate{get;set;}
        Public string Joindate{get;set;}
        Public String CancelReason{get;set;}
        Public Decimal Amount{get;set;}
        Public string Voting{get;set;}
        Public string Marketing{get;set;}
        Public string Technical{get;set;}
        Public String ProjectName{get;set;}
        Public String VCorporateEmail{get;set;}
        Public String TCorporateEmail{get;set;}
        Public String MCorporateEmail{get;set;}
    }
    
    public void getAsset(){
          set<Id> setIds= new Set<Id>();
          List<string> strids = new List<String>();
         Id proId;
        map<id,OpportunityLineItem> mapOpportunityLineItem = new map<id,OpportunityLineItem>();
        if(projectName != ''){
            String strProjectName = projectName.substringBetween('[', ']');
            strProjectName=strProjectName.remove(' ');
            strids = strProjectName.split(',');
            projectName=strProjectName;
            if(strProjectName !=''){
                for(String s :strids){
                    proId=s.substring(0,15);
                    setIds.add(proId);  
                }
            }
        }
        DateTime SD= startDate;
        DateTime ED = EndDate;
        string proName = '%'+projectName + '%';
        String strStartDate='';
        String strEndDate='';
        if(SD != null){
            strStartDate = SD.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
        }
            if(ED != null){
                strEndDate = ED.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
            }
        lstCancelledMembership = new List<Asset>();
        lstOLI = new List<OpportunityLineItem>();
        lstwrap =new List<OppAssetWrapper>();
        
        string queryOpp ='Select id,Opportunity.AccountId,Opportunity.Name,Opportunity.Account.name,Projects__r.Name,TotalPrice,Opportunity.CloseDate,Opportunity.Loss_Reason__c,Opportunity.Account.Billingcountry,Opportunity.Amount,Opportunity.StageName,AgreementDate__c,Product2.Name,UnitPrice,Related_To__c from OpportunityLineItem '+
        'where Opportunity.type LIKE \'Renewal%\'  AND Opportunity.StageName=\'Closed Lost\' AND Opportunity.RecordType.Name=\'Membership\'AND Opportunity.Loss_Reason__c !=\'Reissued\'';
        system.debug('setIds-->'+setIds);
        system.debug('strStartDate-->'+strStartDate);
        system.debug('strEndDate-->'+strEndDate	);
        if(!setIds.isEmpty() && strStartDate != '' && strEndDate != ''){
            system.debug('Inside All');
            queryOpp += ' AND (Projects__c IN:setIds AND Opportunity.CreatedDate >'+strStartDate +'AND Opportunity.CreatedDate <'+ strEndDate+')';
        }
        if(strStartDate != '' && setIds.isEmpty()){
            queryOpp +=' AND Opportunity.CreatedDate >'+strStartDate;
        }
        if(strEndDate != '' && setIds.isEmpty()){
            queryOpp +=' AND Opportunity.CreatedDate <'+strEndDate;
        }
        if(!setIds.isEmpty() && strStartDate == '' && strEndDate == ''){
            queryOpp +=' AND Projects__c IN:setIds order by Opportunity.CreatedDate DESC';
        }
        
        lstOLI = Database.query(queryOpp);
         map<Id,Asset> mapAsset = new Map<Id,Asset>();
         set<Id> AccountIds = new set<Id>();
        for(OpportunityLineItem objOpportunity :lstOLI){
            AccountIds.add(objOpportunity.Opportunity.AccountId);
            
            if(!mapOpportunityLineItem.containsKey(objOpportunity.Opportunity.AccountId)){
                
               mapOpportunityLineItem.put(objOpportunity.Opportunity.AccountId,objOpportunity); 
            }
        }
        system.debug('');
        String query ='Select id,AccountId,Account.Name,PurchaseDate,Annual_Full_Price__c,Product2.Name,Opportunity__r.Name,Account.BillingCountry,Cancellation_Date__c,Cancellation_Reason__c,Opportunity__r.Amount,Opportunity__r.StageName,';
        query +='Status,Projects__r.name,(Select Contact__r.Name,Role__c,Corporate_Email__c from Project_Roles__r where (Role__c =\'Marketing Contact\' OR Role__c =\'Representative/Voting Contact\' OR Role__c =\'Technical Contact\')) from Asset Where ((Status =\'Invoice Cancelled\') OR (Opportunity__r.StageName =\'Closed Won\' AND Status =\'Invoice Cancelled\')'; 
        query +=  ' OR (Opportunity__r.StageName =\'Closed Won\' AND Status =\'Active\' AND Auto_Renew__c = false) OR ((Status =\'Active\' OR Status =\'Expired\') AND Auto_Renew__c = false)) AND ProductFamily =\'Membership\' AND Opportunity__r.Loss_Reason__c !=\'Reissued\' AND Cancellation_Reason__c !=\'Reissued\'';
        
        if(!setIds.isEmpty() && strStartDate != '' && strEndDate != ''){
            system.debug('Inside All');
            query += ' AND (Projects__c IN:setIds AND Opportunity__r.CreatedDate >'+strStartDate +'AND Opportunity__r.CreatedDate <'+ strEndDate+')';
        }
        if(!setIds.isEmpty() && strStartDate == '' && strEndDate == ''){
            query +=' AND (Projects__c IN:setIds ) order by CreatedDate ASC ';
        }
        if(strStartDate != '' && setIds.isEmpty()){
            query +=' AND (Opportunity__r.CreatedDate >'+strStartDate+')';
        }
        if(strEndDate != '' && setIds.isEmpty()){
            query +=' AND (Opportunity__r.CreatedDate <'+strEndDate+')';
        }
        
        lstCancelledMembership = Database.query(Query);
        for(Asset objAsset :lstCancelledMembership){
            if(!mapAsset.containsKey(objAsset.AccountId)){
                if(mapOpportunityLineItem.get(objAsset.AccountId)!=null){
                    if(mapOpportunityLineItem.get(objAsset.AccountId).Opportunity.CloseDate<objAsset.Cancellation_Date__c){
                        mapOpportunityLineItem.remove(objAsset.AccountId);
                        mapAsset.put(objAsset.AccountId,objAsset);
                    }

                }else{
                    mapAsset.put(objAsset.AccountId,objAsset);
                }
                
            }
        }
        set<Id> Opportunityids = new set<Id>();
        for(OpportunityLineItem objOpportunity :mapOpportunityLineItem.values()){
            Opportunityids.add(objOpportunity.OpportunityId);
            OppAssetWrapper objWrap = new OppAssetWrapper();
            objWrap.Product =objOpportunity.Product2.Name;
            objWrap.ProjectName =objOpportunity.Projects__r.Name;
            objWrap.AccountId = objOpportunity.Opportunity.AccountID;
            if(objOpportunity.AgreementDate__c != null){
                objWrap.Joindate =objOpportunity.AgreementDate__c.format();
            }
             objWrap.Amount =objOpportunity.UnitPrice;
            
            objWrap.Account =objOpportunity.Opportunity.Account.name;
            objWrap.Country =objOpportunity.Opportunity.Account.Billingcountry;
            objWrap.CancelReason = objOpportunity.Opportunity.Loss_Reason__c;
            if(objOpportunity.Opportunity.CloseDate != null){
                objWrap.Canceldate = objOpportunity.Opportunity.CloseDate.format();
            }
            mapOppAssetWrapper.put(objOpportunity.Opportunity.AccountId,objWrap);
        }
        set<Id> usedIds = new set<Id>();
        for(Opportunity objOpportunity :[Select id,AccountId,(Select Contact__r.Name,Role__c,Corporate_Email__c from Project_Roles__r where (Role__c ='Marketing Contact' OR Role__c ='Representative/Voting Contact' OR Role__c ='Technical Contact')AND Status__c ='Active') from Opportunity where Id IN:Opportunityids]){
            OppAssetWrapper objWrap = mapOppAssetWrapper.get(objOpportunity.AccountID);
            for(Project_Role__c objPR : objOpportunity.Project_Roles__r){
                if(mapOppAssetWrapper.containsKey(objOpportunity.AccountId)){
                    if(objPR.Role__c =='Representative/Voting Contact'){
                        usedIds.add(objOpportunity.id);
                        objWrap.Voting = objPR.Contact__r.name;
                        objWrap.VCorporateEmail = objPR.Corporate_Email__c;
                    }else
                        if(objPR.Role__c =='Marketing Contact'){
                            objWrap.Marketing =objPR.Contact__r.name;
                            objWrap.MCorporateEmail = objPR.Corporate_Email__c;
                        }else if(objPR.Role__c =='Technical Contact'){
                            objWrap.Technical =objPR.Contact__r.name;
                            objWrap.TCorporateEmail = objPR.Corporate_Email__c;
                        }
                }
            }
            mapOppAssetWrapper.put(objOpportunity.AccountId,objWrap);
        }
         //code for contact role 
         for(Opportunity objOpportunity :[Select id,AccountId,(Select Contact.Name,Role from OpportunityContactRoles where IsPrimary=true) from Opportunity where Id IN:Opportunityids]){
            OppAssetWrapper objWrap = mapOppAssetWrapper.get(objOpportunity.AccountID);
            for(OpportunityContactRole objOCR : objOpportunity.OpportunityContactRoles){
                if(mapOppAssetWrapper.containsKey(objOpportunity.AccountId) && !usedIds.contains(objOpportunity.id)){
                    objWrap.Voting = objOCR.Contact.name;
                }
            }
            lstwrap.add(objWrap);
        }
        
        for(Asset objAsset :mapAsset.values()){
            OppAssetWrapper objWrap = new OppAssetWrapper(); 
            objWrap.Account =objAsset.Account.name;
            objWrap.ProjectName =objAsset.Projects__r.name;
            objWrap.Product =objAsset.Product2.Name;
            objWrap.Country =objAsset.Account.Billingcountry;
            if(objAsset.Cancellation_Date__c !=null){
                objWrap.Canceldate =objAsset.Cancellation_Date__c.format();
            }
            objWrap.CancelReason =objAsset.Cancellation_Reason__c;
            objWrap.Amount =objAsset.Annual_Full_Price__c;
            if(objAsset.PurchaseDate !=null){
                objWrap.Joindate = objAsset.PurchaseDate.format();
            }
            for(Project_Role__c objPR : objAsset.Project_Roles__r){
              if(objPR.Role__c =='Representative/Voting Contact'){
                objWrap.Voting = objPR.Contact__r.name;
                  objWrap.VCorporateEmail = objPR.Corporate_Email__c;
              }else
                if(objPR.Role__c =='Marketing Contact'){
              objWrap.Marketing =objPR.Contact__r.name;
                    objWrap.MCorporateEmail = objPR.Corporate_Email__c;
                }else if(objPR.Role__c =='Technical Contact'){
              objWrap.Technical =objPR.Contact__r.name; 
                    objWrap.TCorporateEmail = objPR.Corporate_Email__c;
                }
            }
            lstwrap.add(objWrap);
        }
        
    }
    Public List<Selectoption> getselectedProject(){
        List<Selectoption> lstProject = new List<selectoption>();
        for(Project__c objProject :[SELECT id,name FROM Project__c]){
            lstProject.add(new selectoption(objProject.id,objProject.name));
        }
        return lstProject; 
    } 
    Public PageReference ExportToExcel(){
        selectedFieldsList = New List<string>();
        
        selectedFieldsList.add('Account'); 
        selectedFieldsList.add('Canceldate'); 
        selectedFieldsList.add('CancelReason');
        selectedFieldsList.add('Joindate'); 
        selectedFieldsList.add('Product');
        selectedFieldsList.add('Country');
        selectedFieldsList.add('Amount');
        selectedFieldsList.add('Voting');
        selectedFieldsList.add('Marketing');
        selectedFieldsList.add('Technical');
        
        PageReference pgRef = New Pagereference('/apex'+'/ExportCancellMembershipReport');
        pgRef.setRedirect(false); 
        return pgRef;
    }
    
}