force-app/main/default/objects/Asset/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto-Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Number_of_Years_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_Required__c</fullName>
    <label>Number of Years Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>OpportunityLineItem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Number_of_Years_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_Required__c</fullName>
    <label>Number of Years Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchUpdatingAccountTypeTest.cls
/*
* Test Class For-BatchUpdatingAccountType and BatchUpdatingAccountTypeHelper Class
*/ 
@isTest
public class BatchUpdatingAccountTypeTest
{
    //create TestData
    @testsetup
    static void setup(){
        Project__c proj  = TestFactory.getProject();
        Opportunity oppt = TestFactory.getOpportunity();
        Product2 prod = TestFactory.getProduct2();
        Account acc = TestFactory.getAccount();
        acc.Type = 'Open';
        update acc;
        OpportunityLineItem oli = TestFactory.getOpportunityLineItem();
        
        Asset asst = new Asset(Name = 'Test Asset',AccountId = acc.ID, Projects__c = proj.ID , Status = 'Active', 
                               UsageEndDate = system.today(),Number_of_Years_Required__c = 1,Opportunity__c = oppt.ID,
                               OpportunityLineItem__c = oli.id,Auto_Renew__c = TRUE,Product2Id = prod.ID);
        insert asst;
        
        // insert another account
        Account acc1 = new Account(Name = 'Test Account 1', Phone = '11111',Website = 'testaccount.com', BillingCity = 'Littleton',
                                   BillingState = 'Colorado', BillingPostalCode = '80120', BillingCountry = 'United States',
                                   BillingStreet = '1601-1649 W Weaver Ave', Type='Customer');
        insert acc1;
        // insert another asset
        Asset asst1 = new Asset(Name = 'Test Asset 1',AccountId = acc1.ID, Projects__c = proj.ID , Status = 'Expired', UsageEndDate = system.today().addDays(-10), Number_of_Years_Required__c = 1);
        insert asst1;
    }
    
    //Test BatchUpdatingAccountType batch without passing Query
    @IsTest
    private static void testBatchApex() {
        
        Test.startTest();
        BatchUpdatingAccountType obj = new BatchUpdatingAccountType(null);
        Database.executeBatch(obj, 100);
        Test.stopTest();
        System.assertEquals('Former Customer',[SELECT Id,Name,Type FROM Account WHERE Name ='Test Account 1' Limit 1 ].Type );
 
    }
    
    //Test BatchUpdatingAccountType batch with passing Query
    @IsTest
    private static void testBatchApex1() {
        
        Test.startTest();
        BatchUpdatingAccountType obj = new BatchUpdatingAccountType('SELECT Id, Type from Account  WHERE Type != \'Former Customer\'');
        Database.executeBatch(obj, 100);
        Test.stopTest();
        System.assertEquals('Former Customer',[SELECT Id,Name,Type FROM Account WHERE Name ='Test Account 1' Limit 1 ].Type );

    }
}