force-app/main/default/objects/Asset/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto-Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/classes/MyProjectsReportEmailHandler.cls
public with sharing class MyProjectsReportEmailHandler implements IEmail{
    

    public List<SendEmailWrapper.SendEmailContactWrapper> getRecipients(){
        //get the recipients
        Map<Id,Set<ID>> recipients = new  Map<Id,Set<ID>>();
        
        List<AggregateResult> results = [Select count(ID),Opportunity__r.OwnerId from Asset WHERE UsageEndDate = NEXT_N_DAYS:60 AND
                                    Product2.Family='Membership' AND Auto_Renew__c = true group by Opportunity__r.OwnerId];
        system.debug('----'+results);
        for(AggregateResult ar : results){
            recipients.put((Id)ar.get('OwnerId'),new Set<Id>{(ID)ar.get('OwnerId')});
        }
        //create list to loop on

        List<SendEmailWrapper.SendEmailContactWrapper> contactWrapper = new list<SendEmailWrapper.SendEmailContactWrapper>();
            for(Id id : recipients.keySet()){
                Map<String, Object> params = new  Map<String, Object>();
                params.put('id',id);
                contactWrapper.add(new SendEmailWrapper.SendEmailContactWrapper(id,recipients.get(id), params));
            }

        return contactWrapper;
    }

    public string getBody(){
       
        list<EmailTemplate> emailTemplate = [select id from EmailTemplate where id =:label.Project_Email_Template];
        return emailTemplate.size()> 0 ? emailTemplate[0].id : '';
    }

    /*
    * This generates the attachments
    * */
    public List<Messaging.EmailFileAttachment>  getAttachments(Map<String, Object> parameters){
        List<Messaging.EmailFileAttachment> emailFileAttachments = new List<Messaging.EmailFileAttachment>();
        Messaging.EmailFileAttachment fileAttachment = new Messaging.EmailFileAttachment();

        String ownerId = (String) parameters.get('id');
      MyProjectsReportController projectReportController = new MyProjectsReportController((String) parameters.get('id'));
        
        list<Asset> asset = projectReportController.getAssetDetails();
        Blob csvBlob;
        if(asset != null){
             csvBlob = projectReportController.csvGenerate(asset);
        }
        fileAttachment.setBody(csvBlob);
        fileAttachment.setFileName('My Renewals.csv');
        fileAttachment.setContentType('text/csv');  
        emailFileAttachments.add(fileAttachment);
        return emailFileAttachments;
    }
}