force-app/main/default/objects/Asset/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto-Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <formula>IF((TODAY()- (PurchaseDate + VALUE( MID( PaymentTerms__c , 5, 4) )) )&lt;=30 &amp;&amp; (TODAY()- (PurchaseDate + VALUE( MID( PaymentTerms__c , 5, 4) )) )&gt;=0 ,30,IF(AND((TODAY()- (PurchaseDate + VALUE( MID( PaymentTerms__c , 5, 4) )) )&gt;30,(TODAY()- (PurchaseDate + VALUE( MID( PaymentTerms__c , 5, 4) )))&lt;=60),60,IF(AND((TODAY()- (PurchaseDate + VALUE( MID( PaymentTerms__c , 5, 4) )))&gt;60,(TODAY()- (PurchaseDate + VALUE( MID( PaymentTerms__c , 5, 4) )))&lt;=90),90,IF((TODAY()- (PurchaseDate + VALUE( MID( PaymentTerms__c , 5, 4) )))&gt;90,120,0))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Number_of_Years_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_Required__c</fullName>
    <label>Number of Years Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>OpportunityLineItem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SalesOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>SalesOrderStatus__c</fullName>
    <label>Sales Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not Synced to Netsuite</fullName>
                <default>true</default>
                <label>Not Synced to Netsuite</label>
            </value>
            <value>
                <fullName>At Risk</fullName>
                <isActive>false</isActive>
                <label>At Risk</label>
            </value>
            <value>
                <fullName>Invoice not created</fullName>
                <isActive>false</isActive>
                <label>Invoice not created</label>
            </value>
            <value>
                <fullName>Sent</fullName>
                <isActive>false</isActive>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Unsent</fullName>
                <isActive>false</isActive>
                <label>Unsent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Payment Due Immediately</fullName>
            </value>
            <value>
                <fullName>Payment Due Prior To Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Number_of_Years_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_Required__c</fullName>
    <label>Number of Years Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <formula>TEXT(Opportunity.PaymentTerms__c)</formula>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountReceivableChartControllerTest.cls
/* Test Class For - AccountReceivableChartController class
 */ 
@isTest
public class AccountReceivableChartControllerTest {
    
    //create data
    @TestSetup
    public static void setupdata(){
        Project__c testProject =TestFactory.getProject();
        Opportunity oppt = TestFactory.getOpportunity();
        Product2 prod = TestFactory.getProduct2();
        Account acc = TestFactory.getAccount();
        OpportunityLineItem oli = TestFactory.getOpportunityLineItem();
        
        Id recordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get('Corporate').getRecordTypeId();
        Asset asst = new Asset(Name = 'TEstcreateasset',RecordTypeId=recordTypeId,AccountId = acc.ID, Projects__c = testProject.ID ,
                               Status = 'Active', UsageEndDate = system.today(), Number_of_Years_Required__c = 1,Opportunity__c = oppt.ID, 
                               OpportunityLineItem__c = oli.id,Auto_Renew__c = TRUE,Product2Id = prod.ID,SalesOrderStatus__c='Open',
                               PaymentTerms__c ='Net 30',Price =10000,
                               purchasedate=Date.newinstance(2020,9,8));
        insert asst;
        asset ast =[select id,days__c from asset where id=:asst.id];
        system.debug('days '+ast.days__c);
        
    }
    
    //Test method for getSelectedProjectDetails
    @isTest 
    public static void getSelectedProjectDetails_test(){
        
        Id prjId =[SELECT ID from project__c LIMIT 1].Id;
        Project__c returnedProject = AccountReceivableChartController.getSelectedProjectDetails(prjId);
        system.assertEquals('Test Project',returnedProject.Name );
        
    }
    
    //Test method for getAccountReceivableDetails
    @isTest 
    public static void getAccountReceivableDetails_test(){
        Id prjId =[SELECT ID from project__c LIMIT 1].Id;
        String returnedString = AccountReceivableChartController.getAccountReceivableDetails(prjId,'120');
        system.assertNotEquals(null,returnedString );
    }
    
    //Test method for getAccountReceivableTableDetails
    @isTest 
    public static void getAccountReceivableTableDetails_test(){
        Id prjId =[SELECT ID from project__c LIMIT 1].Id;
        List<integer> intList = new List<Integer>{120};
        List<Asset> returnedAssetList = AccountReceivableChartController.getAccountReceivableTableDetails(
            prjId,JSON.serialize(intList),false,null,true);
        system.assertNotEquals(0,returnedAssetList.size());
    }
}