force-app/main/default/objects/Asset/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</description>
    <inlineHelpText>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</inlineHelpText>
    <label>Billing Account Override</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Endpoints__c/Endpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Endpoints</label>
</CustomObject>

force-app/main/default/objects/Endpoints__c/fields/Nlauth_Account__c.field-meta.xml
<CustomField>
    <fullName>Nlauth_Account__c</fullName>
    <label>Nlauth_Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/Hotel_Commissions__c.object-meta.xml
<CustomObject>
    <description>Hotel Commissions are revenue transactions.These are the commissions which Linux Foundation receives from Hotel&apos;s when event registrant registers for an LF event and books the room to stay in and attend the event.</description>
    <label>Hotel Commissions</label>
    <nameField>
        <label>Hotel Commissions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotel Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel_Commissions__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hotel Commissions</relationshipLabel>
    <relationshipName>Hotel_Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Bill_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hotel Commissions</relationshipLabel>
    <relationshipName>Hotel_Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Sync_to_Netsuite__c.field-meta.xml
<CustomField>
    <fullName>Sync_to_Netsuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync to Netsuite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HotelCommissionSyncToNetsuite_Test.cls
@isTest
public class HotelCommissionSyncToNetsuite_Test {
    @testSetup
    public static void testdata(){
        
        Endpoints__c endPoint = new Endpoints__c();
        endPoint.Name = 'For Other than Membership Asset';
        endPoint.Endpoint__c = 'https://4010327-sb1.restlets.api.netsuite.com/app/site/hosting/restlet.nl?script=40&deploy=1';
        endPoint.Password__c = 'jYdpn8sp22F8C45b';
        endPoint.User_Id__c = 'nsapi@linuxfoundation.org';
        endPoint.Nlauth_Account__c = '4010327_SB1';
        insert endPoint;
        
        Endpoints__c endPoint2 = new Endpoints__c();
        endPoint2.Name = 'For Product Details';
        endPoint2.Endpoint__c = 'https://4010327-sb1.restlets.api.netsuite.com/app/site/hosting/restlet.nl?script=41&deploy=1';
        endPoint2.Password__c = 'jYdpn8sp22F8C45b';
        endPoint2.User_Id__c = 'nsapi@linuxfoundation.org';
        endPoint2.Nlauth_Account__c = '4010327_SB1';
        insert endPoint2;
        
    	Account account = new Account();
        account.Name = 'Test Account';
        insert account;
        
        Contact contact = new Contact();
        contact.AccountId = account.Id;
        contact.LastName = 'Test Contact';
        contact.Email = 'testContact@noReply.com';
        insert contact;
        
        Hotel_Commissions__c hotelCommission = new Hotel_Commissions__c();
        hotelCommission.Name = 'Test Hotel Commissions';
        hotelCommission.Amount__c = 123;
        hotelCommission.Bill_to_Account__c = account.Id;
        hotelCommission.Bill_to_Contact__c = contact.Id;
        hotelCommission.Product_Description__c = 'Test Description';
        hotelCommission.Start_Date__c = System.today();
        hotelCommission.End_Date__c = System.today()+2;
        insert hotelCommission;
        
        ContentVersion objCV = new ContentVersion(Title = 'Penguins', PathOnClient = 'Penguins.pdf',
                                                  VersionData = Blob.valueOf('Test Content'), 
                                                  IsMajorVersion = true );
        insert objCV;
        
        ContentVersion objContentVer = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :objCV.Id];
        ContentDocumentLink newFileShare = new ContentDocumentLink();
        system.debug('conDoc -->'+ objContentVer.contentDocumentid);
        newFileShare.contentdocumentid = objContentVer.contentDocumentid;
        newFileShare.LinkedEntityId = hotelCommission.Id;
        newFileShare.ShareType= 'V';
        insert newFileShare;
    }
    
	@isTest
    static void validateContactTest(){
        Hotel_Commissions__c hotelCommission= [SELECT Id FROM Hotel_Commissions__c limit 1];
        hotelCommission.Bill_to_Contact__c = null;
        update hotelCommission;
        
        String jsonWrapper = HotelCommissionSyncToNetSuiteController.validateAndSyncToNetSuite(hotelCommission.Id);
        Map<String, Object> hotelCommissionsMap = (Map<String, Object>) JSON.deserializeUntyped(jsonWrapper);
        system.assertEquals(hotelCommissionsMap.get('message'), 'The Bill To Contact field is not populated.');
    }
    
    @isTest
    static void validateFileTest(){
        Account account = [SELECT Id FROM Account limit 1];
        Contact contact = [SELECT Id FROM Contact limit 1];
        Hotel_Commissions__c hotelCommission = new Hotel_Commissions__c();
        hotelCommission.Name = 'Test Hotel Commissions';
        hotelCommission.Amount__c = 123;
        hotelCommission.Bill_to_Account__c = account.Id;
        hotelCommission.Product_Description__c = 'Test Description';
        hotelCommission.Start_Date__c = System.today();
        hotelCommission.End_Date__c = System.today()+2;
        insert hotelCommission;
        
        String jsonWrapper = HotelCommissionSyncToNetSuiteController.validateAndSyncToNetSuite(hotelCommission.Id);
        Map<String, Object> hotelCommissionsMap = (Map<String, Object>) JSON.deserializeUntyped(jsonWrapper);
        system.assertEquals(hotelCommissionsMap.get('message'), 'No files attached. Please upload the file.');
    }
    
    @isTest
    static void validateDescriptionTest(){
        Hotel_Commissions__c hotelCommission= [SELECT Id FROM Hotel_Commissions__c limit 1];
        hotelCommission.Product_Description__c = '';
        update hotelCommission;
        
        String jsonWrapper = HotelCommissionSyncToNetSuiteController.validateAndSyncToNetSuite(hotelCommission.Id);
        Map<String, Object> hotelCommissionsMap = (Map<String, Object>) JSON.deserializeUntyped(jsonWrapper);
        system.assertEquals(hotelCommissionsMap.get('message'), 'The Description is not populated.');
    }
    
    @isTest
    static void validateStartDateTest(){
        Hotel_Commissions__c hotelCommission= [SELECT Id FROM Hotel_Commissions__c limit 1];
        hotelCommission.Start_Date__c = null;
        update hotelCommission;
        String jsonWrapper = HotelCommissionSyncToNetSuiteController.validateAndSyncToNetSuite(hotelCommission.Id);
        Map<String, Object> hotelCommissionsMap = (Map<String, Object>) JSON.deserializeUntyped(jsonWrapper);
        system.assertEquals(hotelCommissionsMap.get('message'), 'The Start Date is not populated.');
    }
    
    @isTest
    static void validateEndDateTest(){
        Hotel_Commissions__c hotelCommission= [SELECT Id FROM Hotel_Commissions__c limit 1];
        hotelCommission.End_Date__c = null;
        update hotelCommission;
        
        String jsonWrapper = HotelCommissionSyncToNetSuiteController.validateAndSyncToNetSuite(hotelCommission.Id);
        Map<String, Object> hotelCommissionsMap = (Map<String, Object>) JSON.deserializeUntyped(jsonWrapper);
        system.assertEquals(hotelCommissionsMap.get('message'), 'The End Date is not populated.');
    }
    
    @isTest
    static void validateAmountTest(){
        Hotel_Commissions__c hotelCommission= [SELECT Id FROM Hotel_Commissions__c limit 1];
        hotelCommission.Amount__c = null;
        update hotelCommission;
        
        String jsonWrapper = HotelCommissionSyncToNetSuiteController.validateAndSyncToNetSuite(hotelCommission.Id);
        Map<String, Object> hotelCommissionsMap = (Map<String, Object>) JSON.deserializeUntyped(jsonWrapper);
        system.assertEquals(hotelCommissionsMap.get('message'), 'The Amount is not populated.');
    }
    
    @isTest
    static void validateAlreadySyncedTest(){
        Hotel_Commissions__c hotelCommission= [SELECT Id FROM Hotel_Commissions__c limit 1];
        hotelCommission.Sync_to_Netsuite__c = True;
        update hotelCommission;
        
        String jsonWrapper = HotelCommissionSyncToNetSuiteController.validateAndSyncToNetSuite(hotelCommission.Id);
        Map<String, Object> hotelCommissionsMap = (Map<String, Object>) JSON.deserializeUntyped(jsonWrapper);
        system.assertEquals(hotelCommissionsMap.get('message'), 'This record is already synced.');
    }
    
    @isTest
    static void validateSuccessTest(){
        List<Endpoints__c> endpoints = [SELECT name, endpoint__c, Password__c, User_Id__c, Nlauth_Account__c FROM Endpoints__c];
        Hotel_Commissions__c hotelCommission= [SELECT Id FROM Hotel_Commissions__c limit 1];
        
        Test.setMock(HttpCalloutMock.class, new NetSuiteToSalesforce_Mock());
        Test.startTest();
        String jsonWrapper = HotelCommissionSyncToNetSuiteController.validateAndSyncToNetSuite(hotelCommission.Id);
        Test.stopTest();
        System.debug('jsonWrapper'+jsonWrapper);
        Map<String, Object> hotelCommissionsMap = (Map<String, Object>) JSON.deserializeUntyped(jsonWrapper);
        system.assertEquals(True, hotelCommissionsMap.get('isSuccess'));
    }
}