force-app/main/default/objects/Asset/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</description>
    <inlineHelpText>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</inlineHelpText>
    <label>Billing Account Override</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Bill To Address selected must be associated with the Account selected.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Address__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CNCF_Level__c.field-meta.xml
<CustomField>
    <fullName>CNCF_Level__c</fullName>
    <label>CNCF Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>End User Supporter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Display_Logo_On_Website__c.field-meta.xml
<CustomField>
    <fullName>Display_Logo_On_Website__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Don&apos;t Display Logo On Website</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Marked_for_Renewal_Processing__c.field-meta.xml
<CustomField>
    <fullName>Marked_for_Renewal_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marked for Renewal Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NS_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>NS_Entity_ID__c</fullName>
    <externalId>true</externalId>
    <label>NS Entity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>OpportunityLineItem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Press_Release_Announcement__c.field-meta.xml
<CustomField>
    <fullName>Press_Release_Announcement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Press Release Announcement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Renewal_Opportunity_Created__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewal Opportunity Created?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Renewal_Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity_Name__c</fullName>
    <label>Renewal Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the membership/sponsorship/training items are to be billed to an Account other than the receiving Account.</description>
    <inlineHelpText>If the membership/sponsorship/training items are to be billed to an Account other than the receiving Account.</inlineHelpText>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Use if bill to address is different from Account Name billing Address. You can find addresses under Bill to Name and Address under Account</inlineHelpText>
    <label>Bill to Name and address</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_To_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Days_to_Deduct__c.field-meta.xml
<CustomField>
    <fullName>Days_to_Deduct__c</fullName>
    <defaultValue>&quot;30&quot;</defaultValue>
    <description>All renewals will close 30 days as default. If your project needs to close earlier than 30 days pick a value other than 30. This change will update all open Renewal opportunity&apos;s close date, Except for Year end renewals.</description>
    <inlineHelpText>All renewals will close 30 days as default. If your project needs to close earlier than 30 days pick a value other than 30. This change will update all open Renewal opportunity&apos;s close date.</inlineHelpText>
    <label>Days to Close Renewals</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <default>true</default>
                <label>30</label>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projects</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateRenewal.cls
global with sharing class CreateRenewal{
   @AuraEnabled
    WebService static String executeBatchForAutoRenewal(Id asstId){
        Map<ID,Asset> updateAssets = new Map<ID,Asset>();
        
            List<Asset> assetDetail = [SELECT id,OpportunityLineItem__c,UsageEndDate,Renewal_Opportunity_Created__c,order__c,NS_Entity_ID__c,NetSuite_ID__c,
                                       Display_Logo_On_Website__c, Press_Release_Announcement__c,Bill_To_Address__c,Bill_To_Account__c,CNCF_Level__c, Opportunity__c, AccountID ,
                                       Projects__r.Days_to_Deduct__c FROM Asset WHERE id=: asstId AND Opportunity__c !=null];
            
            Map<id,Opportunity> updateOpportunityStages = new Map<id,Opportunity>();
            
            RenewalClassForOpps ren = new RenewalClassForOpps();
            
            List<Opportunity> renewalOpps = new List<Opportunity>();
        
            
            system.debug('____assetDetail___size___'+assetDetail.size());
            
            updateAssets = ren.setCheckboxOnAsset(assetDetail);
            
            renewalOpps = ren.createRenewalOpps(assetDetail);
            
        	Map<Id,String> parentAssetIdVsRenewalOppName = new Map<Id,String>();
            if(renewalOpps!=null && renewalOpps.size()>0){
                updateOpportunityStages = ren.updateOppStageForRenewalOpps(renewalOpps);
                parentAssetIdVsRenewalOppName=ren.getParentAssetVsRenewalNameMap(renewalOpps);
                //ren.createTasksForRenewalOpps(renewalOpps);     
            }
            if(updateOpportunityStages!=null && updateOpportunityStages.size()>0)
                update updateOpportunityStages.values();
            
            if(updateAssets!=null && updateAssets.size()>0){
                    updateAssets.values()[0].Renewal_Opportunity_Created__c = true;
                    updateAssets.values()[0].Marked_for_Renewal_Processing__c = false;
                 	updateAssets.values()[0].Renewal_Opportunity_Name__c = parentAssetIdVsRenewalOppName.containsKey(updateAssets.values()[0].Id)?
                    		parentAssetIdVsRenewalOppName.get(updateAssets.values()[0].Id):'';
                    update updateAssets.values();
                }
        	return null;
        
    }
}