force-app/main/default/objects/Asset/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores project category for riscv projects</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LF Event</fullName>
            </value>
            <value>
                <fullName>Project Event</fullName>
            </value>
            <value>
                <fullName>3rd Party Event</fullName>
            </value>
            <value>
                <fullName>Non-LF Event</fullName>
            </value>
            <value>
                <fullName>Migrated Data</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Event&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Indicates if the project has Membership, Crowdfunding (e.g. LFX Funding), or both. Note that a project may have membership requirements that do not have any fees or funding associated with them. In that case, &apos;Membership&apos; is still selected for this field.</inlineHelpText>
    <label>Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Crowdfunding</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>E-Learning</fullName>
            </value>
            <value>
                <fullName>Instructor-Led</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Date Confirmed</fullName>
            </value>
            <value>
                <fullName>Materials Sent</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Services (Fab, design services)</fullName>
    </customValue>
    <customValue>
        <fullName>Chip (SoC, IP, FPGA)</fullName>
    </customValue>
    <customValue>
        <fullName>I/O (Memory, network, storage)</fullName>
    </customValue>
    <customValue>
        <fullName>Systems (ODM, OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Software (Dev tools, firmware, OS)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry (cloud, mobile, HPC, ML, automotive)</fullName>
    </customValue>
    <customValue>
        <fullName>Research (Universities, Labs, other alliances, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <description>Account Project Category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DisplayAssetsTest.cls
@istest
public class DisplayAssetsTest{
	public static testMethod void DisplayAccountsProjectTest(){

		PageReference pg = Page.AssetsOnProject;
		Test.setCurrentPage(pg);

		Account acc = new Account(Name = 'Test Account 1');
		insert acc;

		Project__c project1 = new Project__c(Name = 'The Linux Foundation', Type__c = 'Membership', Category__c = 'Directed Fund', Status__c = 'Planned', Slug__c = 'testing1');
		insert project1;

		List<Asset> asst = new List<Asset>();
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 1', Projects__c = project1.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 2', Projects__c = project1.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 3', Projects__c = project1.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 4', Projects__c = project1.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 5', Projects__c = project1.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 6', Projects__c = project1.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 7', Projects__c = project1.Id));
		insert asst;

		System.debug('>>>>>>>>' + asst);

		String projectID = String.valueOf(project1.Id);
		ApexPages.StandardController ssc = new ApexPages.StandardController(project1);
		DisplayAssets controller = new DisplayAssets(ssc);
		controller.strID = projectID;
		controller.assetsListMethod();
	}

	public static testMethod void DisplayAccountsEventTest(){

		PageReference pg = Page.AssetsOnEvents;
		Test.setCurrentPage(pg);

		Account acc = new Account(Name = 'Test Account 1');
		insert acc;

		Project__c project1 = new Project__c(Name = 'The Linux Foundation', Type__c = 'Membership', Category__c = 'Directed Fund', Status__c = 'Planned', Slug__c = 'testing', Model__c = 'Membership');
		insert project1;

        project1.Status__c = 'Active';
		project1.Funding__c = 'Funded';
		update project1;

		Event__c event = new Event__c(Name = 'Test Event', Type__c = 'Membership', BillFromProject__c = project1.Id);
		insert event;

		List<Asset> asst = new List<Asset>();
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 1', Event__c = event.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 2', Event__c = event.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 3', Event__c = event.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 4', Event__c = event.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 5', Event__c = event.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 6', Event__c = event.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 7', Event__c = event.Id));
		insert asst;

		System.debug('>>>>>>>>' + asst);
		String eventID = String.valueOf(event.Id);

		ApexPages.StandardController ssc = new ApexPages.StandardController(event);
		DisplayAssets controller = new DisplayAssets(ssc);
		controller.strID = eventID;
		controller.assetsListMethod();
	}

	public static testMethod void DisplayAccountsTrainingTest(){

		PageReference pg = Page.AssetsOnTraining;
		Test.setCurrentPage(pg);

		Account acc = new Account(Name = 'Test Account 1');
		insert acc;

		Project__c project1 = new Project__c(Name = 'The Linux Foundation', Type__c = 'Membership', Category__c = 'Directed Fund', Status__c = 'Planned', Slug__c = 'testing1');
		insert project1;

		Training__c tc = new Training__c(Category__c = 'Android Development Training', Type__c = 'Membership');
		insert tc;

		List<Asset> asst = new List<Asset>();
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 1', Training__c = tc.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 2', Training__c = tc.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 3', Training__c = tc.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 4', Training__c = tc.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 5', Training__c = tc.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 6', Training__c = tc.Id));
		asst.add(new Asset(AccountId = acc.Id, Name = 'ABC Asset 7', Training__c = tc.Id));
		insert asst;

		System.debug('>>>>>>>>' + asst);
		String trainingID = String.valueOf(tc.Id);

		ApexPages.StandardController ssc = new ApexPages.StandardController(tc);
		DisplayAssets controller = new DisplayAssets(ssc);
		controller.strID = trainingID;
		controller.assetsListMethod();
	}
}