force-app/main/default/objects/Asset/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores project category for riscv projects</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hold__c.field-meta.xml
<CustomField>
    <fullName>Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Asset__c.field-meta.xml
<CustomField>
    <fullName>Parent_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Products_under_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Total_Products_under_Opportunity__c</fullName>
    <label>Total Products under Opportunity</label>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores the category for Risc-v</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Business_Development_Manager__c.field-meta.xml
<CustomField>
    <fullName>Business_Development_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Development Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Business Development Manager)</relationshipLabel>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Days_to_Deduct__c.field-meta.xml
<CustomField>
    <fullName>Days_to_Deduct__c</fullName>
    <defaultValue>&quot;30&quot;</defaultValue>
    <description>All renewals will close 30 days as default. If your project needs to close earlier than 30 days pick a value other than 30. This change will update all open Renewal opportunity&apos;s close date, Except for Year end renewals.</description>
    <inlineHelpText>All renewals will close 30 days as default. If your project needs to close earlier than 30 days pick a value other than 30. This change will update all open Renewal opportunity&apos;s close date.</inlineHelpText>
    <label>Days to Close Renewals</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <default>true</default>
                <label>30</label>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Executive_Director__c.field-meta.xml
<CustomField>
    <fullName>Executive_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If Executive Director is non-LF employee add contact</inlineHelpText>
    <label>Executive Director</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Executive Director)</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/LF_Membership_Required__c.field-meta.xml
<CustomField>
    <fullName>LF_Membership_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LF membership is required if this project is a Subproject, it has membership, and its parent project is The Linux Foundation. The value of this field is set by workflow rules.</description>
    <inlineHelpText>Indicates if LF membership is required in addition to membership to this project. LF membership is required if this project is a Subproject, it has membership, and its parent project is The Linux Foundation.</inlineHelpText>
    <label>LF Membership Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Opportunity_Owner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The LF staff member who should own New Business Opportunities for this project. In the Project Control Center, this is the equivalent of the &quot;Membership New Sales Owner.&quot;</inlineHelpText>
    <label>Opportunity Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Program_Manager__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If Program Manager is non-LF employee. Create contact and add</inlineHelpText>
    <label>Program Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Program_Manager_U__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager_U__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Manager (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>This field is created for Reporting purpose</description>
    <formula>Name+&apos;;&apos;+Parent_Project__r.Name</formula>
    <label>Proj Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Processing__c.field-meta.xml
<CustomField>
    <fullName>Project_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Project Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <description>Back-end field needed to indicate whether this project has any child projects nested below it (via the Parent Project lookup field). If so, this is a Project Group. If not, this is a Project. This field is automatically updated; users should not set this field manually.</description>
    <inlineHelpText>Back-end field needed to indicate whether this project has any child projects nested below it. If so, this is a Project Group. If not, this is a Project.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
                <default>true</default>
                <label>Project</label>
            </value>
            <value>
                <fullName>Project Group</fullName>
            </value>
            <value>
                <fullName>LF Supported</fullName>
                <isActive>false</isActive>
                <label>LF Supported</label>
            </value>
            <value>
                <fullName>Member Project</fullName>
                <isActive>false</isActive>
                <label>Member Project</label>
            </value>
            <value>
                <fullName>Member Sub-Project</fullName>
                <isActive>false</isActive>
                <label>Member Sub-Project</label>
            </value>
            <value>
                <fullName>Non-Member Project</fullName>
                <isActive>false</isActive>
                <label>Non-Member Project</label>
            </value>
            <value>
                <fullName>Preformation</fullName>
                <isActive>false</isActive>
                <label>Preformation</label>
            </value>
            <value>
                <fullName>Public Domain Project</fullName>
                <isActive>false</isActive>
                <label>Public Domain Project</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <isActive>false</isActive>
                <label>Standalone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Renewal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The LF staff member who should own Renewal Opportunities for this project. In the Project Control Center, this is the equivalent of the &quot;Membership Renewal Owner.&quot;</inlineHelpText>
    <label>Renewal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projects</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Services (Fab, design services)</fullName>
    </customValue>
    <customValue>
        <fullName>Chip (SoC, IP, FPGA)</fullName>
    </customValue>
    <customValue>
        <fullName>I/O (Memory, network, storage)</fullName>
    </customValue>
    <customValue>
        <fullName>Systems (ODM, OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Software (Dev tools, firmware, OS)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry (cloud, mobile, HPC, ML, automotive)</fullName>
    </customValue>
    <customValue>
        <fullName>Research (Universities, Labs, other alliances, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <description>Account Project Category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Project_Handler.cls
public class Project_Handler implements ITriggerHandler{

    public static void BeforeInsert(List<Sobject> triggerNew) {
        //call on Insert action
        updateEDAndProgramManagerUser(triggerNew,null);
    }
    
    public static void BeforeUpdate(Map<Id, Sobject> newMap, Map<Id, Sobject> oldMap) {
        markProjectForProcessing((Map<Id,Project__c>)newMap,(Map<Id,Project__c>)oldMap);
        updateEDAndProgramManagerUser((List<Project__c>)newMap.values(),(Map<Id,Project__c>)oldMap);
        //call before update actions
        // Project_Action action = new Project_Action();
        //   action.validateNetSuiteFieldsBeforeApproval((Map<Id,Project__c>)newMap,(Map<Id, Project__c>) oldMap);
        
    }    
  public static void BeforeDelete(Map<Id, Sobject> oldMap) {
        //call before delete actions
    } 
    
    public static void AfterInsert(Map<Id, SObject> newMap){
        //call onAfterInsert
        //createCollaborations((List<Project__c>)newMap.values());
    }   
    public static void AfterUpdate(Map<Id, SObject> newMap, Map<Id, Sobject> oldMap){  
        
        System.debug('>>>>>>> Call Project');
        //COMMENTED BY PRATIK D - 16-MAY-202
        //updateOpportunityOwner((Map<Id,Project__c>) oldMap, (Map<Id,Project__c>) newMap);
        updateRenewalOpportunityCloseDate((Map<Id, Project__c>) newMap,(Map<Id,Project__c>) oldMap);
    }
    
   public static void AfterDelete(Map<Id, Sobject> oldMap) {
    } 
    
    
   public static void AfterUnDelete(Map<Id, Sobject> newMap) {
        //call after undelete actions
    } 
    
    public Boolean IsDisabled(){
        return false;
    }
    
    //update Opp CloseDate based on projects' Days to deduct
    public static void updateRenewalOpportunityCloseDate(Map<Id, Project__c> newMap,Map<Id,Project__c> oldMap){
        Set<String> projectIdSet = new Set<String>();
        //Iterate through each record and check whether days to deduct is changed or not
        for(Project__c project : newMap.values()){
            if(project.Days_to_Deduct__c != oldMap.get(project.Id).Days_to_Deduct__c && 
               project.Days_to_Deduct__c != null){
                projectIdSet.add(project.Id);
            }
        }
        
        //if set is not empty
        if(!projectIdSet.isEmpty()){
            List<Opportunity> oppList = new List<opportunity>();
            //Get Line item of open renewal opportunity
            List<OpportunityLineItem> oppLineItem = [SELECT Id,OpportunityId,opportunity.parent_asset__r.UsageEndDate,Opportunity.closedate,
                                                     Projects__r.Days_to_Deduct__c
                                                     FROM OpportunityLineItem WHERE Projects__c IN: projectIdSet and Opportunity.Hold__c = false and 
                                                     opportunity.IsClosed = false and opportunity.type like 'Renewal%' and opportunity.parent_asset__c != null];
            if(!oppLineItem.isEmpty()){
                Utility util = new Utility();
                
                //Iterate through line item
                for(OpportunityLineItem oli : oppLineItem){
                    Date endDate = oli.opportunity.parent_asset__r.UsageEndDate;
                    Integer days = Integer.valueOf(oli.Projects__r.Days_to_Deduct__c);
                    
                    //call method to get closeddate
                    Date renewalCloseDate = util.getRenewalCloseDate(endDate, days);
                    if(renewalCloseDate != oli.Opportunity.closedate){
                        System.debug('Opp Id '+oli.OpportunityId+'---'+ oli.Opportunity.closedate);
                        //add to list
                        oppList.add(new Opportunity(Id=oli.OpportunityId,closedate=renewalCloseDate));
                    }
                }
                if(!oppList.isEmpty()){
                    system.debug('oppList '+oppList.size()+' '+oppList); 
                    //update
                    update oppList;
                }
            }
        }
    }
    
    //Mark Project Processing True when project status updated to Active
    public static void markProjectForProcessing( Map<Id,Project__c> newMap,Map<Id,Project__c> oldMap){
        //Id directedProjectId = Schema.SObjectType.Project__c.getRecordTypeInfosByName().get('Directed Fund').getRecordTypeId();
        //Id incorporatedProjectId = Schema.SObjectType.Project__c.getRecordTypeInfosByName().get('Incorporated').getRecordTypeId();
        for(Project__c proj : newMap.values()){
            if(proj.Status__c =='Active' && 
               (proj.Status__c != oldMap.get(proj.ID).Status__c ||
               proj.Name != oldMap.get(proj.ID).Name )&&
               (proj.LF_Membership_Required__c || proj.Category__c == 'Incorporated Entity')){
                proj.Project_Processing__c = true; 
            }
        }
        
    }
    
    // Whenver a project is created create colloborations
    /*public static void createCollaborations(List<Project__c> projects){
        List<Collaboration__c> collaborations = new List<Collaboration__c>();
        for(Project__c project : projects){
            //if the project type is foundation
            if(project.Project_Type__c == 'Foundation')
            {
                collaborations.add(createNewCollaboration('Committee','Governing Board',project.Id));
                collaborations.add(createNewCollaboration('Committee','TOC',project.Id));
                collaborations.add(createNewCollaboration('Committee','Marketing Committee',project.Id));
            }else if(project.Project_Type__c == 'Project'){
                collaborations.add(createNewCollaboration('Committers','Maintainers',project.Id));
                collaborations.add(createNewCollaboration('Committers','Top 100 Contributors',project.Id));
                collaborations.add(createNewCollaboration('Committee','TSC',project.Id));
            }
        }
        if(!collaborations.isEmpty()){
            insert collaborations;
        }
    }*/
    
    /*private static Collaboration__c createNewCollaboration(String collabType,String name,String projectId){
        Collaboration__c collaboration = new Collaboration__c();
        collaboration.Collaboration_Type__c =collabType;
        collaboration.Project_Name__c =projectId;
        collaboration.Collaboration_Name__c = name;
        return collaboration;
    }*/
    
     public static void updateEDAndProgramManagerUser(List<Project__c> projects, Map<Id,Project__c> oldProjects){
        List<Project__c> projectList = new List<Project__c>();
         for(Project__c project : projects) {
             if(oldProjects == null ||( oldProjects!= null && project.Program_Manager__c != oldProjects.get(project.ID).Program_Manager__c)){
                projectList.add(project);
             }
             if(oldProjects == null ||( oldProjects!= null && project.Executive_Director__c != oldProjects.get(project.ID).Executive_Director__c)){
                 projectList.add(project);
             }
             if(oldProjects == null ||( oldProjects!= null && project.Business_Development_Manager__c != oldProjects.get(project.ID).Business_Development_Manager__c)){
                projectList.add(project);   
             }
         }        
         if(!projectList.isEmpty()){
             Project_Action action = new Project_Action();
             action.updateEDAndProgramManagerUser(projectList);
         } 
    }
    //Added by pratik D For update Opportunity Owner From Project based on condition
    /*
    public static void updateOpportunityOwner(Map<Id,Project__c> oldMap, Map<Id,Project__c> newMap){
        
        system.debug('Inside');
        set<Id> setProjectId = new set<Id>();
        set<Id> setOpportunityId = new set<Id>();
        map<Id, Id> mapProjectId_OwnerId = new map<Id, Id>();
        map<Id, Id> mapProjectId_RenewOwnerId = new map<Id, Id>();
        List<Opportunity> lstOpp = new List<Opportunity>();
        map<Id, Opportunity> mapOppId_OpportunityUpdate = new map<Id, Opportunity>();
        
        Id membershipRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Membership').getRecordTypeId();
        
        for(Project__c objProject : newMap.values()){
            
            if( objProject.Renewal_owner__c != oldMap.get(objProject.Id).Renewal_owner__c
                || objProject.Opportunity_owner__c != oldMap.get(objProject.Id).Opportunity_owner__c
                )
            {
                setProjectId.add(objProject.id);
                
                //Owner Preference - opportunityOwnerId, opportunityRenewOwner, ProgramManager
                Id opportunityOwnerId = ( objProject.Opportunity_owner__c != NULL ? objProject.Opportunity_owner__c : objProject.Program_Manager_U__c );
                
                //Owner Preference - opportunityRenewOwner, opportunityOwnerId, ProgramManager 
                
                Id opportunityRenewOwnerId = ( objProject.Renewal_owner__c != NULL ? objProject.Renewal_owner__c : 
                                                                             ( objProject.Opportunity_owner__c != NULL ? objProject.Opportunity_owner__c : objProject.Program_Manager_U__c ) 
                                                                             );
                
                mapProjectId_OwnerId.put( objProject.id, opportunityOwnerId);
                mapProjectId_RenewOwnerId.put( objProject.id, opportunityRenewOwnerId);
            }
        }
        
        map<Id,OpportunityLineItem> mapOpportunityLineItem = new map<Id,OpportunityLineItem>([ SELECT id,Projects__c,opportunityId,opportunity.ownerId 
                                                                                                FROM OpportunityLineItem 
                                                                                                WHERE Projects__c IN:setProjectId 
                                                                                                    AND opportunity.isClosed = false 
                                                                                                    AND opportunity.type != NULL
                                                                                                    AND opportunity.RecordTypeId =: membershipRTId
                                                                                                ]);

        for(OpportunityLineItem objOpportunityLineItem : mapOpportunityLineItem.values()){
            setOpportunityId.add(objOpportunityLineItem.opportunityId);
        }
        map<Id,Opportunity> mapOpportunity = new map<Id,Opportunity>([SELECT id, Name, ownerId, Total_Products_under_Opportunity__c, type
                                                                        FROM Opportunity 
                                                                        WHERE id IN:setOpportunityId 
                                                                            AND isClosed=false 
                                                                            AND type != NULL
                                                                            AND Opportunity.RecordTypeId =: membershipRTId
                                                                    ]);
        
        Integer cpuStart = Limits.getCpuTime();
        
        for(OpportunityLineItem objOpportunityLineItem : mapOpportunityLineItem.values()){
            
            Project__c objProject = newMap.get(objOpportunityLineItem.Projects__c); 
            
            Opportunity objOpportunity = mapOpportunity.get(objOpportunityLineItem.opportunityId);
            
                //NEW OPPORTUNITY
                if(objOpportunity.type == 'New Business'){
                    
                    if(objProject.name =='The Linux Foundation' && objOpportunity.Total_Products_under_Opportunity__c > 1){
                        
                        //DO NOT CHANGE OWNER
                    
                    }else{
                        //CHANGE OWNER
                        if(mapProjectId_OwnerId.get(objProject.Id) != null){
                            Opportunity opp = new Opportunity();
                            opp.Id = objOpportunity.Id;
                            opp.OwnerId = mapProjectId_OwnerId.get(objProject.Id);
                            mapOppId_OpportunityUpdate.put(opp.Id, opp);
                        }
                    }
                }else if( objOpportunity.type == 'Renewal' ){
                    
                    //RENEWAL OPPORTUNITY
                    if(mapProjectId_OwnerId.get(objProject.Id) != null){
                        Opportunity opp = new Opportunity();
                        opp.Id = objOpportunity.Id;
                        opp.OwnerId = mapProjectId_RenewOwnerId.get(objProject.Id);
                        mapOppId_OpportunityUpdate.put(opp.Id, opp);
                    }
                }
        }
        
        if(mapOppId_OpportunityUpdate.size()>0){
            update mapOppId_OpportunityUpdate.values();
        }
    }
    */
}