force-app/main/default/objects/Asset/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores project category for riscv projects</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>OpportunityLineItem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores the category for Risc-v</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Text that will be displayed on invoice</description>
    <inlineHelpText>Text that will be displayed on invoice</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Required</inlineHelpText>
    <label>Start Date*</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Android Development Training</fullName>
            </value>
            <value>
                <fullName>Enterprise IT &amp; Linux System Administration Training</fullName>
            </value>
            <value>
                <fullName>Linux Programming &amp; Development Training</fullName>
            </value>
            <value>
                <fullName>Open Source Compliance Courses</fullName>
            </value>
            <value>
                <fullName>Tizen Project Training</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A one-sentence description of the project, which will be used for external facing (i.e. landscape graphic or a website list of LF projects) descriptions of projects.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Consumer Electronics</fullName>
            </value>
            <value>
                <fullName>Cross-Industry</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Climate</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health Care</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
            <value>
                <fullName>Motion Pictures</fullName>
            </value>
            <value>
                <fullName>Non-profit Organizations</fullName>
            </value>
            <value>
                <fullName>Pharmaceuticals</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Public Health &amp; Disaster Response</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Indicates if the project has Membership, Crowdfunding (e.g. LFX Funding), or both. Note that a project may have membership requirements that do not have any fees or funding associated with them. In that case, &apos;Membership&apos; is still selected for this field.</inlineHelpText>
    <label>Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Crowdfunding</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Parent_Entity_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Parent_Entity_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Incorporated Entity or Series LLC that is the legal parent of the project.</inlineHelpText>
    <label>Legal Parent</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Child Projects of Legal Entity</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Incorporated Entity, Series LLC, or Subproject with which this project is associated. For example, a Series LLC entity may have a legal parent of LF Projects, LLC, but be associated with the parent project LF AI Foundation.</inlineHelpText>
    <label>Parent Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Child Projects</relationshipLabel>
    <relationshipName>Child_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Entity_Name__c</fullName>
    <inlineHelpText>The legal name of the entity or formal Subproject name.</inlineHelpText>
    <label>Formal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <inlineHelpText>The &quot;Prospect&quot; stage is reserved for non-LF projects, e.g. some Community Bridge projects.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Formation - Exploratory</fullName>
            </value>
            <value>
                <fullName>Formation - Engaged</fullName>
            </value>
            <value>
                <fullName>Formation - Confidential</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Formation - On Hold</fullName>
            </value>
            <value>
                <fullName>Formation - Disengaged</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Actively Engaged</fullName>
                <isActive>false</isActive>
                <label>Actively Engaged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Technical_Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Technical_Activity_Type__c</fullName>
    <label>Technical Activity Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Source Software</fullName>
            </value>
            <value>
                <fullName>Open Standard / Specification</fullName>
            </value>
            <value>
                <fullName>Open Hardware</fullName>
            </value>
            <value>
                <fullName>Open Data</fullName>
            </value>
            <value>
                <fullName>Open Governance Network</fullName>
            </value>
            <value>
                <fullName>Community Initiative</fullName>
            </value>
            <value>
                <fullName>Peer Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Services (Fab, design services)</fullName>
    </customValue>
    <customValue>
        <fullName>Chip (SoC, IP, FPGA)</fullName>
    </customValue>
    <customValue>
        <fullName>I/O (Memory, network, storage)</fullName>
    </customValue>
    <customValue>
        <fullName>Systems (ODM, OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Software (Dev tools, firmware, OS)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry (cloud, mobile, HPC, ML, automotive)</fullName>
    </customValue>
    <customValue>
        <fullName>Research (Universities, Labs, other alliances, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <description>Account Project Category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AI, ML, Data &amp; Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud, Containers &amp; Virtualization</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps, CI/CD &amp; Site Reliability</fullName>
    </customValue>
    <customValue>
        <fullName>IoT &amp; Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>Linux Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Networking &amp; Edge</fullName>
    </customValue>
    <customValue>
        <fullName>Open Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source &amp; Compliance Best Practices</fullName>
    </customValue>
    <customValue>
        <fullName>Privacy &amp; Security</fullName>
    </customValue>
    <customValue>
        <fullName>Quantum Computing</fullName>
    </customValue>
    <customValue>
        <fullName>Safety-Critical Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>System Administration</fullName>
    </customValue>
    <customValue>
        <fullName>System Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Visual Effects</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Application Development</fullName>
    </customValue>
    <customValue>
        <fullName>Cybersecurity</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
        <isActive>false</isActive>
        <label>Security</label>
    </customValue>
    <customValue>
        <fullName>Node.js Development</fullName>
        <isActive>false</isActive>
        <label>Node.js Development</label>
    </customValue>
    <customValue>
        <fullName>Open Source Best Practices</fullName>
        <isActive>false</isActive>
        <label>Open Source Best Practices</label>
    </customValue>
    <customValue>
        <fullName>Application Development</fullName>
        <isActive>false</isActive>
        <label>Application Development</label>
    </customValue>
    <description>Technology categories used by training, events, and projects across the LF.  Note that forms in Cvent need to be updated for any label change needed in this value set.</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Chart_RevenueControllerTest.cls
/***
 ** Created by Cloudroute Solutions on 25-03-2021
 ** Test class for Chart_RevenueControllerTest
 ***/
@IsTest
private class Chart_RevenueControllerTest{
	@TestSetup
	static void testSetup(){
		
        Project__c parentProj = new Project__c(Name = 'Parent project', slug__c = 'parent');
        insert parentProj;
        
		/* project */
		Project__c proj = new Project__c();
		proj.Name = 'testProject1';
		proj.Project_Status__c = 'Active';
		proj.Category__c = 'Subproject';
        proj.Slug__c = 'testproj';
        proj.Funding__c = 'Unfunded';
        proj.Project_Entity_Name__c = 'The Linux Foundation';
        proj.Start_Date__c = system.today();
        proj.Industry__c = 'Non-profit Organizations';
        proj.Model__c = 'Alternate Funding';
        proj.Technology__c = 'Blockchain';
        proj.Technical_Activity_Type__c = 'Open Source Software';
        proj.Description__c = 'description';
        proj.Parent_Entity_Relationship__c = parentProj.Id;
        proj.Parent_Project__c = parentProj.Id;
		insert proj;

		/* account */
		Account account = new Account(Name = 'TestAbc');
		insert account;

		/* opportunity */
		Opportunity oppt = new Opportunity();
		oppt.Name = 'Opportunity testing 1';
		oppt.AccountId = account.Id;
		oppt.StageName = '2. Discovery';
		oppt.CloseDate = Date.today().addDays(4);
		insert oppt;

		/* product */
		Product2 prod = new Product2();
		prod.Name = 'Platinum Membership';
		prod.ProductCode = 'test';
		prod.Family = 'Membership';
		prod.isActive = true;
		insert prod;

		/* pricebook and pricebook entry */
		Id pricebookId = Test.getStandardPricebookId();
		PriceBookEntry priceBookEntry = new PriceBookEntry();
		priceBookEntry.PriceBook2Id = pricebookId;
		priceBookEntry.Product2Id = prod.ID;
		priceBookEntry.IsActive = true;
		priceBookEntry.UnitPrice = 34;
		insert priceBookEntry;

		/* opportunity line item */
		OpportunityLineItem oli = new OpportunityLineItem();
		oli.OpportunityId = oppt.Id;
		oli.Quantity = 2;
		oli.UnitPrice = 20;
		oli.PriceBookEntryId = priceBookEntry.ID;
		insert oli;

		/* assets */
		List<Asset> listOfAsset = new List<Asset>();
		for (Integer i = 0; i < 5; i++){
			Asset asset = new Asset();
			asset.Name = 'Test';
			asset.AccountId = account.ID;
			asset.Projects__c = proj.ID;
			asset.Status = 'Active';
            asset.Opportunity__c = oppt.ID;
            asset.Product2Id = prod.ID;
            asset.OpportunityLineItem__c = oli.id;
            asset.InstallDate = System.today();
            asset.Price = 10000;
			listOfAsset.add(asset);
		}
		
        
        Product2 prod2 = new Product2();
        prod2.Name = 'Silver Membership - MPSF';
        prod2.ProductCode = 'test1';
        prod2.Family = 'Membership';
        prod2.isActive = true;
        insert prod2;
        
        Product2 prod3 = new Product2();
        prod3.Name = 'Silver Membership';
        prod3.ProductCode = 'test1';
        prod3.Family = 'Membership';
        prod3.isActive = true;
        insert prod3;
        
        Asset asset2 = new Asset();
        asset2.Name = 'Test1';
        asset2.AccountId = account.ID;
        asset2.Projects__c = proj.ID;
        asset2.Status = 'Active';
        asset2.Opportunity__c = oppt.ID;
        asset2.Product2Id = prod2.ID;
        asset2.OpportunityLineItem__c = oli.id;
        asset2.InstallDate = System.today();
        asset2.Price = 10000;
        
        Asset asset3 = new Asset();
        asset3.Name = 'Test1';
        asset3.AccountId = account.ID;
        asset3.Projects__c = proj.ID;
        asset3.Status = 'Active';
        asset3.Opportunity__c = oppt.ID;
        asset3.Product2Id = prod3.ID;
        asset3.OpportunityLineItem__c = oli.id;
        asset3.InstallDate = System.today();
        asset3.Price = 10000;
        
        listOfAsset.add(asset2);
        listOfAsset.add(asset3);
        insert listOfAsset;
	}

	@IsTest
	static void getFilteredChartDataTest(){
		Project__c proj = [SELECT Id
		                   FROM Project__c  where slug__c = 'testproj'];
		List<String> selectedDates = new List<String>{'2022-02-22', '2020-03-22'};
            List<String> purchaseList = new List<String>{'Renewal'};
		String result = Chart_RevenueController.getFilteredChartData(proj.Id, '', selectedDates, JSON.serialize(purchaseList), 'March-2022', false);
		System.assertNotEquals(null, result);
	}

    @IsTest
	static void getLessThanEqualChartDataTest(){
		Project__c proj = [SELECT Id
		                   FROM Project__c  where slug__c = 'testproj'];
		List<String> selectedDates = new List<String>{'2022-02-22', '2020-03-22'};
		String result = Chart_RevenueController.getFilteredChartData(proj.Id, 'lessThanEqual', selectedDates, null, 'March-2022', false);
		System.assertNotEquals(null, result);
	}

    @IsTest
	static void getFilteredChartDataLessThanEqualTest(){
		Project__c proj = [SELECT Id
		                   FROM Project__c  where slug__c = 'testproj'];
		List<String> selectedDates = new List<String>{'2022-02-22', '2020-03-22'};
		String result = Chart_RevenueController.getFilteredChartData(proj.Id, 'between', selectedDates, null, 'March-2022', false);
		System.assertNotEquals(null, result);
	}

    @IsTest
	static void getFilteredChartDataGreaterThanEqualTest(){
		Project__c proj = [SELECT Id
		                   FROM Project__c  where slug__c = 'testproj'];
		List<String> selectedDates = new List<String>{'2022-02-22', '2020-03-22'};
		String result = Chart_RevenueController.getFilteredChartData(proj.Id, 'greaterThanEqual', selectedDates, null, 'March-2022', false);
		System.assertNotEquals(null, result);
	}

    @IsTest
	static void getFilteredChartDataEqualTest(){
		Project__c proj = [SELECT Id
		                   FROM Project__c  where slug__c = 'testproj'];
		List<String> selectedDates = new List<String>{'2022-02-22'};
		String result = Chart_RevenueController.getFilteredChartData(proj.Id, 'equal', selectedDates, null, 'March-2022', false);
		System.assertNotEquals(null, result);
        selectedDates.add('2022-02-24');
        String result1 = Chart_RevenueController.getFilteredChartData(proj.Id, 'equal', selectedDates, null, 'March-2022', false);
	}

    @IsTest
	static void getFilteredChartDataEqualLessThanTest(){
		Project__c proj = [SELECT Id
		                   FROM Project__c  where slug__c = 'testproj'];
		List<String> selectedDates = new List<String>{'THIS_YEAR_Plus_To_Date'};
		String result = Chart_RevenueController.getFilteredChartData(proj.Id, 'equalLessThan', selectedDates, null, 'December-2022', false);
		System.assertNotEquals(null, result);
	}
    
    @IsTest
    static void getFilteredChartDataEqualLessThanTest1(){
        Project__c proj = [SELECT Id
                           FROM Project__c  where slug__c = 'testproj'];
        List<String> selectedDates = new List<String>{'Fiscal_Quarter_Plus_To_Date'};
            String result = Chart_RevenueController.getFilteredChartData(proj.Id, 'equalLessThan', selectedDates, null, 'December-2022', false);
        //System.assertNotEquals(null, result);
    }
    
    @IsTest
    static void getFilteredChartDataEqualLessThanTest2(){
        Project__c proj = [SELECT Id
                           FROM Project__c  where slug__c = 'testproj'];
        List<String> selectedDates = new List<String>{'Fiscal_Year_Plus_To_Date'};
            String result = Chart_RevenueController.getFilteredChartData(proj.Id, 'equalLessThan', selectedDates, null, 'December-2022', false);
        //System.assertNotEquals(null, result);
    }

    @IsTest
	static void getFilteredChartDataMonthlyTest(){
		Project__c proj = [SELECT Id
		                   FROM Project__c  where slug__c = 'testproj'];
		List<String> selectedDates = new List<String>{'2022-02-22', '2020-03-22'};
		String result = Chart_RevenueController.getFilteredChartData(proj.Id, 'between', selectedDates, null, 'March-2022', true);
		System.assertNotEquals(null, result);
	}
    
    @IsTest
    static void getListOfAssets1(){
        Project__c proj = [SELECT Id
                           FROM Project__c  where slug__c = 'testproj'];
        List<String> selectedDates = new List<String>{'2022-02-22', '2020-03-22'};
        Chart_RevenueController.getListOfAssets(proj.Id, 'between', selectedDates, null, null, null,null, true, true, null);
        //System.assertNotEquals(null, result);
    }

	@IsTest
	static void getActiveMembersTest(){
		Project__c proj = [SELECT Id
		                   FROM Project__c  where slug__c = 'testproj'];
		Double result = Chart_RevenueController.getActiveMembers(proj.Id);
		//System.assertEquals(5.0, result);
	}

	@IsTest
	static void getFilteredTableDataTest(){
		Project__c proj = [SELECT Id
		                   FROM Project__c  where slug__c = 'testproj'];
		List<String> selectedDates = new List<String>{'2020-02-22', '2022-03-22'};
		Chart_RevenueController.ReturnAssetWrapper result = Chart_RevenueController.getFilteredTableData(proj.Id, 'between', selectedDates, null, 'March-2022', 'Platinum Membership', false, true);
		System.assertNotEquals(null, result);
	}

	@IsTest
	static void getPurchaseTypesTest(){
		List<String> result = Chart_RevenueController.getPurchaseTypes();
		System.assertEquals(5, result.size());
	}
    
    @isTest
    static void prepareMapForAggregatePurchaseHistTest(){
        test.startTest();
        Project__c proj = [SELECT Id
		                   FROM Project__c  where slug__c = 'testproj' LIMIT 1];
        List<AggregateResult> lfSilverMemberMpsfSum = [SELECT SUM(Price)total, Name year, AssetLevel month  FROM Asset WHERE Product2.Name = 'Silver Membership - MPSF' and Projects__c =: proj.Id AND Status IN ('Active', 'Completed', 'Expired', 'Purchased') GROUP BY Name, AssetLevel];
        Chart_RevenueController.prepareMapForAggregatePurchaseHist(lfSilverMemberMpsfSum, new Map<String, Decimal>{}, true);
        test.stopTest();
    }
}