force-app/main/default/objects/Asset/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores project category for riscv projects</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <formula>IF(NOT(ISBLANK(Projects__c)),HYPERLINK(&quot;/&quot;+Projects__c,Projects__r.Name,&quot;_top&quot;), 
IF(NOT(ISBLANK(Event__c)),HYPERLINK(&quot;/&quot;+Event__c,Event__r.Name,&quot;_top&quot;),IF(NOT(ISBLANK(Training__c)),HYPERLINK(&quot;/&quot;+Training__c,Training__r.Name,&quot;_top&quot;),&quot;&quot;)) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>E-Learning</fullName>
            </value>
            <value>
                <fullName>Instructor-Led</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Services (Fab, design services)</fullName>
    </customValue>
    <customValue>
        <fullName>Chip (SoC, IP, FPGA)</fullName>
    </customValue>
    <customValue>
        <fullName>I/O (Memory, network, storage)</fullName>
    </customValue>
    <customValue>
        <fullName>Systems (ODM, OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Software (Dev tools, firmware, OS)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry (cloud, mobile, HPC, ML, automotive)</fullName>
    </customValue>
    <customValue>
        <fullName>Research (Universities, Labs, other alliances, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <description>Account Project Category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UpdateStatusOfAssetsBatch.cls
global class UpdateStatusOfAssetsBatch implements Database.Batchable<sObject>,Database.Stateful {

    public Date closeDateForZeroPriceAssets;
     
    public UpdateStatusOfAssetsBatch(Date closeDateForZeroPriceAssets) {
        this.closeDateForZeroPriceAssets = closeDateForZeroPriceAssets;   
    }
   
    public UpdateStatusOfAssetsBatch() {
        this.closeDateForZeroPriceAssets = NULL;   
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Related_To__c, Training__c, Training__r.Category__c, RecordTypeId, RecordType.Name, Opportunity__c, Price, UsageEndDate, PurchaseDate, Opportunity__r.Amount '+
             'FROM Asset WHERE Training__c != NULL AND RecordType.Name = \'Corporate\' AND Training__r.Category__c = \'Subscription\' AND '+
             'Status != \'Expired\' AND Opportunity__c != NULL AND Price != NULL AND PurchaseDate != NULL AND Opportunity__r.Amount != NULL' 
        );
        
    }
    global void execute(Database.BatchableContext bc, List<Asset> scope){
        if(!scope.isEmpty()){
            UpdateStatusOfAssetsBatchHelper.updateAssets(scope, closeDateForZeroPriceAssets);
        }
      
    }       
    global void finish(Database.BatchableContext bc){
    }    
}