force-app/main/default/objects/Asset/fields/CNCF_Level__c.field-meta.xml
<CustomField>
    <fullName>CNCF_Level__c</fullName>
    <label>CNCF Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>End User Supporter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Skip_NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>Skip_NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Account_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Account_Team_Member__c</fullName>
    <label>Account Team Member</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/AgreementDate__c.field-meta.xml
<CustomField>
    <fullName>AgreementDate__c</fullName>
    <inlineHelpText>Countersigned date of agreement (manually set by membership sales)</inlineHelpText>
    <label>Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CNCF_Level__c.field-meta.xml
<CustomField>
    <fullName>CNCF_Level__c</fullName>
    <label>CNCF Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>End User Supporter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/End_Tier__c.field-meta.xml
<CustomField>
    <fullName>End_Tier__c</fullName>
    <label>End Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Membership_Tier__c.field-meta.xml
<CustomField>
    <fullName>Membership_Tier__c</fullName>
    <label>Membership Tier</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <description>Cannot be entered after closed won. Notify Finance via email if needed.</description>
    <inlineHelpText>Cannot be entered after closed won. Notify Finance via email if needed.</inlineHelpText>
    <label>PO Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Prorate__c.field-meta.xml
<CustomField>
    <fullName>Prorate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prorate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quote_Product__c.field-meta.xml
<CustomField>
    <fullName>Quote_Product__c</fullName>
    <label>Quote Product</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Renewal_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Campaign__c</fullName>
    <label>Renewal Campaign</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Skip_NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>Skip_NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, the Purchase History that is created from this line item will not be sent to NetSuite. You probably don&apos;t want this.</description>
    <inlineHelpText>When selected, the Purchase History that is created from this line item will not be sent to NetSuite. You probably don&apos;t want this.</inlineHelpText>
    <label>Skip NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Skip_Sync_Updated_By__c.field-meta.xml
<CustomField>
    <fullName>Skip_Sync_Updated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skip Sync Updated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Product1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Skip_Sync_Updated_On__c.field-meta.xml
<CustomField>
    <fullName>Skip_Sync_Updated_On__c</fullName>
    <label>Skip Sync Updated On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Start_Tier__c.field-meta.xml
<CustomField>
    <fullName>Start_Tier__c</fullName>
    <label>Start Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Team_Member_Title__c.field-meta.xml
<CustomField>
    <fullName>Team_Member_Title__c</fullName>
    <label>Team Member Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
            <value>
                <fullName>01241000001E0UhAAK</fullName>
                <isActive>false</isActive>
                <label>01241000001E0UhAAK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Course</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>E-Learning</fullName>
            </value>
            <value>
                <fullName>Instructor-Led</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/End_Tier__c.field-meta.xml
<CustomField>
    <fullName>End_Tier__c</fullName>
    <label>End Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Start_Tier__c.field-meta.xml
<CustomField>
    <fullName>Start_Tier__c</fullName>
    <label>Start Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/End_Tier__c.field-meta.xml
<CustomField>
    <fullName>End_Tier__c</fullName>
    <label>End Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projects</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Start_Tier__c.field-meta.xml
<CustomField>
    <fullName>Start_Tier__c</fullName>
    <label>Start Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OppChangeProductController.cls
public with sharing class OppChangeProductController {

        @AuraEnabled(cacheable=false)
        public static List<List<Product_Details__c>> getOptions(ID oppID){
            //get current membership Opportunity Products on this opp
            List<OpportunityLineItem> olis = new List<OpportunityLineItem>();
            olis = [SELECT Projects__c, Projects__r.Name, Product_Details__c, Product2.Name
                    FROM OpportunityLineItem
                    WHERE OpportunityId = :oppID
                    AND Product2.Family = 'Membership'
                    ORDER BY Product2.Name ASC
                ];
            
            //if no membership Opportunity Products were found, return empty list
            if(olis.size() == 0){
                List<List<Product_Details__c>> emptyList = new List<List<Product_Details__c>>();
                return emptyList;
            }
            
            //create and populate a map of the Projects on the current Opportunity Products
            //create and populate a set of the Product Details on the current Opportunity Products
            Set<ID> projects = new Set<ID>();
            Set<ID> prodDetailsSelected = new Set<ID>();
            for(OpportunityLineItem oli : olis){
                projects.add(oli.Projects__r.Id);
                prodDetailsSelected.add(oli.Product_Details__c);
            }

            //check for a few scenarios (that shouldn't ever happen, but just in case)
            //that could break the LWC, and return null if any are true
            if( olis.size() != projects.size() ){
                System.debug('error: number of distinct Project IDs found on Opp Products does not match number of Opp Products found');
                return null;
            }else if( olis.size() != prodDetailsSelected.size() ){
                System.debug('error: number of distinct Product Detail IDs found on Opp Products does not match number of Opp Products found');
                return null;
            }else if(olis.size() > 2){
                System.debug('error: more than two membership Opp Products were found');
                return null;
            }
            
            //get all possible (active) Product Details for these Projects,
            //except the ones that are already on this opportunity
            List<Product_Details__c> prodDetails = new List<Product_Details__c>();
            prodDetails = [SELECT Project__c, Start_Tier__c, End_Tier__c, Price__c,
                                Project__r.Name, Products__r.Name
                        FROM Product_Details__c
                        WHERE Project__c IN :projects
                        AND Id NOT IN :prodDetailsSelected
                        AND Status__c = 'Active'
                        AND Products__r.Family = 'Membership'
                        AND Products__r.Name != 'Individual Supporter'
                        AND Products__r.Name != 'Lifetime Linux.com Email Add-On'
                        AND Products__r.Name != 'Silver Membership - MPSF'
                        ORDER BY Products__r.Name ASC, Price__c DESC
                        ];

            //split the prodDetails returned into two different lists (one for each project),
            //if there were two OLIs
            List<Product_Details__c> prodDetails1 = new List<Product_Details__c>();
            List<Product_Details__c> prodDetails2 = new List<Product_Details__c>();
            for(Product_Details__c pd : prodDetails){
                if(pd.Project__c == olis[0].Projects__c){
                    prodDetails1.add(pd);
                }else if(olis.size() == 2 && pd.Project__c == olis[1].Projects__c){
                    prodDetails2.add(pd);
                }
            }

            //create and populate list to be returned
            List<List<Product_Details__c>> listOfLists = new List<List<Product_Details__c>>();
            if(prodDetails1.size() > 0){
                listOfLists.add(prodDetails1);
            }
            if(prodDetails2.size() > 0){
                listOfLists.add(prodDetails2);
            }
            return listOfLists;
        }

        @AuraEnabled
        public static void updateProducts(ID oppID, List<ID> selectedProdDetailIDs){
            //get current membership Opportunity Products on this opp
            Map<Id, OpportunityLineItem> olis = new Map<Id, OpportunityLineItem>([SELECT OpportunityId, Product2Id, Product_Details__c, Prorate__c, 
            PO_Number__c, Skip_NetSuite_Sync__c, Skip_Sync_Updated_By__c,
            Skip_Sync_Updated_On__c, CNCF_Level__c, Renewal_Campaign__c,
            Membership_Tier__c, Quote_Product__c, Account_Team_Member__c,
            Team_Member_Title__c, AgreementDate__c, Quantity, Type__c,
            Start_Date__c, End_Date__c, Year__c, NetSuite_Invoice_Memo__c,
            Display_Logo_On_Website__c, No_Press_Release_Announcement__c,
            Send_Date__c, Parent_Product__c, Projects__c,
            Opportunity.Parent_Asset__r.Annual_Full_Price__c, Opportunity.Type
                    FROM OpportunityLineItem
                    WHERE OpportunityId = :oppID
                    AND Product2.Family = 'Membership'
                    ]);

            //create a map of Project ID to OLI ID
            Map<ID, Id> projectIDToOLIID = new Map<ID, Id>();
            for(OpportunityLineItem oli : olis.values()){
                projectIDToOLIID.put(oli.Projects__c, oli.Id);
            }

            //get the Project of each Product Detail selected
            List<Product_Details__c> selectedProdDetails = new List<Product_Details__c>();
            selectedProdDetails = [SELECT Project__c, Products__c, Start_Tier__c, End_Tier__c, Tier__c, Number_Of_Years_Required__c,
            Renewal_Type__c, NetSuite_Class__c, toLabel(NS_Department__c),
            toLabel(NS_Deferred_Revenue_Account__c), toLabel(NS_Income_GL_Account__c),
            toLabel(NS_Revenue_Schedule__c), Netsuite_ID__c, Tax_Class__c, Price__c
                                FROM Product_Details__c
                                WHERE Id IN :selectedProdDetailIDs
                                ];
            
            //map each Product Detail selected to the correct Opp Product
            //by looking at the Project on each
            Map<Id, Product_Details__c> oliIDToProdDetailID = new Map<ID, Product_Details__c>();
            for(Product_Details__c pd : selectedProdDetails){
                oliIDToProdDetailID.put( projectIDToOLIID.get(pd.Project__c), pd );
            }
            
            //Added by Priyesh @cloudroute to bulkify
            ChangeProductUtil.changeProductDetailOnOLI(oliIDToProdDetailID, olis);

            return;
        }

    }