force-app/main/default/objects/Asset/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Manual_Status_Check__c.field-meta.xml
<CustomField>
    <fullName>Manual_Status_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <businessProcess>Event</businessProcess>
    <description>Record type for event opportunities</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>false</active>
    <businessProcess>Training</businessProcess>
    <description>Record type for training opportunities</description>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Product_Details__c/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Product_Details__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/Profile_by_allowed_Opportunity_Type__c/Profile_by_allowed_Opportunity_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Profile by allowed Opportunity Type</label>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Manual_Status_Check__c.field-meta.xml
<CustomField>
    <fullName>Manual_Status_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Date Confirmed</fullName>
            </value>
            <value>
                <fullName>Materials Sent</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataUtilsTest.cls
@isTest
Public Class TestDataUtilsTest{

    private static testMethod void TestDataUtilss(){
    
        TestDataUtils td = new TestDataUtils();
        User userid = TestDataUtils.createUser('TestDataUtils');
        Account accId = TestDataUtils.createAccount('TestData');
        Contact conId = TestDataUtils.createContact('firstname','lastname',accId.id);
        Opportunity oppId = TestDataUtils.createOpenOpportunity(accId.id,'testdata opp','2. Discovery');
        Opportunity closedOppId = TestDataUtils.createClosedOpportunity(accId.id,'testdata opp','2. Discovery');
        OpportunityContactRole billingContact = TestDataUtils.createBillingContact(oppId.id,conId.id);
        Product2 prodId = TestDataUtils.createProduct('Free Training','description',6,'Training');
        PricebookEntry pbid = TestDataUtils.createPriceBookEntryID(prodId.id);
        OpportunityLineItem oppProdID = TestDataUtils.createOpportunityProduct(oppId.id,pbid.id);

        
        //TestDataUtils.insertWorkThanks();
        //TestDataUtils.insertWorkBadge();
        //TestDataUtils.insertWorkBadgeDefinition();
        
    }
    private static testMethod void TestDataUtilsMethod(){
    
        TestDataUtils td = new TestDataUtils();
        User userid = TestDataUtils.createUser(true,'TestDataUtils78');
        Account acc =  TestDataUtils.createAccount(true,'Test 12 Account');   
        Lead ld=TestDataUtils.createLead(true,'Test','Lead1','Lead1 Company','Content','test21134@test.com');
        Opportunity oppt = TestDataUtils.createOpenOpportunity(true,acc.Id,'New Deal 5 Test','2. Discovery');
        Profile_by_allowed_Opportunity_Type__c pb =TestDataUtils.createProfileAllowedOpportunityType (true,'Test demo Setting', 'System Administrator');
        Product2 prod = TestDataUtils.createProduct(true,'Laptop X2001','Test Product',true,'Membership');
        PricebookEntry pbEntry = TestDataUtils.createPriceBookEntryID(true,prod.Id);
        Project__c project= TestDataUtils.createProject(true,'The Linux Foundation','Membership','Linux Foundation','Planned');
        project.Status__c = 'Active';
        project.Manual_Status_Check__c = false;
        project.Funding__c = 'Funded';
        update project;
        Event__c event= TestDataUtils.createEvent(false,'Test Event 989','Event','LF Event','Active');
        event.BillFromProject__c =project.id;
        
        insert event;
        Training__c tc =TestDataUtils.createTraining(true,'Test demo Training','Training','Android Development Training','Active');
        Product_Details__c pd=TestDataUtils.createProductDetail(true,project.Id,null,null,prod.Id);
        Asset asst = TestDataUtils.createAsset(false,'ABC Asset demo',acc.id,prod.Id,'Purchased');
        asst.RecordTypeId=System.label.Corporate_Asset_Record_Type;
        insert asst;
        OpportunityLineItem oli = TestDataUtils.createOpportunityProduct(true,oppt.Id,pbEntry.Id);

        //TestDataUtils.insertWorkThanks();
        //TestDataUtils.insertWorkBadge();
        //TestDataUtils.insertWorkBadgeDefinition();
        
    }
}