force-app/main/default/objects/Asset/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountSponsorshipSummaryController.cls
public with sharing class AccountSponsorshipSummaryController {

    @AuraEnabled(cacheable=true)
    public static List<Asset> getSponsorships(ID accountID,ID NewRecordId){
        if(NewRecordId !=null){
        return [SELECT Name, Price, Event__r.BillFromProject__c, Event__r.BillFromProject__r.Name,
                       Product2.Name, Event__r.Name, Status, Year__c
                FROM Asset
                WHERE AccountId = :NewRecordId
                AND Event__c != ''
                AND Product2Id != ''
                AND ProductFamily = 'Event'
                ORDER BY Year__c DESC, Event__r.Name ASC, Product2.Name ASC
               ];
        }else{
             return [SELECT Name, Price, Event__r.BillFromProject__c, Event__r.BillFromProject__r.Name,
                       Product2.Name, Event__r.Name, Status, Year__c
                FROM Asset
                WHERE AccountId = :accountID
                AND Event__c != ''
                AND Product2Id != ''
                AND ProductFamily = 'Event'
                ORDER BY Year__c DESC, Event__r.Name ASC, Product2.Name ASC 
               ];
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Asset> getTrainingSponsorships(ID accountID,ID NewRecordId){
        system.debug('NewRecordId-->'+NewRecordId);
        if(NewRecordId !=null){
          return [SELECT Name, Price,
                       Product2.Name, Training__r.Name, Status, Year__c
                FROM Asset
                WHERE AccountId = :NewRecordId 
                AND Product2Id != ''
                AND ProductFamily = 'Training'
                AND RecordType.Name = 'Corporate Training'
                ORDER BY Year__c DESC, Training__r.Name ASC, Product2.Name ASC
               ];
        }else{
            return [SELECT Name, Price,
                       Product2.Name, Training__r.Name, Status, Year__c
                FROM Asset
                WHERE AccountId = :accountID 
                AND Product2Id != ''
                AND ProductFamily = 'Training'
                AND RecordType.Name = 'Corporate Training'  
                ORDER BY Year__c DESC, Training__r.Name ASC, Product2.Name ASC
               ];
        }
    }

}