force-app/main/default/objects/Asset/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Manager (without subordinates)</fullName>
            </value>
            <value>
                <fullName>Manager (with subordinates)</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Owner/Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>Event_Location_Country__c</fullName>
    <label>Event Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bonaire S.E.S.</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Program_Manager__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If Program Manager is non-LF employee. Create contact and add</inlineHelpText>
    <label>Program Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/Project_Role__c.object-meta.xml
<CustomObject>
    <label>Membership Roles</label>
    <nameField>
        <displayFormat>PR{000}</displayFormat>
        <label>Role AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Role__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Membership Roles</relationshipLabel>
    <relationshipName>Project_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Project_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Membership Roles</relationshipLabel>
    <relationshipName>Membership_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Voting Contact means this is the person at the company that has the right to vote in the project’s membership elections for their member class.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Representative/Voting Contact</fullName>
                <label>Voting Contact</label>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Legal Contact</fullName>
            </value>
            <value>
                <fullName>Event Sponsorship</fullName>
            </value>
            <value>
                <fullName>PO Contact</fullName>
            </value>
            <value>
                <fullName>Press Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projects</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EventProjectContactWrapper_Test.cls
@isTest
public class EventProjectContactWrapper_Test {
    
    @isTest
    static void sortyByProjectRole(){
        Asset ast =  TestFactory.getAsset();
        Contact con2 = new Contact();
        con2.LastName = 'Phil';
        con2.FirstName ='Wright';
        insert con2;
        Project_Role__c projRole1 = new Project_Role__c(Contact__c = con2.Id, Role__c = 'Representative/Voting Contact', Asset__c = ast.Id);
        Project_Role__c projRole2 = new Project_Role__c(Contact__c = con2.Id, Role__c = 'Marketing Contact', Asset__c = ast.Id);
        Project_Role__c projRole3 = new Project_Role__c(Contact__c = con2.Id, Role__c = 'Marketing Contact', Asset__c = ast.Id,PrimaryContact__c = true);

        List<EventProjectContactWrapper> wrapper = new List<EventProjectContactWrapper>();
        wrapper.add(new EventProjectContactWrapper(null,projRole1,con2));   
        wrapper.add(new EventProjectContactWrapper(null,projRole2,con2));   
        wrapper.add(new EventProjectContactWrapper(null,projRole3,con2)); 
        
        EventProjectContactWrapper.compareField = 'projRole.PrimaryContact__c';
        EventProjectContactWrapper.sortOrder = 'ASC';
        wrapper.sort();
        
        EventProjectContactWrapper.compareField = 'projRole.Asset__r.Projects__r.Name';
        EventProjectContactWrapper.sortOrder = 'ASC';
        wrapper.sort();
        System.assertEquals('Representative/Voting Contact', wrapper[0].projRole.Role__c);

        EventProjectContactWrapper.compareField = 'projRole.Role__c';
        EventProjectContactWrapper.sortOrder = 'ASC';
        wrapper.sort();
        System.assertEquals('Marketing Contact', wrapper[0].projRole.Role__c);
        
        
    }
    
    @isTest
    static void sortyByContact(){
        List<EventProjectContactWrapper> wrapper = new List<EventProjectContactWrapper>();
        Contact cnt = new Contact(LastName = 'Name',FirstName='test',MailingCountry = 'US',HasOptedOutOfEmail= true);
        Contact cnt1 = new Contact(LastName = 'Name2',FirstName='test2',MailingCountry='EU',HasOptedOutOfEmail =false,Email='test1@12.com');
        Contact cnt2 = new Contact(LastName = 'Name1',FirstName='test',MailingCountry='US');
        Contact cnt3 = new Contact(LastName = 'Name',FirstName='test1',Email ='test@test.com');
        
        
        wrapper.add(new EventProjectContactWrapper(null,null,cnt));   
        wrapper.add(new EventProjectContactWrapper(null,null,cnt1));
        wrapper.add(new EventProjectContactWrapper(null,null,cnt2));            
        wrapper.add(new EventProjectContactWrapper(null,null,cnt3));            
        
        
        EventProjectContactWrapper.compareField = 'cnt.Name';
        EventProjectContactWrapper.sortOrder = 'ASC';
        wrapper.sort();
        System.assertEquals(null, wrapper[0].cnt.Name);
        
        EventProjectContactWrapper.compareField = 'cnt.LastName';
        wrapper.sort();
        System.assertEquals('Name', wrapper[0].cnt.LastName);
        
        EventProjectContactWrapper.compareField = 'cnt.FirstName';
        wrapper.sort();
        System.assertEquals('test', wrapper[0].cnt.FirstName);
        
        EventProjectContactWrapper.compareField = 'cnt.MailingCountry';
        wrapper.sort();
        System.assertEquals(null, wrapper[0].cnt.MailingCountry);
        
        EventProjectContactWrapper.compareField = 'cnt.Email';
        wrapper.sort();
        
        EventProjectContactWrapper.compareField = 'cnt.HasOptedOutOfEmail';
        wrapper.sort();
    }
    
    @isTest
    static void sortyByEvent(){
        List<EventProjectContactWrapper> wrapper = new List<EventProjectContactWrapper>();
        Project__c prj = TestDataUtils.createProject(true, 'The Linux Foundation', 'Event', 'Directed Fund', 'Planned');
        prj.Subsidiary_ID__c = 8;
        prj.Status__c = 'Active';
        prj.Funding__c = 'Funded';
        update prj;
        
        Event__c evt = TestDataUtils.createEvent(false, 'Test Event', 'Unfunded', 'LF Event', 'Planned');
        evt.BillFromProject__c = prj.Id;
        evt.Event_Location_Country__c = 'United Kingdom';
        
        Event__c evt1 = TestDataUtils.createEvent(false, 'Test Event1', 'Unfunded', 'LF Event', 'Planned');
        evt.BillFromProject__c = prj.Id;
        evt.Event_Location_Country__c = 'United States';
        
        Event__c evt2 = TestDataUtils.createEvent(false, 'Test Event2', 'Unfunded', 'LF Event', 'Planned');
        evt.BillFromProject__c = prj.Id;
        evt.Event_Location_Country__c = 'United Kingdom';
        
        
        wrapper.add(new EventProjectContactWrapper(evt,null,null));
        wrapper.add(new EventProjectContactWrapper(evt1,null,null));
        wrapper.add(new EventProjectContactWrapper(evt2,null,null));
        
        
        EventProjectContactWrapper.compareField = 'event.Name';
        EventProjectContactWrapper.sortOrder = 'ASC';
        wrapper.sort();
        System.assertEquals('Test Event', wrapper[0].event.Name);
        
        EventProjectContactWrapper.compareField = 'event.Start_Date__c';
        EventProjectContactWrapper.sortOrder = 'ASC';
        wrapper.sort();
        System.assertEquals('Test Event', wrapper[0].event.Name);
        
        EventProjectContactWrapper.compareField = 'event.Event_Location_Country__c';
        EventProjectContactWrapper.sortOrder = 'ASC';
        wrapper.sort();        
    }
    
    
    
}