force-app/main/default/objects/Asset/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Membership AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Annual_Price__c.field-meta.xml
<CustomField>
    <fullName>Annual_Price__c</fullName>
    <inlineHelpText>Annual/Full Price of most recent renewal of this membership</inlineHelpText>
    <label>Annual Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Membership level of most recent renewal of this membership</inlineHelpText>
    <label>Level</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
   TODAY() &lt; Start_Date__c,
   &quot;Purchased&quot;,
   IF(
      OR(
         TODAY() &gt; End_Date__c,
         ISBLANK(End_Date__c)
        ),
      &quot;Expired&quot;,
      &quot;Active&quot;
     )
  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectMemberSummaryController.cls
public with sharing class ProjectMemberSummaryController {

    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getCorporateMemberships(ID projectID) {
        List<AggregateResult> groupedResults = new List<AggregateResult>();
        groupedResults = [SELECT Product__r.Name, COUNT(Id)
                          FROM Membership__c
                          WHERE Project__c = :projectID
                          AND Product__c != null
                          AND (Status__c = 'Active' OR Status__c = 'Purchased')
                          GROUP BY Product__r.Name
                          ORDER BY AVG(Annual_Price__c) DESC
                         ];
        return groupedResults;
    }

    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getIndividualMemberships(ID projectID) {
        List<AggregateResult> groupedResults = new List<AggregateResult>();
        groupedResults = [SELECT Product2.Name, COUNT(Id)
                          FROM Asset
                          WHERE Projects__c = :projectID 
                          AND Status = 'Active'
                          AND ProductFamily = 'Membership'
                          AND RecordTypeId = :Label.Individual_Asset_Record_Type
                          AND Product2.Name != 'Individual Supporter'
                          AND Product2.Name != 'Lifetime Linux.com Email Add-On'
                          GROUP BY Product2.Name 
                          ORDER BY AVG(Price) DESC
                         ];
        return groupedResults;
    }

}