force-app/main/default/objects/Asset/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Skip_NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>Skip_NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Membership AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Annual_Price__c.field-meta.xml
<CustomField>
    <fullName>Annual_Price__c</fullName>
    <inlineHelpText>Annual/Full Price of most recent renewal of this membership</inlineHelpText>
    <label>Annual Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Membership level of most recent renewal of this membership</inlineHelpText>
    <label>Level</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectMemberSummaryControllerTest.cls
@isTest
private class ProjectMemberSummaryControllerTest {

    @isTest static void testGettingCorporateMemberships() {
        Account acc = TestFactory.getAccount();
        Project__c proj = TestFactory.getProject();
        Product2 prod = TestFactory.getProduct2();
        
        Membership__c memb = new Membership__c();
        memb.Account__c = acc.Id;
        memb.Project__c = proj.Id;
        memb.Product__c = prod.Id;
        memb.Annual_Price__c = 50000;
        memb.End_Date__c = Date.today();
        insert memb;
        
        List<AggregateResult> groupedResults = ProjectMemberSummaryController.getCorporateMemberships(proj.Id);
        System.assert(groupedResults.size() == 1);
    }
    
    @isTest static void testGettingIndividualMemberships() {
        Id individualRTID = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        
        Contact con = TestFactory.getContact();
        Project__c proj = TestFactory.getProject();
        Product2 prod = TestFactory.getProduct2();
        
        Asset asst = new Asset();
        asst.Name = 'Test individual asset';
        asst.RecordTypeId = individualRTID;
        asst.ContactId = con.Id;
        asst.Projects__c = proj.Id;
        asst.Product2Id = prod.Id;
        asst.Skip_NetSuite_Sync__c = true;
        asst.Status = 'Active';
        asst.UsageEndDate = System.today();
        insert asst;
        
        List<AggregateResult> groupedResults = ProjectMemberSummaryController.getIndividualMemberships(proj.Id);
        System.assert(groupedResults.size() == 1);
    }

}