force-app/main/default/objects/Asset/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Number_of_Years_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_Required__c</fullName>
    <label>Number of Years Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SalesOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>SalesOrderStatus__c</fullName>
    <label>Sales Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Not Synced to Netsuite</fullName>
                <default>true</default>
                <label>Not Synced to Netsuite</label>
            </value>
            <value>
                <fullName>At Risk</fullName>
                <isActive>false</isActive>
                <label>At Risk</label>
            </value>
            <value>
                <fullName>Invoice not created</fullName>
                <isActive>false</isActive>
                <label>Invoice not created</label>
            </value>
            <value>
                <fullName>Sent</fullName>
                <isActive>false</isActive>
                <label>Sent</label>
            </value>
            <value>
                <fullName>Unsent</fullName>
                <isActive>false</isActive>
                <label>Unsent</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Skip_NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>Skip_NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Endpoints__c/Endpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Endpoints</label>
</CustomObject>

force-app/main/default/objects/Endpoints__c/fields/Nlauth_Account__c.field-meta.xml
<CustomField>
    <fullName>Nlauth_Account__c</fullName>
    <label>Nlauth_Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesOrderStatusControllerTest.cls
@isTest
public class SalesOrderStatusControllerTest {
    
    @testSetup
    public static void setup(){
        Endpoints__c endPoint = new Endpoints__c();
        endPoint.Name = 'To Get Sales Order Status From NS';
        endPoint.Endpoint__c = 'https://4010327-sb1.restlets.api.netsuite.com/app/site/hosting/restlet.nl?script=43&deploy=1';
        endPoint.Password__c = 'jYdpn8sp22F8C45b';
        endPoint.User_Id__c = 'nsapi@linuxfoundation.org';
        endPoint.Nlauth_Account__c = '4010327_SB1';
        insert endPoint;
        
        Account acc = new Account();
        acc.Name = 'TEST ACC';
        insert acc;
        Asset assetObj = new Asset ();
        assetObj.name = 'Test';
        assetObj.Number_of_Years_Required__c = 1;
        assetObj.NetSuite_ID__c = '1539958';
        assetObj.AccountId = acc.id;
        assetObj.Skip_NetSuite_Sync__c = true;
        insert assetObj;
    }
    
    @isTest
    static void getStatusTest(){
        Asset asset =  [Select Id From Asset LIMIT 1];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new NetSuiteToSalesforce_Mock ());
        SalesOrderStatusController.getSalesOrderStatus(asset.Id);
		Test.stopTest();        
        System.assertEquals('Open',[SELECT Id,SalesOrderStatus__c FROM Asset LIMIT 1].SalesOrderStatus__c);
    }
}