force-app/main/default/objects/Asset/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Lead source from Opp</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/EdxTraining.recordType-meta.xml
<RecordType>
    <fullName>EdxTraining</fullName>
    <active>true</active>
    <label>EdxTraining</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Bundle_Product__c/Bundle_Product__c.object-meta.xml
<CustomObject>
    <label>Bundle Product</label>
    <nameField>
        <label>Bundle Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundle Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bundle_Product__c/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Type__c</field>
            <operation>equals</operation>
            <value>Bundle</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Products (Bundle)</relationshipLabel>
    <relationshipName>Bundle_Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bundle_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.TI_Id__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Products</relationshipLabel>
    <relationshipName>Bundle_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/LF_Training__c.field-meta.xml
<CustomField>
    <fullName>LF_Training__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LF Training</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Training_Technology_List__c.field-meta.xml
<CustomField>
    <fullName>Training_Technology_List__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Training Technology List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <inlineHelpText>Date of last enrollment as related to campaign</inlineHelpText>
    <label>Enrollment Date</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/LF_Training__c.field-meta.xml
<CustomField>
    <fullName>LF_Training__c</fullName>
    <formula>Campaign.LF_Training__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LF Training</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <inlineHelpText>Completion for Elearning, ILT</inlineHelpText>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <label>Enrollment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Ext_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Ext_Product_Id__c</fullName>
    <externalId>true</externalId>
    <label>Ext Product Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Is_free__c.field-meta.xml
<CustomField>
    <fullName>Is_free__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is free</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/isBootcampbundle__c.field-meta.xml
<CustomField>
    <fullName>isBootcampbundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isBootcampbundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Enrollments (Collection)</relationshipLabel>
    <relationshipName>Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Purchase_History__c.field-meta.xml
<CustomField>
    <fullName>Purchase_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase History</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edx</fullName>
            </value>
            <value>
                <fullName>Panorama</fullName>
            </value>
            <value>
                <fullName>SugarCRM</fullName>
            </value>
            <value>
                <fullName>TI</fullName>
            </value>
            <value>
                <fullName>TI SCORM</fullName>
            </value>
            <value>
                <fullName>TI Panorama</fullName>
            </value>
            <value>
                <fullName>TI Other</fullName>
            </value>
            <value>
                <fullName>TI Purchase</fullName>
            </value>
            <value>
                <fullName>QuickStart</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Enrolled - Update status for , Course_purchase and when enrollment date is added
Started - Update status for Course_start and when start date is added
Completed -Update status for Course_complete and completed date is added
Expired - If complete date is null and Expired date is in past
Revoked - update for revoke_access
Not started - multiple enrollments when there is an record already with above statuses enrolled, started</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Not started</fullName>
            </value>
            <value>
                <fullName>Not Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/TI_Id__c.field-meta.xml
<CustomField>
    <fullName>TI_Id__c</fullName>
    <externalId>true</externalId>
    <label>TI Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Course</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>E-Learning</fullName>
            </value>
            <value>
                <fullName>Instructor-Led</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Date Confirmed</fullName>
            </value>
            <value>
                <fullName>Materials Sent</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/TI_Id__c.field-meta.xml
<CustomField>
    <fullName>TI_Id__c</fullName>
    <externalId>true</externalId>
    <label>TI Id</label>
    <length>150</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Training__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AI, ML, Data &amp; Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud, Containers &amp; Virtualization</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps, CI/CD &amp; Site Reliability</fullName>
    </customValue>
    <customValue>
        <fullName>IoT &amp; Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>Linux Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Networking &amp; Edge</fullName>
    </customValue>
    <customValue>
        <fullName>Open Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source &amp; Compliance Best Practices</fullName>
    </customValue>
    <customValue>
        <fullName>Privacy &amp; Security</fullName>
    </customValue>
    <customValue>
        <fullName>Quantum Computing</fullName>
    </customValue>
    <customValue>
        <fullName>Safety-Critical Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>System Administration</fullName>
    </customValue>
    <customValue>
        <fullName>System Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Visual Effects</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Application Development</fullName>
    </customValue>
    <customValue>
        <fullName>Cybersecurity</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
        <isActive>false</isActive>
        <label>Security</label>
    </customValue>
    <customValue>
        <fullName>Node.js Development</fullName>
        <isActive>false</isActive>
        <label>Node.js Development</label>
    </customValue>
    <customValue>
        <fullName>Open Source Best Practices</fullName>
        <isActive>false</isActive>
        <label>Open Source Best Practices</label>
    </customValue>
    <customValue>
        <fullName>Application Development</fullName>
        <isActive>false</isActive>
        <label>Application Development</label>
    </customValue>
    <description>Technology categories used by training, events, and projects across the LF.  Note that forms in Cvent need to be updated for any label change needed in this value set.</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EnrollmentTriggerHandlerTest.cls
@isTest
public class EnrollmentTriggerHandlerTest {
    @TestSetup
    public static void makeData(){
        Account account = new Account (Name = 'Acme, Inc.');
        insert account;
        Contact contact = new Contact(
            FirstName = 'Robin',
            LastName = 'Koehler',
            AccountId = account.Id
        );
        insert contact;
    }
    @isTest
    public static void createPurchaseHistoryForPaidEnrollment_Test(){
        
        Map<id,Enrollment__c> oldmap = new Map<id,Enrollment__c>();
        Map<id,Enrollment__c> newmap = new Map<id,Enrollment__c>();
        Map<id,Decimal> productVsPrice = new Map<id,Decimal>();
        Set<Id> enrollmentIds = new Set<Id>();
        Product2 product = new Product2(Name = 'Laptop X400', Family = 'Training', ProductCode = 'LX400', IsActive = true);
        insert product;
        
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        Update standardPricebook;
        standardPricebook = [SELECT Id, IsStandard FROM Pricebook2 WHERE Id = :standardPricebook.Id];
        
        PricebookEntry pbe2 = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = product.Id,
            UnitPrice = 1020,
            IsActive = true
        ); 
        Insert pbe2; 
        productVsPrice.put(pbe2.Product2Id ,pbe2.UnitPrice);
        
        Account account = new Account();
        account.Name = 'Test Account';
        insert account;
        
        Contact contact = new Contact();
        contact.AccountId = account.Id;
        contact.LastName = 'Test Contact';
        contact.Email = 'testcontact@noreply.com';
        insert contact;
        
        Training__c edxtraining = new Training__c();
        edxtraining.Name = 'Edx Training';
        insert edxtraining;
        
        Training__c instructortraining = new Training__c();
        instructortraining.Name = 'Instructor Led';
        insert instructortraining;
        
        Training__c certificationtraining = new Training__c();
        certificationtraining.Name = 'Certification';
        insert certificationtraining;
        
        Training__c eLearningtraining = new Training__c();
        eLearningtraining.Name = 'E-Learning';
        insert eLearningtraining;
        
        List<Asset> assetList =  new List<Asset>();
        Asset asset =  TestFactory.getAsset();
        asset.Name = 'TEST';
        Id indRecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Asset ast = new Asset();
        ast.Name='Test Asset';
        ast.price= 75;
        ast.Product2Id = product.Id;
        ast.RecordTypeId = indRecordTypeId;
        
        Id edxRecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('EdxTraining').getRecordTypeId();
        Asset ast1 = new Asset();
        ast1.Name='Test Data Asset';
        ast1.RecordTypeId =edxRecordTypeId;
        ast1.price= 75;
        ast1.Product2Id = product.Id;
        assetList.add(ast);
        assetList.add(ast1);
        insert assetList;
        
        test.startTest();
        Lead lead =  TestFactory.getLead();
        
        Enrollment__c enrollment = new Enrollment__c();
        enrollment.Name = 'Test enrollment';
        enrollment.Contact_Name__c = contact.Id;
        enrollment.Lead_Name__c =null;
        enrollment.Product_Name__c =null; 
        enrollment.Ext_Product_Id__c ='Training+LX400+2021';
        enrollment.Purchase_history__c =asset.id;
        enrollment.Source__c ='Edx';
        insert enrollment;
        
		enrollment.Id = null;
        enrollment.Name = null;
        enrollment.Contact_Name__c = null;
		enrollment.Lead_Name__c = lead.id;
		insert enrollment;
        
        Enrollment__c enrollment1 = new Enrollment__c();
        enrollment1.Name = 'Test enrollment';
        enrollment1.Contact_Name__c = contact.Id;
        enrollment1.Lead_Name__c =lead.id;
        enrollment1.Product_Name__c = product.Id;
        enrollment1.Purchase_history__c =asset.id;
        enrollment.Is_free__c = false;
        enrollment1.Source__c ='SugarCRM';
        enrollment.Amount__c  = 100;
        insert enrollment1;
        
        
        oldmap.put(enrollment.id, enrollment);
        enrollmentIds.add(enrollment.id);
        enrollment.Name = 'Test enrollment1';
        update enrollment;
        newmap.put(enrollment.id, enrollment);
        
        oldmap.put(enrollment1.id, enrollment1);
        enrollmentIds.add(enrollment1.id);
        enrollment1.Name = 'Test enrollment1';
        update enrollment1;
        test.stopTest();
        newmap.put(enrollment1.id, enrollment1);
        
        List<Enrollment__c> lst =[Select id,Name,Product_Name__c,Ext_Product_Id__c,Lead_Name__c,Contact_Name__c from Enrollment__c where Name='Test enrollment' OR Name='Test enrollment1'];
        EnrollmentTriggerHandler obj = new EnrollmentTriggerHandler();
        EnrollmentTriggerHandler.BeforeInsert(lst);
        EnrollmentTriggerHandler.AfterUpdate(newmap, oldmap);
        EnrollmentTriggerHandler.afterInsert(newMap);
        
        EnrollmentTriggerHandler.createPurchaseHistory(enrollmentIds, productVsPrice);
        
        List<Enrollment__c> enrList = [Select ID from Enrollment__c where Purchase_History__c=: asset.ID];
        System.debug('enrList ===>'+enrList.size());
        System.assertEquals(1,enrList.size());
    }
    
    @isTest
    public static void upsertCampaignMember(){
        Contact contact =[SELECT ID FROM Contact LIMIT 1];
        Lead lead = new Lead();
        lead.LastName = 'Test Lead';
        lead.Email = 'testEmail@test.com';
        insert lead;
        
        Product2 parentProduct = new Product2(Name = 'Cloud Engineer Boot Camp', productcode = 'parent', 
                                              isActive = true,Type__c='Bundle');
        insert parentProduct;
        
        Product2 product = new Product2(Name = 'TestP', productcode = 'campaign', isActive = true,TI_Id__c='TestTiid');
        insert product;
        
        Bundle_Product__c bundleProduct = new Bundle_Product__c(Bundle__c=parentProduct.Id,Product__c=product.Id);
        insert bundleProduct;
        
        Campaign parentCampaign = new Campaign(
            Name = 'LF Training Bootcamp June 2020',
            IsActive = TRUE,
            startDate=System.today()-1,
            endDate=System.today()+30,
            Product__c='Cloud Engineer Boot Camp'
        );            
        insert parentCampaign;
        System.debug('parentCampaign '+parentCampaign);
        
        Campaign campaign = new Campaign(
            Name = 'Test campaign',
            IsActive = TRUE,
            ParentId = parentCampaign.id,
            Type = 'Training'
        );            
        insert campaign;
        
        List<Campaign> campaigns = [SELECT Id,Name FROM Campaign WHERE Parent.Name='LF Training Bootcamp June 2020' ];
        System.debug('campaigns'+campaigns);
        CampaignMember member = new CampaignMember(
            ContactId = contact.Id,LeadId = lead.Id,
            Status = 'testsent',
            CampaignId = campaign.Id
        ); 
        insert member;
        
        Enrollment__c enrollment = new Enrollment__c();
        enrollment.Name = 'Test enrollment';
        enrollment.Contact_Name__c = contact.Id;
        enrollment.Product_Name__c = product.Id;
        enrollment.Parent_Product__c=parentProduct.Id;
        enrollment.Is_free__c = true;
        enrollment.Source__c ='SugarCRM';
        enrollment.Completion_Date__c = System.today()-1;
        enrollment.isBootcampbundle__c = true;
        enrollment.Enrollment_Date__c = System.today();
        insert enrollment;
        
        
        /*CampaignMemberStatus newStatus = new CampaignMemberStatus(
            CampaignID=campaign.id,
            Label='Sent',
            IsDefault=false,
            HasResponded=false,
            SortOrder=3
        );
        
        insert newStatus;*/
        
        System.assertEquals('Sent', [SELECT id,Status FROM CampaignMember WHERE CampaignId =: campaign.Id][0].Status);
    }
    
    @isTest
    public static void updateStatusofNotStartedEnrollment(){
        Contact contact =[SELECT ID FROM Contact LIMIT 1];
        Product2 product = new Product2(Name = 'TestP', productcode = 'campaign', isActive = true);
        insert product;
        
        Enrollment__c enrollment = new Enrollment__c();
        enrollment.Contact_Name__c = contact.Id;
        enrollment.Product_Name__c = product.Id;
        enrollment.Is_free__c = true;
        enrollment.Source__c ='SugarCRM';
        enrollment.Enrollment_Date__c = System.today()-1;
        insert enrollment;
        
        Enrollment__c enrollment2 = new Enrollment__c();
        enrollment2.Contact_Name__c = contact.Id;
        enrollment2.Product_Name__c = product.Id;
        enrollment2.Is_free__c = true;
        enrollment2.Source__c ='SugarCRM';
        enrollment2.Enrollment_Date__c = System.today()-1;
        enrollment2.Status__c = 'Not Started';
        insert enrollment2;
        
        enrollment.Status__c = 'Completed';
        update enrollment;
        
    }
    
    @isTest
    public static void updateEnrollmentName_test(){
        
      
        Contact contact =[SELECT ID FROM Contact LIMIT 1];
        Product2 product = new Product2(Name = 'TestProduct', productcode = 'campaign', isActive = true);
        insert product;
        
        Enrollment__c enrollment = new Enrollment__c();
        enrollment.Contact_Name__c = contact.Id;
        enrollment.Product_Name__c = product.Id;
        enrollment.Is_free__c = true;
        enrollment.Source__c ='SugarCRM';
        insert enrollment;
        
        System.assertEquals('Robin Koehler TestProduct', [SElECT Id,Name from Enrollment__c WHERE Contact_Name__c =: contact.Id].Name);
    }
    @isTest
    public static void addToTechnologyCampaignTest(){
        Lead lead = new Lead();
        lead.LastName = 'Test Lead';
        lead.Email = 'testEmail@test.com';
        insert lead;
        
       Contact contact =[SELECT ID FROM Contact LIMIT 1];
        Product2 product = new Product2(Name = 'TestP', productcode = 'campaign', isActive = true,Technology__c='Blockchain');
        insert product;
        
        Campaign campaign = new Campaign(
            Name = 'Test campaign',
            IsActive = TRUE,
            Training_Technology_List__c=true,
            LF_Training__c=true,
            Type = 'Training',
            Technology__c='Blockchain'
        );            
        insert campaign;
        List<Enrollment__c> enrollmentList = new List<Enrollment__c>();
        Enrollment__c enrollment = new Enrollment__c();
        enrollment.Name = 'Test enrollment';
        enrollment.Contact_Name__c = contact.Id;
        enrollment.Product_Name__c = product.Id;
        enrollment.Source__c ='SugarCRM';
        enrollment.Completion_Date__c = System.today()-1;
        enrollmentList.add(enrollment);

        Enrollment__c enrollment1 = new Enrollment__c();
        enrollment1.Name = 'Test enrollment1';
        enrollment1.Lead_Name__c = lead.Id;
        enrollment1.Product_Name__c = product.Id;
        enrollment1.Source__c ='SugarCRM';
        enrollment1.Completion_Date__c = System.today()-1;
        enrollmentList.add(enrollment1);

        Test.startTest();
        insert enrollmentList;
              Test.stopTest();
        System.assertNotEquals(null,[SELECT Id from CampaignMember where campaignid=:campaign.Id].size());
    }
    
}