force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Project_Role__c.field-meta.xml
<CustomField>
    <fullName>Project_Role__c</fullName>
    <label>Project Role</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Member_Readout_Campaign__mdt/Member_Readout_Campaign__mdt.object-meta.xml
<CustomObject>
    <label>Member Readout Campaign</label>
    <pluralLabel>Member Readout Campaigns</pluralLabel>
</CustomObject>

force-app/main/default/objects/Member_Readout_Campaign__mdt/fields/Campaign_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Id__c</fullName>
    <label>Campaign Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member_Readout_Campaign__mdt/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <label>Project Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member_Readout_Campaign__mdt/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/Project_Role__c.object-meta.xml
<CustomObject>
    <label>Membership Roles</label>
    <nameField>
        <displayFormat>PR{000}</displayFormat>
        <label>Role AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Role__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Membership Roles</relationshipLabel>
    <relationshipName>Project_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Project_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_Out__c</fullName>
    <formula>Contact__r.HasOptedOutOfEmail</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Opt-Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Voting Contact means this is the person at the company that has the right to vote in the project’s membership elections for their member class.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Representative/Voting Contact</fullName>
                <label>Voting Contact</label>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Legal Contact</fullName>
            </value>
            <value>
                <fullName>Event Sponsorship</fullName>
            </value>
            <value>
                <fullName>PO Contact</fullName>
            </value>
            <value>
                <fullName>Press Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MemberReadoutBatch.cls
public class MemberReadoutBatch implements Database.Batchable<Sobject>,Schedulable {
    
    public Set<String> setOfStatus = new set<String>();
    public Set<String> setOfRoles = new set<String>();
    
    //Schedule 's Execute method to call batch
    public void execute(SchedulableContext sc){
        Database.executeBatch(new MemberReadoutBatch(),1);
    }

    public MemberReadoutBatch(){
        setOfStatus = new Set<String>(Label.Readout_PurchaseHistoryStatus.split(';'));
       
    }
    
    public  Database.QueryLocator start(Database.BatchableContext BC){

        //Query Metadata which stored the projects and campaignid
        return Database.getQueryLocator([Select Id, Roles__c,Project_Id__c, Campaign_Id__c From Member_Readout_Campaign__mdt]);
    }
    
    public void execute(Database.BatchableContext BC, List<Member_Readout_Campaign__mdt> scope ){
        system.debug('scope '+scope.size());
       ID projectId = scope[0].Project_Id__c;
       Id campaignId = scope[0].Campaign_Id__c;
       setOfRoles = new Set<String>(scope[0].Roles__c.split(';'));

       //Retrieve the projectroles of the projectid
        String query = 'SELECT Contact__c,count(ID) FROM Project_Role__c WHERE '+
        'Asset__r.Projects__c = :projectId'+
        ' AND Asset__r.Status IN :setOfStatus AND Role__c IN :setOfRoles AND '+
        'Email_Opt_Out__c = false AND Status__c != \'Inactive\' Group by Contact__c';
        system.debug('query '+query);

        Set<Id> setOfContactId = new Set<Id>();
        List<CampaignMember> listOfCampMemberToInsert = new List<CampaignMember>();
        List<AggregateResult> projectRolesList = database.query(query);

        system.debug(projectRolesList.size());
        for (AggregateResult aggrResult : projectRolesList){
            CampaignMember campaignMember = new CampaignMember();
            campaignMember.ContactId = (Id)aggrResult.get('Contact__c');
            campaignMember.CampaignId = campaignId;
            setOfContactId.add((Id)aggrResult.get('Contact__c'));
            listOfCampMemberToInsert.add(campaignMember);
        }

        //Insert
        if (!listOfCampMemberToInsert.isEmpty()){
            List<Database.SaveResult> saveResults = Database.insert(listOfCampMemberToInsert, false);
            System.debug('#--saveResults--#' + saveResults);
        }
        
        //Retrieve members which do not have active membership roles so delete them
        List<CampaignMember> listOfMemberToDelete = [SELECT Id
                                                     FROM CampaignMember
                                                     WHERE CampaignId = :campaignId AND 
                                                     ContactId NOT IN :setOfContactId AND ContactId != null];

         //Delete
        if (!listOfMemberToDelete.isEmpty()){
            System.debug('#--delete--#' + listOfMemberToDelete);
            delete listOfMemberToDelete;
        }
      
    }
    
    public void finish(Database.BatchableContext info){ 
    }
    
}