force-app/main/default/objects/AccountProjectBenchmark__c/AccountProjectBenchmark__c.object-meta.xml
<CustomObject>
    <description>The Benchmark scores for an Account/Project Combination</description>
    <label>Account Project Benchmark</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Project Benchmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountProjectBenchmark__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Project Related to the Benchmark Score</description>
    <inlineHelpText>Project Related to the Benchmark Score</inlineHelpText>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Project Stage Must be Formation - Engaged, Formation - Confidential or Active</errorMessage>
        <filterItems>
            <field>Project__c.Project_Status__c</field>
            <operation>equals</operation>
            <value>Formation - Engaged, Formation - Confidential, Active</value>
        </filterItems>
        <infoMessage>Project Stage Must be Formation - Engaged, Formation - Confidential or Active</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Account Project Benchmarks</relationshipLabel>
    <relationshipName>AccountProjectBenchmarksProject</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountProjectBenchmarkItem__c/AccountProjectBenchmarkItem__c.object-meta.xml
<CustomObject>
    <description>Benchmark Items that make up a Benchmark Score</description>
    <label>Account Project Benchmark Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Project Benchmark Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountProjectBenchmarkItem__c/fields/AccountProjectBenchmark__c.field-meta.xml
<CustomField>
    <fullName>AccountProjectBenchmark__c</fullName>
    <description>Account Project Benchmark Associated with the Benchmark Item</description>
    <inlineHelpText>Account Project Benchmark Associated with the Benchmark Item</inlineHelpText>
    <label>Account Project Benchmark</label>
    <referenceTo>AccountProjectBenchmark__c</referenceTo>
    <relationshipLabel>Account Project Benchmark Items</relationshipLabel>
    <relationshipName>AccountProjectBenchmarkItemsAccountProje</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectBenchmarkInput__c/ProjectBenchmarkInput__c.object-meta.xml
<CustomObject>
    <description>Defines multiplier for input into a Projects Scorecard</description>
    <label>Project Benchmark Input</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Benchmark Inputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/BenchmarkInputType__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkInputType__c</fullName>
    <description>The Type of Input used for the Benchmark</description>
    <inlineHelpText>The Type of Input used for the Benchmark</inlineHelpText>
    <label>Benchmark Input Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BenchmarkInputType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Project Benchmark Input Types Related To</description>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Project__c.Project_Status__c</field>
            <operation>equals</operation>
            <value>Formation - Engaged, Formation - Confidential, Active</value>
        </filterItems>
        <infoMessage>Project Stage must be Formation - Engaged, Formation - Confidential or Active</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Benchmark Inputs</relationshipLabel>
    <relationshipName>ProjectBenchmarkInputsProject</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/BenchmarkInputType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PersonOrgCertCnt</fullName>
        <label>Associated Person Certifications</label>
    </customValue>
    <customValue>
        <fullName>BoardMeetingAttendCnt</fullName>
        <label>Board Meetings Attended</label>
    </customValue>
    <customValue>
        <fullName>CodeCommitCnt</fullName>
        <label>Code Commits</label>
    </customValue>
    <customValue>
        <fullName>EvntAttendCnt</fullName>
        <label>Event Attendence</label>
    </customValue>
    <customValue>
        <fullName>ForumContribCnt</fullName>
        <label>Forum Contributions</label>
    </customValue>
    <customValue>
        <fullName>QBRAttendCnt</fullName>
        <label>QBR Attendence</label>
    </customValue>
    <customValue>
        <fullName>TrainingCmpltCnt</fullName>
        <label>Training Completed</label>
    </customValue>
    <masterLabel>Benchmark Input Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountProjBenchmarkItmTrigger_Test.cls
/**
AccountProjectBenchmarkItem trigger handler Test Coverage
@author (c) Idea Science  2023
*
* History
* *******
* Date       By             Ticket      Change
* *********  *************  **********  **************************************
* 21FEB2023  Craig Jackson  LF240-271   Initial Version
*/
@isTest
public class AccountProjBenchmarkItmTrigger_Test {

    //
    // Test Happy Path for Insert
    // Expect Name to be changed and Benchmark Input Records to be created
    //
    @isTest
    static void insertHappyPath() {
        String projectName  = 'PBI Project Test';
        String accountName  = 'PBI Account Test';
        Project__c prj      = TestDataFactory.getProject(projectName, true);
        Account    acnt     = TestDataFactory.getCompanyAccount(accountName, true);
        AccountProjectBenchmark__c apb         = TestDataFactory.getAccountProjectBenchmark(prj, acnt, true);
        Schema.DescribeFieldResult fieldResult = ProjectBenchmarkInput__c.BenchmarkInputType__c.getDescribe();
        List<Schema.PicklistEntry> ple         = fieldResult.getPicklistValues();
        String itemType     = ple[0].getValue();
        String expectedName = projectName + ' - ' + accountName + ' - ' + itemType;

        // Setup AccountProjectBenchmarkItem__c
        AccountProjectBenchmarkItem__c apbi = TestDataFactory.getAccountProjectBenchmarkItem(apb, itemType, false);

        // Insert AccountProjectBenchmarkItem__c
        Test.startTest();
        insert apbi;
        Test.stopTest();

        // Assert Record created and Name changed
        List<AccountProjectBenchmarkItem__c> actualLst = [SELECT Id, Name FROM AccountProjectBenchmarkItem__c];
        Assert.isTrue(actualLst.size() == 1, 'Expected 1 AccountProjectBenchmarkItem__c record to be found');
        Assert.areEqual(expectedName, actualLst[0].name, 'Expected Name to be ' + expectedName + ', actual ' + actualLst[0].name);
    }

    //
    // Test Happy Path for Update
    // Expect Name to be changed and no extra Benchmark Input Records to be created
    //
    @isTest
    static void updateHappyPath() {
        String projectName  = 'PBI Project Test';
        String accountName  = 'PBI Account Test';
        Project__c prj      = TestDataFactory.getProject(projectName, true);
        Account    acnt     = TestDataFactory.getCompanyAccount(accountName, true);
        AccountProjectBenchmark__c apb         = TestDataFactory.getAccountProjectBenchmark(prj, acnt, true);
        Schema.DescribeFieldResult fieldResult = ProjectBenchmarkInput__c.BenchmarkInputType__c.getDescribe();
        List<Schema.PicklistEntry> ple         = fieldResult.getPicklistValues();
        String itemType     = ple[0].getValue();
        String expectedName = projectName + ' - ' + accountName + ' - ' + itemType;

        // Setup AccountProjectBenchmarkItem__c
        AccountProjectBenchmarkItem__c apbi = TestDataFactory.getAccountProjectBenchmarkItem(apb, itemType, true);

        // Assert Record created and Name changed
        List<AccountProjectBenchmarkItem__c> actualLst = [SELECT Id, Name FROM AccountProjectBenchmarkItem__c];
        Assert.isTrue(actualLst.size() == 1, 'Expected 1 AccountProjectBenchmarkItem__c record to be found');
        Assert.areEqual(expectedName, actualLst[0].name);

        // Update Name
        apbi.Name = 'Changed';

        // Update AccountProjectBenchmarkItem__c
        Test.startTest();
        update apbi;
        Test.stopTest();

        // Assert Record Name updated
        List<AccountProjectBenchmarkItem__c> actualLst2 = [SELECT Id, Name FROM AccountProjectBenchmarkItem__c];
        Assert.isTrue(actualLst2.size() == 1, 'Expected 1 AccountProjectBenchmarkItem__c record to be found');
        Assert.areEqual(expectedName, actualLst2[0].name);
    }

    //
    // Test Happy Path for Delete
    // No extra coding exists for delete and undelete so just for code coverage
    //
    @isTest
    static void deleteHappyPath() {
        String projectName  = 'PBI Project Test';
        String accountName  = 'PBI Account Test';
        Project__c prj      = TestDataFactory.getProject(projectName, true);
        Account    acnt     = TestDataFactory.getCompanyAccount(accountName, true);
        AccountProjectBenchmark__c apb         = TestDataFactory.getAccountProjectBenchmark(prj, acnt, true);
        Schema.DescribeFieldResult fieldResult = ProjectBenchmarkInput__c.BenchmarkInputType__c.getDescribe();
        List<Schema.PicklistEntry> ple         = fieldResult.getPicklistValues();
        String itemType     = ple[0].getValue();

        // Setup AccountProjectBenchmarkItem__c
        AccountProjectBenchmarkItem__c apbi = TestDataFactory.getAccountProjectBenchmarkItem(apb, itemType, true);

        // Assert Record created and Name changed
        List<AccountProjectBenchmarkItem__c> actualLst = [SELECT Id, Name FROM AccountProjectBenchmarkItem__c];
        Assert.isTrue(actualLst.size() == 1, 'Expected 1 AccountProjectBenchmarkItem__c record to be found');

        // Delete AccountProjectBenchmarkItem__c
        Test.startTest();
        delete apbi;

        // Assert Record Deleted
        List<AccountProjectBenchmarkItem__c> actualLst2 = [SELECT Id, Name FROM AccountProjectBenchmarkItem__c];
        Assert.isTrue(actualLst2.size()==0, 'Expected 0 AccountProjectBenchmarkItem__c record to be found');

        // Undelete AccountProjectBenchmarkItem__c
        undelete apbi;
        Test.stopTest();

        // Assert Record Undeleted
        List<AccountProjectBenchmarkItem__c> actualLst3 = [SELECT Id, Name FROM AccountProjectBenchmarkItem__c];
        Assert.isTrue(actualLst3.size() == 1, 'Expected 1 AccountProjectBenchmarkItem__c record to be found');
    }

    //
    // Should not be able to create multiple records with the same Project/Membership combination
    // Expect Exception to be thrown
    //
    @isTest
    static void insertDuplicateCheck() {
        String projectName  = 'PBI Project Test';
        String accountName  = 'PBI Account Test';
        Project__c prj      = TestDataFactory.getProject(projectName, true);
        Account    acnt     = TestDataFactory.getCompanyAccount(accountName, true);
        AccountProjectBenchmark__c apb         = TestDataFactory.getAccountProjectBenchmark(prj, acnt, true);
        Schema.DescribeFieldResult fieldResult = ProjectBenchmarkInput__c.BenchmarkInputType__c.getDescribe();
        List<Schema.PicklistEntry> ple         = fieldResult.getPicklistValues();
        String itemType     = ple[0].getValue();

        // Setup AccountProjectBenchmarkItem__c
        AccountProjectBenchmarkItem__c apbi     = TestDataFactory.getAccountProjectBenchmarkItem(apb, itemType, true);
        AccountProjectBenchmarkItem__c apbiDupe = TestDataFactory.getAccountProjectBenchmarkItem(apb, itemType, false);

        // Attempt to insert duplicate AccountProjectBenchmarkItem__c
        Test.startTest();
        try {
            insert apbiDupe;
            Assert.fail('Expected Duplicate Reocrd to thrown an Exception');
        } catch (Exception ex) {
            Assert.areEqual(ex.getTypeName(), 'System.DmlException', 'Expected DmlException to be thrown');
        }
        Test.stopTest();
    }
}