force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Created for DocuSign to show Account Address in Single Line.</description>
    <formula>IF(NOT(ISBLANK(BillingStreet)),BillingStreet +&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingCity)),BillingCity+&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingPostalCode)),BillingPostalCode+&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingCountry)),BillingCountry,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/No_Of_Employess__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Employess__c</fullName>
    <label>JoinNow No Of Employees</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Alternate Bill to Name and Address</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alternate Bill to Name and Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>if(LEN(Street__c )&gt;0, Street__c &amp; &quot; &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN(City__c )&gt;0, City__c &amp; &quot;, &quot; , &quot;&quot; )&amp;
if(LEN(State__c )&gt;0, State__c &amp; &quot; &quot; , &quot;&quot; )&amp;
if(LEN(Zip_Postal_Code__c )&gt;0, Zip_Postal_Code__c,&quot;&quot;) &amp; BR() &amp;
If(LEN(Country__c) &gt;0,Country__c ,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alternate_Email__c/Alternate_Email__c.object-meta.xml
<CustomObject>
    <label>Alternate Email</label>
    <nameField>
        <displayFormat>AE-{000}</displayFormat>
        <label>Alternate Email ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternate Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alternate_Email__c/fields/Alternate_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email_Address__c</fullName>
    <externalId>true</externalId>
    <label>Alternate Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <description>Individual Member Account</description>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/TestAccountTrigger.cls
@isTest
public class TestAccountTrigger{

    static testmethod void testTrigger(){
        
        Account acc = new Account(Name = 'Test account' , billingStreet = 'street');
        insert acc;
                
        User u = insertStandardUser(UserInfo.getProfileId());
            
        acc.OwnerId=u.Id;
        update acc;
        Contact contact = new Contact(LastName='Test',Email='personaccount@noreply.com',AccountId= acc.Id);
        insert contact;
        System.assertEquals(1,[Select count() FROM Alternate_Email__c WHERE Alternate_Email_Address__c ='personaccount@noreply.com']);
        delete acc;
        System.assertEquals(0,[Select count() FROM Alternate_Email__c WHERE Alternate_Email_Address__c ='personaccount@noreply.com']);
    }
    
    static String getUserNamePrefix(){

        return UserInfo.getOrganizationId() + System.now().millisecond();

    }
    
    static User insertStandardUser(Id standardProfileId){

        // assert standardProfileId valid

        User standardUser = new User(
            Username = getUserNamePrefix() + 'standarduser@testorg.com',
            Alias = 'standt',
            email = 'standarduser@testorg.com',
            emailencodingkey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = standardProfileId,
            TimeZoneSidKey = 'America/Los_Angeles'
        );

        insert standardUser;

        return standardUser;
    }
  
    @isTest
    public static void updateAddressObjForAccount_Test(){
        Account objAcc = new Account();
        objAcc.Name='Test Account';
        objAcc.BillingStreet ='Test street';
        objAcc.BillingCity ='Test city';
        objAcc.BillingState='Test state';
                objAcc.BillingPostalCode ='147852';
                objAcc.BillingCountry='Test';
        insert objAcc;

        Address__c objAddress = new Address__c();
        objAddress.Account__c =objAcc.id;
        objAddress.Street__c =objAcc.billingstreet;
                objAddress.City__c=objAcc.billingcity;
                objAddress.State__c=objAcc.billingstate;
                objAddress.Country__c=objAcc.billingcountry;
                objAddress.Zip_Postal_Code__c=objAcc.billingpostalcode;
        insert objAddress;
        System.debug(objAddress.Address__c);
        Test.startTest();
        objAcc.BillingStreet = 'VIP Store';
        update objAcc;
        Test.stopTest();
        System.assertEquals('VIP Store',[SELECT Id,Street__c from Address__c Where Id=:objAddress.id].street__c);
    }
    
    @isTest
    static void testUpdateSector(){
        Account acc = new Account(Name = 'Test account' , billingStreet = 'street');
        insert acc;
        Contact con = new Contact(LastName = 'testCon', email = 'test333@testing123.com1',AccountId=acc.id);
        insert con;
        acc.No_Of_Employess__c ='100';
         acc.Industry = 'Professional Services';
        acc.Sector__c='Industrials';
        update acc;
        System.assertEquals('Professional Services',[SELECT Id,Sector__c from Account Where Id=:acc.id].Sector__c);
  
    }
}