force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Created for DocuSign to show Account Address in Single Line.</description>
    <formula>IF(NOT(ISBLANK(BillingStreet)),BillingStreet +&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingCity)),BillingCity+&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingPostalCode)),BillingPostalCode+&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingCountry)),BillingCountry,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Alternate Bill to Name and Address</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alternate Bill to Name and Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>if(LEN(Street__c )&gt;0, Street__c &amp; &quot; &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN(City__c )&gt;0, City__c &amp; &quot;, &quot; , &quot;&quot; )&amp;
if(LEN(State__c )&gt;0, State__c &amp; &quot; &quot; , &quot;&quot; )&amp;
if(LEN(Zip_Postal_Code__c )&gt;0, Zip_Postal_Code__c,&quot;&quot;) &amp; BR() &amp;
If(LEN(Country__c) &gt;0,Country__c ,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>To describe purpose of this address, i.e. Japan Office or to be used for HPL invoices, etc.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Billing Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>false</active>
    <businessProcess>Training</businessProcess>
    <description>Record type for training opportunities</description>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Product (Billing Contact)</relationshipLabel>
    <relationshipName>Opportunity_Product5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Text that will be displayed on invoice</description>
    <inlineHelpText>Text that will be displayed on invoice</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Standard Memberships will auto-populate date.</description>
    <inlineHelpText>Standard Memberships will auto-populate date.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Representative_Voting_Contact__c.field-meta.xml
<CustomField>
    <fullName>Representative_Voting_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Required</inlineHelpText>
    <label>Representative/Voting Contact*</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Skip_NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>Skip_NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, the Purchase History that is created from this line item will not be sent to NetSuite. You probably don&apos;t want this.</description>
    <inlineHelpText>When selected, the Purchase History that is created from this line item will not be sent to NetSuite. You probably don&apos;t want this.</inlineHelpText>
    <label>Skip NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Required</inlineHelpText>
    <label>Start Date*</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/Netsuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>NS Item ID</inlineHelpText>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
            <value>
                <fullName>Straight Line</fullName>
                <isActive>false</isActive>
                <label>Straight Line</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <formula>IF(Project__c != null ,Project__r.Subsidiary_ID__c , Event__r.BillFromProject__r.Subsidiary_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/SubsidiaryID__c.field-meta.xml
<CustomField>
    <fullName>SubsidiaryID__c</fullName>
    <label>SubsidiaryID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Product_Details__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A one-sentence description of the project, which will be used for external facing (i.e. landscape graphic or a website list of LF projects) descriptions of projects.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Deferred_Revenue_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>284</fullName>
        <label>Deferred Revenue : Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>282</fullName>
        <label>Deferred Revenue : Deferred Revenue - Membership</label>
    </customValue>
    <customValue>
        <fullName>4494</fullName>
        <label>Deferred Revenue : Deferred Revenue - Directed Funds</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Other</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Membership</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Membership</label>
    </customValue>
    <masterLabel>NetSuite Deferred Revenue Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NetSuite_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Events</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Training</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Training (Linux Labs)</label>
    </customValue>
    <masterLabel>NetSuite Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/addressTriggerHandlerTest.cls
/*
* Test Class For-AddressTriggerHandler 
*/
@isTest
public class addressTriggerHandlerTest {
    
    @TestSetup
    static void createTestData(){
        // get Account
        Account acc = testFactory.getAccount();
        // get Corporate Training Record Type Id
        Id corporateTrainingRecordId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Corporate Training').getRecordTypeId();
        
        // create Alternate Bill to Name and Address
        Address__c objAddress = new Address__c();
        objAddress.Account__c = acc.id;
        objAddress.Name ='Test Address';
        objAddress.City__c = 'Test City';
        objAddress.Country__c = 'Test Country';
        objAddress.State__c = 'Test State';
        objAddress.Street__c = 'Test Street';
        objAddress.Zip_Postal_Code__c = 'CODE';
        insert objAddress;
        
        // get Contact
        Contact con = testFactory.getContact();
        // get OpportunityLineItem
        OpportunityLineItem oli = TestFactory.getOpportunityLineItem();
        
        Product2 prod =[Select ID From Product2 Where Name='TestP' Limit 1];
        // get Project
        Project__c prj = testFactory.getProject();
        prj.NS_Department__c= '	10';
        prj.NS_Income_GL_Account__c= '297';
        prj.NS_Deferred_Revenue_Account__c= '282';
        prj.Project_Code__c='TP';
        prj.Subsidiary_ID__c = 1;
        update prj;
        
        // create product details 
        Product_Details__c prodDetail = new Product_Details__c();
        prodDetail.Price__c = 56;
        prodDetail.Project__c = prj.Id;
        prodDetail.NS_Income_GL_Account__c = '290';
        prodDetail.NS_Deferred_Revenue_Account__c = '284';
        prodDetail.NS_Department__c = '10';
        prodDetail.NS_Revenue_Schedule__c = '29';
        prodDetail.Netsuite_Sync__c = false;
        prodDetail.Products__c = prod.id;
        prodDetail.Duration__c = '45';
        prodDetail.Description__c = 'Description_Test';
        prodDetail.Tier__c = 'Test';
        prodDetail.Netsuite_ID__c = '889955';
        prodDetail.SubsidiaryID__c =1;
        insert prodDetail;
        
        // update line item
        oli.Product_Details__c = prodDetail.Id;
        oli.Start_Date__c = Date.newInstance(2021, 01, 01);
        oli.End_Date__c = Date.newInstance(2021, 12, 31);
        oli.Projects__c = prj.Id;
        oli.Skip_NetSuite_Sync__c = true;
        oli.Representative_Voting_Contact__c = con.Id;
        oli.Billing_Contact__c = con.Id;
        update oli;
        
        Opportunity opp =[Select ID,Type,Bill_To_Address__c,StageName From Opportunity where Name='Opportunity testing 1' Limit 1];
        
        OpportunityContactRole CR = new OpportunityContactRole(OpportunityId = opp.Id,IsPrimary = true, ContactId =con.Id, Role='Membership Decision Maker'); 
        insert CR;
        
        opp.RecordTypeId = corporateTrainingRecordId ;
        opp.Invoice_Only_Opp__c = true;
        opp.Type = 'New Business';
        opp.Bill_To_Address__c = objAddress.Id;
        opp.StageName = 'Closed Won';
        opp.Billing_Contact__c = con.Id;
        Update opp; 
        
    }  
    
    @isTest
    static void testValidateAddressBeforeDelete() {
        
        Opportunity opp =[Select ID,Type,Bill_To_Address__c,StageName From Opportunity Limit 1];
        Address__c objAddress = [Select ID,City__c From Address__c Where Id=:opp.Bill_To_Address__c];
        objAddress.City__c = 'Update City';
        update objAddress;
        
        Test.startTest();
        try {
            delete objAddress;
        }
        catch(Exception e){
            System.debug('Exception: ' + e + ', Message: ' + e.getMessage()+', Line Number: ' + e.getLineNumber()+'\n' + e.getStackTraceString());
            System.Assert(e.getMessage().contains('You can not delete this Address'), 'Delete action is not completed');
        }
        Test.stopTest();
    }
    
    @isTest
    static void testDeleteUndeleteMethod() {
        
        map<Id,Address__c> oldMap = new map<Id,Address__c>();
        map<Id,Address__c> newMap = new map<Id,Address__c>();
        
        Opportunity opp =[Select ID,Type,Bill_To_Address__c,StageName From Opportunity Limit 1];
        Address__c objAddress = [Select ID,City__c From Address__c Where Id=:opp.Bill_To_Address__c];
        
        oldMap.put(objAddress.id, objAddress);
        newMap.put(objAddress.id, objAddress);
        
        AddressTriggerHandler objClass = new AddressTriggerHandler();
        
        AddressTriggerHandler.AfterDelete(oldMap);
        AddressTriggerHandler.AfterUnDelete(newMap);
        
    }
}