force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Created for DocuSign to show Account Address in Single Line.</description>
    <formula>IF(NOT(ISBLANK(BillingStreet)),BillingStreet +&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingCity)),BillingCity+&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingPostalCode)),BillingPostalCode+&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingCountry)),BillingCountry,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/No_Of_Employess__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Employess__c</fullName>
    <label>JoinNow No Of Employees</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Alternate Bill to Name and Address</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alternate Bill to Name and Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>if(LEN(Street__c )&gt;0, Street__c &amp; &quot; &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN(City__c )&gt;0, City__c &amp; &quot;, &quot; , &quot;&quot; )&amp;
if(LEN(State__c )&gt;0, State__c &amp; &quot; &quot; , &quot;&quot; )&amp;
if(LEN(Zip_Postal_Code__c )&gt;0, Zip_Postal_Code__c,&quot;&quot;) &amp; BR() &amp;
If(LEN(Country__c) &gt;0,Country__c ,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alternate_Email__c/Alternate_Email__c.object-meta.xml
<CustomObject>
    <label>Alternate Email</label>
    <nameField>
        <displayFormat>AE-{000}</displayFormat>
        <label>Alternate Email ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternate Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alternate_Email__c/fields/Alternate_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email_Address__c</fullName>
    <externalId>true</externalId>
    <label>Alternate Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Alternate_Email__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Alternate Emails</relationshipLabel>
    <relationshipName>Alternate_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alternate_Email__c/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company_Type_Needs_Verified__c.field-meta.xml
<CustomField>
    <fullName>Company_Type_Needs_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Company Type Needs Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Employee_Count_Needs_Verified__c.field-meta.xml
<CustomField>
    <fullName>Employee_Count_Needs_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Employee Count Needs Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hold__c.field-meta.xml
<CustomField>
    <fullName>Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Tier_Needs_Verification__c.field-meta.xml
<CustomField>
    <fullName>Product_Tier_Needs_Verification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Drives the Product Tier verification section of the oppJoinNowVerification LWC</description>
    <label>Product Tier Needs Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/End_Tier__c.field-meta.xml
<CustomField>
    <fullName>End_Tier__c</fullName>
    <label>End Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Start_Tier__c.field-meta.xml
<CustomField>
    <fullName>Start_Tier__c</fullName>
    <label>Start Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/End_Tier__c.field-meta.xml
<CustomField>
    <fullName>End_Tier__c</fullName>
    <label>End Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Start_Tier__c.field-meta.xml
<CustomField>
    <fullName>Start_Tier__c</fullName>
    <label>Start Tier</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <label>Membership</label>
</RecordType>

force-app/main/default/classes/AccountTriggerHandler.cls
public Class AccountTriggerHandler implements ITriggerHandler{
    AccountTriggerAction action = new AccountTriggerAction();
    public static Set<Id> deleteAlternateEmails = new Set<Id>();
    public void BeforeInsert(List<SObject> triggerNew){
        
        // action.updateWebsite((List<Account>)triggerNew, NULL);
    }
    
    public void beforeUpdate(Map<id, SObject> newAccount, Map<id, SObject> oldAccount){
        action.updateOldOwnersEmail((Map<id, Account>)newAccount, (Map<id, Account>)oldAccount);
        AccountTriggerAction.updateSectorAccount((Map<id, Account>)newAccount, (Map<id, Account>)oldAccount);
        // action.updateWebsite((List<Account>)newAccount.Values(), (Map<id,Account>)oldAccount);
    }
    
    public static void BeforeDelete(Map<Id, Sobject> oldMap){
        //call before delete actions
        getAlternateEmailsToBeDeleted((List<Account>)oldMap.Values());
    }
    
    public static void afterInsert(Map<Id, SObject> newMap){
        System.debug('in after insert');
        //createOrUpdateAlternateEmail((Map<Id, Account>)newMap,null);
    }
    
    public static void AfterUpdate(Map<Id, SObject> newMap, Map<Id, Sobject> oldMap){
        //createOrUpdateAlternateEmail((Map<Id, Account>)newMap,(Map<Id, Account>)oldMap);
        //Call Method to update address obj for an Account
        updateAddressObjForAccount((Map<Id, Account>)newMap, (Map<Id, Account>)oldMap);
        updateEmployeeCountNeedVerified((Map<Id, Account>)newMap, (Map<Id, Account>)oldMap);
        AccountTriggerAction.updateSectorIndustryOnContact((Map<id, Account>)newMap, (Map<id, Account>)oldMap);
    }
    
    public static void AfterDelete(Map<Id, Sobject> oldMap){
        AccountTriggerAction.deleteAlternateEmail((List<Account>)oldMap.values(), deleteAlternateEmails);
    }
    
    public static void AfterUnDelete(Map<Id, Sobject> newMap){
        //call after undelete actions
    }
    
    public Boolean IsDisabled(){
        return false;
    }
    
    /*
public static void createOrUpdateAlternateEmail(Map<Id, Account> newMap,Map<Id, Account> oldMap){
List<Alternate_Email__c> alternateEmailList = new List<Alternate_Email__c>();
Set<String> alternateEmailSet = new Set<String>();
for(Account acc : newMap.values()){
if(((String.isNotBlank(acc.PersonEmail) && acc.IsPersonAccount) && (oldMap == null || (oldMap != null  && oldMap.get(acc.id).PersonEmail != acc.PersonEmail)))){
alternateEmailSet.add(acc.PersonEmail);
}
}
if(!alternateEmailSet.IsEmpty()){
List<Alternate_Email__c> alternateEmails = [SELECT Alternate_Email_Address__c FROM Alternate_Email__c
WHERE Alternate_Email_Address__c IN : alternateEmailSet];
Set<String> emailSet = new Set<String>();
for(Alternate_Email__c altEmail :alternateEmails){
emailSet.add(altEmail.Alternate_Email_Address__c);
}
for(Account acc : newMap.values()){
if(!emailSet.contains(acc.PersonEmail)){
Alternate_Email__c altEmail = new Alternate_Email__c();
altEmail.Alternate_Email_Address__c = acc.PersonEmail;
altEmail.Primary_Email__c = true;
altEmail.Active__c = true;
altEmail.Contact_Name__c = acc.PersonContactId;
alternateEmailList.add(altEmail);
}
}
if(!alternateEmailList.isEmpty()){
insert alternateEmailList;
}
}
}
*/
    private static void getAlternateEmailsToBeDeleted(List<Account> accounts){
        deleteAlternateEmails.clear();
        for (Alternate_Email__c alternateEmail : [SELECT Id
                                                  FROM Alternate_Email__c
                                                  WHERE contact_name__r.AccountId IN:accounts]){
                                                      deleteAlternateEmails.add(alternateEmail.Id);
                                                  }
    }
    
    public static void updateAddressObjForAccount(Map<Id, Account> newMap, Map<Id, Account> oldMap){
        Map<Id, String> IdVsAddress = new Map<Id, String>();
        
        //Iterate over old values
        for (Account accnt : oldMap.values()){
            
            //if the billing address is changed
            if (newMap.get(accnt.Id).Name != accnt.Name || newMap.get(accnt.Id).BillingStreet != accnt.BillingStreet || newMap.get(accnt.Id).BillingCity != accnt.BillingCity || newMap.get(accnt.Id).BillingState != accnt.BillingState || newMap.get(accnt.Id).BillingPostalCode != accnt.BillingPostalCode || newMap.get(accnt.Id).BillingCountry != accnt.BillingCountry){
                //Storing the billing address in the form which is stored on address record
                String oldBillingAddress = (!String.isBlank(accnt.BillingStreet) ? accnt.BillingStreet + ' ' : '') + '<br>' + (!String.isBlank(accnt.BillingCity) ? accnt.BillingCity + ', ' : '') + (!String.isBlank(accnt.BillingState) ? accnt.BillingState + ' ' : '') + (!String.isBlank(accnt.BillingPostalCode) ? accnt.BillingPostalCode : '') + '<br>' + (!String.isBlank(accnt.BillingCountry) ? accnt.BillingCountry : '');
                
                IdVsAddress.put(accnt.Id, oldBillingAddress);
            }
        }
        System.debug('IdVsAddress ' + IdVsAddress);
        //if map is not empty
        if (!IdVsAddress.isEmpty()){
            List<Address__c> addressToUpdate = new List<Address__c>();
            
            //Retrieve the Account records with its associated address records
            List<Account> accountList = [SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, (SELECT Id, Address__c
                                                                                                                                        FROM Addresses__r)
                                         FROM Account 
                                         WHERE Id IN:IdVsAddress.keySet() AND BillingCity != null AND BillingState != null AND BillingPostalCode != null];
            System.debug('accountList ' + accountList);
            
            //Iterate over the list
            for (Account acc : accountList){
                
                //if it has any address record associated with it
                if (acc.Addresses__r.size() > 0){
                    
                    //if the oldAddress of account matches with address record's address then update the address record with new address of account
                    for (Address__c addr : acc.Addresses__r){
                        if (IdVsAddress.containsKey(acc.Id) && IdVsAddress.get(acc.Id) == addr.Address__c){
                            Address__c addrss = new Address__c(Id = addr.Id);
                            String billToNameString = (acc.Name + (String.isNotBlank(acc.BillingCountry) ? ' - ' + acc.BillingCountry : '')).length() >= 80 ? (acc.Name + (String.isNotBlank(acc.BillingCountry) ? ' - ' + acc.BillingCountry : '')).subString(0, 80) : (acc.Name + (String.isNotBlank(acc.BillingCountry) ? ' - ' + acc.BillingCountry : ''));
                                addrss.Name = billToNameString;
                            addrss.Street__c = !String.isBlank(acc.BillingStreet) ? acc.BillingStreet : '';
                            addrss.City__c = acc.BillingCity;
                            addrss.State__c = acc.BillingState;
                            addrss.Zip_Postal_Code__c = acc.BillingPostalCode;
                            addrss.Country__c = !String.isBlank(acc.BillingCountry) ? acc.BillingCountry : '';
                            addressToUpdate.add(addrss);
                            break;
                        }
                    }
                }
            }
            System.debug('addressToUpdate ' + addressToUpdate);
            
            //update the address records
            if (!addressToUpdate.isEmpty()){
                update addressToUpdate;
            }
        }
    }
    
    public static void updateEmployeeCountNeedVerified(Map<Id, Account> newMap, Map<Id, Account> oldMap){
        Id idMembershipOpp = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Membership').getRecordTypeId();
        set<Id> setAccountIds = new set<Id>();
        set<Id> setEmployeeCountNeedVerified = new set<Id>();
        set<Id> setOpportunityIds = new set<Id>();
        map<Id, Opportunity> mapOpportunity = new map<Id, Opportunity>();
        map<Id, Account> mapAccount = new map<Id, Account>();
        map<Id, List<Product_Details__c>> mapProject_ProductDetails = new map<Id, List<Product_Details__c>>();
        List<Opportunity> listOppstoUpdate = new List<Opportunity>();
        string joinnowEmployees;
        
        for (Account objAccount : newMap.values()){
            
            if (oldMap.get(objAccount.id).No_Of_Employess__c != objAccount.No_Of_Employess__c){
                setAccountIds.add(objAccount.id);
                mapAccount.put(objAccount.id, objAccount);
                //
                if (objAccount.No_Of_Employess__c != null && objAccount.No_Of_Employess__c != ''){
                    joinnowEmployees = objAccount.No_Of_Employess__c;
                } else{
                    joinnowEmployees = '';
                }
                
                system.debug('jn1: ' + objAccount.No_Of_Employess__c);
                system.debug('jn2: ' + joinnowEmployees);
                
                if (joinnowEmployees.contains(',')){
                    joinnowEmployees = joinnowEmployees.replace(',', '');
                }
                
                if (!joinnowEmployees.isNumeric()){
                    joinnowEmployees = '';
                }
                
                if (joinnowEmployees != null && joinnowEmployees != ''){
                    if (objAccount.NumberOfEmployees != Integer.valueOf(joinnowEmployees)){
                        setEmployeeCountNeedVerified.add(objAccount.Id);
                    }
                }
                
            }
        }
        
        if (setAccountIds.size() > 0 && !setEmployeeCountNeedVerified.isEmpty()){
            for (Opportunity objOpportunity : [Select id, accountId, Employee_Count_Needs_Verified__c, Product_Tier_Needs_Verification__c, Company_Type_Needs_Verified__c, Account.No_Of_Employess__c, Type, recordtypeid
                                               from Opportunity
                                               where AccountId IN:setEmployeeCountNeedVerified AND isClosed = false AND Hold__c != true and Type != 'Renewal' AND recordTypeid = :idMembershipOpp]){
                                                   
                                                   
                                                   objOpportunity.Employee_Count_Needs_Verified__c = true;
                                                   
                                                   
                                                   listOppstoUpdate.add(objOpportunity);
                                                   
                                                   //mapOpportunity.put(objOpportunity.Id,objOpportunity);
                                                   //setOpportunityIds.add(objOpportunity.Id);
                                               }
            
            /*system.debug('setOpportunityIds-->'+setOpportunityIds);
for(OpportunityLineItem objOpportunityProduct : [Select OpportunityId,Projects__c,Product2Id,Start_Tier__c,End_Tier__c, Opportunity.AccountId, Opportunity.Account.No_Of_Employess__c from OpportunityLineItem Where OpportunityId IN:setOpportunityIds]){
Opportunity objOpportunity = mapOpportunity.get(objOpportunityProduct.OpportunityId);
String jnEmployees = objOpportunity.account.No_Of_Employess__c;
jnEmployees = jnEmployees.replace(',','');
if (!jnEmployees.isNumeric()) {
jnEmployees = '';
}
if (jnEmployees != null && jnEmployees != '') {
if(objOpportunityProduct.Start_Tier__c < Integer.valueOf(jnEmployees) && objOpportunityProduct.End_Tier__c < Integer.valueOf(jnEmployees)  && objOpportunityProduct.End_Tier__c != null ){
objOpportunity.Product_Tier_Needs_Verification__c = true;
}
}

if (!listOppstoUpdate.contains(objOpportunity)) {
listOppstoUpdate.add(objOpportunity);
}
}*/
            
            if (listOppstoUpdate.size() > 0){
                try{
                    update listOppstoUpdate;
                } catch (DmlException e){
                    system.debug('Account Trigger Handler Error in Updating Related Opportunity Tier Verification: ' + e.getMessage());
                }
            }
            system.debug('mapOpportunity--->' + mapOpportunity.values());
        }
    }
    
}