force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Created for DocuSign to show Account Address in Single Line.</description>
    <formula>IF(NOT(ISBLANK(BillingStreet)),BillingStreet +&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingCity)),BillingCity+&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingPostalCode)),BillingPostalCode+&apos;, &apos;,&apos;&apos;)&amp;
IF(NOT(ISBLANK(BillingCountry)),BillingCountry,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Alternate Bill to Name and Address</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alternate Bill to Name and Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>if(LEN(Street__c )&gt;0, Street__c &amp; &quot; &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN(City__c )&gt;0, City__c &amp; &quot;, &quot; , &quot;&quot; )&amp;
if(LEN(State__c )&gt;0, State__c &amp; &quot; &quot; , &quot;&quot; )&amp;
if(LEN(Zip_Postal_Code__c )&gt;0, Zip_Postal_Code__c,&quot;&quot;) &amp; BR() &amp;
If(LEN(Country__c) &gt;0,Country__c ,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Payment Due Immediately</fullName>
            </value>
            <value>
                <fullName>Payment Due Prior To Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BillToAddressesOnOppControllerTest.cls
@isTest public with sharing class BillToAddressesOnOppControllerTest {
    @isTest public static void testController() {
        //stage data
        Account acc = new Account();
        acc.Name = 'Acme Inc';
        insert acc;

        Address__c addr1 = new Address__c();
        addr1.Account__c = acc.Id;
        insert addr1;

        Address__c addr2 = new Address__c();
        addr2.Account__c = acc.Id;
        insert addr2;

        Opportunity opp = new Opportunity();
        opp.Name = 'Test Acme Opp';
        opp.StageName = '2. Discovery';
        opp.CloseDate = Date.today();
        opp.AccountId = acc.Id;
        opp.PaymentTerms__c = 'Net 30';
        insert opp;

        //test controller's methods and verify results
        List<Address__c> addresses = new List<Address__c>();
        addresses = BillToAddressesOnOppController.getBillToAddresses(opp.Id);
        System.assertEquals(2, addresses.size());
        
        ID nonexistantID1 = BillToAddressesOnOppController.getBillToAddress(opp.Id);
        System.assertEquals(null, nonexistantID1);
        
        BillToAddressesOnOppController.saveSelectedAddress(opp.Id, addr1.Id);
        ID addr1ID = BillToAddressesOnOppController.getBillToAddress(opp.Id);
        System.assertEquals(addr1.Id, addr1ID);
            
        BillToAddressesOnOppController.saveSelectedAddress(opp.Id, addr2.Id);
        ID addr2ID = BillToAddressesOnOppController.getBillToAddress(opp.Id);
        System.assertEquals(addr2.Id, addr2ID);
        
        BillToAddressesOnOppController.clearBillToAddress(opp.Id);
        ID nonexistantID2 = BillToAddressesOnOppController.getBillToAddress(opp.Id);
        System.assertEquals(null, nonexistantID2);
    }
}