force-app/main/default/objects/Account/fields/Company_Type__c.field-meta.xml
<CustomField>
    <fullName>Company_Type__c</fullName>
    <label>Company Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>education</fullName>
            </value>
            <value>
                <fullName>government</fullName>
            </value>
            <value>
                <fullName>nonprofit</fullName>
            </value>
            <value>
                <fullName>personal</fullName>
            </value>
            <value>
                <fullName>private</fullName>
            </value>
            <value>
                <fullName>public</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company_Account.recordType-meta.xml
<RecordType>
    <fullName>Company_Account</fullName>
    <active>true</active>
    <description>Account record type for companies</description>
    <label>Company Account</label>
</RecordType>

force-app/main/default/objects/AccountProjectBenchmark__c/AccountProjectBenchmark__c.object-meta.xml
<CustomObject>
    <description>The Benchmark scores for an Account/Project Combination</description>
    <label>Account Project Benchmark</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Project Benchmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountProjectBenchmark__c/fields/MembershipLevel__c.field-meta.xml
<CustomField>
    <fullName>MembershipLevel__c</fullName>
    <defaultValue>&quot;Non Member&quot;</defaultValue>
    <description>The Membership Level Related to the Score</description>
    <inlineHelpText>The Membership Level Related to the Score</inlineHelpText>
    <label>Membership Level</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountProjectBenchmark__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Project Related to the Benchmark Score</description>
    <inlineHelpText>Project Related to the Benchmark Score</inlineHelpText>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Project Stage Must be Formation - Engaged, Formation - Confidential or Active</errorMessage>
        <filterItems>
            <field>Project__c.Project_Status__c</field>
            <operation>equals</operation>
            <value>Formation - Engaged, Formation - Confidential, Active</value>
        </filterItems>
        <infoMessage>Project Stage Must be Formation - Engaged, Formation - Confidential or Active</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Account Project Benchmarks</relationshipLabel>
    <relationshipName>AccountProjectBenchmarksProject</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Consumer Electronics</fullName>
            </value>
            <value>
                <fullName>Cross-Industry</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Climate</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health Care</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
            <value>
                <fullName>Motion Pictures</fullName>
            </value>
            <value>
                <fullName>Non-profit Organizations</fullName>
            </value>
            <value>
                <fullName>Pharmaceuticals</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Public Health &amp; Disaster Response</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Indicates if the project has Membership, Crowdfunding (e.g. LFX Funding), or both. Note that a project may have membership requirements that do not have any fees or funding associated with them. In that case, &apos;Membership&apos; is still selected for this field.</inlineHelpText>
    <label>Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Crowdfunding</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/ProjectBenchmarkInput__c.object-meta.xml
<CustomObject>
    <description>Defines multiplier for input into a Projects Scorecard</description>
    <label>Project Benchmark Input</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Benchmark Inputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/BenchmarkInputType__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkInputType__c</fullName>
    <description>The Type of Input used for the Benchmark</description>
    <inlineHelpText>The Type of Input used for the Benchmark</inlineHelpText>
    <label>Benchmark Input Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BenchmarkInputType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Project Benchmark Input Types Related To</description>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Project__c.Project_Status__c</field>
            <operation>equals</operation>
            <value>Formation - Engaged, Formation - Confidential, Active</value>
        </filterItems>
        <infoMessage>Project Stage must be Formation - Engaged, Formation - Confidential or Active</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Benchmark Inputs</relationshipLabel>
    <relationshipName>ProjectBenchmarkInputsProject</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/ScoreMultiplier__c.field-meta.xml
<CustomField>
    <fullName>ScoreMultiplier__c</fullName>
    <description>The count will be multipled by this value when used in the benchmark</description>
    <inlineHelpText>The count will be multipled by this value when used in the benchmark</inlineHelpText>
    <label>Score Multiplier</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/UseInEvntBenchmark__c.field-meta.xml
<CustomField>
    <fullName>UseInEvntBenchmark__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use Input when calculating the Event Benchmark</description>
    <inlineHelpText>Use Input when calculating the Event Benchmark</inlineHelpText>
    <label>Use In Evnt Benchmark</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/UseInMemberBenchmark__c.field-meta.xml
<CustomField>
    <fullName>UseInMemberBenchmark__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use Input when calculating the Membership Benchmark</description>
    <inlineHelpText>Use Input when calculating the Membership Benchmark</inlineHelpText>
    <label>Use In Member Benchmark</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProjectBenchmarkInput__c/fields/UseInTandCBenchmark__c.field-meta.xml
<CustomField>
    <fullName>UseInTandCBenchmark__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use Input when calculating the Training and Certification Benchmark</description>
    <inlineHelpText>Use Input when calculating the Training and Certification Benchmark</inlineHelpText>
    <label>Use In Training and Cert Benchmark</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/ProjectMembershipBenchmark__c.object-meta.xml
<CustomObject>
    <label>Project Membership Benchmark</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Membership Benchmarks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/MembershipBenchmark__c.field-meta.xml
<CustomField>
    <fullName>MembershipBenchmark__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Membership Benchmark Value Expected to be reached for the Project/Membership Level</description>
    <inlineHelpText>The Membership Benchmark Value Expected to be reached for the Project/Membership Level</inlineHelpText>
    <label>Membership Benchmark</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Project Stage must be Formation - Engaged, Formation - Confidential or Active</errorMessage>
        <filterItems>
            <field>Project__c.Project_Status__c</field>
            <operation>equals</operation>
            <value>Formation - Engaged, Formation - Confidential, Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Membership Benchmarks</relationshipLabel>
    <relationshipName>ProjectMembershipBenchmarks_Project</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectMembershipBenchmark__c/fields/TandCBenchmark__c.field-meta.xml
<CustomField>
    <fullName>TandCBenchmark__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The Training and Certification Benchmark Value Expected to be reached for the Project/Membership Level</description>
    <inlineHelpText>The Training and Certification Benchmark Value Expected to be reached for the Project/Membership Level</inlineHelpText>
    <label>Training and Certification Benchmark</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/BenchmarkInputType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PersonOrgCertCnt</fullName>
        <label>Associated Person Certifications</label>
    </customValue>
    <customValue>
        <fullName>BoardMeetingAttendCnt</fullName>
        <label>Board Meetings Attended</label>
    </customValue>
    <customValue>
        <fullName>CodeCommitCnt</fullName>
        <label>Code Commits</label>
    </customValue>
    <customValue>
        <fullName>EvntAttendCnt</fullName>
        <label>Event Attendence</label>
    </customValue>
    <customValue>
        <fullName>ForumContribCnt</fullName>
        <label>Forum Contributions</label>
    </customValue>
    <customValue>
        <fullName>QBRAttendCnt</fullName>
        <label>QBR Attendence</label>
    </customValue>
    <customValue>
        <fullName>TrainingCmpltCnt</fullName>
        <label>Training Completed</label>
    </customValue>
    <masterLabel>Benchmark Input Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
/**
Used to Genreate Test Data
@author (c) Idea Science  2023
*
* History
* *******
* Date       By             Ticket      Change
* *********  *************  **********  **************************************
* 20FEB2023  Craig Jackson  LF240-271   Initial Version
*/
@isTest
public class TestDataFactory {
    // Create a single Company Account
    public static Account getCompanyAccount(String name, Boolean doInsert) {
        System.debug('CTJ: ' + Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName());
        Account acnt =  new Account (
                Name = name
                , RecordTypeId    = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Company_Account').getRecordTypeId()
                , Type            = 'Customer'
                , Company_Type__c = 'private'
                , Sector__c       = 'Information Technology'
                , Website         = 'www.' + name.replace(' ', '-') + '.com');

        // Insert Record if asked to
        if (doInsert) {
            insert acnt;
        }
        return acnt;
    }

    // Create a multiple Company Accounts
    public static List<Account> getCompanyAccounts(Integer noAccounts, String name, Boolean doInsert) {
        List<Account> acntLst = new List<Account>();
        for (integer i = 1; i<=noAccounts; ++i) {
            Account acnt = getCompanyAccount(name + ' ' + i, false);
            acntLst.add(acnt);
        }

        // Insert Record if asked to
        if (doInsert) {
            insert acntLst;
        }
        return acntLst;
    }

    // Create a single Project
    public static Project__c getProject(String name, Boolean doInsert) {
        Project__c prj =  new Project__c (
                Name = name
                , Category__c   = 'Incorporated Entity'
                , Industry__c   = 'Automotive'
                , Model__c      = 'Membership'
                , Status__c     = 'Planned'
                , Slug__c       = name.replaceAll(' ', '').toLowerCase()
                , Start_Date__c = Date.Today().addMonths(-1));

        // Insert Record if asked to
        if (doInsert) {
            insert prj;
        }
        return prj;
    }

    // Create a multiple Projects
    public static List<Project__c> getProjects(Integer noProjects, String name, Boolean doInsert) {
        List<Project__c> prjLst = new List<Project__c>();
        for (integer i = 1; i<=noProjects; ++i) {
            Project__c prj = getProject(name + ' ' + i, false);
            prjLst.add(prj);
        }

        // Insert Record if asked to
        if (doInsert) {
            insert prjLst;
        }
        return prjLst;
    }

    // Create a single ProjectBenchmarkInput__c
    public static ProjectBenchmarkInput__c getProjectBenchmarkInput(Project__c prj, String inputType, Boolean doInsert) {
        ProjectBenchmarkInput__c prjBMInput = new ProjectBenchmarkInput__c (
            Name                      = 'Dummy'
            , Project__c              = prj.Id
            , BenchmarkInputType__c   = inputType
            , ScoreMultiplier__c      = 1
            , UseInEvntBenchmark__c   = false
            , UseInMemberBenchmark__c = false
            , UseInTandCBenchmark__c  = false
        );

        // Insert Record if asked to
        if (doInsert) {
            insert prjBMInput;
        }
        return prjBMInput;
    }

    // Create a single ProjectMembershipBenchmark__c
    public static ProjectMembershipBenchmark__c getProjectMembershipBenchmark(Project__c prj, String membershipLvl, Boolean doInsert) {
        ProjectMembershipBenchmark__c prjMemBM = new ProjectMembershipBenchmark__c (
            Name                     = 'Dummy'
            , Project__c             = prj.Id
            , MembershipLevel__c     = membershipLvl
            , EventBenchmark__c      = 1
            , EventMaxValue__c       = 2
            , MembershipBenchmark__c = 3
            , MembershipMaxValue__c  = 4
            , TandCBenchmark__c      = 5
            , TandCMaxValue__c       = 6
        );

        // Insert Record if asked to
        if (doInsert) {
            insert prjMemBM;
        }
        return prjMemBM;
    }

    // Create a single AccountProjectBenchmark__c
    public static AccountProjectBenchmark__c getAccountProjectBenchmark(Project__c prj, Account acnt, Boolean doInsert) {
        AccountProjectBenchmark__c acntPrjBM = new AccountProjectBenchmark__c (
            Name                     = 'Dummy'
            , Account__c             = acnt.Id
            , Project__c             = prj.Id
            , MembershipLevel__c     = 'Non Member'
            , EvntBenchmarkScore__c  = 1
            , MemBenchmarkScore__c   = 3
            , TandCBenchmarkScore__c = 5
        );

        // Insert Record if asked to
        if (doInsert) {
            insert acntPrjBM;
        }
        return acntPrjBM;
    }

    // Create a single AccountProjectBenchmarkItem__c
    public static AccountProjectBenchmarkItem__c getAccountProjectBenchmarkItem(AccountProjectBenchmark__c acntPrjBM, String itemType, Boolean doInsert) {
        AccountProjectBenchmarkItem__c acntPrjBMI = new AccountProjectBenchmarkItem__c (
            Name                     = 'Dummy'
            , AccountProjectBenchmark__c = acntPrjBM.Id
            , BenchmarkType__c           = itemType
            , BenchmarkValue__c          = 1
        );

        // Insert Record if asked to
        if (doInsert) {
            insert acntPrjBMI;
        }
        return acntPrjBMI;
    }
}