force-app/main/default/objects/Account/fields/Current_Year_Spend__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Spend__c</fullName>
    <description>This field will store Current Year Spend Amount which will calculated from Purchase History Record from Opportunity.</description>
    <label>Current Year Spend</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bill_From_ID__c.field-meta.xml
<CustomField>
    <fullName>Bill_From_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill From ID</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Assets (Bill From ID)</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</description>
    <inlineHelpText>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</inlineHelpText>
    <label>Billing Account Override</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores project category for riscv projects</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Number_of_Years_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_Required__c</fullName>
    <label>Number of Years Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Pipeline_Stage__c.field-meta.xml
<CustomField>
    <fullName>Pipeline_Stage__c</fullName>
    <label>Pipeline Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exploratory Discussions</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Intent To Form</fullName>
            </value>
            <value>
                <fullName>Moving To Full Launch</fullName>
            </value>
            <value>
                <fullName>Disengaged</fullName>
            </value>
            <value>
                <fullName>Launched</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Services (Fab, design services)</fullName>
    </customValue>
    <customValue>
        <fullName>Chip (SoC, IP, FPGA)</fullName>
    </customValue>
    <customValue>
        <fullName>I/O (Memory, network, storage)</fullName>
    </customValue>
    <customValue>
        <fullName>Systems (ODM, OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Software (Dev tools, firmware, OS)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry (cloud, mobile, HPC, ML, automotive)</fullName>
    </customValue>
    <customValue>
        <fullName>Research (Universities, Labs, other alliances, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <description>Account Project Category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CurrentYearRevenueProjectBatchTest.cls
@isTest
public class CurrentYearRevenueProjectBatchTest{
	@isTest
	static void Test1(){

		Account acc = new Account();
		acc.Name = 'Test';
		acc.Current_Year_Spend__c = 2000;
		insert acc;
		List<Asset> lstAsset = new List<Asset>();
		Project__c project = new Project__c();
		project.Name = 'Test Project';
		project.Type__c = 'Membership';
		project.Category__c = 'Subproject';
		project.Pipeline_Stage__c = 'Engaged';
		project.Slug__c = 'testing';
		insert project;
		Project__c P = [SELECT Id, Name
		                FROM Project__c];
		System.assertEquals('Test Project', P.Name);
		Asset assetObj = new Asset();
		assetObj.Name = 'Test Asset';
		assetObj.AccountId = acc.Id;
		assetObj.Projects__c = P.Id;
		assetObj.Status = 'Purchased';
		assetObj.PurchaseDate = Date.today();
		assetObj.Price = 15000;
		assetObj.Number_of_Years_Required__c = 1;
		insert assetObj;
		Asset a = [SELECT Id, Name, Projects__c
		           FROM Asset];
		System.assertEquals('Test Asset', a.Name);
		System.assertEquals(P.Id, a.Projects__c);
		P = [SELECT Id, Name, (SELECT Id
		                       FROM Assets__r)
		     FROM Project__c
		     WHERE Name = 'Test Project'];
		lstAsset = [SELECT Id, Price
		            FROM Asset
		            WHERE Name = 'Test Asset'];
		for (Asset rec : lstAsset){
			rec.Price = rec.Price + 2000;
		}

		update lstAsset;
		Test.startTest();
		CurrentYearRevenueProjectBatch obj = new CurrentYearRevenueProjectBatch();
		DataBase.executeBatch(obj, 200);
		Test.stopTest();
	}
}