force-app/main/default/objects/Account/fields/Current_Year_Spend__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Spend__c</fullName>
    <description>This field will store Current Year Spend Amount which will calculated from Purchase History Record from Opportunity.</description>
    <label>Current Year Spend</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Number_of_Years_Required__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Years_Required__c</fullName>
    <label>Number of Years Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CurrentYearSpendOnAccountBatchTest.cls
@isTest
public class CurrentYearSpendOnAccountBatchTest {
    @isTest static void Test1(){
        List<Account> lstAccount= new List<Account>();
		List<Asset> lstAsset= new List<Asset>();
        for(Integer i=0 ;i<5;i++)
        {
          Account acc = new Account();
          acc.Name ='Test'+i;
          acc.Current_Year_Spend__c = 2000+i;
          lstAccount.add(acc);
        }
         insert lstAccount;
        for(Account acc:lstAccount){
            Asset a = new Asset();
          	a.Name ='Test Asset';
          	a.AccountId = acc.Id;
            a.PurchaseDate = Date.today() ;
            a.InstallDate = Date.today();
            a.Price = 15000;
            a.Number_of_Years_Required__c = 1;
          	lstAsset.add(a);
        }
        insert lstAsset;
         Test.startTest();
         CurrentYearSpendOnAccountBatch obj = new CurrentYearSpendOnAccountBatch();
         DataBase.executeBatch(obj);
         Test.stopTest();

        
    }
}