force-app/main/default/objects/Account/fields/P_O_Required__c.field-meta.xml
<CustomField>
    <fullName>P_O_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This account requires purchase order numbers for invoices.</inlineHelpText>
    <label>P.O. Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</description>
    <inlineHelpText>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</inlineHelpText>
    <label>Billing Account Override</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>OpportunityLineItem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Manager (without subordinates)</fullName>
            </value>
            <value>
                <fullName>Manager (with subordinates)</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Owner/Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Authorized_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorized Signatory</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the membership/sponsorship/training items are to be billed to an Account other than the receiving Account.</description>
    <inlineHelpText>If the membership/sponsorship/training items are to be billed to an Account other than the receiving Account.</inlineHelpText>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Sent_By__c.field-meta.xml
<CustomField>
    <fullName>Contract_Sent_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Sent By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Opportunities__c</fullName>
    <inlineHelpText>The Opportunities area of your SWOT</inlineHelpText>
    <label>Opportunities</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Asset__c.field-meta.xml
<CustomField>
    <fullName>Parent_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>false</active>
    <businessProcess>Training</businessProcess>
    <description>Record type for training opportunities</description>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Program_Manager__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If Program Manager is non-LF employee. Create contact and add</inlineHelpText>
    <label>Program Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Program_Manager_U__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager_U__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Manager (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Role__c/Project_Role__c.object-meta.xml
<CustomObject>
    <label>Membership Roles</label>
    <nameField>
        <displayFormat>PR{000}</displayFormat>
        <label>Role AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Project_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Project_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Opportunity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item__c</fullName>
    <label>Opportunity Line Item</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Parent_Asset__c.field-meta.xml
<CustomField>
    <fullName>Parent_Asset__c</fullName>
    <formula>Opportunity__r.Parent_Asset__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Asset</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Voting Contact means this is the person at the company that has the right to vote in the project’s membership elections for their member class.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Representative/Voting Contact</fullName>
                <label>Voting Contact</label>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Legal Contact</fullName>
            </value>
            <value>
                <fullName>Event Sponsorship</fullName>
            </value>
            <value>
                <fullName>PO Contact</fullName>
            </value>
            <value>
                <fullName>Press Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projects</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MyProjectsReportControllerTest.cls
@istest
public class MyProjectsReportControllerTest {
    
    @testSetup static void setup(){
        Account acc = TestDataUtils.createAccount('free training Account');

        Contact con = TestDataUtils.createContact('test','linuxtest',acc.Id);

        User standard = TestFactory.getUser();

        Opportunity oppt= TestFactory.getOpportunity();
        oppt.OwnerId = standard.id;
        update oppt;
        
        Asset ass =  TestFactory.getAsset();
        ass.UsageEndDate = ass.UsageEndDate.addDays(2);
        ass.OwnerId = standard.Id;
        update ass;
        
        oppt.Parent_Asset__c =ass.id;
        update oppt;
    }
    
    @isTest
    static  void testAssetDetail(){
        
        Opportunity opp = [Select ID, Name From Opportunity Where Name = 'Opportunity testing 1'];
        
        User userdetail = [Select ID, email From User Where email ='standarduser123@testorg.com'];
        System.debug('userdetail' +userdetail);
        

        List<Asset> listofasset = [Select ID,Name,ownerid, InstallDate,UsageEndDate,Price,Opportunity__c,Opportunity__r.Name,Product2.ID,Product2.Name,Projects__r.Name,
                                   Projects__c,OpportunityLineItem__c, Account.Name, Account.BillingStreet, Account.BillingCity, Account.BillingState,Account.P_O_Required__c,
                                   Account.BillingPostalCode, Account.BillingCountry,Contact.Name,Contact.Email,Projects__r.OwnerId,Product2.Family,Bill_To_Account__c,(select id,StageName,Name from Opportunities__r)
                                   from Asset WHERE Opportunity__c =: opp.ID];
		system.debug('listofasset: ' + listofasset[0]);
        Project_Role__c objProjectRole = new Project_Role__c();
        objProjectRole.status__c ='Active';
        objProjectRole.Contact__c = [select id from contact limit 1].id;
        objProjectRole.Role__c ='Billing Contact';
        objProjectRole.Opportunity__c = opp.Id;
        objProjectRole.Opportunity_Line_Item__c = listofasset[0].OpportunityLineItem__c;
        objProjectRole.PrimaryContact__c = true;
        insert objProjectRole;
		
        test.startTest();
        MyProjectsReportController mycon = new  MyProjectsReportController(userdetail.ID);
        mycon.getAssetDetails();
        blob csvblob=  mycon.csvGenerate(listofasset);
        System.assert(csvblob != null);
        test.stopTest();
        
        
    }
    
}