force-app/main/default/objects/Account/fields/P_O_Required__c.field-meta.xml
<CustomField>
    <fullName>P_O_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This account requires purchase order numbers for invoices.</inlineHelpText>
    <label>P.O. Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto-Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</description>
    <inlineHelpText>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</inlineHelpText>
    <label>Billing Account Override</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>OpportunityLineItem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Manager (without subordinates)</fullName>
            </value>
            <value>
                <fullName>Manager (with subordinates)</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Owner/Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Authorized_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorized Signatory</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the membership/sponsorship/training items are to be billed to an Account other than the receiving Account.</description>
    <inlineHelpText>If the membership/sponsorship/training items are to be billed to an Account other than the receiving Account.</inlineHelpText>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Opportunities__c</fullName>
    <inlineHelpText>The Opportunities area of your SWOT</inlineHelpText>
    <label>Opportunities</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Asset__c.field-meta.xml
<CustomField>
    <fullName>Parent_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Renewal Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Text that will be displayed on invoice</description>
    <inlineHelpText>Text that will be displayed on invoice</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Standard Memberships will auto-populate date.</description>
    <inlineHelpText>Standard Memberships will auto-populate date.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Required</inlineHelpText>
    <label>Start Date*</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A one-sentence description of the project, which will be used for external facing (i.e. landscape graphic or a website list of LF projects) descriptions of projects.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Program_Manager__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If Program Manager is non-LF employee. Create contact and add</inlineHelpText>
    <label>Program Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Role__c/Project_Role__c.object-meta.xml
<CustomObject>
    <label>Membership Roles</label>
    <nameField>
        <displayFormat>PR{000}</displayFormat>
        <label>Role AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Project_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Project_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Opportunity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item__c</fullName>
    <label>Opportunity Line Item</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Voting Contact means this is the person at the company that has the right to vote in the project’s membership elections for their member class.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Representative/Voting Contact</fullName>
                <label>Voting Contact</label>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Legal Contact</fullName>
            </value>
            <value>
                <fullName>Event Sponsorship</fullName>
            </value>
            <value>
                <fullName>PO Contact</fullName>
            </value>
            <value>
                <fullName>Press Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projects</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MyProjectsReportController.cls
public class MyProjectsReportController {
    private string ownerId;
    public Map<id,OpportunityLineItem> opportunityLineItemsMap{get;set;}
    public Map<Id, Project_Role__c> oliIdVsProjectRoles;
    public Map<id,list<Asset>> projectName;
    Map<id,boolean> projectNameMap = new Map<id,boolean>();
    public list<Asset> assets;
    
    
    public MyProjectsReportController(){
        this('00541000007libo');
    }
    
    public MyProjectsReportController(string ownerId){
        this.OwnerId = ownerId;
       /*list<asset> assets = getAssetDetails();
        if(assets != null && !assets.isEmpty())
        sendEmailWithAttachment(csvGenerate(assets));
        system.debug('----'+this.OwnerId);*/
    }
    
    public list<asset> getAssetDetails(){
       set<id> opportunityID = new set<id>();
       Map<id, OpportunityLineItem> opportunityLineItemMap= new Map<id, OpportunityLineItem>();
         opportunityLineItemsMap = new Map<id,OpportunityLineItem>();
        projectName = new Map<id,list<Asset>>();
        oliIdVsProjectRoles = new Map<Id, Project_Role__c>();
        
       assets = [Select ID,Name,Opportunity__r.OwnerId,InstallDate,UsageEndDate,Price,Opportunity__c,Bill_To_Account__r.Name,Product2.ID,Product2.Name,Projects__r.Name,
                     Projects__c,OpportunityLineItem__c, Account.Name,Account.P_O_Required__c, Account.BillingStreet, Account.BillingCity, Account.BillingState,
                     Account.BillingPostalCode, Account.BillingCountry,Contact.Name,Contact.Email,Bill_To_Account__c,(select id,StageName,Name from Opportunities__r)
                      from Asset Where UsageEndDate = NEXT_N_DAYS:60 AND Product2.Family='Membership' 
                      AND Auto_Renew__c = true and Opportunity__r.OwnerId=: ownerId order by Projects__r.Name];
        
        System.debug('asset list' +assets[0].Opportunity__r.OwnerId);
        system.debug('asset list owner id: ' + ownerId);
        
        
        for(Asset assest : assets){
            projectNameMap.put(assest.Projects__c,false);
            if(assest.Opportunities__r.size() > 0){
                for(Opportunity oppor : assest.Opportunities__r){
                	opportunityID.add(oppor.id); 
                }
            }
        }
        if(opportunityID.size() > 0){
            
            list<opportunityLineItem> oliList = [select id,Start_Date__c,End_Date__c,OpportunityId,
                                                 TotalPrice,Description__c from opportunityLineItem
                                                 where OpportunityId in:opportunityID];
            if(oliList.size() > 0){
               Set<Id> oliIds = new Set<Id>();
                for(opportunityLineItem oli: oliList){
                    if(oli.OpportunityId != null && !opportunityLineItemsMap.containsKey(oli.OpportunityId))
                        opportunityLineItemsMap.put(oli.OpportunityId,oli);

                    oliIds.add(oli.Id);
                }
                //Added by Priyesh @Cloudoroute to fetch the billing contact from Membership roles instead of oli
                for(Project_Role__c billingRole : [
                        SELECT Id, Contact__r.Name, Contact__r.Email, Opportunity_Line_Item__c
                        FROM Project_Role__c
                        WHERE Opportunity_Line_Item__c IN:oliIds AND Role__c = 'Billing Contact' AND Status__c = 'Active' AND PrimaryContact__c = TRUE
                ]) {
                        if(!oliIdVsProjectRoles.containsKey(billingRole.Opportunity_Line_Item__c)){
                            oliIdVsProjectRoles.put(billingRole.Opportunity_Line_Item__c, billingRole);
                        }
                }

            } 
        }
        if(assets != null && assets.size() > 0){
            return assets; 
        }
        else{
            return null;
        }

    }
    public blob csvGenerate(list<Asset> assets){
        String header = 'Account Name, Account Billing Address , Product Name, Purchase History Name, Install Date, Usage End Date, Price, Opportunity Name, Start Date,  End Date,  Description, Total Price,Contact Full Name,Contact Email \n';
        String finalstr = header;
         String s = line(new String[] {
               format('Project Name'),
                format('Account Name'),
                format('Account PO Required'),   
                format('Account Billing Address'),
                format('Billing Account Override:Account Name'),
                format('Product Name'),    
                format('Purchase History Name'),
                format('Install Date'),
                format('Usage End Date'),
                format('Price'),
                format('Opportunity Name'),
                format('Start Date'),
                format('End Date'),  
                format('Description'),
                format('Total Price'), 
                format('Contact Full Name'),
                format('Contact Email'),
                format('Stage')   
                });
        if(assets.size() > 0){
           for (Asset assest : assets) {
               Map<id,boolean> projectNameOppporMap = new Map<id,boolean>();
           // system.debug('---'+opportunityLineItemsMap.get(assest.OpportunityLineItem__c).TotalPrice); projectNameMap
            
            if(projectNameMap.get(assest.Projects__c) == true){
                if(assest.Opportunities__r.size() > 0){
                    system.debug('---1IF--');
                    for(Opportunity oppor : assest.Opportunities__r){
                        
                        s += csvFormat(assest,null,oppor);	
                    }  
                }
                else{
                      system.debug('---2ELSE--');
                    s += csvFormat(assest,null);	
                }
            }
            else{
                System.debug('assest.Opportunities__r:: ' + assest.Opportunities__r);
                if(assest.Opportunities__r.size() > 0){
                    
                    for(Opportunity oppor : assest.Opportunities__r){
                        if(projectNameOppporMap.containsKey(assest.Projects__c) && projectNameOppporMap.get(assest.Projects__c) == true){
                             system.debug('---1IF--');
                           s += csvFormat(assest,null,oppor);
                        }
                        else{
                             system.debug('---2ELSE--');
                            s += csvFormat(assest,assest.Projects__r.Name,oppor); 
                            projectNameOppporMap.put(assest.Projects__c,true); 
                        }
                    }  
                }
                else{
                     system.debug('---3ELSE--');
                     s += csvFormat(assest,assest.Projects__r.Name);
                     	
                }
                projectNameMap.put(assest.Projects__c,true);
                
            }
            
           /* s += line(new String[] {
                    format(assest.Account.Name),
                    format(temp),
                    format(assest.Product2.Name),
                    format(assest.Name),
                    format(assest.InstallDate),
                    format(assest.UsageEndDate),
                   format(assest.Price),  
                    format(assest.Opportunity__r.Name),
                    format(opportunityLineItemsMap.get(assest.OpportunityLineItem__c).Start_Date__c),
                    format(opportunityLineItemsMap.get(assest.OpportunityLineItem__c).End_Date__c),
                    format(opportunityLineItemsMap.get(assest.OpportunityLineItem__c).Description__c), 
                    
                    format(opportunityLineItemsMap.get(assest.OpportunityLineItem__c).TotalPrice),
                    format(assest.Contact.Name),
                    format(assest.Contact.Email)    
                    }); */
            system.debug('---'+s);
        } 
        }
        
       
        system.debug('---'+s);
        Blob csvBlob = Blob.valueOf(s);
        system.debug('----'+csvBlob);
        return csvBlob;
    }
     private String line(String[] cells) {
        return String.join(cells, ',') + '\n';
    }
    private String format(Date d)    {
        return d != null ? d.format().escapeCsv() : '""';
    }
    private String format(String s) {
        String temp = s != null ?  s.escapeCsv() : '""';
            system.debug('---'+temp);
          return temp;
        
    }
    private String format(Decimal d, Integer scale) {
        return d != null ? String.valueOf(d.setScale(scale)) : '';
    }
    private String format(Decimal d) {
        return format(d, 2);
    }
     private String format(boolean d) {
         String temp;
         if(d != null && d == true){
             temp = 'TRUE';
             
         }
         else{
             temp = 'FALSE';
         }
         return temp;
    }
  /*  private void sendEmailWithAttachment(Blob csvContent){
        
        Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();//Create csv attachment
        system.debug('add csv file attachment');     
        blob csvBlob = csvContent; //updatedEntities
        string csvname= 'UpdatedEntityrecords.csv';
        csvAttc.setFileName(csvname);
        csvAttc.setBody(csvBlob);  
        csvAttc.setContentType('text/csv');  
        //Create Email      
        Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();
        String[] toAddresses = new list<string> {'yatish.salian@cloudroute.in'}; 
            String[] ccAddresses = new list<string> {'snehal@cloudroute.in'}; 
                
        email.setSenderDisplayName('Entity records Equation status Batch job');
        email.setSubject('Entity records Equation status updated');       
        
        email.setToAddresses( toAddresses );
        email.setCcAddresses( ccAddresses );
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});    
        email.setPlainTextBody('THis is Testing');      
        
        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
    }  */
   /* private string AddEscapeSequenceInCsvField(string ValueToEscape)       
    {
        if(ValueToEscape != null){
           if (ValueToEscape.contains(','))
            {
                system.debug('-----'+'\"' + ValueToEscape + '\"');
                return '\"' + ValueToEscape + '\"';
            } else{
                return ValueToEscape;
            }   
        }
        return null;
    }*/
    private String csvFormat(Asset assest,String ProjectName){
        String temp = getAddress(assest.Account.BillingStreet,assest.Account.BillingCity,assest.Account.BillingState,assest.Account.BillingPostalCode,assest.Account.BillingCountry);
        system.debug('=temp='+temp);   
        String billFromAccount = assest.Bill_To_Account__c != null ?assest.Bill_To_Account__r.Name:'';
        String lineFormat =  line(new String[] {
                           	   	format(ProjectName),
                               	format(assest.Account.Name),
                                format(assest.Account.P_O_Required__c),
                                format(temp),
                                format(billFromAccount),    
                                format(assest.Product2.Name),
                                format(assest.Name),
                                format(assest.InstallDate),
                                format(assest.UsageEndDate),
                                format(assest.Price),  
                                format(assest.Opportunities__r.size() > 0 ? assest.Opportunities__r[0].Name : ''),
                                format(assest.Opportunities__r.size() > 0 ? (opportunityLineItemsMap.containsKey(assest.Opportunities__r[0].id) ? opportunityLineItemsMap.get(assest.Opportunities__r[0].id).Start_Date__c : NULL) : NULL),
                                format(assest.Opportunities__r.size() > 0 ? (opportunityLineItemsMap.containsKey(assest.Opportunities__r[0].id)?opportunityLineItemsMap.get(assest.Opportunities__r[0].id).End_Date__c : NULL): NULL),
                                format(assest.Opportunities__r.size() > 0 ? (opportunityLineItemsMap.containsKey(assest.Opportunities__r[0].id)?opportunityLineItemsMap.get(assest.Opportunities__r[0].id).Description__c : NULL): NULL),
                                format(assest.Opportunities__r.size() > 0 ? (opportunityLineItemsMap.containsKey(assest.Opportunities__r[0].id)?opportunityLineItemsMap.get(assest.Opportunities__r[0].id).TotalPrice : NULL): NULL),
                                format(assest.Opportunities__r.size() > 0 ? (opportunityLineItemsMap.containsKey(assest.Opportunities__r[0].id) && oliIdVsProjectRoles.containsKey(opportunityLineItemsMap.get(assest.Opportunities__r[0].id).Id) ? oliIdVsProjectRoles.get(opportunityLineItemsMap.get(assest.Opportunities__r[0].id).Id).Contact__r.Name : NULL): NULL), //Added by Priyesh @Cloudoroute to fetch the billing contact from Membership roles instead of oli
                                format(assest.Opportunities__r.size() > 0 ? (opportunityLineItemsMap.containsKey(assest.Opportunities__r[0].id) && oliIdVsProjectRoles.containsKey(opportunityLineItemsMap.get(assest.Opportunities__r[0].id).Id) ? oliIdVsProjectRoles.get(opportunityLineItemsMap.get(assest.Opportunities__r[0].id).Id).Contact__r.Email : NULL): NULL), //Added by Priyesh @Cloudoroute to fetch the billing contact from Membership roles instead of oli
                                format(assest.Opportunities__r.size() > 0 ? assest.Opportunities__r[0].StageName : '')
                                });
        system.debug('---lineFormat---'+lineFormat);
        return lineFormat ;
    }    
    
     private String csvFormat(Asset assest,String ProjectName,Opportunity oppor){
         String temp = getAddress(assest.Account.BillingStreet,assest.Account.BillingCity,assest.Account.BillingState,assest.Account.BillingPostalCode,assest.Account.BillingCountry);
         system.debug('=temp='+temp);   
        String billFromAccount = assest.Bill_To_Account__c != null ?assest.Bill_To_Account__r.Name:'';
        String lineFormat =  line(new String[] {
                           	   	format(ProjectName),
                               	format(assest.Account.Name),
                                format(assest.Account.P_O_Required__c),
                                format(temp),
                                format(billFromAccount),    
                                format(assest.Product2.Name),
                                format(assest.Name),
                                format(assest.InstallDate),
                                format(assest.UsageEndDate),
                                format(assest.Price),  
                                format(oppor.Name),
                                format(opportunityLineItemsMap.containsKey(oppor.id) ? opportunityLineItemsMap.get(oppor.id).Start_Date__c : NULL),
                                format(opportunityLineItemsMap.containsKey(oppor.id)?opportunityLineItemsMap.get(oppor.id).End_Date__c : NULL),
                                format(opportunityLineItemsMap.containsKey(oppor.id)?opportunityLineItemsMap.get(oppor.id).Description__c : NULL),
                                format(opportunityLineItemsMap.containsKey(oppor.id)?opportunityLineItemsMap.get(oppor.id).TotalPrice : NULL),
                                format(opportunityLineItemsMap.containsKey(oppor.id) && oliIdVsProjectRoles.containsKey(opportunityLineItemsMap.get(oppor.id).Id) ? oliIdVsProjectRoles.get(opportunityLineItemsMap.get(oppor.id).Id).Contact__r.Name : NULL),//Added by Priyesh @Cloudoroute to fetch the billing contact from Membership roles instead of oli
                                format(opportunityLineItemsMap.containsKey(oppor.id) && oliIdVsProjectRoles.containsKey(opportunityLineItemsMap.get(oppor.id).Id) ? oliIdVsProjectRoles.get(opportunityLineItemsMap.get(oppor.id).Id).Contact__r.Email : NULL),//Added by Priyesh @Cloudoroute to fetch the billing contact from Membership roles instead of oli
                                format(oppor.StageName)
                                });
        return lineFormat ;
     }
    
    private String getAddress(String street, String city,String state,String postalCode, String country){
        String address = '';
        if(street != null && street != ''){
            address +=  street+' ,';
            system.debug('---street---'+street);
        }
        if(city != null && city != ''){
			address +=  city+' ,'; 
            system.debug('---city---'+city);
        }
        if(state != null && state != ''){
			address +=  state+' ,';  
            system.debug('---state---'+state);
        }
        if(postalCode != null && postalCode != ''){
			address +=  postalCode+' ,';  
            system.debug('---postalCode---'+postalCode);
        }
        if(country != null && country != ''){
			address +=  country+' ,';   
             system.debug('---country---'+country);
        }
        system.debug('---address---'+address);
        address = address.removeEnd(',');
        return address;
        
    }
}