force-app/main/default/objects/Account/fields/Project_Memberships__c.field-meta.xml
<CustomField>
    <fullName>Project_Memberships__c</fullName>
    <label>Project Memberships</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>a0941000002wBz2</fullName>
                <label>Automotive Grade Linux</label>
            </value>
            <value>
                <fullName>a092M00001G4R7x</fullName>
                <label>Chips Alliance Fund</label>
            </value>
            <value>
                <fullName>a0941000002wBz3</fullName>
                <label>Civil Infrastructure Platform</label>
            </value>
            <value>
                <fullName>a0941000011ABSNAA4</fullName>
                <label>Clearwater Pass</label>
            </value>
            <value>
                <fullName>a0941000002wBz5AAE</fullName>
                <label>Cloud Foundry Foundation, Inc. - Archived</label>
            </value>
            <value>
                <fullName>a0941000002wBz4AAE</fullName>
                <label>Cloud Native Computing Foundation (CNCF)</label>
            </value>
            <value>
                <fullName>a0941000002wBz6AAE</fullName>
                <label>Code Aurora Forum (CAF)</label>
            </value>
            <value>
                <fullName>a092M00001G3xhxQAB</fullName>
                <label>Continuous Delivery Foundation (CDF)</label>
            </value>
            <value>
                <fullName>a0941000002wBz7AAE</fullName>
                <label>Cord (Central Office Re-Architected As A Datacenter)</label>
            </value>
            <value>
                <fullName>a0941000002wBz8AAE</fullName>
                <label>Core Embedded Linux Project (CELP)</label>
            </value>
            <value>
                <fullName>a0941000002wBzAAAU</fullName>
                <label>Core Infrastructure Initiative (CII)</label>
            </value>
            <value>
                <fullName>a0941000002wBzBAAU</fullName>
                <label>DiaMon Workgroup</label>
            </value>
            <value>
                <fullName>a092M00001G5794QAB</fullName>
                <label>Decentralized Identity Foundation (DIF)</label>
            </value>
            <value>
                <fullName>a0941000005osNmAAI</fullName>
                <label>Data Plane Development Kit (DPDK)</label>
            </value>
            <value>
                <fullName>a0941000002wBzCAAU</fullName>
                <label>Dronecode Project, Inc.</label>
            </value>
            <value>
                <fullName>a0941000005osNnAAI</fullName>
                <label>EdgeX Foundry</label>
            </value>
            <value>
                <fullName>a094100001ETJINAA5</fullName>
                <label>ELISA Fund</label>
            </value>
            <value>
                <fullName>a092M00001IkOVaQAN</fullName>
                <label>FD.io</label>
            </value>
            <value>
                <fullName>a0941000002wByXAAU</fullName>
                <label>Fossology</label>
            </value>
            <value>
                <fullName>a092M00001G4R8CQAV</fullName>
                <label>GraphQL Foundation</label>
            </value>
            <value>
                <fullName>a0941000002wByYAAU</fullName>
                <label>Hyperledger</label>
            </value>
            <value>
                <fullName>a0941000002wByeAAE</fullName>
                <label>Internet Security Research Group (ISRG)</label>
            </value>
            <value>
                <fullName>a0941000002wByaAAE</fullName>
                <label>Iotivity</label>
            </value>
            <value>
                <fullName>a0941000002wByZAAU</fullName>
                <label>IO Visor Project</label>
            </value>
            <value>
                <fullName>a0941000002wBybAAE</fullName>
                <label>JanusGraph</label>
            </value>
            <value>
                <fullName>a092M00001G56cjQAB</fullName>
                <label>Joint Development Foundation</label>
            </value>
            <value>
                <fullName>a0941000002wBycAAE</fullName>
                <label>JSFoundation</label>
            </value>
            <value>
                <fullName>a094100001ESu1rAAD</fullName>
                <label>kernelCI Initiative Fund</label>
            </value>
            <value>
                <fullName>a0941000002wBydAAE</fullName>
                <label>Kinetic Open Storage Project</label>
            </value>
            <value>
                <fullName>a094100000I8WueAAF</fullName>
                <label>LF Asia, LLC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Processing__c.field-meta.xml
<CustomField>
    <fullName>Project_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Project Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchUpdateAccountPicklist.cls
public class BatchUpdateAccountPicklist implements Database.Batchable<sObject>,Schedulable, Database.AllowsCallouts {
    
    public void execute(SchedulableContext SC) {
        Database.executeBatch(new BatchUpdateAccountPicklist());
    } 
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        //Query those Project which are active and Project Processing is true
        return Database.getQueryLocator('Select id, Name,Status__c,Project_Processing__c From Project__c WHERE Project_Processing__c = True');
    }
    
    public void execute(Database.BatchableContext bc,List<Project__c> scope ){
        
        //Add Project name against Id in a Map for updating Account Picklist value.
		Map<Id,String> projectIdVSName= new Map<Id,String>();   
        for(Project__c proj :scope){
            proj.Project_Processing__c = false;
            projectIdVSName.put(proj.Id,proj.Name);
        }
        
        //Call MetaData Api for inserting Project Name in Account.Project_Memberships__c Picklist field.
        if(!projectIdVSName.isEmpty()){
            System.debug('projectIdVSName' +projectIdVSName);
            MetadataUpdatePicklist.updatePicklistField(projectIdVSName);
        }
        
        update scope;
    }
    
    public void finish(Database.BatchableContext bc){
        
    } 
    
}