force-app/main/default/objects/Account/fields/Sugar_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Sugar_Account_ID__c</fullName>
    <description>Legacy ID from Sugar CRM kept for reference</description>
    <externalId>true</externalId>
    <label>Sugar_Account_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SugarContactID__c.field-meta.xml
<CustomField>
    <fullName>SugarContactID__c</fullName>
    <externalId>true</externalId>
    <label>Sugar Contact ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/Original_Sugar_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_Sugar_ID__c</fullName>
    <label>Original Sugar ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/Sugar_EmailMessage_Id__c.field-meta.xml
<CustomField>
    <fullName>Sugar_EmailMessage_Id__c</fullName>
    <externalId>true</externalId>
    <label>Sugar EmailMessage Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RelateEmailMessageWithTheirParentTest.cls
@isTest
public class RelateEmailMessageWithTheirParentTest 
{
    @isTest public static void UpdateEmailMessagesTestMethod1()
    {
        
        Account acc=new Account();
        acc.Name='Peter';
        acc.Sugar_Account_ID__c='TestId2';
        insert acc;
        
        Contact con=new Contact();
        con.LastName='Parker';
        con.AccountId=acc.id;
        con.SugarContactID__c='TestId2';
        Insert con;
        
        EmailMessage em=new EmailMessage();
        em.Original_Sugar_ID__c='TestId1';
        em.Parent_Id__c ='TestId2';
        em.Sugar_EmailMessage_Id__c='TestId2';
        insert em;
        
        
        
        
    }
   
    
}