force-app/main/default/objects/Account/fields/Training_MSA_File_ID__c.field-meta.xml
<CustomField>
    <fullName>Training_MSA_File_ID__c</fullName>
    <label>Training MSA File ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Training Master Service Agreement</fullName>
            </value>
            <value>
                <fullName>Project Assignment Agreement</fullName>
            </value>
            <value>
                <fullName>Project Dissolution Document</fullName>
            </value>
            <value>
                <fullName>Project Governance Document</fullName>
            </value>
            <value>
                <fullName>Project Incorporation Document</fullName>
            </value>
            <value>
                <fullName>Project Management Services Agreement</fullName>
            </value>
            <value>
                <fullName>Project Series Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Related_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_ID__c</fullName>
    <label>Related Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Assignment_Agreement_URL__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Agreement_URL__c</fullName>
    <description>This field is applicable to Incorporated Entities, Subprojects, Series LLCs, and Unofficial Subprojects. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Assignment Agreement Link field on page layouts instead.)</description>
    <label>Assignment Agreement File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Dissolution_Document_URL__c.field-meta.xml
<CustomField>
    <fullName>Dissolution_Document_URL__c</fullName>
    <label>Dissolution Document File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Governance_Document_URL__c.field-meta.xml
<CustomField>
    <fullName>Governance_Document_URL__c</fullName>
    <description>This field is only applicable to Incorporated Entities. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Governance Document Link field on page layouts instead.)</description>
    <label>Governance Document File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/MasterServiceAgreementURL__c.field-meta.xml
<CustomField>
    <fullName>MasterServiceAgreementURL__c</fullName>
    <description>This field is only applicable to Incorporated Entities. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Management Services Agreement Link field on page layouts instead.)</description>
    <label>Management Services Agreement File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Entity_Formation_Document__c.field-meta.xml
<CustomField>
    <fullName>Project_Entity_Formation_Document__c</fullName>
    <description>This field is only applicable to Incorporated Entities. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Incorporation Document Link field on page layouts instead.)</description>
    <label>Incorporation Document File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Series_Agreement_URL__c.field-meta.xml
<CustomField>
    <fullName>Series_Agreement_URL__c</fullName>
    <description>This field is only applicable to Series LLCs. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Series Agreement Link field on page layouts instead.)</description>
    <label>Series Agreement File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ContentDocumentTriggerHandler.cls
public class ContentDocumentTriggerHandler implements ITriggerHandler {
    
    public static void BeforeInsert(List<SObject> triggerNew){
        //call before insert actions
    }

    public static void BeforeUpdate(Map<id,SObject> newContentDocument,Map<id,SObject> oldContentDocument){
        //call before update actions
    }

    public static void BeforeDelete(Map<Id, Sobject> oldMap){
        //call before delete actions
        clearFileIDFromRelatedRecords( (List<ContentDocument>)oldMap.values() );
    }

    public static void AfterInsert(Map<Id, SObject> newMap){
        //call after insert actions
    }

    public static void AfterUpdate(Map<Id, SObject> newMap, Map<Id, Sobject> oldMap){
        //call after update actions
    }

    public static void AfterDelete(Map<Id, Sobject> oldMap){
        //call after delete actions
    }

    public static void AfterUndelete(Map<Id, Sobject> newMap){
        //call after undelete actions
    }

    public Boolean IsDisabled(){
        return false;
    }

    public static void clearFileIDFromRelatedRecords(List<ContentDocument> deletedDocs){
        Set<Id> deletedDocIDs = (new Map<Id,ContentDocument>(deletedDocs)).keySet();
        List<ContentVersion> docVersions = new List<ContentVersion>();
        docVersions = [SELECT Related_Record_ID__c, Document_Type__c, ContentDocument.Id
                       FROM ContentVersion
                       WHERE ContentDocument.Id IN :deletedDocIDs
                       AND Related_Record_ID__c != null
                       AND Document_Type__c != null
                      ];

        if(docVersions.size() == 0){
            //no related record ID (or no document type) on deleted files,
            //so exit method
            return;
        }

        Set<ID> accountIDs = new Set<ID>();
        Set<ID> projectIDs = new Set<ID>();

        for(ContentVersion dv : docVersions){
            switch on dv.Document_Type__c {
                when 'Account Training Master Service Agreement' {
                    accountIDs.add(dv.Related_Record_ID__c);
                }
                when 'Project Assignment Agreement' {
                    projectIDs.add(dv.Related_Record_ID__c);
                }
                when 'Project Dissolution Document' {
                    projectIDs.add(dv.Related_Record_ID__c);
                }
                when 'Project Governance Document' {
                    projectIDs.add(dv.Related_Record_ID__c);
                }
                when 'Project Incorporation Document' {
                    projectIDs.add(dv.Related_Record_ID__c);
                }
                when 'Project Management Services Agreement' {
                    projectIDs.add(dv.Related_Record_ID__c);
                }
                when 'Project Series Agreement' {
                    projectIDs.add(dv.Related_Record_ID__c);
                }
            }
        }

        List<Account> accounts = new List<Account>();
        List<Project__c> projects = new List<Project__c>();

        if( accountIDs.size() > 0 ){
            accounts = [SELECT Training_MSA_File_ID__c
                        FROM Account
                        WHERE ID IN :accountIDs
                       ];
        }else if( projectIDs.size() > 0 ){
            projects = [SELECT Assignment_Agreement_URL__c, Dissolution_Document_URL__c,
                               Governance_Document_URL__c, Project_Entity_Formation_Document__c,
                               MasterServiceAgreementURL__c, Series_Agreement_URL__c
                        FROM Project__c
                        WHERE ID IN :projectIDs
                       ];
        }else{
            //exit method, since no accounts or projects were queried
            return;
        }

        Boolean accountsModified = false;
        Boolean projectsModified = false;

        for(ContentVersion dv : docVersions){

            if(dv.Document_Type__c.startsWith('Account ')){
                for(Account acc : accounts){
                    if( idsMatch(dv.ContentDocument.Id, acc.Training_MSA_File_ID__c) ){
                        acc.Training_MSA_File_ID__c = null;
                        accountsModified = true;
                    }
                }
            }else if(dv.Document_Type__c.startsWith('Project ')){
                for(Project__c proj : projects){
                    switch on dv.Document_Type__c {
                        when 'Project Assignment Agreement' {
                            if( idMatchesURL(dv.ContentDocument.Id, proj.Assignment_Agreement_URL__c) ){
                                proj.Assignment_Agreement_URL__c = null;
                                projectsModified = true;
                            }
                        }
                        when 'Project Dissolution Document' {
                            if( idMatchesURL(dv.ContentDocument.Id, proj.Dissolution_Document_URL__c) ){
                                proj.Dissolution_Document_URL__c = null;
                                projectsModified = true;
                            }
                        }
                        when 'Project Governance Document' {
                            if( idMatchesURL(dv.ContentDocument.Id, proj.Governance_Document_URL__c) ){
                                proj.Governance_Document_URL__c = null;
                                projectsModified = true;
                            }
                        }
                        when 'Project Incorporation Document' {
                            if( idMatchesURL(dv.ContentDocument.Id, proj.Project_Entity_Formation_Document__c) ){
                                proj.Project_Entity_Formation_Document__c = null;
                                projectsModified = true;
                            }
                        }
                        when 'Project Management Services Agreement' {
                            if( idMatchesURL(dv.ContentDocument.Id, proj.MasterServiceAgreementURL__c) ){
                                proj.MasterServiceAgreementURL__c = null;
                                projectsModified = true;
                            }
                        }
                        when 'Project Series Agreement' {
                            if( idMatchesURL(dv.ContentDocument.Id, proj.Series_Agreement_URL__c) ){
                                proj.Series_Agreement_URL__c = null;
                                projectsModified = true;
                            }
                        }
                    }
                }
            }
        }

        if(accountsModified){
            update accounts;
        }

        if(projectsModified){
            update projects;
        }

        return;
    }

    private static Boolean idsMatch(ID fileID, String fileIDOnRelatedRecord){
        if( get18DigitIDString(fileIDOnRelatedRecord).equals(fileID) ){
            return true;
        }else{
            return false;
        }
    }

    private static Boolean idMatchesURL(ID fileID, String urlOnRelatedRecord){
        //get ID from URL on Related Record
        String urlBeginning = URL.getSalesforceBaseUrl().toExternalForm() + '/lightning/r/ContentDocument/';
        String idString = urlOnRelatedRecord.removeEnd('/view').removeStart(urlBeginning);
        return idsMatch(fileID, idString);
    }

    private static String get18DigitIDString(String idString){
        //get 18-digit ID, even if the 15-digit ID was provided
        if( idString.length() == 15 ){
            Id idValue = idString;
            String idString18 = idValue;
            return idString18;
        }else{
            return idString;
        }
    }

}