force-app/main/default/objects/Account/fields/Training_MSA_File_ID__c.field-meta.xml
<CustomField>
    <fullName>Training_MSA_File_ID__c</fullName>
    <label>Training MSA File ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Assignment_Agreement_URL__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Agreement_URL__c</fullName>
    <description>This field is applicable to Incorporated Entities, Subprojects, Series LLCs, and Unofficial Subprojects. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Assignment Agreement Link field on page layouts instead.)</description>
    <label>Assignment Agreement File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Dissolution_Document_URL__c.field-meta.xml
<CustomField>
    <fullName>Dissolution_Document_URL__c</fullName>
    <label>Dissolution Document File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Do_not_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Do_not_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, memberships will not be invoiced</inlineHelpText>
    <label>Do not Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Governance_Document_URL__c.field-meta.xml
<CustomField>
    <fullName>Governance_Document_URL__c</fullName>
    <description>This field is only applicable to Incorporated Entities. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Governance Document Link field on page layouts instead.)</description>
    <label>Governance Document File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/MasterServiceAgreementURL__c.field-meta.xml
<CustomField>
    <fullName>MasterServiceAgreementURL__c</fullName>
    <description>This field is only applicable to Incorporated Entities. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Management Services Agreement Link field on page layouts instead.)</description>
    <label>Management Services Agreement File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Parent_Entity_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Parent_Entity_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Incorporated Entity or Series LLC that is the legal parent of the project.</inlineHelpText>
    <label>Legal Parent</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Child Projects of Legal Entity</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Entity_Formation_Document__c.field-meta.xml
<CustomField>
    <fullName>Project_Entity_Formation_Document__c</fullName>
    <description>This field is only applicable to Incorporated Entities. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Incorporation Document Link field on page layouts instead.)</description>
    <label>Incorporation Document File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <inlineHelpText>The &quot;Prospect&quot; stage is reserved for non-LF projects, e.g. some Community Bridge projects.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Formation - Exploratory</fullName>
            </value>
            <value>
                <fullName>Formation - Engaged</fullName>
            </value>
            <value>
                <fullName>Formation - Confidential</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Formation - On Hold</fullName>
            </value>
            <value>
                <fullName>Formation - Disengaged</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Actively Engaged</fullName>
                <isActive>false</isActive>
                <label>Actively Engaged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Series_Agreement_URL__c.field-meta.xml
<CustomField>
    <fullName>Series_Agreement_URL__c</fullName>
    <description>This field is only applicable to Series LLCs. This field should not be included on the page layout for most users, since it stores the URL of a file uploaded to the Project Control Center. (Use the Series Agreement Link field on page layouts instead.)</description>
    <label>Series Agreement File URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocumentTriggerHandlerTest.cls
@isTest
private class ContentDocumentTriggerHandlerTest {
    
    @isTest static void testRegularFileDelete() {
        //prep data
        Id fileID = createFile();
        
        //delete file
        deleteFile(fileID);
        
        //verify file was deleted
        Boolean wasDeleted = verifyFileDelete(fileID);
        System.assertEquals(true, wasDeleted);
    }
    
    @isTest static void testProjectSeriesAgreementDelete() {
        //prep data
        Id fileID = createFile();
        Id projID = createSeriesLLC();
        Date seriesAgreementDate = Date.newInstance(2000, 12, 31);
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'series', seriesAgreementDate);
        
		//delete file
		deleteFile(fileID);
        
        //verify file was deleted
        Boolean wasDeleted = verifyFileDelete(fileID);
        System.assertEquals(true, wasDeleted);
        
        //verify Series Agreement URL field on Project was cleared out
        Project__c proj = new Project__c();
        proj = [SELECT Series_Agreement_URL__c FROM Project__c WHERE ID = :projID];
        System.assertEquals(null, proj.Series_Agreement_URL__c);
	}
    
    @isTest static void testProjectAssignmentAgreementDelete() {
        //prep data
        Id fileID = createFile();
        Id projID = createSeriesLLC();
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'assignment', null);
        
        //delete file
        deleteFile(fileID);
        
        //verify file was deleted
        Boolean wasDeleted = verifyFileDelete(fileID);
        System.assertEquals(true, wasDeleted);
        
        //verify Assignment Agreement URL field on Project was cleared out
        Project__c proj = new Project__c();
        proj = [SELECT Assignment_Agreement_URL__c FROM Project__c WHERE ID = :projID];
        System.assertEquals(null, proj.Assignment_Agreement_URL__c);
	}
    
    @isTest static void testProjectIncorporationDocumentDelete() {
        //prep data
        Id fileID = createFile();
        Id projID = createIncorporatedProject();
        Date incorporationDocumentDate = Date.newInstance(2000, 12, 31);
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'incorporation', incorporationDocumentDate);
        
        //delete file
        deleteFile(fileID);
        
        //verify file was deleted
        Boolean wasDeleted = verifyFileDelete(fileID);
        System.assertEquals(true, wasDeleted);
        
        //verify Incorporation Document URL field on Project was cleared out
        Project__c proj = new Project__c();
        proj = [SELECT Project_Entity_Formation_Document__c FROM Project__c WHERE ID = :projID];
        System.assertEquals(null, proj.Project_Entity_Formation_Document__c);
	}
    
    @isTest static void testProjectMSADelete() {
        //prep data
        Id fileID = createFile();
        Id projID = createIncorporatedProject();
        Date msaDate = Date.newInstance(2000, 12, 31);
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'msa', msaDate);
        
        //delete file
        deleteFile(fileID);
        
        //verify file was deleted
        Boolean wasDeleted = verifyFileDelete(fileID);
        System.assertEquals(true, wasDeleted);
        
        //verify Management Services Agreement URL field on Project was cleared out
        Project__c proj = new Project__c();
        proj = [SELECT MasterServiceAgreementURL__c FROM Project__c WHERE ID = :projID];
        System.assertEquals(null, proj.MasterServiceAgreementURL__c);
	}
    
    @isTest static void testProjectGovernanceDocumentDelete() {
        //prep data
        Id fileID = createFile();
        Id projID = createIncorporatedProject();
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'governance', null);
        
        //delete file
        deleteFile(fileID);
        
        //verify file was deleted
        Boolean wasDeleted = verifyFileDelete(fileID);
        System.assertEquals(true, wasDeleted);
        
        //verify Governance Document URL field on Project was cleared out
        Project__c proj = new Project__c();
        proj = [SELECT Governance_Document_URL__c FROM Project__c WHERE ID = :projID];
        System.assertEquals(null, proj.Governance_Document_URL__c);
	}
    
    @isTest static void testProjectDissolutionDocumentDelete() {
        //prep data
        Id fileID = createFile();
        Id projID = createIncorporatedProject();
        Date dissolutionDocumentDate = Date.newInstance(2000, 12, 31);
		ProjectFileUploadController.updateProjectAndFile(projID, fileID, 'dissolution', dissolutionDocumentDate);
        
        //delete file
        deleteFile(fileID);
        
        //verify file was deleted
        Boolean wasDeleted = verifyFileDelete(fileID);
        System.assertEquals(true, wasDeleted);
        
        //verify Dissolution Document URL field on Project was cleared out
        Project__c proj = new Project__c();
        proj = [SELECT Dissolution_Document_URL__c FROM Project__c WHERE ID = :projID];
        System.assertEquals(null, proj.Dissolution_Document_URL__c);
	}
    
    @isTest static void testAccountMSADelete() {
        //prep data
        Id fileID = createFile();
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Website = 'testaccount.com';
        insert acc;
        AccountTrainingMSAController.addFileIDToAccount(acc.Id, fileID);
        
        //delete file
        deleteFile(fileID);
        
        //verify file was deleted
        Boolean wasDeleted = verifyFileDelete(fileID);
        System.assertEquals(true, wasDeleted);
        
        //verify Training MSA File ID field on Account was cleared out
        Account acc2 = new Account();
        acc2 = [SELECT Training_MSA_File_ID__c FROM Account WHERE ID = :acc.Id];
        System.assertEquals(null, acc2.Training_MSA_File_ID__c);
    }
    
    @isTest static void testAccountMSADelete15Digit() {
        //repeats Account MSA delete test, but this time with a 15-digit
        //ID in the Training_MSA_File_ID__c field (instead of the 18-digit
        //ID this field will typically have)
        
        //prep initial data
        Id fileID = createFile();
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Website = 'testaccount.com';
        insert acc;
        AccountTrainingMSAController.addFileIDToAccount(acc.Id, fileID);
        
        //query 18-digit ID currently in the Training MSA File ID
        Account acc2 = new Account();
        acc2 = [SELECT Training_MSA_File_ID__c FROM Account WHERE ID = :acc.Id];
        
        //update 18-digit ID (string) to a 15-digit ID (string)
        Integer currentLength = acc2.Training_MSA_File_ID__c.length();
        String fifteenDigitID;
        if(currentLength == 18){
            fifteenDigitID = acc2.Training_MSA_File_ID__c.substring(0, 15);
        }
        
        //confirm this is now 15 digits to ensure a proper test
        System.assertEquals(15, fifteenDigitID.length());
        
        //update the Account MSA field with the 15-digit ID
        acc2.Training_MSA_File_ID__c = fifteenDigitID;
        update acc2;
        
        //delete file
        deleteFile(fileID);
        
        //verify file was deleted
        Boolean wasDeleted = verifyFileDelete(fileID);
        System.assertEquals(true, wasDeleted);
        
        //verify Training MSA File ID field on Account was cleared out
        Account acc3 = new Account();
        acc3 = [SELECT Training_MSA_File_ID__c FROM Account WHERE ID = :acc.Id];
        System.assertEquals(null, acc3.Training_MSA_File_ID__c);
    }
    
    private static ID createFile(){
        //create new Content Version
        ContentVersion cv = new ContentVersion();
        cv.VersionData = Blob.valueOf('Test Content Data');
        cv.Title = 'test file';
        cv.PathOnClient = 'test.pdf';
        insert cv;
        
        //query new Content Version to get ContentDocumentId from it
        ContentVersion uploadedFile = new ContentVersion();
        uploadedFile = [SELECT ContentDocumentId
                        FROM ContentVersion
                        WHERE Id = :cv.Id];
        
        return uploadedFile.ContentDocumentId;
    }
    
    private static Id createSeriesLLC(){
        //Project
        Project__c prj = new Project__c(Name = 'LF Projects, LLC',Slug__c='lfproject', Do_not_Invoice__c = true,Status__c = 'Planned',Category__c = 'Subproject');
        insert prj;

        Project__c seriesLLC = new Project__c();
        seriesLLC.Name = 'Test Series LLC';
        seriesLLC.Project_Status__c = 'Formation - Exploratory';
        seriesLLC.Category__c = 'Series LLC';
        seriesLLC.Slug__c = 'test-series-llc';
        seriesLLC.Parent_Entity_Relationship__c = prj.Id;
        insert seriesLLC;
        return seriesLLC.Id;
    }
    
    private static Id createIncorporatedProject(){
        Project__c inc = new Project__c();
        inc.Name = 'Test Inc';
        inc.Project_Status__c = 'Formation - Exploratory';
        inc.Category__c = 'Incorporated Project';
        inc.Slug__c = 'test-inc';
        insert inc;
        return inc.Id;
    }
    
    private static void deleteFile(ID fileID){
        ContentDocument file = new ContentDocument();
        file = [SELECT Id FROM ContentDocument WHERE Id = :fileID];
        delete file;
        return;
    }
    
    private static Boolean verifyFileDelete(ID fileID){
        List<ContentDocument> files = new List<ContentDocument>();
        files = [SELECT Id FROM ContentDocument WHERE Id = :fileID];
        if(files.size() == 0){
            return true;
        }else{
            return false;
        }
    }

}