force-app/main/default/objects/Account/fields/Training_MSA_File_ID__c.field-meta.xml
<CustomField>
    <fullName>Training_MSA_File_ID__c</fullName>
    <label>Training MSA File ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Training Master Service Agreement</fullName>
            </value>
            <value>
                <fullName>Project Assignment Agreement</fullName>
            </value>
            <value>
                <fullName>Project Dissolution Document</fullName>
            </value>
            <value>
                <fullName>Project Governance Document</fullName>
            </value>
            <value>
                <fullName>Project Incorporation Document</fullName>
            </value>
            <value>
                <fullName>Project Management Services Agreement</fullName>
            </value>
            <value>
                <fullName>Project Series Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Related_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_ID__c</fullName>
    <label>Related Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTrainingMSAController.cls
public with sharing class AccountTrainingMSAController {

    @AuraEnabled
    public static void addFileIDToAccount(Id accountID, Id fileID) {
        Account acc = [SELECT Name, Training_MSA_File_ID__c
                       FROM Account
                       WHERE Id = :accountID];
        acc.Training_MSA_File_ID__c = fileID;
        update acc;

        ContentVersion file = [SELECT Title, CreatedDate
                               FROM ContentVersion
                               WHERE ContentDocumentId = :fileID
                               ORDER BY CreatedDate DESC
                               LIMIT 1];
        file.Description = file.Title; //preserve original document name in the Description field
        file.Title = 'Training MSA: ' + acc.Name; //standardize titles of all Training MSAs
        file.Document_Type__c = 'Account Training Master Service Agreement';
        file.Related_Record_ID__c = accountID;
        update file;
    }

}