force-app/main/default/objects/EmailIdforbatch__c/EmailIdforbatch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Email Id for batch</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Emailcustom</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mixmax_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Mixmax_Campaign_Name__c</fullName>
    <label>Mixmax Campaign Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/MixMax_Create_Campaign__c.field-meta.xml
<CustomField>
    <fullName>MixMax_Create_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked, we are yet to create MixMax campaign for this Lead. It will be created within and hour.</description>
    <inlineHelpText>This will identify whether campaign and campaign member needs to be created or not?</inlineHelpText>
    <label>MixMax Create Campaign?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CreateMixMaxCampaignForLeadBatch_Test.cls
/**
 * Test class for CreateMixMaxCampaignForLeadBatch
 */
@isTest
public class CreateMixMaxCampaignForLeadBatch_Test{
    
	/**
	 * TestSetup inserting required data for test class
	 */
	@TestSetup
	static void createTestData(){
		Lead objLead = new Lead(lastname = 'Test Contact', Email = 'test@lead.com',
                                Mixmax_Campaign_Name__c = 'My Campaign 001', MixMax_Create_Campaign__c = true);
		insert objLead;
		EmailIdforbatch__c objEmail = new EmailIdforbatch__c();
		objEmail.Name = 'Pratik';
		objEmail.Email__c = 'pratikd@proximabiz.com';
		insert objEmail;
	}

	/**
	 * executeBatch_Test : Test Method for batch class
	 */
	@isTest
	static void executeBatch_Test(){
		Lead lead = [SELECT Id
		             FROM Lead
		             LIMIT 1];
        
        //Test
		Test.startTest();
		CreateMixMaxCampaignForLeadBatch c = new CreateMixMaxCampaignForLeadBatch();
		Database.executeBatch(c);
		Test.stopTest();
        
        //Asserts
		System.assertEquals(true, ![SELECT Id
		                            FROM CampaignMember
		                            WHERE LeadId = :lead.Id].isEmpty(),'List must not be empty');
	}
}