force-app/main/default/objects/Endpoints__c/Endpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Endpoints</label>
</CustomObject>

force-app/main/default/objects/Product2/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Netsuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>NS Item ID</inlineHelpText>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Name_Override__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Name_Override__c</fullName>
    <label>NetSuite Name Override</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
            <value>
                <fullName>Straight Line</fullName>
                <isActive>false</isActive>
                <label>Straight Line</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <formula>IF(Project__c != null ,Project__r.Subsidiary_ID__c , Event__r.BillFromProject__r.Subsidiary_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Product_Details__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A one-sentence description of the project, which will be used for external facing (i.e. landscape graphic or a website list of LF projects) descriptions of projects.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/job_Code__c.field-meta.xml
<CustomField>
    <fullName>job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Deferred_Revenue_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>284</fullName>
        <label>Deferred Revenue : Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>282</fullName>
        <label>Deferred Revenue : Deferred Revenue - Membership</label>
    </customValue>
    <customValue>
        <fullName>4494</fullName>
        <label>Deferred Revenue : Deferred Revenue - Directed Funds</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Other</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Membership</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Membership</label>
    </customValue>
    <masterLabel>NetSuite Deferred Revenue Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NetSuite_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Events</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Training</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Training (Linux Labs)</label>
    </customValue>
    <masterLabel>NetSuite Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CallOutToNetSuiteTrigger_Test.cls
@isTest
private class CallOutToNetSuiteTrigger_Test{
	/**
	 * TestSetup inserting required data for test class
	 */
	@TestSetup
	static void createTestData(){

		Endpoints__c endPoint = new Endpoints__c();
		endPoint.name = 'For Product Details';
		endPoint.endpoint__c = 'https://rest.sandbox.netsuite.com/app/site/hosting/restlet.nl?script=86&deploy=11';
		insert endPoint;
		Product2 prod = TestDataUtils.createProduct(true, 'Test_Prod', 'Test Product', true, 'Membership');
		Project__c project = TestDataUtils.createProject(false, 'testing11', 'Membership', 'Directed Fund', 'Planned');
		project.Subsidiary_ID__c = 8;
		insert project;
	}

	/**
	 * Test Methods for CalloutToNetsuoteTrigger with different scenarios
	 */
	@isTest
	static void updateProdDetails_Test(){
		Product2 product = [SELECT Id
		                    FROM Product2
		                    WHERE Name = 'Test_Prod'];
		Product_Details__c prodDetail = new Product_Details__c();
		prodDetail.Products__c = product.id;
		prodDetail.Price__c = 56;
		prodDetail.NS_Income_GL_Account__c = 'Membership Dues : Platinum Membership';
		prodDetail.NS_Deferred_Revenue_Account__c = '284';
		prodDetail.NS_Department__c = '10';
		prodDetail.NS_Revenue_Schedule__c = '29';
		prodDetail.Netsuite_Sync__c = false;
		prodDetail.Duration__c = '45';
		prodDetail.Description__c = 'Description_Test';
		prodDetail.Tier__c = 'Test';
		prodDetail.Job_Code__c = 'test';
		prodDetail.NetSuite_Class__c = 'test';
		prodDetail.NetSuite_Name_Override__c = 'test';
		insert prodDetail;

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new CallOutToNetSuiteMockHttp());

		prodDetail.Netsuite_Sync__c = true;
		update prodDetail;

		Test.stopTest();

		//Asserts
		System.assertEquals('12345',[SELECT Netsuite_ID__c
		                     FROM Product_Details__c
		                     WHERE Id = :prodDetail.Id].Netsuite_ID__c, 'NetsuiteId must be 12345');
	}

	@isTest
	static void updateProdDetails1_Test(){

		Product2 product = [SELECT Id
		                    FROM Product2
		                    WHERE Name = 'Test_Prod'];

		Product_Details__c prodDetail = new Product_Details__c();
		prodDetail.Products__c = product.id;
		prodDetail.Price__c = 56;
		prodDetail.NS_Income_GL_Account__c = 'Membership Dues : Platinum Membership';
		prodDetail.NS_Deferred_Revenue_Account__c = '284';
		prodDetail.NS_Department__c = '10';
		prodDetail.NS_Revenue_Schedule__c = '29';
		prodDetail.Netsuite_Sync__c = false;
		prodDetail.Duration__c = '45';
		prodDetail.Description__c = 'Description_Test';
		prodDetail.Tier__c = 'Test';
		insert prodDetail;

		prodDetail.Netsuite_Sync__c = true;
		update prodDetail;

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new CallOutToNetSuiteMockHttp());
		//Manually called this method for coverage
		
        set <string> prodDetailIDSet = new set <string>();
        prodDetailIDSet.add(prodDetail.id);
        Database.executebatch(new BatchForProjectEvent(prodDetailIDSet));
		//NSProductDetailHelper.mappingFromSFToNSThroughBatch(prodDetail.id);
		Test.stopTest();

		//Asserts
		System.assertEquals('12345',[SELECT Netsuite_ID__c
		                     FROM Product_Details__c
		                     WHERE Id = :prodDetail.Id].Netsuite_ID__c,'NetsuiteId must be 12345');
	}

	@isTest
	static void updateProdDetails2_Test(){

		Product2 product = [SELECT Id
		                    FROM Product2
		                    WHERE Name = 'Test_Prod'];
		Project__c project = [SELECT Id
		                      FROM Project__c
		                      WHERE Name = 'testing11'];
		Product_Details__c prodDetail = new Product_Details__c();
		prodDetail.RecordTypeId = Schema.SObjectType.Product_Details__c.getRecordTypeInfosByName().get('Training').getRecordTypeId();
		prodDetail.Products__c = product.id;
		prodDetail.Price__c = 56;
		prodDetail.Project__c = project.id;
		prodDetail.NS_Income_GL_Account__c = '290';
		prodDetail.NS_Deferred_Revenue_Account__c = '284';
		prodDetail.NS_Department__c = '10';
		prodDetail.NS_Revenue_Schedule__c = '29';
		prodDetail.Netsuite_Sync__c = false;
		prodDetail.Duration__c = '45';
		prodDetail.Netsuite_ID__c = '123456';
		prodDetail.Description__c = 'Description_Test';
		prodDetail.Tier__c = 'Test';
		prodDetail.NetSuite_Class__c = '';
		insert prodDetail;

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new CallOutToNetSuiteMockHttp());

		prodDetail.Netsuite_Sync__c = true;
		update prodDetail;

		Test.stopTest();

		//Asserts
		System.assertEquals('12345',[SELECT Netsuite_ID__c
		                     FROM Product_Details__c
		                     WHERE Id = :prodDetail.Id].Netsuite_ID__c,'NetsuiteId must be 12345');
	}

	@isTest
	public static void updateProdDetails3_Test(){

		Product2 product = [SELECT Id
		                    FROM Product2
		                    WHERE Name = 'Test_Prod'];
		Project__c project = [SELECT Id
		                      FROM Project__c
		                      WHERE Name = 'testing11'];

		Product_Details__c prodDetail = new Product_Details__c();
		prodDetail.RecordTypeId = Schema.SObjectType.Product_Details__c.getRecordTypeInfosByName().get('Training').getRecordTypeId();
		prodDetail.Products__c = product.id;
		prodDetail.Price__c = 56;
		prodDetail.Project__c = project.id;
		prodDetail.NS_Income_GL_Account__c = '290';
		prodDetail.NS_Deferred_Revenue_Account__c = '284';
		prodDetail.NS_Department__c = '10';
		prodDetail.NS_Revenue_Schedule__c = '29';
		prodDetail.Netsuite_Sync__c = false;
		prodDetail.NetSuite_Class__c = '';
		prodDetail.Job_Code__c = '123';
		prodDetail.Duration__c = '45';
		prodDetail.Netsuite_ID__c = '123456';
		prodDetail.Description__c = 'Description_Test';
		prodDetail.Tier__c = 'Test';
		insert prodDetail;

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new CallOutToNetSuiteMockHttp());

		prodDetail.Netsuite_Sync__c = true;
		update prodDetail;

		Test.stopTest();

		//Asserts
		System.assertEquals('12345',[SELECT Netsuite_ID__c
		                     FROM Product_Details__c
		                     WHERE Id = :prodDetail.Id].Netsuite_ID__c,'NetsuiteId must be 12345');
	}

	/**
	 * Test Methods for getting error if different Fields having null value
	 */
	@isTest
	public static void getErrors_Test(){

		List<Product2> productListToInsert = new List<Product2>();
		for (Integer i = 0; i < 10; i++){
			Product2 prod = new Product2();
			prod.name = 'Test_Prod' + i;
			prod.Family = 'Membership';
			productListToInsert.add(prod);
		}
		insert productListToInsert;
		Product2 product = [SELECT Id
		                    FROM Product2
		                    WHERE Name = 'Test_Prod'];
		Project__c project = [SELECT Id
		                      FROM Project__c
		                      WHERE Name = 'testing11'];

		List<Product_Details__c> productDetailListToInsert = new List<Product_Details__c>();
		for (Integer i = 0; i < 10; i++){
			Product_Details__c prodDetail = new Product_Details__c();
			prodDetail.RecordTypeId = Schema.SObjectType.Product_Details__c.getRecordTypeInfosByName().get('Training').getRecordTypeId();
			prodDetail.Products__c = productListToInsert[i].id;
			prodDetail.Price__c = 56;
			prodDetail.Project__c = project.id;
			prodDetail.NS_Income_GL_Account__c = '290';
			prodDetail.NS_Deferred_Revenue_Account__c = '284';
			prodDetail.NS_Department__c = '10';
			prodDetail.NS_Revenue_Schedule__c = '29';
			prodDetail.Netsuite_Sync__c = false;
			prodDetail.NetSuite_Class__c = '';
			prodDetail.Job_Code__c = '123';
			prodDetail.Duration__c = '45';
			prodDetail.Netsuite_ID__c = '123456';
			prodDetail.Description__c = 'Description_Test';
			prodDetail.Tier__c = 'Test';
			productDetailListToInsert.add(prodDetail);

		}
		//Price Null
		Product_Details__c prodDetail = new Product_Details__c();
		prodDetail.Products__c = product.id;
		prodDetail.Project__c = project.id;
		prodDetail.NS_Income_GL_Account__c = '290';
		prodDetail.NS_Deferred_Revenue_Account__c = '284';
		prodDetail.NS_Department__c = '10';
		prodDetail.NS_Revenue_Schedule__c = '29';
		prodDetail.Netsuite_Sync__c = false;
		prodDetail.NetSuite_Class__c = '';
		prodDetail.Job_Code__c = '123';
		prodDetail.Duration__c = '45';
		prodDetail.Netsuite_ID__c = '123456';
		prodDetail.Description__c = 'Description_Test';
		prodDetail.Tier__c = 'Test';
		prodDetail.Netsuite_Sync__c = true;
		productDetailListToInsert.add(prodDetail);

		//Products__c Null
		Product_Details__c prodDetail1 = new Product_Details__c();
		prodDetail1.Price__c = 56;
		prodDetail1.Project__c = project.id;
		prodDetail1.NS_Income_GL_Account__c = '290';
		prodDetail1.NS_Deferred_Revenue_Account__c = '284';
		prodDetail1.NS_Department__c = '10';
		prodDetail1.NS_Revenue_Schedule__c = '29';
		prodDetail1.Netsuite_Sync__c = false;
		prodDetail1.NetSuite_Class__c = '';
		prodDetail1.Job_Code__c = '123';
		prodDetail1.Duration__c = '45';
		prodDetail1.Netsuite_ID__c = '123456';
		prodDetail1.Description__c = 'Description_Test';
		prodDetail1.Tier__c = 'Test';
		prodDetail1.Netsuite_Sync__c = true;
		productDetailListToInsert.add(prodDetail1);

		Database.insert(productDetailListToInsert, false);

		List<Product_Details__c> productDetailListToUpdate = new List<Product_Details__c>();

		productDetailListToInsert[0].Netsuite_Sync__c = true;
		productDetailListToInsert[0].price__c = null;
		productDetailListToUpdate.add(productDetailListToInsert[0]);

		productDetailListToInsert[2].Netsuite_Sync__c = true;
		productDetailListToInsert[2].NS_Income_GL_Account__c = null;
		productDetailListToUpdate.add(productDetailListToInsert[2]);


		productDetailListToInsert[3].Netsuite_Sync__c = true;
		productDetailListToInsert[3].NS_Deferred_Revenue_Account__c = null;
		productDetailListToUpdate.add(productDetailListToInsert[3]);


		productDetailListToInsert[4].Netsuite_Sync__c = true;
		productDetailListToInsert[4].NS_Revenue_Schedule__c = null;
		productDetailListToUpdate.add(productDetailListToInsert[4]);

		productDetailListToInsert[5].Netsuite_Sync__c = true;
		productDetailListToInsert[5].Products__c = null;
		productDetailListToUpdate.add(productDetailListToInsert[5]);

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new CallOutToNetSuiteMockHttp());

		List<Database.SaveResult> saveResultsList = Database.update(productDetailListToUpdate, false);

		//AssertsTest.stopTest();
		System.assertEquals(false, saveResultsList[0].isSuccess(),'Updation of product detail must be successful');
	}
}