force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Alternate Bill to Name and Address</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alternate Bill to Name and Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>if(LEN(Street__c )&gt;0, Street__c &amp; &quot; &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN(City__c )&gt;0, City__c &amp; &quot;, &quot; , &quot;&quot; )&amp;
if(LEN(State__c )&gt;0, State__c &amp; &quot; &quot; , &quot;&quot; )&amp;
if(LEN(Zip_Postal_Code__c )&gt;0, Zip_Postal_Code__c,&quot;&quot;) &amp; BR() &amp;
If(LEN(Country__c) &gt;0,Country__c ,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Bill_to_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Address__c</fullName>
    <description>Created for DocuSign to show billing address in single line.</description>
    <formula>SUBSTITUTE(

SUBSTITUTE(

IF(
   ISBLANK(Street__c),
   &quot;&quot;,
   Street__c + &quot;, &quot;
  )
+
IF(
   ISBLANK(City__c),
   &quot;&quot;,
   IF(
      ISBLANK(State__c),
      City__c + &quot; &quot;,
      City__c + &quot;, &quot;
     )
  )
+
IF(
   ISBLANK(State__c),
   &quot;&quot;,
   State__c + &quot; &quot;
  )
+
IF(
   ISBLANK(Zip_Postal_Code__c),
   &quot;&quot;,
   Zip_Postal_Code__c
  )
+
IF(
   ISBLANK(Country__c),
   &quot;&quot;,
   IF(
      ISBLANK(Zip_Postal_Code__c),
      IF(
         ISBLANK(State__c),
         &quot; &quot; + Country__c,
         &quot;, &quot; + Country__c
        ),
      &quot;, &quot; + Country__c
     )
  )

/* removes any spaces that immediately precede a comma, so &quot;Madrid , Spain&quot; would become &quot;Madrid, Spain&quot; */
, &quot; ,&quot;, &quot;,&quot;)


/* removes any double commas and replaces them with a single comma, so &quot;Madrid,, Spain&quot; would become &quot;Madrid, Spain&quot; */
, &quot;,,&quot;, &quot;,&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill to Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Use if bill to address is different from Account Name billing Address. You can find addresses under Bill to Name and Address under Account</inlineHelpText>
    <label>Bill to Name and address</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_To_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BillToAddressesOnOppController.cls
public with sharing class BillToAddressesOnOppController {

    @AuraEnabled(cacheable=true)
    public static List<Address__c> getBillToAddresses(ID oppID) {
        Opportunity opp = [SELECT AccountId FROM Opportunity WHERE Id = :oppID LIMIT 1];
        List<Address__c> addresses = new List<Address__c>();
        addresses = [SELECT Name, Street__c, City__c, State__c, Zip_Postal_Code__c, Country__c
                     FROM Address__c
                     WHERE Account__c = :opp.AccountId];
        return addresses;
    }

    @AuraEnabled(cacheable=true)
    public static ID getBillToAddress(ID oppID) {
        Opportunity opp = [SELECT Bill_To_Address__c FROM Opportunity WHERE Id = :oppID LIMIT 1];
        return opp.Bill_To_Address__c;
    }

    @AuraEnabled
    public static void saveSelectedAddress(ID oppID, ID addrID){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Id = :oppID LIMIT 1];
        opp.Bill_To_Address__c = addrID;
        update opp;
    }

    @AuraEnabled
    public static void clearBillToAddress(ID oppID){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Id = :oppID LIMIT 1];
        opp.Bill_To_Address__c = null;
        update opp;
    }

}