force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Alternate Bill to Name and Address</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alternate Bill to Name and Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Bill_to_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Address__c</fullName>
    <description>Created for DocuSign to show billing address in single line.</description>
    <formula>SUBSTITUTE(

SUBSTITUTE(

IF(
   ISBLANK(Street__c),
   &quot;&quot;,
   Street__c + &quot;, &quot;
  )
+
IF(
   ISBLANK(City__c),
   &quot;&quot;,
   IF(
      ISBLANK(State__c),
      City__c + &quot; &quot;,
      City__c + &quot;, &quot;
     )
  )
+
IF(
   ISBLANK(State__c),
   &quot;&quot;,
   State__c + &quot; &quot;
  )
+
IF(
   ISBLANK(Zip_Postal_Code__c),
   &quot;&quot;,
   Zip_Postal_Code__c
  )
+
IF(
   ISBLANK(Country__c),
   &quot;&quot;,
   IF(
      ISBLANK(Zip_Postal_Code__c),
      IF(
         ISBLANK(State__c),
         &quot; &quot; + Country__c,
         &quot;, &quot; + Country__c
        ),
      &quot;, &quot; + Country__c
     )
  )

/* removes any spaces that immediately precede a comma, so &quot;Madrid , Spain&quot; would become &quot;Madrid, Spain&quot; */
, &quot; ,&quot;, &quot;,&quot;)


/* removes any double commas and replaces them with a single comma, so &quot;Madrid,, Spain&quot; would become &quot;Madrid, Spain&quot; */
, &quot;,,&quot;, &quot;,&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill to Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>To describe purpose of this address, i.e. Japan Office or to be used for HPL invoices, etc.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</description>
    <inlineHelpText>The asset was billed to an Account other than the receiving Account (e.g. an parent company is sponsoring a subsidiary).</inlineHelpText>
    <label>Billing Account Override</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Address</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Bill To Address selected must be associated with the Account selected.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Address__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/NetSuite_Location__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Location__c</fullName>
    <label>NetSuite Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Asset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <label>OpportunityLineItem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Skip_NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>Skip_NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the membership/sponsorship/training items are to be billed to an Account other than the receiving Account.</description>
    <inlineHelpText>If the membership/sponsorship/training items are to be billed to an Account other than the receiving Account.</inlineHelpText>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Use if bill to address is different from Account Name billing Address. You can find addresses under Bill to Name and Address under Account</inlineHelpText>
    <label>Bill to Name and address</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_To_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Text that will be displayed on invoice</description>
    <inlineHelpText>Text that will be displayed on invoice</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Skip_NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>Skip_NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When selected, the Purchase History that is created from this line item will not be sent to NetSuite. You probably don&apos;t want this.</description>
    <inlineHelpText>When selected, the Purchase History that is created from this line item will not be sent to NetSuite. You probably don&apos;t want this.</inlineHelpText>
    <label>Skip NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Required</inlineHelpText>
    <label>Start Date*</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Netsuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>NS Item ID</inlineHelpText>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <formula>IF(Project__c != null ,Project__r.Subsidiary_ID__c , Event__r.BillFromProject__r.Subsidiary_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A one-sentence description of the project, which will be used for external facing (i.e. landscape graphic or a website list of LF projects) descriptions of projects.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssetSyncToNetSuiteController.cls
public class AssetSyncToNetSuiteController {
    @AuraEnabled
    public static String validateAndSyncToNetSuite(Id recordId) {
        String assetId = recordId;
        AssetSyncWrapper wrapper = new AssetSyncWrapper();
        wrapper.isSuccess = false;
        Asset assetObject = [SELECT id ,  memo__c , AccountId ,Bill_To_Account__c,
                             Bill_To_Account__r.Name, installdate , usageenddate ,Opportunity__c,Opportunity__r.recordtype.name,OpportunityLineItem__c,Bill_To_Account__r.billingstate,Bill_To_Account__r.billingcity,Bill_To_Account__r.billingcountry,Bill_To_Account__r.billingpostalcode,Bill_To_Account__r.billingstreet,
                             netsuite_class__c ,Account.name,Account.billingstate,Account.billingcity,Account.billingcountry,Account.billingpostalcode,Account.billingstreet , NetSuite_Location__c,
                             Bill_To_Address__c,Bill_To_Address__r.Name,Bill_To_Address__r.Street__c,Bill_To_Address__r.City__c,Bill_To_Address__r.State__c,Bill_To_Address__r.Zip_Postal_Code__c,Bill_To_Address__r.Country__c FROM Asset WHERE ID = :recordId AND Skip_NetSuite_Sync__c = FALSE];
        
        String billToAddress = AssetToSalesOrderHelper.getBillingAddress(assetObject);
        
        OpportunityLineItem oli = [SELECT id , name , Product_Details__c,Product_Details__r.project__c,
                                   Product_Details__r.project__r.Subsidiary_ID__c,
                                   description__c,Product_Details__r.Netsuite_ID__c,Start_Date__c,
                                   Product_Details__r.Subsidiary_ID__c FROM OpportunityLineItem 
                                   WHERE id=:assetObject.OpportunityLineItem__c AND Skip_NetSuite_Sync__c = FALSE];
        
        if (assetObject.memo__c != null && assetObject.memo__c.length() > 999) {
            wrapper.message = 'memo cant be more than 999 chars ';
        }
        else if (billToAddress == '') {
            wrapper.message = 'Account Billing Address incomplete';
        }
        else if (oli.Start_Date__c == null) {
            wrapper.message = 'The Start Date is not populated.';
        }
        else if (oli.Product_Details__c != null && oli.Product_Details__r.Netsuite_ID__c == null) {
            wrapper.message = 'Product Detail netsuiteId cannot be blank ';
        }
        else if (oli.Product_Details__c != null && oli.Product_Details__r.Subsidiary_ID__c == null) {
            wrapper.message = 'Product Detail subsidiary cannot be blank ';
        }
        else if (oli.description__c != null && oli.description__c.length() > 4000) {
            wrapper.message = 'Opportunity product description cannot be more than 4000 chars ';
        }
        else if(oli.Product_Details__c != null && oli.Product_Details__r.project__c != null && oli.Product_Details__r.project__r.Subsidiary_ID__c == null){
            wrapper.message = 'Projects Subsidiary ID cannot be null';
        }
        else if (assetObject.installdate == null) {
            wrapper.message = 'Start Date cannot be null';
        }
        else if (assetObject.usageenddate == null) {
            wrapper.message = 'End Date cannot be null';
        }
        
        
        Map<String, Schema.SObjectField> mapOfOppFields = Opportunity.getSobjectType().getDescribe().fields.getMap();
        String query = 'SELECT ';
        for(Schema.SObjectField s : mapOfOppFields.values()){
            query += s + ',';
        }
        String query1 = query.removeEnd(',');
        query1 += ' FROM Opportunity WHERE Id = \''+assetObject.Opportunity__c+'\'';
        List<Opportunity> oppList = Database.query(query1);
        Map<Id,Opportunity> mapOfOpportunity = new Map<Id,Opportunity>(oppList);
        
        if(String.isBlank(wrapper.message) ){
            if(assetObject.Opportunity__c != null && (assetObject.Opportunity__r.recordtype.name.equalsIgnoreCase('Membership') 
            || assetObject.Opportunity__r.recordtype.name.equalsIgnoreCase('Alternate Funding'))){
                NSAssetTriggerHelper.checkRecordTypeAndCallNS(new Set<Id>{recordId},assetObject.Opportunity__c,mapOfOpportunity);
                
            }else{
                NSAssetTriggerHelper.checkRecordTypeAndCallNS1(assetId,assetObject.Opportunity__c,mapOfOpportunity);
            }
        }
        return JSON.serialize(wrapper);
    }
    
    public class AssetSyncWrapper{
        @auraEnabled
        public Boolean isSuccess {get;set;}
        @auraEnabled
        public String message {get; set;}
    }
    
    
}