force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Alternate Bill to Name and Address</label>
    <nameField>
        <label>Bill To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alternate Bill to Name and Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>if(LEN(Street__c )&gt;0, Street__c &amp; &quot; &quot; , &quot;&quot; ) &amp; BR() &amp;
if(LEN(City__c )&gt;0, City__c &amp; &quot;, &quot; , &quot;&quot; )&amp;
if(LEN(State__c )&gt;0, State__c &amp; &quot; &quot; , &quot;&quot; )&amp;
if(LEN(Zip_Postal_Code__c )&gt;0, Zip_Postal_Code__c,&quot;&quot;) &amp; BR() &amp;
If(LEN(Country__c) &gt;0,Country__c ,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Bill_to_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Address__c</fullName>
    <description>Created for DocuSign to show billing address in single line.</description>
    <formula>SUBSTITUTE(

SUBSTITUTE(

IF(
   ISBLANK(Street__c),
   &quot;&quot;,
   Street__c + &quot;, &quot;
  )
+
IF(
   ISBLANK(City__c),
   &quot;&quot;,
   IF(
      ISBLANK(State__c),
      City__c + &quot; &quot;,
      City__c + &quot;, &quot;
     )
  )
+
IF(
   ISBLANK(State__c),
   &quot;&quot;,
   State__c + &quot; &quot;
  )
+
IF(
   ISBLANK(Zip_Postal_Code__c),
   &quot;&quot;,
   Zip_Postal_Code__c
  )
+
IF(
   ISBLANK(Country__c),
   &quot;&quot;,
   IF(
      ISBLANK(Zip_Postal_Code__c),
      IF(
         ISBLANK(State__c),
         &quot; &quot; + Country__c,
         &quot;, &quot; + Country__c
        ),
      &quot;, &quot; + Country__c
     )
  )

/* removes any spaces that immediately precede a comma, so &quot;Madrid , Spain&quot; would become &quot;Madrid, Spain&quot; */
, &quot; ,&quot;, &quot;,&quot;)


/* removes any double commas and replaces them with a single comma, so &quot;Madrid,, Spain&quot; would become &quot;Madrid, Spain&quot; */
, &quot;,,&quot;, &quot;,&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill to Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Use if bill to address is different from Account Name billing Address. You can find addresses under Bill to Name and Address under Account</inlineHelpText>
    <label>Bill to Name and address</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Bill_To_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddressTriggerHandler.cls
/********************************************************
* Created by: Pratik D 
* Created Date: 28 - APR - 2020.
* Description: AddressTriggerHandler
* JIRA - SFDC-1230 - validateAddressBeforeDelete() - Restrict User from deleting address if any associated Opportunity is Closed Won
********************************************************/

public class AddressTriggerHandler implements ITriggerHandler{
    public static void BeforeInsert(List<SObject> triggerNew){
        
    }
    public static void BeforeUpdate(Map<Id, Sobject> newMap, Map<Id, Sobject> oldMap) {
        
    }   
    public static void BeforeDelete(Map<Id, Sobject> oldMap){
        validateAddressBeforeDelete((Map<Id, Address__c>)oldMap);
    } 
    
    public static void AfterInsert(Map<Id, SObject> newMap){
        
    }   
    public static void AfterUpdate(Map<Id, SObject> newMap, Map<Id, Sobject> oldMap){
        
    }
    
    public static void AfterDelete(Map<Id, Sobject> oldMap){
    }
    
    
    public static void AfterUnDelete(Map<Id, Sobject> newMap){
        
    } 
    
    public Boolean IsDisabled(){
        return false;
    }
    
    public static void validateAddressBeforeDelete(Map<Id,Address__c> oldMap){
        
        Set<Id> setAddressId = oldMap.keySet();
        Set<Id> setAddressForClosedWonOpp = new Set<Id>();
        
        for(Opportunity objOpportunity : [ SELECT ID, Bill_To_Address__c
                                        FROM Opportunity 
                                        WHERE Bill_To_Address__c IN: setAddressId 
                                        AND IsWon = TRUE 
                                        ] ){
            setAddressForClosedWonOpp.add(objOpportunity.Bill_To_Address__c);
        }
        
        if(setAddressForClosedWonOpp.size() > 0){
            for(Address__c objAddress : oldMap.values()){
                if(setAddressForClosedWonOpp.contains(objAddress.Id))
                    objAddress.addError('You can not delete this Address, it is associated with one or more Closed Won Opportunities.');
            }
        }
    }
    
}