force-app/main/default/objects/Hotel_Commissions__c/Hotel_Commissions__c.object-meta.xml
<CustomObject>
    <description>Hotel Commissions are revenue transactions.These are the commissions which Linux Foundation receives from Hotel&apos;s when event registrant registers for an LF event and books the room to stay in and attend the event.</description>
    <label>Hotel Commissions</label>
    <nameField>
        <label>Hotel Commissions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotel Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel_Commissions__c/fields/Bill_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hotel Commissions</relationshipLabel>
    <relationshipName>Hotel_Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/Bill_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill to Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hotel Commissions</relationshipLabel>
    <relationshipName>Hotel_Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Commissions__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Events</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Training</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Training (Linux Labs)</label>
    </customValue>
    <masterLabel>NetSuite Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HotelCommissionsTriggerHandler_Test.cls
@isTest
public class HotelCommissionsTriggerHandler_Test {
	
    @isTest
    public static void populateDefaultNSFields_Test(){
        List<Hotel_Commissions__c> hotelCommissionList = new List<Hotel_Commissions__c>(); 
        Account account = new Account();
        account.Name = 'Test Account For Hotel Commission';
        insert account;
        
        Contact contact = new Contact();
        contact.LastName = 'Test Contact for Hotel Commission';
        contact.AccountId = account.Id;
        contact.Email = 'testContact@hotel.com';
        insert contact;
        
        for(Integer i=0;i<80;i++){
            Hotel_Commissions__c hotelCommission = new Hotel_Commissions__c();
            hotelCommission.Name = 'test hotel Commission'+''+i;
            hotelCommission.Amount__c = 1000;
            hotelCommission.Bill_to_Account__c = account.Id;
            hotelCommission.Bill_to_Contact__c = contact.Id;
            hotelCommission.Start_Date__c = System.today();
            hotelCommission.Product_Description__c = 'test description';
            hotelCommissionList.add(hotelCommission);
        }
        insert hotelCommissionList;
        System.assertEquals('2', [SELECT Id,NS_Department__c FROM Hotel_Commissions__c limit 1].NS_Department__c);
        
        delete hotelCommissionList;
    }
}