force-app/main/default/objects/Opportunity/fields/JoinNow_Update__c.field-meta.xml
<CustomField>
    <fullName>JoinNow_Update__c</fullName>
    <label>JoinNow Update</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Firm Acquired</fullName>
            </value>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>No Budget / Lost Funding</fullName>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
            </value>
            <value>
                <fullName>No Engagement</fullName>
            </value>
            <value>
                <fullName>Non payment</fullName>
            </value>
            <value>
                <fullName>Org Change/Lost Champion or Funding</fullName>
            </value>
            <value>
                <fullName>Perceived Value</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Reissued</fullName>
            </value>
            <value>
                <fullName>Solution Fit</fullName>
            </value>
            <value>
                <fullName>SPAM Opportunity</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Payment Due Immediately</fullName>
            </value>
            <value>
                <fullName>Payment Due Prior To Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Standard Memberships will auto-populate date.</description>
    <inlineHelpText>Standard Memberships will auto-populate date.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/JoinNow_Update__c.field-meta.xml
<CustomField>
    <fullName>JoinNow_Update__c</fullName>
    <formula>Opportunity.JoinNow_Update__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>JoinNow Update</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <formula>TEXT(Opportunity.PaymentTerms__c)</formula>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/opportunitylistviewComTest.cls
@isTest
public class opportunitylistviewComTest {
    @isTest
    public static void test1(){
        
        Product2 prod = new Product2(Name = 'Laptop X200', Family = 'Hardware');
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, 
                                                          Product2Id = prod.Id, 
                                                          UnitPrice = 10000, 
                                                          IsActive = true);
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry(Pricebook2Id = customPB.Id, 
                                                        Product2Id = prod.Id, 
                                                        UnitPrice = 12000, 
                                                        IsActive = true);
        insert customPrice;
        Account acc = new Account(name='Test Account');
        insert acc;
        opportunity opp = new opportunity(name='Test Opportunity', 
                                          AccountId=acc.id,
                                          CloseDate =Date.newInstance(2016, 12, 9),
                                          stageName='Closed Lost',
                                          ForecastCategoryName='Pipeline',
                                          PaymentTerms__c='Net 30',
                                          type='New Business',
                                          Amount=5676,
                                          Pricebook2Id=customPB.Id,
                                          Loss_Reason__c ='Other'
                                         );
        insert opp;
        opportunity opp1 = new opportunity(name='Test Opportunity', 
                                           AccountId=acc.id,
                                           CloseDate =Date.newInstance(2016, 12, 9),
                                           stageName='Closed Lost',
                                           ForecastCategoryName='Pipeline',
                                           PaymentTerms__c='Net 30',
                                           type='New Business',
                                           Amount=5676,
                                           Pricebook2Id=customPB.Id,
                                           JoinNow_Update__c=Date.newInstance(2016, 12, 9),
                                           Loss_Reason__c ='Other'
                                          );
        insert opp1;
        
        OpportunityLineItem oppLineItem = new OpportunityLineItem(OpportunityId=opp.id,
                                                                  TotalPrice =664557,
                                                                  End_Date__c=Date.newInstance(2016, 12, 9),
                                                                  Quantity =56,
                                                                  PricebookEntryId = customPrice.Id);
        insert oppLineItem;
        blob attBlob;
        attBlob = EncodingUtil.base64Decode('AA==');
        attachment  at = new attachment();
        at.ParentId = opp1.Id;  
        at.Name ='testattach';
        at.Body = attblob;
        insert at;
        
        
        
        //Create Document
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = Opp.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        
        id AccountId=acc.id;
        string sortField ='ASC';
        boolean isAsc =true;
        OpportunitylistViewCom objclass = new OpportunitylistViewCom();
        OpportunitylistViewCom.getOpportunityLineItem(AccountId, sortField, isAsc);
        OpportunitylistViewCom.fetchopportunity(AccountId,'Membership');
        
    }
     @isTest
    public static void test2(){
       Product2 prod = new Product2(Name = 'Laptop X200', Family = 'Hardware');
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, 
                                                          Product2Id = prod.Id, 
                                                          UnitPrice = 10000, 
                                                          IsActive = true);
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry(Pricebook2Id = customPB.Id, 
                                                        Product2Id = prod.Id, 
                                                        UnitPrice = 12000, 
                                                        IsActive = true);
        insert customPrice;
        Account acc = new Account(name='Test Account');
        insert acc;
        opportunity opp = new opportunity(name='Test Opportunity', 
                                          AccountId=acc.id,
                                          CloseDate =Date.newInstance(2016, 12, 9),
                                          stageName='Closed Lost',
                                          ForecastCategoryName='Pipeline',
                                          PaymentTerms__c='Net 30',
                                          type='New Business',
                                          Amount=5676,
                                          Pricebook2Id=customPB.Id,
                                          Loss_Reason__c ='Other'
                                         );
        insert opp;
        
        
        OpportunityLineItem oppLineItem = new OpportunityLineItem(OpportunityId=opp.id,
                                                                  TotalPrice =664557,
                                                                  End_Date__c=Date.newInstance(2016, 12, 9),
                                                                  Quantity =56,
                                                                  PricebookEntryId = customPrice.Id);
        insert oppLineItem;
        
        blob attBlob;
        
         attBlob = EncodingUtil.base64Decode('AA==');
        attachment  at1 = new attachment();
        at1.ParentId = opp.Id;  
        at1.Name ='testattach';
        at1.Body = attblob;
        insert at1;
        
        //Create Document
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = Opp.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        
        id AccountId=acc.id;
        string sortField ='ASC';
        boolean isAsc =true;
        OpportunitylistViewCom objclass = new OpportunitylistViewCom();
        OpportunitylistViewCom.getOpportunityLineItem(AccountId, sortField, isAsc);
        OpportunitylistViewCom.fetchopportunity(AccountId,''); 
        OpportunitylistViewCom.getRecordTypeList();
    }
}