force-app/main/default/objects/Opportunity/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Payment Due Immediately</fullName>
            </value>
            <value>
                <fullName>Payment Due Prior To Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/AgreementDate__c.field-meta.xml
<CustomField>
    <fullName>AgreementDate__c</fullName>
    <inlineHelpText>Countersigned date of agreement (manually set by membership sales)</inlineHelpText>
    <label>Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <formula>TEXT(Opportunity.PaymentTerms__c)</formula>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Required_Active_LF_Membership__c.field-meta.xml
<CustomField>
    <fullName>Required_Active_LF_Membership__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required Active LF Membership</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Payment Due Immediately</fullName>
            </value>
            <value>
                <fullName>Payment Due Prior to Training</fullName>
            </value>
            <value>
                <fullName>Payment in full prior to training</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalInitialPriceOf_QuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>TotalInitialPriceOf_QuoteLineItem__c</fullName>
    <label>Total InitialPrice Of QuoteLineItem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Agreement_Date__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projects</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteSyncUtil_Test.cls
@isTest
public class QuoteSyncUtil_Test {
    
    @testSetup
    static void setup(){
        QuoteSyncField__c quoteSyncField = new QuoteSyncField__c(Name = 'PaymentTerms__c', OppSyncField__c = 'PaymentTerms__c');
        insert quoteSyncField;
        
        /* quote line sync field */
        QuoteLineSyncField__c quoteLineSyncField = new QuoteLineSyncField__c(Name = 'Agreement_Date__c', OppLineSyncField__c = 'AgreementDate__c');
        insert quoteLineSyncField;
        
    }
    
    @isTest
    static void getQuoteLineFieldsTest(){
        
        QuoteSyncUtil.getQuoteFields();
        QuoteSyncUtil.addQuoteField('TotalInitialPriceOf_QuoteLineItem__c','TotalInitialPriceOf_QuoteLineItem__c');
        System.assertEquals('TotalInitialPriceOf_QuoteLineItem__c', QuoteSyncUtil.getQuoteFieldMapTo('TotalInitialPriceOf_QuoteLineItem__c'));
        System.assert(!QuoteSyncUtil.getOppFields().isEmpty());
        
        QuoteSyncUtil.removeQuoteField('TotalInitialPriceOf_QuoteLineItem__c');
        System.assert(!QuoteSyncUtil.getQuoteFields().contains('TotalInitialPriceOf_QuoteLineItem__c'));
        
        QuoteSyncUtil.addQuoteLineField('TotalInitialPriceOf_QuoteLineItem__c','TotalInitialPriceOf_QuoteLineItem__c');
        System.assert(!QuoteSyncUtil.getOppLineFields().isEmpty());
        System.assertEquals('TotalInitialPriceOf_QuoteLineItem__c', QuoteSyncUtil.getQuoteLineFieldMapTo('TotalInitialPriceOf_QuoteLineItem__c'));
        
        QuoteSyncUtil.removeQuoteLineField('TotalInitialPriceOf_QuoteLineItem__c');
        System.assert(!QuoteSyncUtil.getQuoteLineFields().contains('TotalInitialPriceOf_QuoteLineItem__c'));
        
        System.assert(QuoteSyncUtil.getQuoteFieldsString().contains('PaymentTerms__c') );  
        System.assert(QuoteSyncUtil.getQuoteLineFieldsString().contains('Agreement_Date__c') );
        System.assert(QuoteSyncUtil.getOppFieldsString().contains('PaymentTerms__c') );
        QuoteSyncUtil.getOppLineFieldsString(); 
        
        //check add/remove quoteIDs
        QuoteSyncUtil.addNewQuoteId(userInfo.getUserId());
        System.assert(!QuoteSyncUtil.getNewQuoteIds().IsEmpty());
        QuoteSyncUtil.clearNewQuoteIds();
        System.assert(QuoteSyncUtil.getNewQuoteIds().IsEmpty());
        QuoteSyncUtil.addNewQuoteId(userInfo.getUserId());
        QuoteSyncUtil.removeNewQuoteId(userInfo.getUserId());
        QuoteSyncUtil.removeAllNewQuoteIds(new Set<Id>{userInfo.getUserId()});
        QuoteSyncUtil.isNewQuote(userInfo.getUserId()); 
        
        QuoteSyncUtil.getField('Quote','PaymentTerms__c');
        QuoteSyncUtil.getField('Opportunity','PaymentTerms__c');
		QuoteSyncUtil.getField('QuoteLineItem','Agreement_Date__c');
		QuoteSyncUtil.getField('OpportunityLineItem','UnitPrice');

    }
    
    @isTest
    static void syncFields_Test(){
        Opportunity memberShipOpp = TestFactory.getOpportunity();
        Product2 prodId = TestDataUtils.createProduct('Platinumm Membership', 'description', 6, 'Membership');
        prodId.IsActive = true;
        update prodId;
        
        PriceBookEntry pbe = new PriceBookEntry(PriceBook2Id = Test.getStandardPricebookId(), Product2Id = prodId.ID, isActive = true, unitPrice = 34);
        insert pbe;
        
        Project__c project = TestFactory.getProject();
        
        OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = memberShipOpp.Id, Quantity = 2, UnitPrice = 20, PriceBookEntryId = pbe.ID, Required_Active_LF_Membership__c = true, Projects__c = project.Id);
        insert oli;
        List<OpportunityLineItem> oliList = [SELECT Id,PriceBookEntryId,Product2Id,OpportunityId,Projects__c
                                             FROM OpportunityLineItem
                                             Where Projects__c != null];
        Quote quote = new Quote();
        quote.Name = 'Test Quote';
        quote.OpportunityId = memberShipOpp.Id;
        insert quote;
        QuoteLineItem qli = new QuoteLineItem(QuoteId = quote.Id, OpportunityLineItemId = oli.Id, Quantity = 2, unitPrice = 20, PriceBookEntryId = oli.PriceBookEntryId, Projects__c = oli.Projects__c);
        insert qli;
        
        QuoteSyncUtil.getOppLineItemVsQuoteLineItemMap(new List<QuoteLineItem>{qli});
        QuoteSyncutil.populateRequiredFields(memberShipOpp);
        QuoteSyncutil.populateRequiredFields(oli);
        QuoteSyncutil.populateRequiredFields(quote);
        QuoteSyncutil.populateRequiredFields(qli);
        
        
        Schema.DescribeFieldResult result = QuoteSyncUtil.getField('OpportunityLineItem', 'Quantity');
        QuoteSyncUtil.createValue(oli, 'OpportunityLineItem', 'Quantity', result, false);
		
        result = QuoteSyncUtil.getField('OpportunityLineItem', 'unitPrice');
        QuoteSyncUtil.createValue(oli, 'OpportunityLineItem', 'unitPrice', result, false);

		result = QuoteSyncUtil.getField('OpportunityLineItem', 'Description');
        QuoteSyncUtil.createValue(oli, 'OpportunityLineItem', 'Description', result, false);
        
        
    }
    
    
    
}