force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores the category for Risc-v</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Text that will be displayed on invoice</description>
    <inlineHelpText>Text that will be displayed on invoice</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Required</inlineHelpText>
    <label>Start Date*</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Android Development Training</fullName>
            </value>
            <value>
                <fullName>Enterprise IT &amp; Linux System Administration Training</fullName>
            </value>
            <value>
                <fullName>Linux Programming &amp; Development Training</fullName>
            </value>
            <value>
                <fullName>Open Source Compliance Courses</fullName>
            </value>
            <value>
                <fullName>Tizen Project Training</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A one-sentence description of the project, which will be used for external facing (i.e. landscape graphic or a website list of LF projects) descriptions of projects.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Consumer Electronics</fullName>
            </value>
            <value>
                <fullName>Cross-Industry</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Climate</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Health Care</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Materials</fullName>
            </value>
            <value>
                <fullName>Motion Pictures</fullName>
            </value>
            <value>
                <fullName>Non-profit Organizations</fullName>
            </value>
            <value>
                <fullName>Pharmaceuticals</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Public Health &amp; Disaster Response</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Indicates if the project has Membership, Crowdfunding (e.g. LFX Funding), or both. Note that a project may have membership requirements that do not have any fees or funding associated with them. In that case, &apos;Membership&apos; is still selected for this field.</inlineHelpText>
    <label>Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Crowdfunding</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Parent_Entity_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Parent_Entity_Relationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Incorporated Entity or Series LLC that is the legal parent of the project.</inlineHelpText>
    <label>Legal Parent</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Child Projects of Legal Entity</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Entity_Name__c</fullName>
    <inlineHelpText>The legal name of the entity or formal Subproject name.</inlineHelpText>
    <label>Formal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <inlineHelpText>The &quot;Prospect&quot; stage is reserved for non-LF projects, e.g. some Community Bridge projects.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Formation - Exploratory</fullName>
            </value>
            <value>
                <fullName>Formation - Engaged</fullName>
            </value>
            <value>
                <fullName>Formation - Confidential</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Formation - On Hold</fullName>
            </value>
            <value>
                <fullName>Formation - Disengaged</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Actively Engaged</fullName>
                <isActive>false</isActive>
                <label>Actively Engaged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Technical_Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Technical_Activity_Type__c</fullName>
    <label>Technical Activity Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Source Software</fullName>
            </value>
            <value>
                <fullName>Open Standard / Specification</fullName>
            </value>
            <value>
                <fullName>Open Hardware</fullName>
            </value>
            <value>
                <fullName>Open Data</fullName>
            </value>
            <value>
                <fullName>Open Governance Network</fullName>
            </value>
            <value>
                <fullName>Community Initiative</fullName>
            </value>
            <value>
                <fullName>Peer Network</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology Sector</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Services (Fab, design services)</fullName>
    </customValue>
    <customValue>
        <fullName>Chip (SoC, IP, FPGA)</fullName>
    </customValue>
    <customValue>
        <fullName>I/O (Memory, network, storage)</fullName>
    </customValue>
    <customValue>
        <fullName>Systems (ODM, OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Software (Dev tools, firmware, OS)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry (cloud, mobile, HPC, ML, automotive)</fullName>
    </customValue>
    <customValue>
        <fullName>Research (Universities, Labs, other alliances, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <description>Account Project Category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AI, ML, Data &amp; Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud, Containers &amp; Virtualization</fullName>
    </customValue>
    <customValue>
        <fullName>Cross-Technology</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps, CI/CD &amp; Site Reliability</fullName>
    </customValue>
    <customValue>
        <fullName>IoT &amp; Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>Linux Kernel</fullName>
    </customValue>
    <customValue>
        <fullName>Networking &amp; Edge</fullName>
    </customValue>
    <customValue>
        <fullName>Open Hardware</fullName>
    </customValue>
    <customValue>
        <fullName>Open Source &amp; Compliance Best Practices</fullName>
    </customValue>
    <customValue>
        <fullName>Privacy &amp; Security</fullName>
    </customValue>
    <customValue>
        <fullName>Quantum Computing</fullName>
    </customValue>
    <customValue>
        <fullName>Safety-Critical Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>System Administration</fullName>
    </customValue>
    <customValue>
        <fullName>System Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Visual Effects</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Application Development</fullName>
    </customValue>
    <customValue>
        <fullName>Cybersecurity</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
        <isActive>false</isActive>
        <label>Security</label>
    </customValue>
    <customValue>
        <fullName>Node.js Development</fullName>
        <isActive>false</isActive>
        <label>Node.js Development</label>
    </customValue>
    <customValue>
        <fullName>Open Source Best Practices</fullName>
        <isActive>false</isActive>
        <label>Open Source Best Practices</label>
    </customValue>
    <customValue>
        <fullName>Application Development</fullName>
        <isActive>false</isActive>
        <label>Application Development</label>
    </customValue>
    <description>Technology categories used by training, events, and projects across the LF.  Note that forms in Cvent need to be updated for any label change needed in this value set.</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OppChangeProductControllerTest.cls
@isTest
private class OppChangeProductControllerTest{
	@isTest
	static void testGetOptions(){
		Project__c lfProject = new Project__c();
		lfProject.Name = 'The Linux Foundation';
		lfProject.Category__c = 'Incorporated Entity';
		lfProject.Project_Status__c = 'Active';
		lfProject.Funding__c = 'Funded';
		lfProject.Slug__c = 'testing';
        lfProject.Project_Entity_Name__c = 'The Linux Foundation';
        lfProject.Start_Date__c = System.today();
        lfProject.Industry__c = 'Non-profit Organizations';
        lfProject.Model__c = 'Alternate Funding';
        lfProject.Technology__c = 'Blockchain';
        lfProject.Technical_Activity_Type__c = 'Open Source Software';
        lfProject.Description__c = 'description';
		insert lfProject;

		Project__c lfnProject = new Project__c();
		lfnProject.Name = 'LF Networking';
		lfnProject.Category__c = 'Subproject';
		lfnProject.Project_Status__c = 'Active';
		lfnProject.Funding__c = 'Funded';
        lfnProject.Slug__c = 'testing1';
        lfnProject.Project_Entity_Name__c = 'The Linux Foundation';
        lfnProject.Start_Date__c = System.today();
        lfnProject.Industry__c = 'Non-profit Organizations';
        lfnProject.Model__c = 'Alternate Funding';
        lfnProject.Technology__c = 'Blockchain';
        lfnProject.Technical_Activity_Type__c = 'Open Source Software';
        lfnProject.Description__c = 'description';
        lfnProject.Parent_Entity_Relationship__c = lfProject.Id;
        lfnProject.Parent_Project__c = lfProject.Id;
		insert lfnProject;

		Account acc = new Account();
		acc.Name = 'Google';
		acc.Website = 'www.google.com';
		insert acc;

		Id pricebookId = Test.getStandardPricebookId();

		Opportunity opp = new Opportunity();
		opp.AccountId = acc.Id;
		opp.StageName = '5. Decision Commitment';
		opp.Type = 'New Business';
		opp.CloseDate = Date.today();
		opp.Name = 'Google New Business Opp';
		opp.Pricebook2Id = pricebookId;
		insert opp;

		Product2 silverMembershipProduct = new Product2();
		silverMembershipProduct.Name = 'Silver Membership';
		silverMembershipProduct.Family = 'Membership';
		insert silverMembershipProduct;

		PricebookEntry silverPBE = new PricebookEntry();
		silverPBE.Pricebook2Id = pricebookId;
		silverPBE.Product2Id = silverMembershipProduct.Id;
		silverPBE.UnitPrice = 500;
		silverPBE.UseStandardPrice = false;
		silverPBE.IsActive = true;
		insert silverPBE;

		Product_Details__c silverPDLF = new Product_Details__c();
		silverPDLF.Products__c = silverMembershipProduct.Id;
		silverPDLF.Project__c = lfProject.Id;
		silverPDLF.Price__c = 500;
		silverPDLF.Start_Tier__c = 1;
		silverPDLF.Status__c = 'Active';
        silverPDLF.Description__c = 'test';
		insert silverPDLF;

		Product_Details__c silverPDLFN = new Product_Details__c();
		silverPDLFN.Products__c = silverMembershipProduct.Id;
		silverPDLFN.Project__c = lfnProject.Id;
		silverPDLFN.Price__c = 750;
		silverPDLFN.Start_Tier__c = 1;
		silverPDLFN.Status__c = 'Active';
        silverPDLFN.Description__c = 'test';
		insert silverPDLFN;

		Product_Details__c silverPDLF2 = new Product_Details__c();
		silverPDLF2.Products__c = silverMembershipProduct.Id;
		silverPDLF2.Project__c = lfProject.Id;
		silverPDLF2.Price__c = 5000;
		silverPDLF2.Start_Tier__c = 500;
		silverPDLF2.Status__c = 'Active';
        silverPDLF2.Description__c = 'test';
		insert silverPDLF2;

		Product_Details__c silverPDLFN2 = new Product_Details__c();
		silverPDLFN2.Products__c = silverMembershipProduct.Id;
		silverPDLFN2.Project__c = lfnProject.Id;
		silverPDLFN2.Price__c = 7500;
		silverPDLFN2.Start_Tier__c = 500;
		silverPDLFN2.Status__c = 'Active';
        silverPDLFN2.Description__c = 'test';
		insert silverPDLFN2;

		OpportunityLineItem lfOLI = new OpportunityLineItem();
		lfOLI.OpportunityId = opp.Id;
		lfOLI.Product2Id = silverMembershipProduct.Id;
		lfOLI.Product_Details__c = silverPDLF.Id;
		lfOLI.Projects__c = lfProject.Id;
		lfOLI.Start_Date__c = Date.newInstance(2020, 1, 1);
		lfOLI.Quantity = 1;
		lfOLI.TotalPrice = silverPDLF.Price__c;
		lfOLI.PricebookEntryId = silverPBE.Id;
		insert lfOLI;

		OpportunityLineItem lfnOLI = new OpportunityLineItem();
		lfnOLI.OpportunityId = opp.Id;
		lfnOLI.Product2Id = silverMembershipProduct.Id;
		lfnOLI.Product_Details__c = silverPDLFN.Id;
		lfnOLI.Projects__c = lfnProject.Id;
		lfnOLI.Start_Date__c = Date.newInstance(2020, 1, 1);
		lfnOLI.Quantity = 1;
		lfnOLI.TotalPrice = silverPDLF.Price__c;
		lfnOLI.PricebookEntryId = silverPBE.Id;
		insert lfnOLI;

		OppChangeProductController.getOptions(opp.Id);
	}

	@isTest
	static void testGetOptionsEmptyList(){
		Account acc = new Account();
		acc.Name = 'Google';
		acc.Website = 'www.google.com';
		insert acc;

		Opportunity opp = new Opportunity();
		opp.AccountId = acc.Id;
		opp.StageName = '5. Decision Commitment';
		opp.Type = 'New Business';
		opp.CloseDate = Date.today();
		opp.Name = 'Google New Business Opp';
		insert opp;

		OppChangeProductController.getOptions(opp.Id);
	}

	@isTest
	static void testUpdateProducts(){
		Project__c lfProject = new Project__c();
		lfProject.Name = 'The Linux Foundation';
		lfProject.Category__c = 'Incorporated Entity';
		lfProject.Project_Status__c = 'Active';
		lfProject.Funding__c = 'Funded';
        lfProject.Slug__c = 'testing';
        lfProject.Project_Entity_Name__c = 'The Linux Foundation';
        lfProject.Start_Date__c = System.today();
        lfProject.Industry__c = 'Non-profit Organizations';
        lfProject.Model__c = 'Alternate Funding';
        lfProject.Technology__c = 'Blockchain';
        lfProject.Technical_Activity_Type__c = 'Open Source Software';
        lfProject.Description__c = 'description';
		insert lfProject;

		Account acc = new Account();
		acc.Name = 'Google';
		acc.Website = 'www.google.com';
		insert acc;

		Id pricebookId = Test.getStandardPricebookId();

		Opportunity newBusinessOpp = new Opportunity();
		newBusinessOpp.AccountId = acc.Id;
		newBusinessOpp.StageName = '5. Decision Commitment';
		newBusinessOpp.Type = 'New Business';
		newBusinessOpp.CloseDate = Date.today();
		newBusinessOpp.Name = 'Google New Business Opp';
		newBusinessOpp.Pricebook2Id = pricebookId;
		insert newBusinessOpp;

		Product2 silverMembershipProduct = new Product2();
		silverMembershipProduct.Name = 'Silver Membership';
		silverMembershipProduct.Family = 'Membership';
		insert silverMembershipProduct;

		PricebookEntry silverPBE = new PricebookEntry();
		silverPBE.Pricebook2Id = pricebookId;
		silverPBE.Product2Id = silverMembershipProduct.Id;
		silverPBE.UnitPrice = 500;
		silverPBE.UseStandardPrice = false;
		silverPBE.IsActive = true;
		insert silverPBE;

		Product_Details__c silverPD1 = new Product_Details__c();
		silverPD1.Products__c = silverMembershipProduct.Id;
		silverPD1.Project__c = lfProject.Id;
		silverPD1.Price__c = 500;
		silverPD1.Status__c = 'Active';
        silverPD1.Description__c = 'test';
		insert silverPD1;

		Product_Details__c silverPD2 = new Product_Details__c();
		silverPD2.Products__c = silverMembershipProduct.Id;
		silverPD2.Project__c = lfProject.Id;
		silverPD2.Price__c = 1000;
		silverPD2.Status__c = 'Active';
        silverPD2.Description__c = 'test';
		insert silverPD2;

		OpportunityLineItem newBusinessOLI = new OpportunityLineItem();
		newBusinessOLI.OpportunityId = newBusinessOpp.Id;
		newBusinessOLI.Product2Id = silverMembershipProduct.Id;
		newBusinessOLI.Product_Details__c = silverPD1.Id;
		newBusinessOLI.Start_Date__c = Date.newInstance(2020, 1, 1);
		newBusinessOLI.Quantity = 1;
		newBusinessOLI.TotalPrice = silverPD1.Price__c;
		newBusinessOLI.PricebookEntryId = silverPBE.Id;
		newBusinessOLI.Projects__c = lfProject.Id;
		insert newBusinessOLI;

		List<ID> pdIDsList = new List<ID>();
		pdIDsList.add(silverPD2.Id);

		OppChangeProductController.updateProducts(newBusinessOpp.Id, pdIDsList);
	}
}