force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Opportunity_Owner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The LF staff member who should own New Business Opportunities for this project. In the Project Control Center, this is the equivalent of the &quot;Membership New Sales Owner.&quot;</inlineHelpText>
    <label>Opportunity Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Renewal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The LF staff member who should own Renewal Opportunities for this project. In the Project Control Center, this is the equivalent of the &quot;Membership Renewal Owner.&quot;</inlineHelpText>
    <label>Renewal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Projects</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateOpportunityPBHandler.cls
public class UpdateOpportunityPBHandler implements Queueable{
    public list<Opportunity> oppListToUpdateList;
    @InvocableMethod(label='updateOpportunityPBHandler' description='update Owner Id of Related opportunities')
    public static void updateOpportunityOwner(list<Project__c> prObjectRec){       
        //system.debug('prObjectRec::: => ' + prObjectRec);
        Id membershipRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Membership').getRecordTypeId();
        //system.debug('membershipRecordTypeId::::'+membershipRecordTypeId);
        
        list<id> acntIds=new list<id>();
        for(Project__c acntPrj:prObjectRec){ 
            acntIds.add(acntPrj.id);
        }
        
        list<OpportunityLineItem> oppLineItemLst= [select id,OpportunityId,Projects__r.Opportunity_Owner__c, Opportunity.isClosed,Opportunity.Type,
                                                   Projects__r.Renewal_Owner__c from OpportunityLineItem where Projects__c IN:acntIds and Opportunity.isClosed=false and Opportunity.RecordTypeId =: membershipRecordTypeId];
        system.debug('oppLineItemLst size()::: => ' + oppLineItemLst.size() +', oppLineItemLst ::: => ' + oppLineItemLst);
        set<id> oppIds=new set<id>();
        list<Opportunity> oppListToUpdate=new list<Opportunity>();
        for(OpportunityLineItem oliRec:oppLineItemLst){
            if(!oppIds.contains(oliRec.OpportunityId) ){ 
                if((oliRec.Opportunity.Type.contains('Renewal') && oliRec.Projects__r.Renewal_Owner__c == null)|| oliRec.Opportunity.Type == 'New Business'){
                    oppListToUpdate.add(new Opportunity(OwnerId=String.valueOf(oliRec.Projects__r.Opportunity_Owner__c).substring(0, 15),Id=oliRec.OpportunityId));
                    oppIds.add(oliRec.OpportunityId);
                }
                
            }
        }
        //system.debug('oppIds size()::: => ' + oppIds.size() +', oppIds ::: => ' + oppIds);
        //system.debug('oppListToUpdate size()::: => ' + oppListToUpdate.size() +', oppListToUpdate ::: => ' + oppListToUpdate);
        //system.debug('DATA::'+oppListToUpdate);
        UpdateOpportunityPBHandler PBHAndler= new UpdateOpportunityPBHandler(oppListToUpdate);
        ID jobID = System.enqueueJob(PBHAndler);
        //system.debug('jobID::'+jobID);
    }
    
    public UpdateOpportunityPBHandler(list<Opportunity> ooplist){
        this.oppListToUpdateList=ooplist;
    }
    
    public void execute(QueueableContext context) {
        //system.debug('oppListToUpdateList ::: ' + oppListToUpdateList);
        Database.SaveResult [] updateResult = Database.update(oppListToUpdateList, false);
        //system.debug('updateResult ::: ' + updateResult);
        for (Database.SaveResult r : updateResult){
            if (!r.isSuccess()){
                for (Database.Error e : r.getErrors()){ 
                    system.debug('\n ERRROR :::: '+e);
                }
            }
        }
    }
}