force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Manager (without subordinates)</fullName>
            </value>
            <value>
                <fullName>Manager (with subordinates)</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Owner/Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Docusign_Settings__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <label>AccountID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Opportunity_Closed__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity_Closed__c</fullName>
    <label>Renewal Opportunity Closed</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <businessProcess>Event</businessProcess>
    <description>Record type for event opportunities</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores the category for Risc-v</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Required_Active_LF_Membership__c.field-meta.xml
<CustomField>
    <fullName>Required_Active_LF_Membership__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required Active LF Membership</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
            <value>
                <fullName>01241000001E0UhAAK</fullName>
                <isActive>false</isActive>
                <label>01241000001E0UhAAK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Android Development Training</fullName>
            </value>
            <value>
                <fullName>Enterprise IT &amp; Linux System Administration Training</fullName>
            </value>
            <value>
                <fullName>Linux Programming &amp; Development Training</fullName>
            </value>
            <value>
                <fullName>Open Source Compliance Courses</fullName>
            </value>
            <value>
                <fullName>Tizen Project Training</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Course</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>E-Learning</fullName>
            </value>
            <value>
                <fullName>Instructor-Led</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Project_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Signatory</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Role__c/Project_Role__c.object-meta.xml
<CustomObject>
    <label>Membership Roles</label>
    <nameField>
        <displayFormat>PR{000}</displayFormat>
        <label>Role AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Project_Roles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Project_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Opportunity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Line_Item__c</fullName>
    <label>Opportunity Line Item</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Membership Roles</relationshipLabel>
    <relationshipName>Membership_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>Voting Contact means this is the person at the company that has the right to vote in the project’s membership elections for their member class.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Representative/Voting Contact</fullName>
                <label>Voting Contact</label>
            </value>
            <value>
                <fullName>Billing Contact</fullName>
            </value>
            <value>
                <fullName>Marketing Contact</fullName>
            </value>
            <value>
                <fullName>Legal Contact</fullName>
            </value>
            <value>
                <fullName>Event Sponsorship</fullName>
            </value>
            <value>
                <fullName>PO Contact</fullName>
            </value>
            <value>
                <fullName>Press Contact</fullName>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Services (Fab, design services)</fullName>
    </customValue>
    <customValue>
        <fullName>Chip (SoC, IP, FPGA)</fullName>
    </customValue>
    <customValue>
        <fullName>I/O (Memory, network, storage)</fullName>
    </customValue>
    <customValue>
        <fullName>Systems (ODM, OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Software (Dev tools, firmware, OS)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry (cloud, mobile, HPC, ML, automotive)</fullName>
    </customValue>
    <customValue>
        <fullName>Research (Universities, Labs, other alliances, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <description>Account Project Category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DocusignAPI_Test.cls
@isTest
public class DocusignAPI_Test{
	@TestSetup
	static void testData(){
	}

	@isTest
	static void mDebugUntruncated_Test(){
		DocusignAPI.mDebugUntruncated('hello');
	}

	@isTest
	static void getPRValue_Test(){
		Docusign_Settings__c setting = new Docusign_Settings__c();
		setting.AccountID__c = '34b9d81f-63d3-48cb-968d-72fc1a9df29f';
		//Docusign_Settings__c setting = Docusign_Settings__c.getOrgDefaults();
		List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
		Account acc = new Account(Name = 'Test account', billingStreet = 'street');
		insert acc;

		Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
		insert con;

		Project__c project1 = new Project__c(Name = 'test Project', Type__c = 'Membership', Category__c = 'Subproject', Status__c = 'Planned', Slug__c = 'testing1');
		insert project1;

		Opportunity oppt = new Opportunity(Name = 'Opportunity testing 1', accountId = acc.Id, StageName = '2. Discovery', Type = 'Renewal', CloseDate = Date.today().addDays(4), Renewal_Opportunity_Closed__c = 'True');
		insert oppt;

		Id pricebookId = Test.getStandardPricebookId();
		PriceBook2 pbk = new PriceBook2(Name = 'testBook', isActive = true);
		insert pbk;

		Product2 prod = new Product2(Name = 'TestP', productcode = 'test');
		insert prod;

		PriceBookEntry standardPbe = new PriceBookEntry(PriceBook2Id = pricebookId, Product2Id = prod.ID, isActive = true, unitPrice = 34);
		insert standardPbe;

		PriceBookEntry pbe = new PriceBookEntry(PriceBook2Id = pbk.Id, isActive = true, Product2Id = prod.ID, unitPrice = 20.0, useStandardPrice = false);
		insert pbe;

		OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = oppt.Id, Quantity = 2, unitPrice = 20, PriceBookEntryId = pbe.ID, Required_Active_LF_Membership__c = true, Projects__c = project1.id);
		insert oli;
		oliList.add(oli);

		List<Project_Role__c> projectRoles = new List<Project_Role__c>();
		Project_Role__c objProjectRole = new Project_Role__c();
		objProjectRole.status__c = 'Active';
		objProjectRole.Contact__c = con.id;
		objProjectRole.Role__c = 'Billing Contact';
		objProjectRole.PrimaryContact__c = true;
		objProjectRole.Opportunity__c = oppt.Id;
		objProjectRole.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole);

		Project_Role__c objProjectRole1 = new Project_Role__c();
		objProjectRole1.status__c = 'Active';
		objProjectRole1.Contact__c = con.id;
		objProjectRole1.Role__c = 'Representative/Voting Contact';
		objProjectRole1.PrimaryContact__c = true;
		objProjectRole1.Opportunity__c = oppt.Id;
		objProjectRole1.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole1);

		Project_Role__c objProjectRole2 = new Project_Role__c();
		objProjectRole2.status__c = 'Active';
		objProjectRole2.Contact__c = con.id;
		objProjectRole2.Role__c = 'Technical Contact';
		objProjectRole2.PrimaryContact__c = true;
		objProjectRole2.Opportunity__c = oppt.Id;
		objProjectRole2.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole2);

		Project_Role__c objProjectRole3 = new Project_Role__c();
		objProjectRole3.status__c = 'Active';
		objProjectRole3.Contact__c = con.id;
		objProjectRole3.Role__c = 'Marketing Contact';
		objProjectRole3.PrimaryContact__c = true;
		objProjectRole3.Opportunity__c = oppt.Id;
		objProjectRole3.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole3);

		Project_Role__c objProjectRole4 = new Project_Role__c();
		objProjectRole4.status__c = 'Active';
		objProjectRole4.Contact__c = con.id;
		objProjectRole4.Role__c = 'Press Contact';
		objProjectRole4.PrimaryContact__c = true;
		objProjectRole4.Opportunity__c = oppt.Id;
		objProjectRole4.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole4);

		Project_Role__c objProjectRole5 = new Project_Role__c();
		objProjectRole5.status__c = 'Active';
		objProjectRole5.Contact__c = con.id;
		objProjectRole5.Role__c = 'Legal Contact';
		objProjectRole5.PrimaryContact__c = true;
		objProjectRole5.Opportunity__c = oppt.Id;
		objProjectRole5.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole5);

		Project_Role__c objProjectRole6 = new Project_Role__c();
		objProjectRole6.status__c = 'Active';
		objProjectRole6.Contact__c = con.id;
		objProjectRole6.Role__c = 'Authorized Signatory';
		objProjectRole6.PrimaryContact__c = true;
		objProjectRole6.Opportunity__c = oppt.Id;
		objProjectRole6.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole6);

		Project_Role__c objProjectRole7 = new Project_Role__c();
		objProjectRole7.status__c = 'Active';
		objProjectRole7.Contact__c = con.id;
		objProjectRole7.Role__c = 'Event Sponsorship';
		objProjectRole7.PrimaryContact__c = true;
		objProjectRole7.Opportunity__c = oppt.Id;
		objProjectRole7.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole7);

		Project_Role__c objProjectRole8 = new Project_Role__c();
		objProjectRole8.status__c = 'Active';
		objProjectRole8.Contact__c = con.id;
		objProjectRole8.Role__c = 'PO Contact';
		objProjectRole8.PrimaryContact__c = true;
		objProjectRole8.Opportunity__c = oppt.Id;
		objProjectRole8.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole8);

		insert projectRoles;

		Test.setMock(HttpCalloutMock.class, new DocusignAPIMockHttp());

		Test.startTest();
		String envelopId = DocusignApi.createEnvelope(oppt.Id);

		Test.stopTest();
	}

	@isTest
	static void getLFMergeFields_Test(){
		List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
		Account acc = new Account(Name = 'Test account', billingStreet = 'street');
		insert acc;

		Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
		insert con;

		Project__c project1 = new Project__c(Name = 'The Linux Foundation', Type__c = 'Membership', Category__c = 'Subproject', Status__c = 'Planned', Slug__c = 'testing2');
		insert project1;

		Opportunity oppt = new Opportunity(Name = 'Opportunity testing 1', accountId = acc.Id, StageName = '2. Discovery', Type = 'Renewal', CloseDate = Date.today().addDays(4), Renewal_Opportunity_Closed__c = 'True');
		insert oppt;

		Id pricebookId = Test.getStandardPricebookId();
		PriceBook2 pbk = new PriceBook2(Name = 'testBook', isActive = true);
		insert pbk;

		Product2 prod = new Product2(Name = 'TestP', productcode = 'test');
		insert prod;

		PriceBookEntry standardPbe = new PriceBookEntry(PriceBook2Id = pricebookId, Product2Id = prod.ID, isActive = true, unitPrice = 34);
		insert standardPbe;

		PriceBookEntry pbe = new PriceBookEntry(PriceBook2Id = pbk.Id, isActive = true, Product2Id = prod.ID, unitPrice = 20.0, useStandardPrice = false);
		insert pbe;

		OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = oppt.Id, Quantity = 2, unitPrice = 20, PriceBookEntryId = pbe.ID, Required_Active_LF_Membership__c = true, Projects__c = project1.id);
		insert oli;
		oliList.add(oli);

		List<Project_Role__c> projectRoles = new List<Project_Role__c>();
		Project_Role__c objProjectRole = new Project_Role__c();
		objProjectRole.status__c = 'Active';
		objProjectRole.Contact__c = con.id;
		objProjectRole.Role__c = 'Billing Contact';
		objProjectRole.PrimaryContact__c = true;
		objProjectRole.Opportunity__c = oppt.Id;
		objProjectRole.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole);

		Project_Role__c objProjectRole1 = new Project_Role__c();
		objProjectRole1.status__c = 'Active';
		objProjectRole1.Contact__c = con.id;
		objProjectRole1.Role__c = 'Representative/Voting Contact';
		objProjectRole1.PrimaryContact__c = true;
		objProjectRole1.Opportunity__c = oppt.Id;
		objProjectRole1.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole1);

		Project_Role__c objProjectRole2 = new Project_Role__c();
		objProjectRole2.status__c = 'Active';
		objProjectRole2.Contact__c = con.id;
		objProjectRole2.Role__c = 'Technical Contact';
		objProjectRole2.PrimaryContact__c = true;
		objProjectRole2.Opportunity__c = oppt.Id;
		objProjectRole2.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole2);

		Project_Role__c objProjectRole3 = new Project_Role__c();
		objProjectRole3.status__c = 'Active';
		objProjectRole3.Contact__c = con.id;
		objProjectRole3.Role__c = 'Marketing Contact';
		objProjectRole3.PrimaryContact__c = true;
		objProjectRole3.Opportunity__c = oppt.Id;
		objProjectRole3.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole3);

		Project_Role__c objProjectRole4 = new Project_Role__c();
		objProjectRole4.status__c = 'Active';
		objProjectRole4.Contact__c = con.id;
		objProjectRole4.Role__c = 'Press Contact';
		objProjectRole4.PrimaryContact__c = true;
		objProjectRole4.Opportunity__c = oppt.Id;
		objProjectRole4.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole4);

		Project_Role__c objProjectRole5 = new Project_Role__c();
		objProjectRole5.status__c = 'Active';
		objProjectRole5.Contact__c = con.id;
		objProjectRole5.Role__c = 'Legal Contact';
		objProjectRole5.PrimaryContact__c = true;
		objProjectRole5.Opportunity__c = oppt.Id;
		objProjectRole5.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole5);

		Project_Role__c objProjectRole6 = new Project_Role__c();
		objProjectRole6.status__c = 'Active';
		objProjectRole6.Contact__c = con.id;
		objProjectRole6.Role__c = 'Authorized Signatory';
		objProjectRole6.PrimaryContact__c = true;
		objProjectRole6.Opportunity__c = oppt.Id;
		objProjectRole6.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole6);

		Project_Role__c objProjectRole7 = new Project_Role__c();
		objProjectRole7.status__c = 'Active';
		objProjectRole7.Contact__c = con.id;
		objProjectRole7.Role__c = 'Event Sponsorship';
		objProjectRole7.PrimaryContact__c = true;
		objProjectRole7.Opportunity__c = oppt.Id;
		objProjectRole7.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole7);

		Project_Role__c objProjectRole8 = new Project_Role__c();
		objProjectRole8.status__c = 'Active';
		objProjectRole8.Contact__c = con.id;
		objProjectRole8.Role__c = 'PO Contact';
		objProjectRole8.PrimaryContact__c = true;
		objProjectRole8.Opportunity__c = oppt.Id;
		objProjectRole8.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole8);

		insert projectRoles;

		Test.setMock(HttpCalloutMock.class, new DocusignAPIMockHttp());

		Test.startTest();
		DocusignApi.createEnvelope(oppt.Id);

		Test.stopTest();
	}

	@isTest
	static void sendEnvelop_Test(){
		Docusign_Settings__c setting = new Docusign_Settings__c();
		setting.AccountID__c = '34b9d81f-63d3-48cb-968d-72fc1a9df29f';
		//Docusign_Settings__c setting = Docusign_Settings__c.getOrgDefaults();
		List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
		Account acc = new Account(Name = 'Test account', billingStreet = 'street');
		insert acc;

		Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
		insert con;

		Project__c project1 = new Project__c(Name = 'test Project', Type__c = 'Membership', Category__c = 'Subproject', Status__c = 'Planned', Slug__c = 'testing4');
		insert project1;

		Opportunity oppt = new Opportunity(Name = 'Opportunity testing 1', accountId = acc.Id, StageName = '2. Discovery', Type = 'Renewal', CloseDate = Date.today().addDays(4), Renewal_Opportunity_Closed__c = 'True');
		insert oppt;

		Id pricebookId = Test.getStandardPricebookId();
		PriceBook2 pbk = new PriceBook2(Name = 'testBook', isActive = true);
		insert pbk;

		Product2 prod = new Product2(Name = 'TestP', productcode = 'test');
		insert prod;

		PriceBookEntry standardPbe = new PriceBookEntry(PriceBook2Id = pricebookId, Product2Id = prod.ID, isActive = true, unitPrice = 34);
		insert standardPbe;

		PriceBookEntry pbe = new PriceBookEntry(PriceBook2Id = pbk.Id, isActive = true, Product2Id = prod.ID, unitPrice = 20.0, useStandardPrice = false);
		insert pbe;

		OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = oppt.Id, Quantity = 2, unitPrice = 20, PriceBookEntryId = pbe.ID, Required_Active_LF_Membership__c = true, Projects__c = project1.id);
		insert oli;
		oliList.add(oli);

		List<Project_Role__c> projectRoles = new List<Project_Role__c>();
		Project_Role__c objProjectRole = new Project_Role__c();
		objProjectRole.status__c = 'Active';
		objProjectRole.Contact__c = con.id;
		objProjectRole.Role__c = 'Billing Contact';
		objProjectRole.PrimaryContact__c = true;
		objProjectRole.Opportunity__c = oppt.Id;
		objProjectRole.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole);

		Project_Role__c objProjectRole1 = new Project_Role__c();
		objProjectRole1.status__c = 'Active';
		objProjectRole1.Contact__c = con.id;
		objProjectRole1.Role__c = 'Representative/Voting Contact';
		objProjectRole1.PrimaryContact__c = true;
		objProjectRole1.Opportunity__c = oppt.Id;
		objProjectRole1.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole1);

		Project_Role__c objProjectRole2 = new Project_Role__c();
		objProjectRole2.status__c = 'Active';
		objProjectRole2.Contact__c = con.id;
		objProjectRole2.Role__c = 'Technical Contact';
		objProjectRole2.PrimaryContact__c = true;
		objProjectRole2.Opportunity__c = oppt.Id;
		objProjectRole2.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole2);

		Project_Role__c objProjectRole3 = new Project_Role__c();
		objProjectRole3.status__c = 'Active';
		objProjectRole3.Contact__c = con.id;
		objProjectRole3.Role__c = 'Marketing Contact';
		objProjectRole3.PrimaryContact__c = true;
		objProjectRole3.Opportunity__c = oppt.Id;
		objProjectRole3.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole3);

		Project_Role__c objProjectRole4 = new Project_Role__c();
		objProjectRole4.status__c = 'Active';
		objProjectRole4.Contact__c = con.id;
		objProjectRole4.Role__c = 'Press Contact';
		objProjectRole4.PrimaryContact__c = true;
		objProjectRole4.Opportunity__c = oppt.Id;
		objProjectRole4.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole4);

		Project_Role__c objProjectRole5 = new Project_Role__c();
		objProjectRole5.status__c = 'Active';
		objProjectRole5.Contact__c = con.id;
		objProjectRole5.Role__c = 'Legal Contact';
		objProjectRole5.PrimaryContact__c = true;
		objProjectRole5.Opportunity__c = oppt.Id;
		objProjectRole5.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole5);

		Project_Role__c objProjectRole6 = new Project_Role__c();
		objProjectRole6.status__c = 'Active';
		objProjectRole6.Contact__c = con.id;
		objProjectRole6.Role__c = 'Authorized Signatory';
		objProjectRole6.PrimaryContact__c = true;
		objProjectRole6.Opportunity__c = oppt.Id;
		objProjectRole6.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole6);

		Project_Role__c objProjectRole7 = new Project_Role__c();
		objProjectRole7.status__c = 'Active';
		objProjectRole7.Contact__c = con.id;
		objProjectRole7.Role__c = 'Event Sponsorship';
		objProjectRole7.PrimaryContact__c = true;
		objProjectRole7.Opportunity__c = oppt.Id;
		objProjectRole7.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole7);

		Project_Role__c objProjectRole8 = new Project_Role__c();
		objProjectRole8.status__c = 'Active';
		objProjectRole8.Contact__c = con.id;
		objProjectRole8.Role__c = 'PO Contact';
		objProjectRole8.PrimaryContact__c = true;
		objProjectRole8.Opportunity__c = oppt.Id;
		objProjectRole8.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole8);

		insert projectRoles;

		Test.setMock(HttpCalloutMock.class, new DocusignAPIMockHttp());

		Test.startTest();
		String envelopId = DocusignApi.createEnvelope(oppt.Id);
		//System.assertEquals('test', envelopId);
		DocusignApi.sendEnvelope(envelopId);
		Test.stopTest();
	}

	@isTest
	static void getPreviewURL_Test(){
		Docusign_Settings__c setting = new Docusign_Settings__c();
		setting.AccountID__c = '34b9d81f-63d3-48cb-968d-72fc1a9df29f';
		//Docusign_Settings__c setting = Docusign_Settings__c.getOrgDefaults();
		List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
		Account acc = new Account(Name = 'Test account', billingStreet = 'street');
		insert acc;

		Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
		insert con;

		Project__c project1 = new Project__c(Name = 'test Project', Type__c = 'Membership', Category__c = 'Subproject', Status__c = 'Planned', Slug__c = 'testing3');
		insert project1;

		Opportunity oppt = new Opportunity(Name = 'Opportunity testing 1', accountId = acc.Id, StageName = '2. Discovery', Type = 'Renewal', CloseDate = Date.today().addDays(4), Renewal_Opportunity_Closed__c = 'True');
		insert oppt;

		Id pricebookId = Test.getStandardPricebookId();
		PriceBook2 pbk = new PriceBook2(Name = 'testBook', isActive = true);
		insert pbk;

		Product2 prod = new Product2(Name = 'TestP', productcode = 'test');
		insert prod;

		PriceBookEntry standardPbe = new PriceBookEntry(PriceBook2Id = pricebookId, Product2Id = prod.ID, isActive = true, unitPrice = 34);
		insert standardPbe;

		PriceBookEntry pbe = new PriceBookEntry(PriceBook2Id = pbk.Id, isActive = true, Product2Id = prod.ID, unitPrice = 20.0, useStandardPrice = false);
		insert pbe;

		OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = oppt.Id, Quantity = 2, unitPrice = 20, PriceBookEntryId = pbe.ID, Required_Active_LF_Membership__c = true, Projects__c = project1.id);
		insert oli;
		oliList.add(oli);

		List<Project_Role__c> projectRoles = new List<Project_Role__c>();
		Project_Role__c objProjectRole = new Project_Role__c();
		objProjectRole.status__c = 'Active';
		objProjectRole.Contact__c = con.id;
		objProjectRole.Role__c = 'Billing Contact';
		objProjectRole.PrimaryContact__c = true;
		objProjectRole.Opportunity__c = oppt.Id;
		objProjectRole.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole);

		Project_Role__c objProjectRole1 = new Project_Role__c();
		objProjectRole1.status__c = 'Active';
		objProjectRole1.Contact__c = con.id;
		objProjectRole1.Role__c = 'Representative/Voting Contact';
		objProjectRole1.PrimaryContact__c = true;
		objProjectRole1.Opportunity__c = oppt.Id;
		objProjectRole1.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole1);

		Project_Role__c objProjectRole2 = new Project_Role__c();
		objProjectRole2.status__c = 'Active';
		objProjectRole2.Contact__c = con.id;
		objProjectRole2.Role__c = 'Technical Contact';
		objProjectRole2.PrimaryContact__c = true;
		objProjectRole2.Opportunity__c = oppt.Id;
		objProjectRole2.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole2);

		Project_Role__c objProjectRole3 = new Project_Role__c();
		objProjectRole3.status__c = 'Active';
		objProjectRole3.Contact__c = con.id;
		objProjectRole3.Role__c = 'Marketing Contact';
		objProjectRole3.PrimaryContact__c = true;
		objProjectRole3.Opportunity__c = oppt.Id;
		objProjectRole3.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole3);

		Project_Role__c objProjectRole4 = new Project_Role__c();
		objProjectRole4.status__c = 'Active';
		objProjectRole4.Contact__c = con.id;
		objProjectRole4.Role__c = 'Press Contact';
		objProjectRole4.PrimaryContact__c = true;
		objProjectRole4.Opportunity__c = oppt.Id;
		objProjectRole4.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole4);

		Project_Role__c objProjectRole5 = new Project_Role__c();
		objProjectRole5.status__c = 'Active';
		objProjectRole5.Contact__c = con.id;
		objProjectRole5.Role__c = 'Legal Contact';
		objProjectRole5.PrimaryContact__c = true;
		objProjectRole5.Opportunity__c = oppt.Id;
		objProjectRole5.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole5);

		Project_Role__c objProjectRole6 = new Project_Role__c();
		objProjectRole6.status__c = 'Active';
		objProjectRole6.Contact__c = con.id;
		objProjectRole6.Role__c = 'Authorized Signatory';
		objProjectRole6.PrimaryContact__c = true;
		objProjectRole6.Opportunity__c = oppt.Id;
		objProjectRole6.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole6);

		Project_Role__c objProjectRole7 = new Project_Role__c();
		objProjectRole7.status__c = 'Active';
		objProjectRole7.Contact__c = con.id;
		objProjectRole7.Role__c = 'Event Sponsorship';
		objProjectRole7.PrimaryContact__c = true;
		objProjectRole7.Opportunity__c = oppt.Id;
		objProjectRole7.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole7);

		Project_Role__c objProjectRole8 = new Project_Role__c();
		objProjectRole8.status__c = 'Active';
		objProjectRole8.Contact__c = con.id;
		objProjectRole8.Role__c = 'PO Contact';
		objProjectRole8.PrimaryContact__c = true;
		objProjectRole8.Opportunity__c = oppt.Id;
		objProjectRole8.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole8);

		insert projectRoles;
		Test.setMock(HttpCalloutMock.class, new DocusignAPIMockHttp());

		Test.startTest();
		String envelopId = DocusignApi.createEnvelope(oppt.Id);
		//System.assertEquals('test', envelopId);
		String retType = DocusignApi.getPreviewURL(envelopId);
		Test.stopTest();
		System.assertEquals(null, retType);
	}

	@isTest
	static void voidEnvelop_Test(){
		Docusign_Settings__c setting = new Docusign_Settings__c();
		setting.AccountID__c = '34b9d81f-63d3-48cb-968d-72fc1a9df29f';
		//Docusign_Settings__c setting = Docusign_Settings__c.getOrgDefaults();
		List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
		Account acc = new Account(Name = 'Test account', billingStreet = 'street');
		insert acc;

		Contact con = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
		insert con;

		User standardUser = TestFactory.getUser();

		Project__c project1 = new Project__c(Name = 'test Project', Type__c = 'Membership', Category__c = 'Subproject', Status__c = 'Planned', Project_Signatory__c = standardUser.Id, Slug__c = 'testing5');
		insert project1;

		Opportunity oppt = new Opportunity(Name = 'Opportunity testing 1', accountId = acc.Id, StageName = '2. Discovery', Type = 'Renewal', CloseDate = Date.today().addDays(4), Renewal_Opportunity_Closed__c = 'True');
		insert oppt;

		Id pricebookId = Test.getStandardPricebookId();
		PriceBook2 pbk = new PriceBook2(Name = 'testBook', isActive = true);
		insert pbk;

		Product2 prod = new Product2(Name = 'TestP', productcode = 'test');
		insert prod;

		PriceBookEntry standardPbe = new PriceBookEntry(PriceBook2Id = pricebookId, Product2Id = prod.ID, isActive = true, unitPrice = 34);
		insert standardPbe;

		PriceBookEntry pbe = new PriceBookEntry(PriceBook2Id = pbk.Id, isActive = true, Product2Id = prod.ID, unitPrice = 20.0, useStandardPrice = false);
		insert pbe;

		OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = oppt.Id, Quantity = 2, unitPrice = 20, PriceBookEntryId = pbe.ID, Required_Active_LF_Membership__c = true, Projects__c = project1.id);
		insert oli;
		oliList.add(oli);

		List<Project_Role__c> projectRoles = new List<Project_Role__c>();
		Project_Role__c objProjectRole = new Project_Role__c();
		objProjectRole.status__c = 'Active';
		objProjectRole.Contact__c = con.id;
		objProjectRole.Role__c = 'Billing Contact';
		objProjectRole.PrimaryContact__c = true;
		objProjectRole.Opportunity__c = oppt.Id;
		objProjectRole.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole);

		Project_Role__c objProjectRole1 = new Project_Role__c();
		objProjectRole1.status__c = 'Active';
		objProjectRole1.Contact__c = con.id;
		objProjectRole1.Role__c = 'Representative/Voting Contact';
		objProjectRole1.PrimaryContact__c = true;
		objProjectRole1.Opportunity__c = oppt.Id;
		objProjectRole1.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole1);

		Project_Role__c objProjectRole2 = new Project_Role__c();
		objProjectRole2.status__c = 'Active';
		objProjectRole2.Contact__c = con.id;
		objProjectRole2.Role__c = 'Technical Contact';
		objProjectRole2.PrimaryContact__c = true;
		objProjectRole2.Opportunity__c = oppt.Id;
		objProjectRole2.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole2);

		Project_Role__c objProjectRole3 = new Project_Role__c();
		objProjectRole3.status__c = 'Active';
		objProjectRole3.Contact__c = con.id;
		objProjectRole3.Role__c = 'Marketing Contact';
		objProjectRole3.PrimaryContact__c = true;
		objProjectRole3.Opportunity__c = oppt.Id;
		objProjectRole3.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole3);

		Project_Role__c objProjectRole4 = new Project_Role__c();
		objProjectRole4.status__c = 'Active';
		objProjectRole4.Contact__c = con.id;
		objProjectRole4.Role__c = 'Press Contact';
		objProjectRole4.PrimaryContact__c = true;
		objProjectRole4.Opportunity__c = oppt.Id;
		objProjectRole4.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole4);

		Project_Role__c objProjectRole5 = new Project_Role__c();
		objProjectRole5.status__c = 'Active';
		objProjectRole5.Contact__c = con.id;
		objProjectRole5.Role__c = 'Legal Contact';
		objProjectRole5.PrimaryContact__c = true;
		objProjectRole5.Opportunity__c = oppt.Id;
		objProjectRole5.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole5);

		Project_Role__c objProjectRole6 = new Project_Role__c();
		objProjectRole6.status__c = 'Active';
		objProjectRole6.Contact__c = con.id;
		objProjectRole6.Role__c = 'Authorized Signatory';
		objProjectRole6.PrimaryContact__c = true;
		objProjectRole6.Opportunity__c = oppt.Id;
		objProjectRole6.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole6);

		Project_Role__c objProjectRole7 = new Project_Role__c();
		objProjectRole7.status__c = 'Active';
		objProjectRole7.Contact__c = con.id;
		objProjectRole7.Role__c = 'Event Sponsorship';
		objProjectRole7.PrimaryContact__c = true;
		objProjectRole7.Opportunity__c = oppt.Id;
		objProjectRole7.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole7);

		Project_Role__c objProjectRole8 = new Project_Role__c();
		objProjectRole8.status__c = 'Active';
		objProjectRole8.Contact__c = con.id;
		objProjectRole8.Role__c = 'PO Contact';
		objProjectRole8.PrimaryContact__c = true;
		objProjectRole8.Opportunity__c = oppt.Id;
		objProjectRole8.Opportunity_Line_Item__c = oli.Id;
		projectRoles.add(objProjectRole8);

		insert projectRoles;

		Test.setMock(HttpCalloutMock.class, new DocusignAPIMockHttp());

		Test.startTest();
		String envelopId = DocusignApi.createEnvelope(oppt.Id);
		//System.assertEquals('test', envelopId);
		HttpResponse response = DocusignApi.voidEnvelope(envelopId, 'void msg test');
		System.assertEquals('OK', response.getStatus());
		HttpResponse success = DocusignApi.reSendEnvelope(envelopId);
		System.assertEquals('OK', success.getStatus());
		HttpResponse successOfgetDocument = DocusignApi.getDocument(envelopId);
		System.assertEquals('OK', successOfgetDocument.getStatus());
		Test.stopTest();
	}
}