force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_PO_Required__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_PO_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opportunity PO Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
                <default>true</default>
                <label>Net 30</label>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 65</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Payment Due Immediately</fullName>
            </value>
            <value>
                <fullName>Payment Due Prior To Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores the category for Risc-v</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Text that will be displayed on invoice</description>
    <inlineHelpText>Text that will be displayed on invoice</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <formula>TEXT(Opportunity.PaymentTerms__c)</formula>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Android Development Training</fullName>
            </value>
            <value>
                <fullName>Enterprise IT &amp; Linux System Administration Training</fullName>
            </value>
            <value>
                <fullName>Linux Programming &amp; Development Training</fullName>
            </value>
            <value>
                <fullName>Open Source Compliance Courses</fullName>
            </value>
            <value>
                <fullName>Tizen Project Training</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
            <value>
                <fullName>Straight Line</fullName>
                <isActive>false</isActive>
                <label>Straight Line</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <formula>IF(Project__c != null ,Project__r.Subsidiary_ID__c , Event__r.BillFromProject__r.Subsidiary_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A one-sentence description of the project, which will be used for external facing (i.e. landscape graphic or a website list of LF projects) descriptions of projects.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Do_not_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Do_not_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, memberships will not be invoiced</inlineHelpText>
    <label>Do not Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/Project_Role__c.object-meta.xml
<CustomObject>
    <label>Membership Roles</label>
    <nameField>
        <displayFormat>PR{000}</displayFormat>
        <label>Role AutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Role__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Membership Roles</relationshipLabel>
    <relationshipName>Membership_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Services (Fab, design services)</fullName>
    </customValue>
    <customValue>
        <fullName>Chip (SoC, IP, FPGA)</fullName>
    </customValue>
    <customValue>
        <fullName>I/O (Memory, network, storage)</fullName>
    </customValue>
    <customValue>
        <fullName>Systems (ODM, OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Software (Dev tools, firmware, OS)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry (cloud, mobile, HPC, ML, automotive)</fullName>
    </customValue>
    <customValue>
        <fullName>Research (Universities, Labs, other alliances, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <description>Account Project Category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NetSuite_Deferred_Revenue_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>284</fullName>
        <label>Deferred Revenue : Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>282</fullName>
        <label>Deferred Revenue : Deferred Revenue - Membership</label>
    </customValue>
    <customValue>
        <fullName>4494</fullName>
        <label>Deferred Revenue : Deferred Revenue - Directed Funds</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Other</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Membership</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Membership</label>
    </customValue>
    <masterLabel>NetSuite Deferred Revenue Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NetSuite_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Events</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Training</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Training (Linux Labs)</label>
    </customValue>
    <masterLabel>NetSuite Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/createQuoteOnRenewalOf_OppBatch_Test.cls
@isTest
public class createQuoteOnRenewalOf_OppBatch_Test {
    @isTest
    public static void createQuoteonRenewal(){
        //Account
        Account account = TestDataUtils.createAccount(false,'Test Account');
        account.billingCountry = 'brasil';
        account.billingStreet = 'new';
        insert account ;
        
        //Contact
        Contact contact = new Contact(lastname = 'testContact', email = 'testcontactno@gmail.com', accountid = account.id);
        insert contact;
  
        Opportunity opportunity = new Opportunity(Name = 'Test',
                                           AccountId = account.Id,
                                           CloseDate = Date.newInstance(2023, 9, 8),
                                           StageName = '5. Decision Commitment',
                                           Type = 'Renewal',
                                           PaymentTerms__c = 'Net 30',
                                           SyncedQuoteId = null,
                                           RecordTypeId = '01241000000Zut4AAC',
                                           Opportunity_PO_Required__c = true);
        insert opportunity;
        
		//Product
        Product2 prod = TestDataUtils.createProduct(true,'Laptop X2001','Test Product',true,'Membership');
        //PriceBookEntry
        PricebookEntry standardPrice = TestDataUtils.createPriceBookEntryID(true,prod.Id);
        
        //Project
        Project__c prj = new Project__c(Name = 'testing11', Do_not_Invoice__c = true,Status__c = 'Planned',Category__c = 'Subproject', Subsidiary_ID__c = 8, Project_code__c = 'LF',slug__c='vccu');
        insert prj;
        
        //Product Details
        Product_Details__c productDetail = new Product_Details__c();
        productDetail.Price__c = 56;
        productDetail.NS_Income_GL_Account__c = '290';
        productDetail.NS_Deferred_Revenue_Account__c = '284';
        productDetail.NS_Department__c = '10';
        productDetail.NS_Revenue_Schedule__c = '29';
        productDetail.Netsuite_Sync__c = false;
        productDetail.Duration__c = '45';
        productDetail.Description__c = 'Description_Test';
        productDetail.Tier__c = 'Test';
        productDetail.Netsuite_ID__c = '889955';
        productDetail.Project__c = prj.id;
        productDetail.Products__c = prod.id;
        insert productDetail;
        
        OpportunityLineItem opportunitylineitem = TestDataUtils.createOpportunityProduct(false,opportunity.Id,standardPrice.Id);        
        opportunitylineitem.start_date__c = Date.newInstance(2016, 8, 1);
        opportunitylineitem.end_date__c = date.today().addDays(2);
        opportunitylineitem.Projects__c = prj.Id;
        opportunitylineitem.Product_Details__c = productDetail.id;
        opportunitylineitem.PO_Number__c = '8899774455';
        insert opportunitylineitem;
        
        //Project Roles
        List<Project_Role__c> projectRoles = new List<Project_Role__c>();
        Project_Role__c billingRole =  TestDataUtils.createProjectRole(false,contact.id,'Billing Contact',opportunity.Id,opportunitylineitem.Id,null,true);
        projectRoles.add(billingRole);
        
        Project_Role__c votingRole =  TestDataUtils.createProjectRole(false,contact.id,'Representative/Voting Contact',opportunity.Id,opportunitylineitem.Id,null,true);
        projectRoles.add(votingRole);
        insert projectRoles;
                             
        Test.startTest();
        createQuoteOnRenewalOf_POReqd_OppBatch obj = new createQuoteOnRenewalOf_POReqd_OppBatch();
        database.executeBatch(obj);
        Test.stopTest();
    }
}