force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Authorized_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorized Signatory</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the membership/sponsorship/training items are to be billed to an Account other than the receiving Account.</description>
    <inlineHelpText>If the membership/sponsorship/training items are to be billed to an Account other than the receiving Account.</inlineHelpText>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Authorized_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Signatory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorized Signatory</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Product (Authorized Signatory)</relationshipLabel>
    <relationshipName>Opportunity_ProductAygk</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores the category for Risc-v</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Required_Active_LF_Membership__c.field-meta.xml
<CustomField>
    <fullName>Required_Active_LF_Membership__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required Active LF Membership</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Android Development Training</fullName>
            </value>
            <value>
                <fullName>Enterprise IT &amp; Linux System Administration Training</fullName>
            </value>
            <value>
                <fullName>Linux Programming &amp; Development Training</fullName>
            </value>
            <value>
                <fullName>Open Source Compliance Courses</fullName>
            </value>
            <value>
                <fullName>Tizen Project Training</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/External_Contract_Signed_Notification__c.field-meta.xml
<CustomField>
    <fullName>External_Contract_Signed_Notification__c</fullName>
    <label>External Contract Signed Notification</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/External_Individual_Contract_Signed__c.field-meta.xml
<CustomField>
    <fullName>External_Individual_Contract_Signed__c</fullName>
    <description>This Email send to JoinNowindiviual submission user when they sign the contract</description>
    <label>External Individual Contract Signed</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Services (Fab, design services)</fullName>
    </customValue>
    <customValue>
        <fullName>Chip (SoC, IP, FPGA)</fullName>
    </customValue>
    <customValue>
        <fullName>I/O (Memory, network, storage)</fullName>
    </customValue>
    <customValue>
        <fullName>Systems (ODM, OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Software (Dev tools, firmware, OS)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry (cloud, mobile, HPC, ML, automotive)</fullName>
    </customValue>
    <customValue>
        <fullName>Research (Universities, Labs, other alliances, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <description>Account Project Category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DocusignRecipientStatusTrigger_Test.cls
/********************************************************
 * Created by: Martand Atrey @ CloudRoute Solutions
 * Created Date: 04-11-2019.
 * Description: DocusignRecipientStatusTrigger_Test
 ********************************************************/
@isTest
public class DocusignRecipientStatusTrigger_Test{
	@testSetup
	public static void createTestData(){


		Account a = new Account(Name = 'testAccount ');
		insert a;
		Contact con = new Contact(FirstName = 'Test ', lastname = 'testCreateAsset', email = 'AssetonClosedWon@gmail.com', accountid = a.id);
		insert con;
		/*
		 PricebookEntry pbID = new PricebookEntry();
		 pbID.Pricebook2Id = Test.getStandardPricebookId();
		 pbID.Product2 = [select Id from Product2 limit 1];
		 insert pbID;*/
		Opportunity o = new Opportunity();
		Id membershipRecordId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Membership').getRecordTypeId();
		o.RecordTypeId = membershipRecordId;
		o.AccountId = a.Id;
		o.Name = 'Individual Membership test';
		o.StageName = '2. Discovery';
		o.Type = 'New Business';
		o.CloseDate = date.today();
		o.Bill_To_Account__c = a.Id;
		o.Authorized_Signatory__c = con.Id;
		insert o;

		OpportunityContactRole ocr = new OpportunityContactRole(opportunityid = o.id, contactid = con.id, role = 'Membership Decision Maker', IsPrimary = True);
		insert ocr;


		Project__c prj = new Project__c(Name = 'testing11', Status__c = 'Planned', Subsidiary_ID__c = 8, Category__c = 'LF Supported', Slug__c = 'testing', External_Individual_Contract_Signed__c = 'Test [ProjectName] [UserFirstName] ');
		insert prj;

		PriceBook2 pbk = new PriceBook2(Name = 'testBook', isActive = true);
		insert pbk;

		Product2 prod = new Product2(Name = 'TestP', productcode = 'test');
		insert prod;

		PriceBookEntry standardPbe = new PriceBookEntry(PriceBook2Id = Test.getStandardPricebookId(), Product2Id = prod.ID, isActive = true, unitPrice = 34);
		insert standardPbe;

		PriceBookEntry pbe = new PriceBookEntry(PriceBook2Id = pbk.Id, isActive = true, Product2Id = prod.ID, unitPrice = 20.0, useStandardPrice = false);
		insert pbe;

		OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = o.Id, Quantity = 2, unitPrice = 20, PriceBookEntryId = pbe.ID, Required_Active_LF_Membership__c = true, Projects__c = prj.id);
		insert oli;

		dsfs__DocuSign_Status__c ds = new dsfs__DocuSign_Status__c(dsfs__Envelope_Status__c = 'Sent', dsfs__Opportunity__c = o.id);
		insert ds;
	}
	static testMethod void testIndividualSendEmail(){
		dsfs__DocuSign_Status__c ds = [SELECT ID
		                               FROM dsfs__DocuSign_Status__c
		                               LIMIT 1];

		dsfs__DocuSign_Recipient_Status__c drs = new dsfs__DocuSign_Recipient_Status__c(dsfs__DocuSign_Recipient_Email__c = 'test@test.com', Name = 'Test Name', dsfs__Parent_Status_Record__c = ds.Id, dsfs__DocuSign_Recipient_Id__c = 'esasd', dsfs__Recipient_Status__c = 'Sent', dsfs__DocuSign_Routing_Order__c = 1);
		insert drs;
		drs.dsfs__Recipient_Status__c = 'Completed';
		update drs;
		delete drs;
	}
	static testMethod void testSendEmailForContractReview(){
		dsfs__DocuSign_Status__c ds = [SELECT ID
		                               FROM dsfs__DocuSign_Status__c
		                               LIMIT 1];

		Project__c prj = [SELECT Id
		                  FROM Project__c
		                  LIMIT 1];
		prj.External_Individual_Contract_Signed__c = '';
		update prj;
		dsfs__DocuSign_Recipient_Status__c drs = new dsfs__DocuSign_Recipient_Status__c(dsfs__DocuSign_Recipient_Email__c = 'test@test.com', Name = 'Test Name', dsfs__Parent_Status_Record__c = ds.Id, dsfs__DocuSign_Recipient_Id__c = 'esasd', dsfs__Recipient_Status__c = 'Sent', dsfs__DocuSign_Routing_Order__c = 1);
		insert drs;
		drs.dsfs__Recipient_Status__c = 'Completed';
		update drs;
		System.assertEquals(1, Limits.getEmailInvocations(), 'Email must have been sent');

		delete drs;
	}
	static testMethod void testSendEmailForNonIndividual(){
		dsfs__DocuSign_Status__c ds = [SELECT ID
		                               FROM dsfs__DocuSign_Status__c
		                               LIMIT 1];

		Opportunity opp = [SELECT Id
		                   FROM Opportunity
		                   LIMIT 1];
		opp.Name = 'Test';
		update opp;
		Project__c prj = [SELECT Id
		                  FROM Project__c
		                  LIMIT 1];
		prj.External_Individual_Contract_Signed__c = '';
		prj.External_Contract_Signed_Notification__c = 'Test [ProjectName] [UserFirstName] ';
		update prj;
		Test.startTest();
		dsfs__DocuSign_Recipient_Status__c drs = new dsfs__DocuSign_Recipient_Status__c(dsfs__DocuSign_Recipient_Email__c = 'test@test.com', Name = 'Test Name', dsfs__Parent_Status_Record__c = ds.Id, dsfs__DocuSign_Recipient_Id__c = 'esasd', dsfs__Recipient_Status__c = 'Sent', dsfs__DocuSign_Routing_Order__c = 1);
		insert drs;
		drs.dsfs__Recipient_Status__c = 'Completed';
		update drs;
		System.assertEquals(1, Limits.getEmailInvocations(), 'Email must have been sent');

		delete drs;
		Test.stopTest();
	}
}