force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Community_Bridge_Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Community_Bridge_Event_Id__c</fullName>
    <description>This Field will store community Bridge Event Id on Event Object to add Beneficiary.</description>
    <label>Community Bridge Event Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Expensify_Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>Expensify_Policy_ID__c</fullName>
    <label>Expensify Policy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/Travel_Fund_Request__c.object-meta.xml
<CustomObject>
    <label>Travel Fund Request</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Fund Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approved_Amount__c</fullName>
    <label>Approved Amount</label>
    <summarizedField>Travel_Fund_Request_Line_Item__c.Cost__c</summarizedField>
    <summaryFilterItems>
        <field>Travel_Fund_Request_Line_Item__c.Line_Status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Travel_Fund_Request_Line_Item__c.Travel_Fund_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/CommunityBridge_Status__c.field-meta.xml
<CustomField>
    <fullName>CommunityBridge_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CommunityBridge Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Travel Fund Requests</relationshipLabel>
    <relationshipName>Travel_Fund_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Travel Fund Requests</relationshipLabel>
    <relationshipName>Travel_Fund_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Expensify_ID__c.field-meta.xml
<CustomField>
    <fullName>Expensify_ID__c</fullName>
    <label>Expensify ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting Approval</fullName>
            </value>
            <value>
                <fullName>Request Approved - Waiting For Expense Report</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Expense Report Received - Waiting Final Approval</fullName>
            </value>
            <value>
                <fullName>Problem With Expense Report</fullName>
            </value>
            <value>
                <fullName>Expense Report Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Transferred to Another Event</fullName>
            </value>
            <value>
                <fullName>Unable to Use Funds</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>ExpenseReportWaitingFinal</fullName>
                <isActive>false</isActive>
                <label>ExpenseReportWaitingFinal</label>
            </value>
            <value>
                <fullName>InitialApproval</fullName>
                <isActive>false</isActive>
                <label>InitialApproval</label>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
                <isActive>false</isActive>
                <label>Partially Approved</label>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
                <isActive>false</isActive>
                <label>Partially Paid</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddBeneficiaryfromTravelFundHandler.cls
public class AddBeneficiaryfromTravelFundHandler implements Queueable,Database.AllowsCallouts {
    private list<Travel_Fund_Request__c> travelFundList;
    static list<Travel_Fund_Request__c> trvelFundUpdateList=new list<Travel_Fund_Request__c>();
    //Constructer to Set Travel Fund List
    public AddBeneficiaryfromTravelFundHandler(list<Travel_Fund_Request__c> trvlFundList) {        
        this.travelFundList=trvlFundList;        
    }
    //Executing Add Beneficiary into Funding Bridge
    public void execute(QueueableContext context) {
        AddBeneficiaryfromTravelFundHandler.addBeneficiary(travelFundList);
    }
    //Making a Callout from Saleforce once Travel Fund Status changes to Request Approved - Waiting For Expense Report
    public static void addBeneficiary(list<Travel_Fund_Request__c> travelFundList){
        list<Travel_Fund_Request__c> trvelFundList=[select Id,CommunityBridge_Status__c,Approved_Amount__c,
                                                    	ContactEmail__c,Event__r.Expensify_Policy_ID__c ,Contact__r.firstname,Contact__r.lastName,Event__r.Community_Bridge_Event_Id__c,Event__r.Name,FirstName__c,Expensify_ID__c,Status__c 
                                                    FROM 
                                                    	Travel_Fund_Request__c 
                                                    WHERE 
                                                    	Id IN:travelFundList];
        try{
            for(Travel_Fund_Request__c trvlFundObj:trvelFundList) {
                if(trvlFundObj.Status__c.equals('Request Approved - Waiting For Expense Report')){
                    Http http = new Http();
                    HttpRequest request = new HttpRequest();
                    request.setEndpoint('callout:CommunityBridge/'+ trvlFundObj.Event__r.Community_Bridge_Event_Id__c+'/addbeneficiary');
                    JSONGenerator gen = JSON.createGenerator(true);        
                    gen.writeStartObject();        
                    gen.writeStringField('name', trvlFundObj.Contact__r.firstname+' '+trvlFundObj.Contact__r.lastName);
                    gen.writeStringField('email', trvlFundObj.ContactEmail__c);
                    gen.writeEndObject();        
                    request.setMethod('POST');
                    request.setHeader('x-beneficiary-auth',System.Label.Beneficiary_Authentication);        
                    request.setBody(gen.getAsString());
                    request.setTimeout(120000);
                    HttpResponse response = http.send(request);
                    if(response.getStatusCode()==200){
                        trvlFundObj.CommunityBridge_Status__c=true;            
                        trvelFundUpdateList.add(trvlFundObj);//upsert trvlFundObj;
                    }                
                    System.debug('Res'+response.getBody());
                    System.debug(response.getStatusCode());
                }
            }
            if(trvelFundUpdateList.size()>0){
                RecursiveTriggerHandler.isFirstTime=false;
                update trvelFundUpdateList;
            }            
        }catch(exception ex){
            system.debug(logginglevel.ERROR,ex.getLineNumber()+'ERROR in AddBeneficiaryfromTravelFundHandler.addBeneficiary::'+ex);
        }
    }
}