force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Edx</fullName>
            </value>
            <value>
                <fullName>Panorama</fullName>
            </value>
            <value>
                <fullName>SugarCRM</fullName>
            </value>
            <value>
                <fullName>TI</fullName>
            </value>
            <value>
                <fullName>TI SCORM</fullName>
            </value>
            <value>
                <fullName>TI Panorama</fullName>
            </value>
            <value>
                <fullName>TI Other</fullName>
            </value>
            <value>
                <fullName>TI Purchase</fullName>
            </value>
            <value>
                <fullName>QuickStart</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Enrolled - Update status for , Course_purchase and when enrollment date is added
Started - Update status for Course_start and when start date is added
Completed -Update status for Course_complete and completed date is added
Expired - If complete date is null and Expired date is in past
Revoked - update for revoke_access
Not started - multiple enrollments when there is an record already with above statuses enrolled, started</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Not started</fullName>
            </value>
            <value>
                <fullName>Not Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchEnrollmentUpdateStatusTest.cls
@isTest
public class BatchEnrollmentUpdateStatusTest {
    
    @testsetup
    private static void setup(){
        
        Product2 product = new Product2(Name = 'Laptop X400', Family = 'Training');
        insert product;
        
        Account account = new Account();
        account.Name = 'Test Account';
        insert account;
        
        Contact contact = new Contact();
        contact.AccountId = account.Id;
        contact.LastName = 'Test Contact';
        contact.Email = 'testcontact@noreply.com';
        
        List<Enrollment__c> enrollments = new List<Enrollment__c>();
        
        Enrollment__c enrollment = new Enrollment__c();
        enrollment.Name = 'Test enrollment';
        enrollment.Contact_Name__c = contact.Id;        
        enrollment.Product_Name__c = product.Id;        
        enrollment.Source__c ='TI Other';
        enrollment.Status__c = 'Enrolled';
        enrollment.Start_Date__c = Date.today();
        enrollments.add(enrollment);
        insert enrollments;
    }
    
    @isTest
    static void enrollment_batch(){
        Test.startTest();
        Database.executeBatch(new BatchEnrollmentUpdateStatus());
        Test.stopTest();
        System.assertEquals('Started', [SELECT ID,Status__c FROM Enrollment__c LIMIT 1].Status__c);
    }
    
    @isTest
    static void schedule_test(){
        Test.startTest();
        String sch = '0 0 23 * * ?';
		String jobId = system.schedule('ScheduledApexTest', sch, new BatchEnrollmentUpdateStatus() );        
        Test.stopTest(); 
        System.assert(String.isNotBlank(jobId));
    }

}