force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Opportunity_Closed__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity_Closed__c</fullName>
    <label>Renewal Opportunity Closed</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores the category for Risc-v</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>zzProject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
            <value>
                <fullName>01241000001E0UhAAK</fullName>
                <isActive>false</isActive>
                <label>01241000001E0UhAAK</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Android Development Training</fullName>
            </value>
            <value>
                <fullName>Enterprise IT &amp; Linux System Administration Training</fullName>
            </value>
            <value>
                <fullName>Linux Programming &amp; Development Training</fullName>
            </value>
            <value>
                <fullName>Open Source Compliance Courses</fullName>
            </value>
            <value>
                <fullName>Tizen Project Training</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Course</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>E-Learning</fullName>
            </value>
            <value>
                <fullName>Instructor-Led</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Business_Development_Manager__c.field-meta.xml
<CustomField>
    <fullName>Business_Development_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Development Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects (Business Development Manager)</relationshipLabel>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Days_to_Deduct__c.field-meta.xml
<CustomField>
    <fullName>Days_to_Deduct__c</fullName>
    <defaultValue>&quot;30&quot;</defaultValue>
    <description>All renewals will close 30 days as default. If your project needs to close earlier than 30 days pick a value other than 30. This change will update all open Renewal opportunity&apos;s close date, Except for Year end renewals.</description>
    <inlineHelpText>All renewals will close 30 days as default. If your project needs to close earlier than 30 days pick a value other than 30. This change will update all open Renewal opportunity&apos;s close date.</inlineHelpText>
    <label>Days to Close Renewals</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <default>true</default>
                <label>30</label>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Manual_Status_Check__c.field-meta.xml
<CustomField>
    <fullName>Manual_Status_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Opportunity_Owner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The LF staff member who should own New Business Opportunities for this project. In the Project Control Center, this is the equivalent of the &quot;Membership New Sales Owner.&quot;</inlineHelpText>
    <label>Opportunity Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Program_Manager_U__c.field-meta.xml
<CustomField>
    <fullName>Program_Manager_U__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Manager (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Renewal_Owner__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The LF staff member who should own Renewal Opportunities for this project. In the Project Control Center, this is the equivalent of the &quot;Membership Renewal Owner.&quot;</inlineHelpText>
    <label>Renewal Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Services (Fab, design services)</fullName>
    </customValue>
    <customValue>
        <fullName>Chip (SoC, IP, FPGA)</fullName>
    </customValue>
    <customValue>
        <fullName>I/O (Memory, network, storage)</fullName>
    </customValue>
    <customValue>
        <fullName>Systems (ODM, OEM)</fullName>
    </customValue>
    <customValue>
        <fullName>Software (Dev tools, firmware, OS)</fullName>
    </customValue>
    <customValue>
        <fullName>Industry (cloud, mobile, HPC, ML, automotive)</fullName>
    </customValue>
    <customValue>
        <fullName>Research (Universities, Labs, other alliances, etc)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <description>Account Project Category</description>
    <masterLabel>Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectTriggerHandlerTest.cls
@isTest
public class ProjectTriggerHandlerTest {

    @isTest
    static void createTestMethod(){

        Id MembershipOppId = [Select Id, Name From RecordType Where SobjectType = 'Opportunity' and Name='Membership'].Id;
        //testFactory.getAccount();
        //User objUser = testFactory.getUser();
        
        Account acc= new Account(Name='ABC');
        Contact con = new Contact(
        Email = 'standarduser123@testorg.com',
        FirstName = 'Hal', 
        Lastname = 'Jordan', 
        AccountId = acc.Id, 
        MailingCountry= 'United States');
        insert con ;
        
         UserRole rid = [SELECT ID,Name From UserRole where Name ='Business Operations Manager'][0];
        Profile Standardprofile = [Select Id from Profile where name = 'Standard User'];
         User objUser = new User(
                    ProfileId = Standardprofile.Id,
                    //userRoleId=rid.Id,
                    Username = UserInfo.getOrganizationId() + System.now().millisecond()+'@testorg.com',
                    Alias = 'green',
                    Email = 'standarduser123@testorg.com',
                    EmailEncodingKey = 'UTF-8',
                    Firstname = 'Hal',
                    Lastname = 'Jordan',
                    LanguageLocaleKey = 'en_US',
                    LocaleSidKey = 'en_US',
                    TimeZoneSidKey = 'America/Los_Angeles');
            insert objUser;
      
        //Creating Project Record Id
        Project__c objProject = new Project__c ();
        objProject.Name = 'New Test Project 12';
        objProject.Status__c = 'Planned';
        objProject.Type__c = 'Membership';
        objProject.Manual_Status_Check__c = false; 
        objProject.Category__c ='Incorporated Entity';
        objProject.Days_to_Deduct__c = '30';
        objProject.Slug__c = 'testing';
        objProject.Business_Development_Manager__c = con.ID;
        insert objProject; 

        // Creating Account Record in Test Class 
        Account objAccount = new Account();
        objAccount.Name='Test Acnt Record' ;
        insert objAccount;
        
        // Create Opportunity Record
        Opportunity objOpportunity= new Opportunity(RecordTypeId=MembershipOppId,Name='Opportunity testing 1' , accountId=objAccount.Id , StageName='2. Discovery' ,Type='New Business', CloseDate=Date.today().addDays(4),Renewal_Opportunity_Closed__c='True' );
        insert objOpportunity;
        
        Opportunity objOpportunitytest= new Opportunity(RecordTypeId=MembershipOppId,Name='Opportunity testing 2' , accountId=objAccount.Id , StageName='2. Discovery' ,Type='Renewal', CloseDate=Date.today().addDays(4),Renewal_Opportunity_Closed__c='True');
        insert objOpportunitytest;
        // This is how we get the Standard PriceBook Id.  Prior to Summer '14, we needed
        Id pricebookId = Test.getStandardPricebookId();
        
        //Create your product
        Product2 objprod = new Product2(
            Name = 'Product X',
            ProductCode = 'Pro-X',
            isActive = true
        );
        insert objprod;
        
        //Create your pricebook entry
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = objprod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        
        //create your opportunity line item.  This assumes you already have an opportunity created, called opp
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = objOpportunity.Id,
            Quantity = 5,
            PricebookEntryId = pbEntry.Id,
            TotalPrice = 1 * pbEntry.UnitPrice,
            Projects__c = objProject.id
        );
        insert oli;
        
        OpportunityLineItem objoli = new OpportunityLineItem(
            OpportunityId = objOpportunitytest.Id,
            Quantity = 5,
            PricebookEntryId = pbEntry.Id,
            TotalPrice = 1 * pbEntry.UnitPrice,
            Projects__c = objProject.id
        );
        insert objoli;
        
        objProject.Renewal_owner__c = objUser.Id;  
		objProject.Opportunity_Owner__c = objUser.Id;
        objProject.Program_Manager_U__c = objUser.Id;
        objProject.Status__c='Active';
         objProject.Days_to_Deduct__c = '90';
        update objProject;  
        
    }
    

}