force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Total_Approved_Travel_Funds__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Travel_Funds__c</fullName>
    <description>Should calculate from Travel Fund Request</description>
    <label>Total Approved Travel Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Total_Paid_Travel_Funds__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_Travel_Funds__c</fullName>
    <label>Total Paid Travel Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/Travel_Fund_Request__c.object-meta.xml
<CustomObject>
    <label>Travel Fund Request</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Fund Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Amount_Approved__c.field-meta.xml
<CustomField>
    <fullName>Amount_Approved__c</fullName>
    <label>Amount Approved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Travel Fund Requests</relationshipLabel>
    <relationshipName>Travel_Fund_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Travel Fund Requests</relationshipLabel>
    <relationshipName>Travel_Fund_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Expensify_Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expensify_Approved_Amount__c</fullName>
    <label>Expensify Approved Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Expensify_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expensify_Paid_Amount__c</fullName>
    <label>Expensify Paid Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/First_Approval__c.field-meta.xml
<CustomField>
    <fullName>First_Approval__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Previous_Approval__c.field-meta.xml
<CustomField>
    <fullName>Previous_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Approval</label>
    <referenceTo>Travel_Fund_Request__c</referenceTo>
    <relationshipLabel>Travel Fund Requests</relationshipLabel>
    <relationshipName>Travel_Fund_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Requestor_Key__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Key__c</fullName>
    <description>Requestor Key is the MD5-hash of the Salesforce ID. This is used when the requestor wants to review an existing application and/or upload expenses.</description>
    <externalId>true</externalId>
    <inlineHelpText>Requestor Key is the MD5-hash of the Salesforce ID. This is used when the requestor wants to review an existing application and/or upload expenses.</inlineHelpText>
    <label>Requestor Key</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting Approval</fullName>
            </value>
            <value>
                <fullName>Request Approved - Waiting For Expense Report</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Expense Report Received - Waiting Final Approval</fullName>
            </value>
            <value>
                <fullName>Problem With Expense Report</fullName>
            </value>
            <value>
                <fullName>Expense Report Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Transferred to Another Event</fullName>
            </value>
            <value>
                <fullName>Unable to Use Funds</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>ExpenseReportWaitingFinal</fullName>
                <isActive>false</isActive>
                <label>ExpenseReportWaitingFinal</label>
            </value>
            <value>
                <fullName>InitialApproval</fullName>
                <isActive>false</isActive>
                <label>InitialApproval</label>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
                <isActive>false</isActive>
                <label>Partially Approved</label>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
                <isActive>false</isActive>
                <label>Partially Paid</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TravelFundRequestTriggerHandler.cls
public class TravelFundRequestTriggerHandler implements ITriggerHandler{
    public static void BeforeInsert(List<Sobject> triggerNew) {
        contactInsertIfEmailPresent((List<Travel_Fund_Request__c>) triggerNew);
        updatePreviousApprovals((List<Travel_Fund_Request__c>) triggerNew,null);
        populateRequestorKey((List<Travel_Fund_Request__c>) triggerNew);


    }

    public static void BeforeUpdate(Map<Id, Sobject> newMap, Map<Id, Sobject> oldMap) {
        //call before update actions
        updatePreviousApprovals((List<Travel_Fund_Request__c>)newMap.values(),(Map<Id, Travel_Fund_Request__c>)oldMap);
        populateRequestorKey((List<Travel_Fund_Request__c>)newMap.values());


    }
    public static void BeforeDelete(Map<Id, Sobject> oldMap) {
        //call before delete actions
    }

    public static void AfterInsert(Map<Id, SObject> newMap){
        //call onAfterInsert delete actions
        //RollUpTriggerHandler.rollupHelper((List<Travel_Fund_Request__c>)newMap.values());
        calculateRollupfields((Map<Id, Travel_Fund_Request__c>)newMap,null);
    }
    public static void AfterUpdate(Map<Id, SObject> newMap, Map<Id, Sobject> oldMap){
        //RollUpTriggerHandler.rollupHelper((List<Travel_Fund_Request__c>)newMap.values());
        congaComposerInvoke((Map<Id, Travel_Fund_Request__c>)newMap,(Map<Id, Travel_Fund_Request__c>)oldMap);
        calculateRollupfields((Map<Id, Travel_Fund_Request__c>)newMap,(Map<Id, Travel_Fund_Request__c>)oldMap);
        System.debug('Calling Add Beneficiary now ');
        AddBeneficiaryFromTravelFund((Map<Id, Travel_Fund_Request__c>) newMap,(Map<Id, Travel_Fund_Request__c>) oldMap);
    }

    public static void AfterDelete(Map<Id, Sobject> oldMap) {
        //RollUpTriggerHandler.rollupHelper((List<Travel_Fund_Request__c>)oldMap.values());
        calculateRollupfields(null,(Map<Id, Travel_Fund_Request__c>)oldMap);
    }


    public static void AfterUnDelete(Map<Id, Sobject> newMap) {
        //call after undelete actions
        //RollUpTriggerHandler.rollupHelper((List<Travel_Fund_Request__c>)newMap.values());
        calculateRollupfields((Map<Id, Travel_Fund_Request__c>)newMap,null);
    }

    public Boolean IsDisabled(){
        return false;
    }

    public static void contactInsertIfEmailPresent(List<Travel_Fund_Request__c> triggerNew){

        ContactInsertUtilityClass uc = new ContactInsertUtilityClass();
        uc.contactInsert(triggerNew);
    }


    public static void updatePreviousApprovals(List<Travel_Fund_Request__c> triggerNew,  Map<Id, Travel_Fund_Request__c> oldMap){
/*
        Map<Id,List<Travel_Fund_Request__c>> mapOfContactVsTFR = new Map<Id,List<Travel_Fund_Request__c>>();
        for(Travel_Fund_Request__c tfr : triggerNew){
            if(oldMap == null || (oldMap != null && oldMap.get(tfr.id).Contact__c != tfr.Contact__c)){
                if(!mapOfContactVsTFR.containsKey(tfr.Contact__c)){
                    mapOfContactVsTFR.put(tfr.Contact__c,new List<Travel_Fund_Request__c>{tfr});
                }
                else{
                    mapOfContactVsTFR.get(tfr.Contact__c).add(tfr);
                }
            }
        }
        if(!mapOfContactVsTFR.IsEmpty()){

            List<Travel_Fund_Request__c> travelfundList = [Select Id, Status__c, Contact__c From Travel_Fund_Request__c
            WHERE (First_Approval__c = 'Yes')
            AND  Contact__c IN: mapOfContactVsTFR.keySet()];
            for(Travel_Fund_Request__c tf : travelfundList){

                for(Travel_Fund_Request__c trf : mapOfContactVsTFR.get(tf.Contact__c)){
                    trf.Previous_Approval__c = tf.Id;
                }
            }
        }
*/
        Map<Id,Travel_Fund_Request__c> mapOfContactVsTFR = new Map<Id,Travel_Fund_Request__c>();
        for(Travel_Fund_Request__c tfr : triggerNew){
            if(oldMap == null || (oldMap != null && oldMap.get(tfr.id).Contact__c != tfr.Contact__c)){
                if(!mapOfContactVsTFR.containsKey(tfr.Contact__c)){
                    mapOfContactVsTFR.put(tfr.Contact__c,null);
                }
            }
        }
		system.debug('Map of Contact vs TFR'+mapOfContactVsTFR);
        if(!mapOfContactVsTFR.IsEmpty()){
            List<Travel_Fund_Request__c> travelfundList = [Select Id, Status__c, Contact__c, CreatedDate From Travel_Fund_Request__c WHERE 
	    													Status__c IN ('Paid','Approved') 
            												AND Contact__c IN: mapOfContactVsTFR.keySet()
                                                            AND Approved_Date__c !=Null
	    													Order BY Contact__c,Approved_Date__c DESC];
            
            for(Travel_Fund_Request__c tf : travelfundList){
                if(mapOfContactVsTFR.get(tf.Contact__c) == null){
                    mapOfContactVsTFR.put(tf.Contact__c,tf);
                }
            }
		}
        system.debug('Map of Contact vs TFR after approved TFR query'+mapOfContactVsTFR);
   
        for(Travel_Fund_Request__c tf :triggerNew){
 			if(mapOfContactVsTFR.get(tf.Contact__c) != null){
				tf.Previous_Approval__c = mapOfContactVsTFR.get(tf.Contact__c).Id;
			}	
		}
    }

    public static void populateRequestorKey(List<Travel_Fund_Request__c> triggerNew){
        // respect existing value if e.g. the record was imported with one
        for(Travel_Fund_Request__c tfRequest :triggerNew){
            if(String.isBlank(tfRequest.Requestor_Key__c) || tfRequest.Requestor_Key__c == NULL) {
                System.debug('will generate a new Requestor_Key__c value');
                String salt = String.valueOf(System.now().getTime());
                Blob md5 = Crypto.generateDigest('MD5', Blob.valueOf(salt + tfRequest.Name));

                // to get the 32-char hash String, convert to hex
                String md5string = EncodingUtil.convertToHex(md5);
                System.debug('Hashed version of the md5 will be ' + md5string);

                tfRequest.Requestor_Key__c = md5string;
            }
        }
    }

    public static void congaComposerInvoke(Map<Id, Travel_Fund_Request__c> newMap, Map<Id, Travel_Fund_Request__c> oldMap){
        for(Travel_Fund_Request__c tfRequest:newMap.values()){
            if(oldMap.get(tfRequest.id).Status__c != tfRequest.Status__c) {
                System.debug('Travel_Fund_RequestTrigger found a change in the Status__c value');
                String newStatus = tfRequest.Status__c;
                System.debug('Travel_Fund_RequestTrigger found the new Status__c value to be ' + newStatus);

                if(newStatus == 'Expense Report Approved') {
                    System.debug('Travel_Fund_RequestTrigger because the new Status__c value is Expense Report Approved we will send an email');
                    System.debug('Travel_Fund_RequestTrigger has found the Event Name to be ' + tfRequest.Event__r.Name);
                    String templateId = 'a1Q41000004KJxt'; // default template ID
                    if(tfRequest.Event__r.Name == 'CNCF') {
                        templateId = 'a1Q41000004YRHP';
                    }
                    System.debug('Travel_Fund_RequestTrigger will be using the template with ID of ' + templateId);

                    /*Travel_Fund_RequestHelper helper = new Travel_Fund_RequestHelper();
                    helper.CongaComposerInvocation(tfRequest, templateId);*/
                }
            }
        }
    }
    public static void AddBeneficiaryFromTravelFund(Map<Id, Travel_Fund_Request__c> newMap, Map<Id, Travel_Fund_Request__c> oldMap) {
        list<Travel_Fund_Request__c> listToUpdate = new list<Travel_Fund_Request__c>();
        for(Travel_Fund_Request__c iterate : newMap.Values()) {
            if(iterate.Status__c == 'Request Approved - Waiting For Expense Report' && iterate.status__c != oldMap.get(iterate.Id).Status__c) {
                listToUpdate.add(iterate);
            }
        }
        if(listToUpdate.Size()>0) {
            System.enqueuejob(new AddBeneficiaryfromTravelFundHandler(listToUpdate));
        }
    }
    public static void calculateRollupfields(Map<Id, Travel_Fund_Request__c> newMap, Map<Id, Travel_Fund_Request__c> oldMap){
        system.debug('oldMap-->'+oldMap);
        system.debug('newMap-->'+newMap);
        List<Event__c> lstEvent = new List<Event__c>();
        set<Id> eventIds = new set<Id>();
        Decimal Total_Approved_Travel_Funds =0;
        Decimal Total_Paid_Travel_Funds = 0;
        map<Id,Event__c> mapEvent = new map<Id,Event__c>();
        Travel_Fund_Request__c oldTF = new Travel_Fund_Request__c();
        Travel_Fund_Request__c newTF = new Travel_Fund_Request__c();
        if(oldMap != null && newMap == null) {
            for(Travel_Fund_Request__c objTravelFund : oldMap.values()){
                system.debug('Inside old');
                eventIds.add(objTravelFund.Event__c);
                //oldTF = oldMap.get(objTravelFund.id);
            }
        }
        if(newMap != null){
            for(Travel_Fund_Request__c objTravelFund : newMap.values()){
                if(oldMap !=null){
                    oldTF = oldMap.get(objTravelFund.id);
                }
                if(oldTF.Expensify_Approved_Amount__c != objTravelFund.Expensify_Approved_Amount__c
                        ||oldTF.Expensify_Paid_Amount__c != objTravelFund.Expensify_Paid_Amount__c
                        ||oldTF.Amount_Approved__c != objTravelFund.Amount_Approved__c ){
                    system.debug('Inside New');
                    eventIds.add(objTravelFund.Event__c);
                }
            }
        }
        system.debug('eventIds--->'+eventIds);
        if(eventIds.size()>0){
            for(Travel_Fund_Request__c objTravelFund :[Select Event__r.id,Expensify_Approved_Amount__c,
                    Amount_Approved__c,Expensify_Paid_Amount__c,
                    Event__r.Total_Approved_Travel_Funds__c
            From Travel_Fund_Request__c Where Event__c IN:eventIds])
            {
                
                Event__c objEvent = new Event__c();
                objEvent.Id = objTravelFund.Event__r.id;
                //Total_Approved_Travel_Funds =0;
                //Total_Approved_Travel_Funds =0;
                if(objTravelFund.Expensify_Approved_Amount__c != 0 && objTravelFund.Expensify_Approved_Amount__c != null){
                    system.debug('Inside');
                    Total_Approved_Travel_Funds+=objTravelFund.Expensify_Approved_Amount__c;
                }else if(objTravelFund.Amount_Approved__c != 0 && objTravelFund.Amount_Approved__c != null){
                    Total_Approved_Travel_Funds+= objTravelFund.Amount_Approved__c;
                }
                if(objTravelFund.Expensify_Paid_Amount__c != 0 && objTravelFund.Expensify_Paid_Amount__c != null){
                    Total_Paid_Travel_Funds +=objTravelFund.Expensify_Paid_Amount__c;
                }
                objEvent.Total_Paid_Travel_Funds__c =Total_Paid_Travel_Funds;
                objEvent.Total_Approved_Travel_Funds__c = Total_Approved_Travel_Funds;
                lstEvent.add(objEvent);
                system.debug('');
            }
        }
        if(lstEvent.size()>0){
            mapEvent.putAll(lstEvent);
            update mapEvent.values();
        }
    }
}