force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LF Event</fullName>
            </value>
            <value>
                <fullName>Project Event</fullName>
            </value>
            <value>
                <fullName>3rd Party Event</fullName>
            </value>
            <value>
                <fullName>Non-LF Event</fullName>
            </value>
            <value>
                <fullName>Migrated Data</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Registrations__c.field-meta.xml
<CustomField>
    <fullName>Event_Registrations__c</fullName>
    <label>Event Registrations</label>
    <summaryForeignKey>Event_Registrations__c.Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/Event_Registrations__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registrations__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/fields/Cvent_Registration_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Registration_FirstName__c</fullName>
    <label>Cvent Registration FirstName</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/fields/Cvent_Registration_LastName__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Registration_LastName__c</fullName>
    <label>Cvent Registration LastName</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/fields/Cvent_Registration_RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Registration_RegistrationDate__c</fullName>
    <label>Cvent Registration RegistrationDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/fields/Cvent_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Registration_Status__c</fullName>
    <label>Cvent Registration Status</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <description>Where did this information come from?</description>
    <inlineHelpText>Where did this information come from?</inlineHelpText>
    <label>Data Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cvent</fullName>
            </value>
            <value>
                <fullName>Manual Entry</fullName>
            </value>
            <value>
                <fullName>RegOnline</fullName>
            </value>
            <value>
                <fullName>Eventbrite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Do_not_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Do_not_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, memberships will not be invoiced</inlineHelpText>
    <label>Do not Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Indicates if the project has Membership, Crowdfunding (e.g. LFX Funding), or both. Note that a project may have membership requirements that do not have any fees or funding associated with them. In that case, &apos;Membership&apos; is still selected for this field.</inlineHelpText>
    <label>Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Crowdfunding</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Notifications_Group__c.field-meta.xml
<CustomField>
    <fullName>Notifications_Group__c</fullName>
    <inlineHelpText>The email address of the email group to which Join Now notifications will be sent.  The email address entered here will receive emails when a new Join Now submission is received and when a Join Now contract is fully executed.</inlineHelpText>
    <label>Notifications Group</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CompareEventsControllerTest.cls
//Test Class for CompareEventsController
@isTest
public class CompareEventsControllerTest {
    
    //Method to create TestData
    @TestSetup
    static void createData(){
        //Account
        Account account = new Account();
        account.Name = 'Test Account';
        insert account;
        
        //ContactList
        List<Contact> contactList = new List<Contact>();
        for (Integer i = 0; i < 2; i++) {
            Contact contact = new Contact();
            contact.AccountId = account.Id;
            contact.FirstName = 'Test';
            contact.LastName = 'Contact'+i;
            contact.Email = 'testUnknown@noreply'+i+'.com';
            contactList.add(contact);
        }
        insert contactList;
        
        //ProjectList
        List<Project__c> projects = new List<Project__c>();
        projects.add(new Project__c(Name = 'testing11',Notifications_Group__c = 'test@test.com',Do_Not_Invoice__c = true,Category__c = 'Directed Fund', Subsidiary_ID__c = 8, Project_code__c = 'LF'
                                    ,Status__c='Active',Funding__c='Funded',Slug__c ='testing',Model__c ='Membership'));
        projects.add(new Project__c(Name = 'The Linux Foundation',Slug__c ='tlf',Notifications_Group__c = 'test@test.com',Do_Not_Invoice__c = true, Status__c = 'Planned',Category__c = 'Directed Fund',Subsidiary_ID__c = 8));
        insert projects;
        
        //EventList
        List<Event__c> eventListToInsert = new List<Event__c>();
        for(Integer i=1 ; i<5 ; i++){
            Event__c eventObj = new Event__c(name = 'test event'+i,Status__c = 'Active', 
                                             BillFromProject__c = projects[0].id, End_Date__c = System.today()+1, Start_Date__c = System.today());
            eventListToInsert.add(eventObj);
        }
        insert eventListToInsert;

        //EventRegistrationList
        List<Event_Registrations__c> EventRegListToInsert = new List<Event_Registrations__c>();
        Integer j=0,l=0;
        for (Integer i = 2; i < 8; i++) {
            if( math.mod(i, 2) == 0){
                j++;
                l=0;
            }
            Event_Registrations__c eventReg = new Event_Registrations__c();
            eventReg.Name = 'Test eventReg';
            eventReg.Contact__c = contactList[l].Id;
            eventReg.Event__c = eventListToInsert[j].Id;
            eventReg.Cvent_Registration_FirstName__c = 'test FirstName';
            eventReg.Cvent_Registration_LastName__c = 'test LastName';
            eventReg.Data_Source__c = 'Cvent';
            eventReg.Cvent_Registration_Status__c='Accepted';
            eventReg.Cvent_Registration_RegistrationDate__c=System.today()-1;
            EventRegListToInsert.add(eventReg);
            l++;
        }
        insert EventRegListToInsert;
        
        
    }
    
    //Test Method to Test the Controller
    @isTest
    private static void testCompareEventsController() {
        Event__c event = [SELECT Id FROM Event__c WHERE Event_Registrations__c != 0 Limit 1];
        
        // Actual test
        Test.startTest();
        Map<String, Object> responseMap = CompareEventsController.getAllEvents(JSON.serialize(new List<Id>{event.Id}));
        System.debug('Map<String, Object> responseMap '+ responseMap);
        Test.stopTest();
        // Asserts
        System.assertEquals(true, responseMap.containsKey('Details'));
        System.assertEquals(true, responseMap.containsKey('Events'));  
        
    }
}