force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Left Company</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS__c/EMS__c.object-meta.xml
<CustomObject>
    <label>EMS</label>
    <nameField>
        <label>EMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS__c/fields/Bill_From__c.field-meta.xml
<CustomField>
    <fullName>Bill_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill From</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>EMS</relationshipLabel>
    <relationshipName>EMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/EMS_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Number__c</fullName>
    <label>EMS Number</label>
    <length>31</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>EMS</relationshipLabel>
    <relationshipName>EMS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LF Event</fullName>
            </value>
            <value>
                <fullName>Project Event</fullName>
            </value>
            <value>
                <fullName>3rd Party Event</fullName>
            </value>
            <value>
                <fullName>Non-LF Event</fullName>
            </value>
            <value>
                <fullName>Migrated Data</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Expensify_Policy_ID__c.field-meta.xml
<CustomField>
    <fullName>Expensify_Policy_ID__c</fullName>
    <label>Expensify Policy ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Manual_Status_Check__c.field-meta.xml
<CustomField>
    <fullName>Manual_Status_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Event&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Manual_Status_Check__c.field-meta.xml
<CustomField>
    <fullName>Manual_Status_Check__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Status Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Indicates if the project has Membership, Crowdfunding (e.g. LFX Funding), or both. Note that a project may have membership requirements that do not have any fees or funding associated with them. In that case, &apos;Membership&apos; is still selected for this field.</inlineHelpText>
    <label>Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Crowdfunding</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/Travel_Fund_Request__c.object-meta.xml
<CustomObject>
    <label>Travel Fund Request</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Fund Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Travel Fund Requests</relationshipLabel>
    <relationshipName>Travel_Fund_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting Approval</fullName>
            </value>
            <value>
                <fullName>Request Approved - Waiting For Expense Report</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Expense Report Received - Waiting Final Approval</fullName>
            </value>
            <value>
                <fullName>Problem With Expense Report</fullName>
            </value>
            <value>
                <fullName>Expense Report Approved</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Transferred to Another Event</fullName>
            </value>
            <value>
                <fullName>Unable to Use Funds</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>ExpenseReportWaitingFinal</fullName>
                <isActive>false</isActive>
                <label>ExpenseReportWaitingFinal</label>
            </value>
            <value>
                <fullName>InitialApproval</fullName>
                <isActive>false</isActive>
                <label>InitialApproval</label>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
                <isActive>false</isActive>
                <label>Partially Approved</label>
            </value>
            <value>
                <fullName>Partially Paid</fullName>
                <isActive>false</isActive>
                <label>Partially Paid</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TravelFundExpensifyHandlerTest.cls
@isTest
public class TravelFundExpensifyHandlerTest {
    @isTest
    static void travelFundExpensifyHandler_Test1() {
        
        Test.setMock(HttpCalloutMock.class, new ExpensifyCalloutMockTest());
        
        Contact conRecord = new Contact();
        conRecord.LastName = 'Kumar';
        conRecord.Email = 'sachin.kumar@webuters.com';
        insert conRecord;
        
        //Creating Project Record Id
       //Id directedProjectId = [Select Id, Name From RecordType Where SobjectType = 'Project__c' and Name='Subproject'].Id;
        testFactory.getAccount();
        Project__c testProjObj = new Project__c ();
        testProjObj.Name = 'The Linux Foundation';
        testProjObj.Category__c = 'Subproject';
        testProjObj.Status__c = 'Planned';
        testProjObj.Type__c = 'Membership';
        testProjObj.Slug__c = 'test_slug';
        testProjObj.Manual_Status_Check__c = false;
        testProjObj.Funding__c = 'Funded';
        testProjObj.Model__c = 'Membership';
        insert testProjObj;

        testProjObj.Status__c = 'Active';
        update testProjObj;

        Event__c evtRecord = new Event__c();
        evtRecord.Name = 'My New Event';
        evtRecord.Expensify_Policy_ID__c = '554237F4AB23B96D';
        evtRecord.BillFromProject__c = testProjObj.Id;
        insert evtRecord;
        
        EMS__c ems = new EMS__c();
        ems.Name = ' - Event Management Service';
        ems.Event__c = evtRecord.Id;
        ems.StartDate__c = evtRecord.Start_Date__c;
        ems.Bill_From__c =testProjObj.id;
        ems.EMS_Number__c=evtRecord.name+' '+String.valueOf(Date.today().year()).substring(2,4)+String.valueOf(Date.today().month());
        ems.Product__c = '22';
        ems.EMS_Status__c = 'Not Started';
        ems.NS_Department__c = '2';
        ems.NS_Income_GL_Account__c = evtRecord.NS_Income_GL_Account__c;
        ems.NS_Deferred_Revenue_Account__c = evtRecord.NS_Deferred_Revenue_Account__c;
        ems.NS_Revenue_Schedule__c = evtRecord.NS_Revenue_Schedule__c;
        insert ems;   
        
        List<Travel_Fund_Request__c> my_list = new List<Travel_Fund_Request__c>();
        Travel_Fund_Request__c newTravelFund = new Travel_Fund_Request__c();
        newTravelFund.Name = 'TestCreateTravelFundTest';
        newTravelFund.Status__c = 'Waiting Approval';
        newTravelFund.Event__c = evtRecord.Id;
        newTravelFund.Contact__c = conRecord.Id;
        my_list.add(newTravelFund);
        insert newTravelFund;
        
        Test.startTest();
        TravelFundExpensifyHandler.CreateExpensifyReport(my_list); 
        //TravelFundExpensifyHandler.CreateExpensifyReport(''); 
        Test.stopTest();
    }
    @isTest
    static void travelFundExpensifyHandler_Test2() {
        
        Test.setMock(HttpCalloutMock.class, new ExpensifyCalloutMockTest());
        
        Contact conRecord = new Contact();
        conRecord.LastName = 'Kumar';
        conRecord.Email = 'sachin.kumar@webuters.com';
        insert conRecord;
        
        //Creating Project Record Id
        //Id directedProjectId = [Select Id, Name From RecordType Where SobjectType = 'Project__c' and Name='Subproject'].Id;
        testFactory.getAccount();
        Project__c testProjObj = new Project__c ();
        testProjObj.Name = 'The Linux Foundation';
        testProjObj.Category__c = 'Subproject';
        testProjObj.Status__c = 'Planned';
        testProjObj.Type__c = 'Membership';
        testProjObj.Manual_Status_Check__c = false;
        testProjObj.Slug__c = 'test_slug';
        testProjObj.Funding__c = 'Funded';
        testProjObj.Model__c = 'Membership';
        insert testProjObj;

        testProjObj.Status__c = 'Active';
        update testProjObj;
        
        Event__c evtRecord = new Event__c();
        evtRecord.Name = 'My New Event';
        evtRecord.Expensify_Policy_ID__c = '554237F4AB23B96D';
        evtRecord.BillFromProject__c = testProjObj.Id;
        insert evtRecord;
        
        EMS__c ems = new EMS__c();
        ems.Name = ' - Event Management Service';
        ems.Event__c = evtRecord.Id;
        ems.StartDate__c = evtRecord.Start_Date__c;
        ems.Bill_From__c =testProjObj.id;
        ems.EMS_Number__c=evtRecord.name+' '+String.valueOf(Date.today().year()).substring(2,4)+String.valueOf(Date.today().month());
        ems.Product__c = '22';
        ems.EMS_Status__c = 'Not Started';
        ems.NS_Department__c = '2';
        ems.NS_Income_GL_Account__c = evtRecord.NS_Income_GL_Account__c;
        ems.NS_Deferred_Revenue_Account__c = evtRecord.NS_Deferred_Revenue_Account__c;
        ems.NS_Revenue_Schedule__c = evtRecord.NS_Revenue_Schedule__c;
        insert ems;   
        
        List<Travel_Fund_Request__c> my_list = new List<Travel_Fund_Request__c>();
        Travel_Fund_Request__c newTravelFund = new Travel_Fund_Request__c();
        newTravelFund.Name = 'New Travel Fund';
        newTravelFund.Status__c = 'Request Approved - Waiting For Expense Report';
        newTravelFund.Event__c = evtRecord.Id;
        newTravelFund.Contact__c = conRecord.Id;
        newTravelFund.Amount_Approved__c = 100;
        my_list.add(newTravelFund);
        insert newTravelFund;
        
        Test.startTest();
        RecursiveTriggerHandler.isFirstTime=false;
        TravelFundExpensifyHandler.notifyExpensifyRequestor(my_list); 
        //TravelFundExpensifyHandler.notifyExpensifyRequestor_Apex(''); 
        Test.stopTest();
    }
    @isTest
    static void travelFundExpensifyHandler_Test3() {
        
        Test.setMock(HttpCalloutMock.class, new ExpensifyCalloutMockTest());
        
        Contact conRecord = new Contact();
        conRecord.LastName = 'Kumar';
        conRecord.Email = 'sachin.kumar@webuters.com';
        insert conRecord;
        
        //Creating Project Record Id
        //Id directedProjectId = [Select Id, Name From RecordType Where SobjectType = 'Project__c' and Name='Subproject'].Id;
        testFactory.getAccount();
        Project__c testProjObj = new Project__c ();
        testProjObj.Name = 'The Linux Foundation';
        testProjObj.Category__c = 'Subproject';
        testProjObj.Status__c = 'Planned';
        testProjObj.Type__c = 'Membership';
        testProjObj.Manual_Status_Check__c = false;
        testProjObj.Slug__c = 'test_slug';
        testProjObj.Funding__c = 'Funded';
        testProjObj.Model__c = 'Membership';
        insert testProjObj;

        testProjObj.Status__c = 'Active';
        update testProjObj;
        
        Event__c evtRecord = new Event__c();
        evtRecord.Name = 'My New Event';
        evtRecord.Expensify_Policy_ID__c = '554237F4AB23B96D';
        evtRecord.BillFromProject__c = testProjObj.Id;
        insert evtRecord;
        
        EMS__c ems = new EMS__c();
        ems.Name = ' - Event Management Service';
        ems.Event__c = evtRecord.Id;
        ems.StartDate__c = evtRecord.Start_Date__c;
        ems.Bill_From__c =testProjObj.id;
        ems.EMS_Number__c=evtRecord.name+' '+String.valueOf(Date.today().year()).substring(2,4)+String.valueOf(Date.today().month());
        ems.Product__c = '22';
        ems.EMS_Status__c = 'Not Started';
        ems.NS_Department__c = '2';
        ems.NS_Income_GL_Account__c = evtRecord.NS_Income_GL_Account__c;
        ems.NS_Deferred_Revenue_Account__c = evtRecord.NS_Deferred_Revenue_Account__c;
        ems.NS_Revenue_Schedule__c = evtRecord.NS_Revenue_Schedule__c;
        insert ems;   
        
        List<Travel_Fund_Request__c> my_list = new List<Travel_Fund_Request__c>();
        Travel_Fund_Request__c newTravelFund = new Travel_Fund_Request__c();
        newTravelFund.Name = 'TestCreateTravelFundTest';
        newTravelFund.Status__c = 'Paid';
        newTravelFund.Event__c = evtRecord.Id;
        newTravelFund.Contact__c = conRecord.Id;
        my_list.add(newTravelFund);
        insert newTravelFund;
        
        Expensify_Attachment__c expenAttach = new Expensify_Attachment__c();
        expenAttach.Report_Id__c = '54160232';
        expenAttach.URL__c = 'https://s3.amazonaws.com/receipts.expensify.com/w_45c7f11b2a8e505d79b434102b3d13acaeed090a.jpg';
        expenAttach.Travel_Fund_Request__c = newTravelFund.Id;
        insert expenAttach;
        
        Test.startTest();
        TravelFundExpensifyHandler.updateStatusFromApprovedToReimbursed(newTravelFund.Id); 
        //TravelFundExpensifyHandler.updateStatusFromApprovedToReimbursed(''); 
        Test.stopTest();
    }
}