force-app/main/default/objects/CampaignMember/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <inlineHelpText>Date of last enrollment as related to campaign</inlineHelpText>
    <label>Enrollment Date</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <label>Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Certification_AchievementDate__c.field-meta.xml
<CustomField>
    <fullName>Certification_AchievementDate__c</fullName>
    <label>Certification AchievementDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <inlineHelpText>Completion for Elearning, ILT</inlineHelpText>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <label>Enrollment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Is_Parent_Product_Bootcamp_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Is_Parent_Product_Bootcamp_Campaign__c</fullName>
    <formula>Parent_Product__r.Bootcamp_Campaign__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Parent Product Bootcamp Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Lead_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Name</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Parent_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product_Name__c</fullName>
    <formula>Parent_Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Enrolled - Update status for , Course_purchase and when enrollment date is added
Started - Update status for Course_start and when start date is added
Completed -Update status for Course_complete and completed date is added
Expired - If complete date is null and Expired date is in past
Revoked - update for revoke_access
Not started - multiple enrollments when there is an record already with above statuses enrolled, started</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Not started</fullName>
            </value>
            <value>
                <fullName>Not Certified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnrollmentToCampaignMemberBatch.cls
public class EnrollmentToCampaignMemberBatch implements Database.Batchable<SObject> {
    String query;
    public EnrollmentToCampaignMemberBatch(String parentProductName){
        if(parentProductName != null){
            query='SELECT Id,Parent_Product_Name__c,Product_Code__c,Contact_Name__c,Enrollment_Date__c,Is_Parent_Product_Bootcamp_Campaign__c,'+
                'Lead_Name__c,Certification_AchievementDate__c,Completion_Date__c,Status__c FROM Enrollment__c '+
                'WHERE Parent_Product_Name__c=\'' + parentProductName + '\''+
                ' AND Product_Code__c != null AND '+
                'Enrollment_Date__c != null AND (Contact_Name__c != null OR Lead_Name__c != null)';
        }
    }
    //Start of the batch
    public  Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('query '+query);
        return Database.getQueryLocator(query);
    }
    
    //Execute of Batch
    public void execute(Database.BatchableContext BC,List<Enrollment__c> enrollmentList){
        System.debug('enrollmentList '+enrollmentList.size());
        addEnrollmentsAsCampaignMember(enrollmentList);
    }
    
    //Finish of batch
    public void finish(Database.BatchableContext info){
    }
    public static void addEnrollmentsAsCampaignMember(List<Enrollment__c> enrollmentList){
        
        Map<String,Set<String>> parentCampaignVSProductCodes = new Map<String,Set<String>>();
        Set<String> productCodes = new Set<String>();
        Map<Enrollment__c,String> enrollmentVsProductCode = new Map<Enrollment__c,String>();
        Set<Id> leadContactIdSet = new Set<Id>();
        
        for(Enrollment__c enrollment:enrollmentList){
            String parentCampaignName = enrollment.Parent_Product_Name__c == 'Cloud Engineer Boot Camp' || enrollment.Parent_Product_Name__c == null?
                'Cloud Engineer Boot Camp':
            (enrollment.Parent_Product_Name__c != null && enrollment.Is_Parent_Product_Bootcamp_Campaign__c?
            enrollment.Parent_Product_Name__c : '');
                if(String.isNotBlank(parentCampaignName)){
                    if(!parentCampaignVSProductCodes.containsKey(parentCampaignName)){
                        parentCampaignVSProductCodes.put(parentCampaignName,new Set<String>());
                    }parentCampaignVSProductCodes.get(parentCampaignName).add(enrollment.Product_Code__c);
                    
                    productCodes.add('%' + enrollment.Product_Code__c+'%');
                    String status = enrollment.Status__c == 'Completed'? 'Completed' : 'Enrolled';

                    enrollmentVsProductCode.put( enrollment,parentCampaignName+' '+ enrollment.Product_Code__c+ ' ' + status);
                    
                    if(enrollment.Contact_Name__c != null)
                        leadContactIdSet.add(enrollment.Contact_Name__c);
                    else if(enrollment.Lead_Name__c != null)
                        leadContactIdSet.add(enrollment.Lead_Name__c);
                    
                }
        }
        if(!parentCampaignVSProductCodes.isEmpty()){
            Map<String,CampaignMember> campaignMemberList =
                Utility.addCampaignMember(parentCampaignVSProductCodes,productCodes,enrollmentVsProductCode,leadContactIdSet);
            if(!campaignMemberList.isEmpty()){
                //upsert campaignmembers
                upsert campaignMemberList.values();
            }
        }
    }
}