force-app/main/default/objects/API_Request__c/API_Request__c.object-meta.xml
<CustomObject>
    <label>API Request Log</label>
    <nameField>
        <label>API Request Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Request Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Request__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <label>Request Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cvent_Integration__c/Cvent_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is used to store data related to cvent integration</description>
    <label>Cvent Integration</label>
</CustomObject>

force-app/main/default/objects/Cvent_Integration__c/fields/Cvent_Password__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Password__c</fullName>
    <label>Cvent Password</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cvent_Registration_Log__c/Cvent_Registration_Log__c.object-meta.xml
<CustomObject>
    <label>Cvent Registration Log</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Cvent Registration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cvent Registration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cvent_Registration_Log__c/fields/Cvent_Id__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Id__c</fullName>
    <externalId>true</externalId>
    <label>Cvent Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Cvent_Registration_Log__c/fields/Retrieved__c.field-meta.xml
<CustomField>
    <fullName>Retrieved__c</fullName>
    <label>Retrieved</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cvent_Registration_Log__c/fields/Sfdc_Upsert_Last_Error__c.field-meta.xml
<CustomField>
    <fullName>Sfdc_Upsert_Last_Error__c</fullName>
    <label>Sfdc Upsert Last Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Cvent_Registration_Log__c/fields/Successfully_Processed__c.field-meta.xml
<CustomField>
    <fullName>Successfully_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Successfully Processed ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Cvent_Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Event_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Id of the corresponding Cvent Event record</description>
    <externalId>true</externalId>
    <inlineHelpText>The Id of the corresponding Cvent Event record</inlineHelpText>
    <label>Cvent Event Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event__c/fields/Cvent_Id__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Id of the corresponding Cvent Event record</description>
    <externalId>true</externalId>
    <inlineHelpText>The Id of the corresponding Cvent Event record</inlineHelpText>
    <label>Cvent Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Registrations__c.field-meta.xml
<CustomField>
    <fullName>Event_Registrations__c</fullName>
    <label>Event Registrations</label>
    <summaryForeignKey>Event_Registrations__c.Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Registration_Source__c.field-meta.xml
<CustomField>
    <fullName>Registration_Source__c</fullName>
    <label>Registration Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cvent</fullName>
            </value>
            <value>
                <fullName>RegOnline</fullName>
            </value>
            <value>
                <fullName>EventBrite</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Event&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/Event_Registrations__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registrations__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/fields/Cvent_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Registration_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Cvent Registration Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CventCalloutUtility_Test.cls
@isTest
public with sharing class CventCalloutUtility_Test{
	/**
	 * TestSetup inserting required data for test class
	 */
	@testSetup
	public static void createTestData(){
		Cvent_Integration__c cventIntegration = TestDataUtils.createCventIntegrationSetting(true);
	}
	/*
	 Test Method for SearchCventRegistrationBatch batch
	 */
	@isTest
	static void SearchCventRegistrationBatchTest(){

		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		Database.executeBatch(new SearchCventRegistrationBatch());
		Test.stopTest();
		System.assertEquals(1, [SELECT Id
		                        FROM Cvent_Registration_Log__c
		                        WHERE Cvent_Id__c != null].size(), 'There must be a record');
	}
	/*
	 Test Method for SearchCventRegistrationBatch batch for schedular
	 */
	@isTest
	static void SearchCventRegistrationSchedularTest(){

		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		SearchCventRegistrationBatch searchBatch = new SearchCventRegistrationBatch();
		searchBatch.execute(null);
		Test.stopTest();
		System.assertEquals(1, [SELECT Id
		                        FROM Cvent_Registration_Log__c
		                        WHERE Cvent_Id__c != null].size(), 'There must be a record');
	}
	/*
	 Test Method for SearchCventRegistrationBatch batch for exception
	 */
	@isTest
	static void SearchBatchExceptionTest(){

		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Cvent_Integration__c cventIntegration = Cvent_Integration__c.getOrgDefaults();
		cventIntegration.Cvent_Password__c = 'expired';
		update cventIntegration;
		Test.startTest();
		try{
			Database.executeBatch(new SearchCventRegistrationBatch());
		} catch (Exception e){
		}
		Test.stopTest();
		System.assertEquals(false, [select id, Source__c, Request_Body__c, createddate
		                            from API_Request__c
		                            where source__c like '%cvent%'].isEmpty(), 'There must be a record');
	}
	/*
	 Test Method for SearchCventRegistrationBatch batch for exception
	 */
	@isTest
	static void SearchBatchExceptionTest1(){

		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Cvent_Integration__c cventIntegration = Cvent_Integration__c.getOrgDefaults();
		cventIntegration.Cvent_Password__c = 'TestSearch';
		update cventIntegration;
		Test.startTest();
		try{
			Database.executeBatch(new SearchCventRegistrationBatch());
		} catch (Exception e){
		}
		Test.stopTest();
		System.assertEquals(false, [select id, Source__c, Request_Body__c, createddate
		                            from API_Request__c
		                            where source__c like '%cvent%'].isEmpty(), 'There must be a record');
	}
	/*
	 Test Method for SearchCventRegistrationBatch batch for exception
	 */
	@isTest
	static void SearchBatchExceptionTest2(){

		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Cvent_Integration__c cventIntegration = Cvent_Integration__c.getOrgDefaults();
		cventIntegration.Cvent_Password__c = 'error';
		update cventIntegration;
		Test.startTest();
		try{
			Database.executeBatch(new SearchCventRegistrationBatch());
		} catch (Exception e){
		}
		Test.stopTest();
		System.assertEquals(false, [select id, Source__c, Request_Body__c, createddate
		                            from API_Request__c
		                            where source__c like '%cvent%'].isEmpty(), 'There must be a record');
	}
	/*
	 Test Method for RetrieveRegistrationsFromCventBatch
	 */
	@isTest
	static void RetrieveRegistrationsFromCventBatchTest(){
		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(true, 'TestSearchId45768', 'Registration');
		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		Database.executeBatch(new RetrieveRegistrationsFromCventBatch());
		Test.stopTest();
		System.assertEquals(1, [SELECT Id
		                        FROM Cvent_Registration_Log__c
		                        WHERE Retrieved__c != null].size(), 'There must be a record');
	}
	/*
	 Test Method for RetrieveRegistrationsFromCventBatch batch for exception
	 */
	@isTest
	static void RetrieveBatchExceptionTest(){

		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Cvent_Integration__c cventIntegration = Cvent_Integration__c.getOrgDefaults();
		cventIntegration.Cvent_Password__c = 'exception';
		update cventIntegration;
		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(true, 'TestSearchId45768', 'Registration');
		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		String query = 'SELECT Id, Cvent_Id__c FROM Cvent_Registration_Log__c WHERE Cvent_Id__c != null AND Retrieved__c = null AND Type__c = \'Registration\'';
		Database.executeBatch(new RetrieveRegistrationsFromCventBatch(query));
		Test.stopTest();
		System.assertEquals(true, ![select id, Source__c, Request_Body__c, createddate
		                            from API_Request__c
		                            where source__c like '%cvent%'].isEmpty(), 'There must be a record');
	}
	/*
	 Test Method for RetrieveRegistrationsFromCventBatch batch for exception
	 */
	@isTest
	static void RetrieveBatchExceptionTest1(){

		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(true, 'TestSessionExpired', 'Registration');
		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		String query = 'SELECT Id, Cvent_Id__c FROM Cvent_Registration_Log__c WHERE Cvent_Id__c != null AND Retrieved__c = null AND Type__c = \'Registration\'';
		Database.executeBatch(new RetrieveRegistrationsFromCventBatch(query));
		Test.stopTest();
		System.assertEquals(true, ![select id, Source__c, Request_Body__c, createddate
		                            from API_Request__c
		                            where source__c like '%cvent%'].isEmpty(), 'There must be a record');
	}
	/*
	 Test Method for RetrieveRegistrationsFromCventBatch batch for exception
	 */
	@isTest
	static void RetrieveBatchExceptionTest2(){

		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(true, 'TestSessionExpiredForContact', 'Registration');
		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		String query = 'SELECT Id, Cvent_Id__c FROM Cvent_Registration_Log__c WHERE Cvent_Id__c != null AND Retrieved__c = null AND Type__c = \'Registration\'';
		Database.executeBatch(new RetrieveRegistrationsFromCventBatch(query));
		Test.stopTest();
		System.assertEquals(true, ![select id, Source__c, Request_Body__c, createddate
		                            from API_Request__c
		                            where source__c like '%cvent%'].isEmpty(), 'There must be a record');
	}
	/*
	 Test Method for batch : when there is no record in salesforce with the registration email
	 */
	@isTest
	static void noRecordInSFWithEmail_Test(){
		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		testDataForCventRegistrationBatch();

		Database.executeBatch(new RetrieveRegistrationsFromCventBatch());

		Test.stopTest();
		System.assertEquals(1, [SELECT Id
		                        FROM Event_registrations__c
		                        WHERE Cvent_Registration_Id__c != null].size(), 'There must be an event registration');
	}
	/*
	 Test Method for CventRegistrationBatch Exception on cventLog record
	 */
	@isTest
	static void CventRegistrationError_Test(){
		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(true, 'TestWrongEmail', 'Registration');
		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		Database.executeBatch(new RetrieveRegistrationsFromCventBatch());
		Test.stopTest();
		System.assertNotEquals(null, [SELECT Id, Sfdc_Upsert_Last_Error__c
		                              FROM Cvent_Registration_Log__c
		                              WHERE Cvent_Id__c = 'TestWrongEmail'].Sfdc_Upsert_Last_Error__c, 'Error must be populated on cventLog Record');
	}
	/*
	 Test Method for CventRegistrationBatch Exception on cventLog record for contact details
	 */
	@isTest
	static void CventRegistrationErrorForContact_Test(){
		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(true, 'TestWrongContact', 'Registration');
		Test.setMock(WebServiceMock.class, new CventSyncMock());
		Test.startTest();
		Database.executeBatch(new RetrieveRegistrationsFromCventBatch());
		Test.stopTest();
		System.assertNotEquals(null, [SELECT Id, Sfdc_Upsert_Last_Error__c
		                              FROM Cvent_Registration_Log__c
		                              WHERE Cvent_Id__c = 'TestWrongContact'].Sfdc_Upsert_Last_Error__c, 'Error must be populated on cventLog Record for contact details');
	}
	/*
	 Test Method for batch : when there is contact record in salesforce with the registration email
	 */
	@isTest
	static void contactRecordWithEmail_Test(){
		Test.setMock(WebServiceMock.class, new CventSyncMock());


		//Account
		Account account = TestDataUtils.createAccount(false, 'Test Account');
		account.billingCountry = 'brasil';
		account.billingStreet = 'new';
		insert account;

		//Contact
		Contact con = new Contact(lastname = 'testContact', email = 'test@email.com', accountid = account.id);
		insert con;
		Test.startTest();
		testDataForCventRegistrationBatch();

		Database.executeBatch(new RetrieveRegistrationsFromCventBatch());

		Test.stopTest();
		System.assertEquals(1, [SELECT Id
		                        FROM Event_registrations__c
		                        WHERE Cvent_Registration_Id__c != null AND Contact__c = :con.Id].size(), 'There must be an event registration');
	}
	/*
	 Test Method for batch : when there is lead record in salesforce with the registration email
	 */
	@isTest
	static void leadRecordWithEmail_Test(){
		Test.setMock(WebServiceMock.class, new CventSyncMock());

		Account anonAccount = TestDataUtils.createAccount(true, 'Individual - No Account');

		Lead lead1 = TestDataUtils.createLead(true, 'TESTING 1', 'Test Lead 1', 'test 1', null, 'test@email.com');

		Test.startTest();
		testDataForCventRegistrationBatch();

		Database.executeBatch(new RetrieveRegistrationsFromCventBatch());


		Test.stopTest();
		System.assertEquals(1, [SELECT Id
		                        FROM Event_registrations__c
		                        WHERE Cvent_Registration_Id__c != null].size(), 'There must be an event registration');
	}
	/*
	 Test Method for DeleteSuccessfulRegistrationLogsBatch batch
	 */
	@isTest
	static void deletionCventLogs_Test(){
		Test.setMock(WebServiceMock.class, new CventSyncMock());

		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(false, 'TestSearchId45768', 'Registration');
		cventRegistrationLog.retrieved__c = Datetime.now();
		cventRegistrationLog.Successfully_Processed__c = true;
		insert cventRegistrationLog;
		/* Datetime sevendaysBack = Datetime.now().addDays(-8);
		 Test.setLastModifiedDate(cventRegistrationLog.Id, sevendaysBack);
		 */
		String query = 'SELECT Id FROM Cvent_Registration_Log__c WHERE Retrieved__c != null AND Successfully_Processed__c = true';
		Test.startTest();

		Database.executeBatch(new DeleteSuccessfulRegistrationLogsBatch(query));

		Test.stopTest();
		System.assertEquals(0, [SELECT Id
		                        FROM Cvent_Registration_Log__c
		                        WHERE Retrieved__c != null AND Successfully_Processed__c = true].size(), 'There must not be an Cvent_Registration_Log__c record');
	}
	/*
	 Test Method for DeleteSuccessfulRegistrationLogsBatch batch
	 */
	@isTest
	static void deletionSchedular(){
		Test.setMock(WebServiceMock.class, new CventSyncMock());

		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(false, 'TestSearchId45768', 'Registration');
		cventRegistrationLog.retrieved__c = Datetime.now();
		cventRegistrationLog.Successfully_Processed__c = true;
		insert cventRegistrationLog;

		Test.startTest();

		DeleteSuccessfulRegistrationLogsBatch deleteBatch = new DeleteSuccessfulRegistrationLogsBatch();
		deleteBatch.execute(null);

		Test.stopTest();
		System.assertEquals(1, [SELECT Id
		                        FROM Cvent_Registration_Log__c
		                        WHERE Retrieved__c != null AND Successfully_Processed__c = true].size(), 'There must be an Cvent_Registration_Log__c record');
	}
	/*
	 Test Method for DeleteSuccessfulRegistrationLogsBatch batch
	 */
	@isTest
	static void deletionSchedularTest(){
		Test.setMock(WebServiceMock.class, new CventSyncMock());

		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(false, 'TestSearchId45768', 'Registration');
		cventRegistrationLog.retrieved__c = Datetime.now();
		cventRegistrationLog.Successfully_Processed__c = true;
		insert cventRegistrationLog;

		Test.startTest();

		Database.executeBatch(new DeleteSuccessfulRegistrationLogsBatch());

		Test.stopTest();
		System.assertEquals(1, [SELECT Id
		                        FROM Cvent_Registration_Log__c
		                        WHERE Retrieved__c != null AND Successfully_Processed__c = true].size(), 'There must be an Cvent_Registration_Log__c record');
	}

	/*
	 * Helper Method for Creation of Cvent_Registration_Log__c
	 */
	public static void testDataForCventRegistrationBatch(){
		Cvent_Registration_Log__c cventRegistrationLog = TestDataUtils.createCventRegistrationLog(true, 'TestSearchId45768', 'Registration');
		Project__c project = TestDataUtils.createProject(true, 'The Linux Foundation', 'Event', 'Directed Fund', 'Planned');

		Event__c evt = TestDataUtils.createEvent(false, 'Test Event', 'Unfunded', 'Project Event', 'Planned');
		evt.Cvent_Event_Id__c = 'TestEventId';
		evt.Registration_Source__c = 'Cvent';
		insert evt;
	}
}