force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Error__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Error__c</fullName>
    <label>NetSuite Error</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Netsuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>NS Item ID</inlineHelpText>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Name_Override__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Name_Override__c</fullName>
    <label>NetSuite Name Override</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>NS_Item_Name__c</fullName>
    <formula>IF(
				RecordType.Name = &quot;Event&quot;,
    Event__r.Name &amp; &apos; - &apos; &amp; Products__r.Name &amp; &apos; - &apos; &amp; Tier__c,
IF(
				AND(NOT(ISBLANK( Tier__c )),
				NOT(ISBLANK( Start_Tier__c )),
				NOT(ISBLANK( End_Tier__c ))
				),
				Products__r.Name &amp; &apos;, &apos; &amp; Project__r.Name &amp; &apos;, &apos; &amp; TEXT(Start_Tier__c) &amp; &apos;-&apos; &amp; TEXT(End_Tier__c) &amp; &apos;-&apos; &amp;  Tier__c,
IF(
				AND(NOT(ISBLANK( Start_Tier__c )),
				NOT(ISBLANK( End_Tier__c ))
			 ),
	   Products__r.Name &amp; &apos;, &apos; &amp; Project__r.Name &amp; &apos;, &apos; &amp; TEXT(Start_Tier__c) &amp; &apos;-&apos; &amp; TEXT(End_Tier__c),
IF(
				AND(NOT(ISBLANK( Tier__c )),
				ISBLANK( Start_Tier__c ),
				ISBLANK( End_Tier__c )
				),
				Products__r.Name &amp; &apos;, &apos; &amp; Project__r.Name &amp; &apos;, &apos; &amp; Tier__c,
				Products__r.Name &amp; &apos;, &apos; &amp; Project__r.Name
		)
	)
)
				)</formula>
    <label>NS Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
            <value>
                <fullName>Straight Line</fullName>
                <isActive>false</isActive>
                <label>Straight Line</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <formula>IF(Project__c != null ,Project__r.Subsidiary_ID__c , Event__r.BillFromProject__r.Subsidiary_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A one-sentence description of the project, which will be used for external facing (i.e. landscape graphic or a website list of LF projects) descriptions of projects.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/job_Code__c.field-meta.xml
<CustomField>
    <fullName>job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Deferred_Revenue_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>284</fullName>
        <label>Deferred Revenue : Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>282</fullName>
        <label>Deferred Revenue : Deferred Revenue - Membership</label>
    </customValue>
    <customValue>
        <fullName>4494</fullName>
        <label>Deferred Revenue : Deferred Revenue - Directed Funds</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Other</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Membership</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Membership</label>
    </customValue>
    <masterLabel>NetSuite Deferred Revenue Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NetSuite_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Events</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Training</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Training (Linux Labs)</label>
    </customValue>
    <masterLabel>NetSuite Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NSProductDetailHelper.cls
/*
    Name : NSProductDetailHelper
    Author : Piyush Kalra(piyush@wiserspread.com)
    Date : 1st Nov 
    Description : This class is used to map with fields with product details to non inventory item in NS 
*/


public class NSProductDetailHelper {
    
   
   // Method for mapping and giving back JSON 
   public static void mappingFromSFToNS(String productDetailId , Map<Id , Product_Details__c> newMapFromTrigger){
       
       if(productDetailId != null && !String.isBlank(productDetailId)){
           
           
           
           /*
               These custom setting/Objects are used to get NS id from drop down or free form fields on Product Detail 
           */
           
         
         
           
           
           //Fetching the productDetailObject
           Product_Details__c productDetailObject = [SELECT id ,recordType.name,Netsuite_ID__c, NetSuite_Name_Override__c, Description__c , Project__r.Project_Code__c , NS_Item_Name__c,
                                                     NS_Income_GL_Account__c , NS_Deferred_Revenue_Account__c  , NS_Department__c , 
                                                   NetSuite_Class__c,Job_Code__c ,NS_Revenue_Schedule__c,Subsidiary_ID__c FROM Product_Details__c WHERE ID =:productDetailId];
           
           //JSON map used for populating
           map<String , String> jsonMapToBeRequestBody = new map<String , String>();   
           
           
           
           // HardCoded mappings will be used always 
           jsonMapToBeRequestBody.put('recordtype','NonInventorySaleItem');
           jsonMapToBeRequestBody.put('taxschedule','1');
           if(productDetailObject.Netsuite_ID__c != null &&productDetailObject.Netsuite_ID__c != ''){
               jsonMapToBeRequestBody.put('id',productDetailObject.Netsuite_ID__c);
           }
           
           //getting from fields now
           //jsonMapToBeRequestBody.put('Description' , productDetailObject.description__c);
          
           
           if(productDetailObject.Job_Code__c != null){
               jsonMapToBeRequestBody.put('location' , productDetailObject.Job_Code__c);
           
           }
           
           if(productDetailObject.NetSuite_Class__c != null){
               jsonMapToBeRequestBody.put('class' , productDetailObject.NetSuite_Class__c);
           
           }else if(productDetailObject.NetSuite_Class__c != null && productDetailObject.NetSuite_Class__c != ''){
               //throw an error 
               newMapFromTrigger.get(productDetailId).NetSuite_Class__c.addError('Didnt match with Netsuite Label Name');
           }
           
           
        
             if(productDetailObject.NS_Revenue_Schedule__c !=null){
               jsonMapToBeRequestBody.put('revrecschedule' ,productDetailObject.NS_Revenue_Schedule__c);
           }else{
               newMapFromTrigger.get(productDetailId).NS_Revenue_Schedule__c.addError('Didnt match with Netsuite Label Name');
           }
           
           
               
           if(productDetailObject.NS_Deferred_Revenue_Account__c !=null){
               jsonMapToBeRequestBody.put('deferredrevenueaccount' ,productDetailObject.NS_Deferred_Revenue_Account__c);
           }else{
               // Throw an error on NS_Deferred Revenue FIeld 
               newMapFromTrigger.get(productDetailId).NS_Deferred_Revenue_Account__c.addError('Didnt match with Netsuite Label Name');
           }
          // system.debug(MappingForNSDepartment);
           system.debug(productDetailObject.NS_Department__c);
           if(  productDetailObject.NS_Department__c != null && productDetailObject.NS_Department__c != 'Training (Linux Labs)'){
                 jsonMapToBeRequestBody.put('department' ,productDetailObject.NS_Department__c);        
               
             }else{
               // Throw an error on NS_Department__c FIeld 
               newMapFromTrigger.get(productDetailId).NS_Department__c.addError('Didnt match with Netsuite Label Name');
             }
           
             if(productDetailObject.NS_Income_GL_Account__c != null){   
               jsonMapToBeRequestBody.put('incomeaccount' ,productDetailObject.NS_Income_GL_Account__c );
             }else{
               // Throw an error on NS_Income_GL_Account__c FIeld 
               newMapFromTrigger.get(productDetailId).NS_Income_GL_Account__c.addError('Didnt match with Netsuite Label Name');
             }
          // system.debug('**MappingForSubsidiaryId**'+MappingForSubsidiaryId);
          //system.debug('**MappingForSubsidiaryId.get(productDetailObject.Subsidiary__c)**'+ MappingForSubsidiaryId.get(productDetailObject.Subsidiary__c));
           /*if(!MappingForSubsidiaryId.isEmpty() && MappingForSubsidiaryId.containsKey(productDetailObject.Subsidiary__c)  && MappingForSubsidiaryId.get(productDetailObject.Subsidiary__c) != null){
           
                   jsonMapToBeRequestBody.put('subsidiary' , MappingForSubsidiaryId.get(productDetailObject.Subsidiary__c));
           }*/
           if(productDetailObject.Subsidiary_ID__c != null && productDetailObject.recordType.Name == 'Training'){
                   jsonMapToBeRequestBody.put('subsidiary' , '1');
           
           }else {
           
           		jsonMapToBeRequestBody.put('subsidiary' , string.valueOf(productDetailObject.Subsidiary_ID__c));
           
           }
           
           
           /*else{
               // Throw an error on Subsidiary_ID__c FIeld 
               newMapFromTrigger.get(productDetailId).Subsidiary__c.addError('Didnt match with Netsuite Label Name');
           }*/ 
            /*if(productDetailObject != null && productDetailObject.NS_Item_name__c != null && productDetailObject.NS_Item_name__c.length() <= 60){
	               jsonMapToBeRequestBody.put('itemid' , productDetailObject.NS_Item_Name__c);
	           }else{
	               if(productDetailObject.NetSuite_Name_Override__c != null && productDetailObject.NetSuite_Name_Override__c != ''){
	                   jsonMapToBeRequestBody.put('itemid' , productDetailObject.NetSuite_Name_Override__c);
	               }else{
	                    //productDetailObject.NetSuite_Error__c ='This field cant be blank because name field is more than 60 characters';
	                    
	                    //isSuccess = true;
	               }
	           }*/
	            if(productDetailObject.NetSuite_Name_Override__c != null && productDetailObject.NetSuite_Name_Override__c != ''){
	                   jsonMapToBeRequestBody.put('itemid' , productDetailObject.NetSuite_Name_Override__c);
	               } else if(productDetailObject != null && productDetailObject.NS_Item_name__c != null && productDetailObject.NS_Item_name__c.length() <= 180){
	               jsonMapToBeRequestBody.put('itemid' , productDetailObject.NS_Item_Name__c);
	               }else {
	                    //productDetailObject[0].NetSuite_Error__c ='NetSuite Name OverRide field cant be blank because name field is more than 60 characters';
	                    newMapFromTrigger.get(productDetailId).NetSuite_Name_Override__c.addError('This field cant be blank because name field is more than 180 characters');
	                    //isSuccess = true;
	               }
	
           
           system.debug(JSON.serialize(jsonMapToBeRequestBody));
           CallOutToNetSuite.callingCallOutToNet(JSON.serialize(jsonMapToBeRequestBody) , productDetailId);
           
           
       }
       
   }
   
    public static void mappingFromSFToNSThroughBatch(String productDetailId){
		//if(!System.isBatch()){	       
	       boolean isSuccess = false;
	       if(productDetailId != null && !String.isBlank(productDetailId)){
	           
	           
	         
	           
	           //Fetching the productDetailObject
	           list<Product_Details__c> productDetailObject = [SELECT id ,Netsuite_ID__c, NetSuite_Name_Override__c, Description__c , Project__r.Project_Code__c , NS_Item_Name__c,
	                                                     NS_Income_GL_Account__c , NS_Deferred_Revenue_Account__c  , NS_Department__c , 
	                                                   NetSuite_Class__c, NetSuite_Error__c ,Job_Code__c ,NS_Revenue_Schedule__c,Subsidiary_ID__c FROM Product_Details__c WHERE ID =:productDetailId];
	           
	           //JSON map used for populating
	           map<String , String> jsonMapToBeRequestBody = new map<String , String>();   
	           
	           
	           
	           // HardCoded mappings will be used always 
	           jsonMapToBeRequestBody.put('recordtype','NonInventorySaleItem');
	           jsonMapToBeRequestBody.put('taxschedule','1');
	           if(productDetailObject[0].Netsuite_ID__c != null &&productDetailObject[0].Netsuite_ID__c != ''){
	               jsonMapToBeRequestBody.put('id',productDetailObject[0].Netsuite_ID__c);
	           }
	           
	           //getting from fields now
	           //jsonMapToBeRequestBody.put('Description' , productDetailObject.description__c);
	          
	           
	           if(productDetailObject[0].Job_Code__c != null){
	               jsonMapToBeRequestBody.put('location' , productDetailObject[0].Job_Code__c);
	           
	           }
	           if(productDetailObject[0].NetSuite_Class__c != null){
	               jsonMapToBeRequestBody.put('class' , productDetailObject[0].NetSuite_Class__c);
	           
	           }else if(productDetailObject[0].NetSuite_Class__c != null && productDetailObject[0].NetSuite_Class__c != ''){
	               //throw an error 
	               productDetailObject[0].NetSuite_Error__c = 'Didnt match with Netsuite Label Name';
	               isSuccess = true;
	           }
	           
	           
	         
	             if(productDetailObject[0].NS_Revenue_Schedule__c !=null){
	               jsonMapToBeRequestBody.put('revrecschedule' ,productDetailObject[0].NS_Revenue_Schedule__c);
	           }else{
	               productDetailObject[0].NetSuite_Error__c = 'Didnt match with Netsuite Label Name';
	               isSuccess = true;
	           }
	           
	          
	                 if(productDetailObject[0].NS_Deferred_Revenue_Account__c !=null){
	                jsonMapToBeRequestBody.put('deferredrevenueaccount' ,productDetailObject[0].NS_Deferred_Revenue_Account__c);
	           }else{
	               // Throw an error on NS_Deferred Revenue FIeld 
	               productDetailObject[0].NetSuite_Error__c = 'Didnt match with Netsuite Label Name';
	               isSuccess = true;
	           }
	           //system.debug(MappingForNSDepartment);
	           system.debug(productDetailObject[0].NS_Department__c);
	           if (productDetailObject[0].NS_Department__c != null && productDetailObject[0].NS_Department__c != 'Training (Linux Labs)'){
	               jsonMapToBeRequestBody.put('department' , productDetailObject[0].NS_Department__c );   
	           }
	           else{
	               // Throw an error on NS_Department__c FIeld 
	               productDetailObject[0].NetSuite_Error__c = 'Didnt match with Netsuite Label Name';
	               isSuccess = true;
	           }
	          
	             if(productDetailObject[0].NS_Income_GL_Account__c != null){  
	               jsonMapToBeRequestBody.put('incomeaccount' , productDetailObject[0].NS_Income_GL_Account__c );
	           }else{
	               // Throw an error on NS_Income_GL_Account__c FIeld 
	               productDetailObject[0].NetSuite_Error__c = 'Didnt match with Netsuite Label Name';
	               isSuccess = true;
	           }
	          // system.debug('**MappingForSubsidiaryId**'+MappingForSubsidiaryId);
	           //system.debug('**MappingForSubsidiaryId.get(productDetailObject.Subsidiary__c)**'+ MappingForSubsidiaryId.get(productDetailObject.Subsidiary__c));
	         
	           if(productDetailObject[0].Subsidiary_ID__c != null){
	                   jsonMapToBeRequestBody.put('subsidiary' , string.valueOf(productDetailObject[0].Subsidiary_ID__c));
	           
	           }
	          
	          
	          
	               if(productDetailObject[0].NetSuite_Name_Override__c != null && productDetailObject[0].NetSuite_Name_Override__c != ''){
	                   jsonMapToBeRequestBody.put('itemid' , productDetailObject[0].NetSuite_Name_Override__c);
	               } else if(productDetailObject != null && productDetailObject[0].NS_Item_name__c != null && productDetailObject[0].NS_Item_name__c.length() <= 60){
	               jsonMapToBeRequestBody.put('itemid' , productDetailObject[0].NS_Item_Name__c);
	               }else {
	                    productDetailObject[0].NetSuite_Error__c ='NetSuite Name OverRide field cant be blank because name field is more than 60 characters';
	                    isSuccess = true;
	               }
	           
	           system.debug(JSON.serialize(jsonMapToBeRequestBody));
	           CallOutToNetSuite.callingCallOutToNetForBatch(JSON.serialize(jsonMapToBeRequestBody) , productDetailId);
	            if(isSuccess = true){
	               update productDetailObject[0];
	           
	           }
	           
	       }
	       
	  // }
	}
}