force-app/main/default/objects/Meeting__c/Meeting__c.object-meta.xml
<CustomObject>
    <label>Meeting</label>
    <nameField>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Meeting__c/fields/Descritpion__c.field-meta.xml
<CustomField>
    <fullName>Descritpion__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>EndTime</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Meeting_Detail__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Detail__c</fullName>
    <label>Meeting Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>StartTime</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meeting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Please select meeting type.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meeting</fullName>
                <default>true</default>
                <label>Meeting</label>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MeetingTriggerHadlerTest.cls
@isTest
public class MeetingTriggerHadlerTest {
    public static testmethod void TestDataSetup(){
        Meeting__c objMeeting = new Meeting__c(
            Name='Test Meeting 1',
            Subject__c='Test Subject',
            Meeting_Detail__c='Discussion',
            StartDate__c=Date.today(),
            EndDate__c=Date.today(),
            Type__c ='Webinar',
            StartTime__c=Time.newInstance(18, 30, 2, 00),
            EndTime__c=Time.newInstance(19, 30, 2, 00));
        insert objMeeting;
        System.assertEquals(1, [SELECT count() FROM Campaign]);
        objMeeting.Descritpion__c = 'This is test';
        update objMeeting;
        System.assertEquals('This is test', [SELECT Description FROM Campaign LIMIT 1].Description);
        delete objMeeting;
    }
}