force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/LF_Membership_Required__c.field-meta.xml
<CustomField>
    <fullName>LF_Membership_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LF Membership Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
            <value>
                <fullName>Straight Line</fullName>
                <isActive>false</isActive>
                <label>Straight Line</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Products</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prorate</fullName>
            </value>
            <value>
                <fullName>Non-Prorate</fullName>
            </value>
            <value>
                <fullName>Calendar Year</fullName>
            </value>
            <value>
                <fullName>Renewable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Product_Details__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/job_Code__c.field-meta.xml
<CustomField>
    <fullName>job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/LF_Membership_Required__c.field-meta.xml
<CustomField>
    <fullName>LF_Membership_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LF membership is required if this project is a Subproject, it has membership, and its parent project is The Linux Foundation. The value of this field is set by workflow rules.</description>
    <inlineHelpText>Indicates if LF membership is required in addition to membership to this project. LF membership is required if this project is a Subproject, it has membership, and its parent project is The Linux Foundation.</inlineHelpText>
    <label>LF Membership Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prorate</fullName>
            </value>
            <value>
                <fullName>Non-Prorate</fullName>
            </value>
            <value>
                <fullName>Calendar Year</fullName>
            </value>
            <value>
                <fullName>Renewable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Reschedule</fullName>
            </value>
            <value>
                <fullName>Date Confirmed</fullName>
            </value>
            <value>
                <fullName>Materials Sent</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Deferred_Revenue_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>284</fullName>
        <label>Deferred Revenue : Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>282</fullName>
        <label>Deferred Revenue : Deferred Revenue - Membership</label>
    </customValue>
    <customValue>
        <fullName>4494</fullName>
        <label>Deferred Revenue : Deferred Revenue - Directed Funds</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Other</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Membership</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Membership</label>
    </customValue>
    <masterLabel>NetSuite Deferred Revenue Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NetSuite_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Events</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Training</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Training (Linux Labs)</label>
    </customValue>
    <masterLabel>NetSuite Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductDetail_Action.cls
public class ProductDetail_Action {

    // When Product Detail is inserted in association with Project/Event/Training object, 
    // then fetch netsuite detail from associated Project/Event/Training
    // and update netsuite fields on Product Detail object   
    public void populateNetSuiteFields(List<Product_Details__c> incomingProductDetails) {

        Set<Id> eventIdSet = new Set<Id>();
        Set<Id> projectIdSet = new Set<Id>();
        Set<Id> trainingIdSet = new Set<Id>();
        Map<Id, Event__c> eventRecords = new Map<Id, Event__c>();
        Map<Id, Project__c> projectRecords = new Map<Id, Project__c>();
        Map<Id, Training__c> trainingRecords = new Map<Id, Training__c>();
        List<Id> productIds = new List<Id>();
        Map<Id, Product2> productRecords = new Map<Id, Product2>();

        //Id directedProjectId = Schema.SObjectType.Project__c.getRecordTypeInfosByName().get('Directed Fund').getRecordTypeId();

        //system.debug('_____directedProjectId____' + directedProjectId);

        for (Product_Details__c pd : incomingProductDetails) {

            if (pd.Event__c != null)
                eventIdSet.add(pd.Event__c); else if (pd.Project__c != null)
                projectIdSet.add(pd.Project__c); else if (pd.Training__c != null)
                trainingIdSet.add(pd.Training__c);

            if (pd.Products__c != null)
                productIds.add(pd.Products__c);
        }

        if (!eventIdSet.isEmpty()) {
            eventRecords = new Map<Id, Event__c>([Select Id,NS_Revenue_Schedule__c, job_code__c,NS_Deferred_Revenue_Account__c, NS_Department__c, NetSuite_Class__c, NS_Income_GL_Account__c 
                                                  from Event__c where Id In :eventIdSet]);
        }

        if (!projectIdSet.isEmpty()) {
            projectRecords = new Map<Id, Project__c>([Select Id,job_code__c, Status__c, Renewal_Type__c,LF_Membership_Required__c,
                                                      Project_Code__c,Category__c ,NS_Deferred_Revenue_Account__c, NS_Department__c, 
                                                      NetSuite_Class__c, NS_Income_GL_Account__c from Project__c where Id In :projectIdSet]);
            // and RecordTypeId = :directedProjectId 
        }

        if (!trainingIdSet.isEmpty()) {
            trainingRecords = new Map<Id, Training__c>([Select Id, NS_Deferred_Revenue_Account__c, NS_Department__c, NetSuite_Class__c, NS_Income_GL_Account__c from Training__c 
                                                        where Id In :trainingIdSet]);
        }

        if (!productIds.isEmpty()) {
            productRecords = new Map<Id, Product2>([Select Id, name, NetSuite_Revenue_Schedule__c, Tax_Class__c from Product2 where Id In:productIds]);
        }

        system.debug('____projectRecords____' + projectRecords);
        system.debug('**event records---' + eventRecords);
        system.debug('incomingProductDetails' + incomingProductDetails);

        for (Product_Details__c pd : incomingProductDetails) {

            String class_str;
            String department;
            String RevenueAccount;
            String GLAccount;
            String JobCode;
            String RevenueSchedule;
            
            if (pd.Event__c != null && eventRecords.size() > 0 && eventRecords.containsKey(pd.Event__c)) {
                system.debug('I am in');
                Event__c event = eventRecords.get(pd.Event__c);
                class_str = event.NetSuite_Class__c ;
                department = event.NS_Department__c ;
                RevenueAccount =event.NS_Deferred_Revenue_Account__c ;
                GLAccount = event.NS_Income_GL_Account__c ;
                JobCode = event.job_code__c ;
                RevenueSchedule = event.NS_Revenue_Schedule__c ;
            } else if (pd.Project__c != null && projectRecords.size() > 0 && projectRecords.containsKey(pd.Project__c)) {
                Project__c project = projectRecords.get(pd.Project__c);
                if (project.LF_Membership_Required__c) {//for directed fund
                    System.debug('in----');
                    class_str = project.NetSuite_Class__c;
                    department = project.NS_Department__c;
                    RevenueAccount = project.NS_Deferred_Revenue_Account__c ;
                    GLAccount = project.NS_Income_GL_Account__c ;
                    JobCode = project.job_code__c ;
                    // pd.Project_Code__c = projectRecords.get(pd.Project__c).Project_Code__c;
                    // pd.SubsidiaryID__c = projectRecords.get(pd.Project__c).Subsidiary_ID__c;            
                    //pd.Status__c = projectRecords.get(pd.Project__c).Status__c; 
                    pd.Renewal_Type__c = project.Renewal_Type__c;
                    RevenueSchedule = '29';
                    pd.NS_Revenue_Schedule__c = '29';
                    System.debug(pd);
                    //pd.Number_of_Years_Required__c = projectRecords.get(pd.Project__c).Number_of_Years_Required__c;
                }else if(project.Category__c == 'Incorporated Entity'){ //for incorporated projects
                    department = project.NS_Department__c;
                    RevenueAccount = project.NS_Deferred_Revenue_Account__c ;
                   	JobCode = project.job_code__c ;
                    //pd.SubsidiaryID__c = projectRecords.get(pd.Project__c).Subsidiary_ID__c;
                    RevenueSchedule = '6';
                    pd.NS_Revenue_Schedule__c = '6';
                    pd.Project_Code__c = project.Project_Code__c;
                }
                /* if(pd.Products__c!=null && productRecords.size()>0 && productRecords.containsKey(pd.Products__c)){

pd.Number_of_Years_Required__c = productRecords.get(pd.Products__c).Number_of_Years_Required__c;
}*/

            } else if (pd.Training__c != null && trainingRecords.size() > 0 && trainingRecords.containsKey(pd.Training__c)) {
                class_str =  String.IsNotEmpty(pd.NetSuite_Class__c) ?pd.NetSuite_Class__c :trainingRecords.get(pd.Training__c).NetSuite_Class__c;
                department = String.IsNotEmpty(pd.NS_Department__c) ?pd.NS_Department__c :trainingRecords.get(pd.Training__c).NS_Department__c ;
                RevenueAccount = String.IsNotEmpty(pd.NS_Deferred_Revenue_Account__c) ?pd.NS_Deferred_Revenue_Account__c :trainingRecords.get(pd.Training__c).NS_Deferred_Revenue_Account__c ;
                GLAccount = String.IsNotEmpty(pd.NS_Income_GL_Account__c) ?pd.NS_Income_GL_Account__c :trainingRecords.get(pd.Training__c).NS_Income_GL_Account__c ;
                //JobCode = trainingRecords.get(pd.Training__c).job_code__c ;
            }

            
                pd.NetSuite_Class__c = class_str;
                pd.NS_Department__c = department;
                pd.NS_Deferred_Revenue_Account__c = RevenueAccount;
                pd.NS_Income_GL_Account__c = GLAccount;
                pd.job_code__c = JobCode;
                pd.NS_Revenue_Schedule__c = String.IsEmpty(pd.NS_Revenue_Schedule__c) ? RevenueSchedule : pd.NS_Revenue_Schedule__c;
                //
                system.debug('*pd*' + pd);
                //pd.Project_Code__c = projectRecords.get(pd.Project__c).Project_Code__c;
                //pd.SubsidiaryID__c = projectRecords.get(pd.Project__c).Subsidiary_ID__c;
            

            if (pd.Products__c != null && productRecords.size() > 0 && productRecords.containsKey(pd.Products__c)) {
                //pd.NS_Revenue_Schedule__c = productRecords.get(pd.Products__c).NetSuite_Revenue_Schedule__c;
                pd.Tax_Class__c = productRecords.get(pd.Products__c).Tax_Class__c;
            }

            system.debug('**pd**' + pd);
        }
    }


    public void sendEmailtoEvents(List<Product_Details__c> productDetails) {
        Set<Id> eventsSet = new Set<Id>();
        for (Product_Details__c pd : productDetails) {
            if(pd.Event__c != null){
                eventsSet.add(pd.Event__c);
            }            
        }
        
        if(!eventsSet.isEmpty()){
            EmailTemplate et = [SELECT Id,Subject, Body FROM EmailTemplate WHERE DeveloperName = 'Alert_Finance_of_New_Event'];
            List<Event__c> eventsProductDetailsList = [
                SELECT Id, Name, Email_Sent__c,BillFromProject__c
                FROM Event__c
                WHERE Id IN :eventsSet AND Status__c = 'Planned'
                AND Email_Sent__c = False
            ];
        //String emailId = Label.Product_Details_Email;
        List<Event__c> eventsToUpdate = new List<Event__c>();


        /*List<GroupMember> groupMembers = [SELECT Id, GroupId, UserOrGroupId FROM GroupMember WHERE GroupId IN (SELECT Id FROM Group WHERE DeveloperName = :Label.ProductDetailsGroupName)];
        System.debug(groupMembers + '  ===> groupMembers');
        Set<Id> userIdSet = new Set<Id>();
        for (GroupMember gm : groupMembers) {
            if (gm.UserOrGroupId != null && String.valueOf(gm.UserOrGroupId).startsWith('005')) {
                userIdSet.add(gm.UserOrGroupId);
            }
        }
        System.debug(userIdSet + '  ===> userIdSet');
        List<User> users = [SELECT Id, Email FROM User WHERE Id IN :userIdSet];*/
        List<String> sendTo = Utility.getEmailAddresses(Label.ProductDetailsGroupName);
        /*for (User u : users) {
            if (u.Email != null) {
                sendTo.add(u.Email);
            }
        }
        System.debug(sendTo + '  ===> sendTo');*/
        if (sendTo.size() > 0) {
            for (Event__c evt : eventsProductDetailsList) {

                Boolean emailSuccess = sendMail(sendTo, evt, et);
                if (emailSuccess) {
                    evt.Email_Sent__c = true;
                    eventsToUpdate.add(evt);
                }
            }
            update eventsToUpdate;
        }
    }
    }

    public boolean sendMail(List<String> sendTo, Event__c evt, EmailTemplate et) {
        Id orgWideEmailAddress = Utility.getOrgWideEmailAddress();
        Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(et.Id, UserInfo.getUserId(), evt.Id);

        email.setOrgWideEmailAddressId(orgWideEmailAddress);
        email.setToAddresses(sendTo);

        email.setSaveAsActivity(false);
        try {

            Messaging.SendEmailResult[] emailResult = Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                    email
            });
            System.debug('Email Result : ' + emailResult);
            return emailResult[0].isSuccess();
        } catch (Exception e) {
            System.debug('Exception : ' + e.getMessage() + ' Line Number: ' + e.getLineNumber());
            return false;
        }
    }


}