force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/LF_Membership_Required__c.field-meta.xml
<CustomField>
    <fullName>LF_Membership_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LF Membership Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Product_Details__c/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Product_Details__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/LF_Membership_Required__c.field-meta.xml
<CustomField>
    <fullName>LF_Membership_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>LF membership is required if this project is a Subproject, it has membership, and its parent project is The Linux Foundation. The value of this field is set by workflow rules.</description>
    <inlineHelpText>Indicates if LF membership is required in addition to membership to this project. LF membership is required if this project is a Subproject, it has membership, and its parent project is The Linux Foundation.</inlineHelpText>
    <label>LF Membership Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NewProductDetailsController.cls
public class NewProductDetailsController {
    @AuraEnabled
    public static String getRecordTypeId(String objectName){
        switch on objectName {
            when 'Project__c' {
                return PicklistOptionsUtility.getProductDetailsRecordTypeId('Membership');
            }
            when 'Event__c' {
                return PicklistOptionsUtility.getProductDetailsRecordTypeId('Event');
            }
            when 'Training__c'{
                return PicklistOptionsUtility.getProductDetailsRecordTypeId('Training');
            }
            when else {
                return null;
            }
        }
    }

    /**
     * Method to get RecordTypeId For ProductDetail When launched from a project record
     * that is to get an option as "Alternate Funding or Membership" before creating product detail
     * so user can select from these two which recordtype is needed for product detail
     */ 
    @AuraEnabled
    public static List<String> fetchRecordTypeValues(){
        List<Schema.RecordTypeInfo> recordtypes = Product_Details__c.SObjectType.getDescribe().getRecordTypeInfos();
        Map<String, Id> recordtypeMap = new Map<String, Id>();
        for(RecordTypeInfo rt : recordtypes){
            if(rt.getName() != 'Training' && rt.getName() != 'Event' && rt.getName() != 'Master')
                recordtypeMap.put(rt.getName(), rt.getRecordTypeId());
        }
        List<String> recTypeNames = new List<String>(recordtypeMap.keySet());
        return recTypeNames;
    }

    /**
     * Method to get RecordTypeId For ProductDetail Record based on RecordTypeLabel
     * @param  recordTypeLabel - value can be Membership or Alternate Funding
     * @param  recordId  - Id Of the Project Record
     */ 
    @AuraEnabled
    public static Map<String,Object> getRecTypeIdProject(String recordTypeLabel,String recordId){
        Map<String,Object> responseMap = new Map<String,Object>();

        //put recordtypeid in map
        responseMap.put('RecordTypeId',PicklistOptionsUtility.getProductDetailsRecordTypeId(recordTypeLabel));
        //If membership recordtype label then retrieve the project record
        if(recordTypeLabel == 'Membership'){
            Project__c projectInstance = [SELECT Id,LF_Membership_Required__c 
            FROM Project__c WHERE Id =: recordId];
            responseMap.put('ProjectRecord',projectInstance);
        }

        //return
        return responseMap;
    }
}