force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LF Event</fullName>
            </value>
            <value>
                <fullName>Project Event</fullName>
            </value>
            <value>
                <fullName>3rd Party Event</fullName>
            </value>
            <value>
                <fullName>Non-LF Event</fullName>
            </value>
            <value>
                <fullName>Migrated Data</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Include_W9__c.field-meta.xml
<CustomField>
    <fullName>Include_W9__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include W9</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Event&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZProject</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities (deprecated)</relationshipLabel>
    <relationshipName>Opportunities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <businessProcess>Event</businessProcess>
    <description>Record type for event opportunities</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Membership.recordType-meta.xml
<RecordType>
    <fullName>Membership</fullName>
    <active>true</active>
    <businessProcess>Membership</businessProcess>
    <description>Record type for membership opportunities</description>
    <label>Membership</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Android Development Training</fullName>
            </value>
            <value>
                <fullName>Enterprise IT &amp; Linux System Administration Training</fullName>
            </value>
            <value>
                <fullName>Linux Programming &amp; Development Training</fullName>
            </value>
            <value>
                <fullName>Open Source Compliance Courses</fullName>
            </value>
            <value>
                <fullName>Tizen Project Training</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tax_Class__c.field-meta.xml
<CustomField>
    <fullName>Tax_Class__c</fullName>
    <defaultValue>&quot;T1&quot;</defaultValue>
    <label>Tax Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Course</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>E-Learning</fullName>
            </value>
            <value>
                <fullName>Instructor-Led</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Bill_From_Address__c.field-meta.xml
<CustomField>
    <fullName>Bill_From_Address__c</fullName>
    <label>Bill From Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Bill_From_City__c.field-meta.xml
<CustomField>
    <fullName>Bill_From_City__c</fullName>
    <label>Bill From City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Bill_From_Country__c.field-meta.xml
<CustomField>
    <fullName>Bill_From_Country__c</fullName>
    <label>Bill From Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Bill_From_Name__c.field-meta.xml
<CustomField>
    <fullName>Bill_From_Name__c</fullName>
    <label>Bill From Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Bill_From_Phone__c.field-meta.xml
<CustomField>
    <fullName>Bill_From_Phone__c</fullName>
    <label>Bill From Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Bill_From_State__c.field-meta.xml
<CustomField>
    <fullName>Bill_From_State__c</fullName>
    <label>Bill From State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Bill_From_Website__c.field-meta.xml
<CustomField>
    <fullName>Bill_From_Website__c</fullName>
    <label>Bill From Website</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Bill_From_Zip__c.field-meta.xml
<CustomField>
    <fullName>Bill_From_Zip__c</fullName>
    <label>Bill From Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Email_From_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_From_Address__c</fullName>
    <label>Email From Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Image_File_for_PDF__c.field-meta.xml
<CustomField>
    <fullName>Image_File_for_PDF__c</fullName>
    <label>Image File for PDF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Include_W9__c.field-meta.xml
<CustomField>
    <fullName>Include_W9__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include W9</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Membership_Autorenew__c.field-meta.xml
<CustomField>
    <fullName>Membership_Autorenew__c</fullName>
    <label>Membership Autorenew</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectSector__c.field-meta.xml
<CustomField>
    <fullName>ProjectSector__c</fullName>
    <label>Tech Sector (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AI &amp; ML</fullName>
            </value>
            <value>
                <fullName>Blockchain, Data &amp; Analytics</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Compliance &amp; Security</fullName>
            </value>
            <value>
                <fullName>Embedded &amp; IOT</fullName>
            </value>
            <value>
                <fullName>Platforms</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prorate</fullName>
            </value>
            <value>
                <fullName>Non-Prorate</fullName>
            </value>
            <value>
                <fullName>Calendar Year</fullName>
            </value>
            <value>
                <fullName>Renewable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>For Series LLCs, the date that the series was created.  For Incorporated Entities, the date that the incorporation document was filed. For Subprojects, the date the project was announced and began operations (not an intent to form date).</inlineHelpText>
    <label>Formation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type (deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Type__c</fullName>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prorate</fullName>
            </value>
            <value>
                <fullName>Non-Prorate</fullName>
            </value>
            <value>
                <fullName>Calendar Year</fullName>
            </value>
            <value>
                <fullName>Renewable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Payment_Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Annually</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
        <isActive>false</isActive>
        <label>Monthly</label>
    </customValue>
    <masterLabel>Payment Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Family.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Crowdfunded</fullName>
    </customValue>
    <customValue>
        <fullName>Unfunded</fullName>
    </customValue>
    <customValue>
        <fullName>LF Supported</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Inherited</fullName>
    </customValue>
    <masterLabel>Product Family</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/triggerToCountUniqueEvents_test.cls
@isTest
private class triggerToCountUniqueEvents_test{
    static testMethod void Test1(){
        //get standard pricebook
        Id  standardPb = Test.getStandardPricebookId();   
        // create product
        Product2 prod = new Product2(Name='test1',Family='test', IsActive=true,Tax_Class__c='t');
        insert prod;   
        
        PricebookEntry pbe = new PricebookEntry (Product2Id=prod.id,Pricebook2ID=standardPb,UnitPrice=50, isActive=true);
        insert pbe;
        // create account
        Account acc = new Account(name='Account');
        insert acc;
        // create opportunity
        Opportunity opp = new Opportunity(AccountId=acc.id,Name='test Oppty',CloseDate=system.today(),stagename='2. Discovery');
        insert opp;
        // create quote
        Quote qt = new Quote(Name='test quote',OpportunityId=opp.id,pricebook2id=standardPb);
        insert qt;
        // create project
        Project__c project = new Project__c(
            Name = 'The Linux Foundation',       
            Status__c = 'Planned', 
            Funding__c ='Funded',
            Category__c = 'Incorporated Entity',    
            ProjectSector__c = 'Platforms',         
            Membership_Autorenew__c = 'Yes',       
            Start_Date__c = system.today() - 10,   
            Renewal_Type__c = 'Prorate',           
            Payment_Frequency__c = 'Annually',     
            Bill_From_Name__c = 'The Linux Foundation',            
            Email_From_Name__c = 'Accounts Receivable',            
            Bill_From_Address__c = '1 Letterman Drive, Suite D4700',                  
            Email_From_Address__c = 'accountsreceivable@linuxfoundation.org',            
            Bill_From_City__c = 'San Francisco',                   
            Bill_From_Phone__c = '+1 415-723-9709',               
            Bill_From_State__c = 'CA',                             
            Bill_From_Website__c = 'www.linuxfoundation.org',      
            Bill_From_Zip__c = '94129',                     
            Image_File_for_PDF__c = 'the_linux_foundation_pdf_logo.jpg',            
            Bill_From_Country__c = 'United States',                        
            Include_W9__c = true,                            
            Project_Code__c = 'LF',                         
            Type__c = 'Membership',                                                                                                                                               
            Billfrom_ID__c = 'bf98299e-6a68-0f85-236b-52a0a366caba',                                                                                                                  
            Manual_Status_Check__c = true,
            Slug__c = 'test',
            Model__c ='Membership'
        );
        insert project;
        // updating Project Status to Active
        project.Manual_Status_Check__c = false;
        project.Status__c ='Active';
        update project;
        // create event
        Event__c event = new Event__c(Event_Name__c = 'KubeCon',
                                      Name= 'KubeCon',   
                                      Status__c = 'Complete',                                                                                                                                                  
                                      Category__c = 'LF Event',                                                                                                                                                
                                      BillFromProject__c = project.id,                                                                                                                                 
                                      Start_Date__c = system.today() - 20,                                                                                                                               
                                      Capacity__c = 0,                                                                                                                                          
                                      End_Date__c = system.today() - 10,                                                                                                                             
                                      Registration_Source__c = 'RegOnline',                                                                                                                                           
                                      Event_Location_Name__c = 'Twitter HQ One 10th Street Expansion',                                                                                                     
                                      Event_Published__c = false,                                                                                                                                           
                                      Event_Location_Address__c = 'One 10th Street',                                                                                                                     
                                      Event_Location_City__c = 'San Francisco',                                                                                                                          
                                      Event_Location_State__c = 'California',                                                                                                                            
                                      Event_Location_Country__c = 'United States',                                                                                                                         
                                      Event_Location_Zip__c = '94103',                                                                                                                                    
                                      Embassy__c = 'US',                                                                                                                                               
                                      Cvent_Event_Is_Sandbox__c = false,                                                                                                                                     
                                      //Type__c = 'Email',                                                                                                                                                     
                                      Netsuite_Sync__c = false );
        insert event;
        // create quote
        Quote objquote=new Quote();
        objquote.Name='TestQuote';
        objquote.OpportunityID=opp.id;
        insert objquote;
        // create quoteline
        QuoteLineItem objquotelineitem=new QuoteLineItem();
        objquotelineitem.QuoteId=qt.id;
        objquotelineitem.Product2ID=prod.id;
        objquotelineitem.Quantity=2;
        objquotelineitem.UnitPrice=45.78;
        objquotelineitem.Event__c=event.id;
        objquotelineitem.PricebookEntryId=pbe.Id;
        insert objquotelineitem; 
       
        System.assert(event.Id != null, 'The Test Event did not insert properly');
    }
    
}