force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Registration_URL__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_URL__c</fullName>
    <label>Event Registration URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/Visa_Request__c.object-meta.xml
<CustomObject>
    <label>Visa Request</label>
    <nameField>
        <label>Visa Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visa Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visa_Request__c/fields/Accommodation_Paid_by__c.field-meta.xml
<CustomField>
    <fullName>Accommodation_Paid_by__c</fullName>
    <label>Accommodation Paid by</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delegate</fullName>
            </value>
            <value>
                <fullName>Linux Foundation</fullName>
            </value>
            <value>
                <fullName>The Linux Foundation</fullName>
            </value>
            <value>
                <fullName>Delegate&apos;s Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Attendee_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Type__c</fullName>
    <label>Attendee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I Will be attending</fullName>
            </value>
            <value>
                <fullName>I have been invited to speak</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Company_or_Organization__c.field-meta.xml
<CustomField>
    <fullName>Company_or_Organization__c</fullName>
    <label>Company or Organization</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visa Requests</relationshipLabel>
    <relationshipName>Visa_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/CountryOfBirth__c.field-meta.xml
<CustomField>
    <fullName>CountryOfBirth__c</fullName>
    <label>CountryOfBirth</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Visa Requests</relationshipLabel>
    <relationshipName>Visa_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/mailing_Address1__c.field-meta.xml
<CustomField>
    <fullName>mailing_Address1__c</fullName>
    <label>mailing Address1</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/mailing_Address_2__c.field-meta.xml
<CustomField>
    <fullName>mailing_Address_2__c</fullName>
    <label>mailing Address 2</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Office_phone__c.field-meta.xml
<CustomField>
    <fullName>Office_phone__c</fullName>
    <label>Office phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Org_paying_for_your_travel__c.field-meta.xml
<CustomField>
    <fullName>Org_paying_for_your_travel__c</fullName>
    <label>Org paying for your travel</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <label>Passport Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Register_Event__c.field-meta.xml
<CustomField>
    <fullName>Register_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Register Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <label>Zipcode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VisaRequestFormSubmission.cls
/********************************************************
 * Created by: CloudRoute Solutions
 * Created Date: 18/11/19.
 * Description: VisaRequestFormSubmission
 ********************************************************/
@RestResource(UrlMapping='/VisaRequestForm/*')
global class VisaRequestFormSubmission {

    @HttpPost
    global static String processForm() {

        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        Blob requestBodyBlob = req.requestBody;
        String requestBody = requestBodyBlob.toString();
        System.debug('Request Body: ' + requestBody);

        String apiId;
        apiId = APIRequestLog.createApiRequestlog(requestBody, 'Visa Request Form');
        System.debug('apiId: ' + apiId);

        Map<String, Object> formMap = (Map<String, Object>) JSON.deserializeUntyped(requestBody);
        System.debug('formMap: ' + formMap);

        String attendeeType = (String) formMap.get('attendeeType');
        String firstName = (String) formMap.get('firstName');
        String lastName = (String) formMap.get('lastName');
        String gender = (String) formMap.get('gender');
        String email = (String) formMap.get('email');
        String passport = (String) formMap.get('passport');
        String dateOfBirth = (String) formMap.get('dateOfBirth');
        String countryOfBirth = (String) formMap.get('countryOfBirth');
        String company = (String) formMap.get('company');
        String accommodationPaidBy = (String) formMap.get('accommodationPaidBy');
        String orgPayingForTravel = (String) formMap.get('orgPayingForTravel');
        String jobTitle = (String) formMap.get('jobTitle');
        String phone = (String) formMap.get('phone');
        String street = (String) formMap.get('street');
        String addLine2 = (String) formMap.get('addLine2');
        String city = (String) formMap.get('city');
        String state = (String) formMap.get('state');
        String zip = (String) formMap.get('zip');
        String country = (String) formMap.get('country');
        String event = (String) formMap.get('event');

        Id contId;
        Id accId;
        String status = 'failed';
        String errorMessage = '';

        try {

            if (email != null && email != '') {
                //Create Visa Request for the Contact
                Visa_Request__c visa_request = new Visa_Request__c();
                visa_request.Event__c = event.replace(',', ''); //ToDo: Check why comma is added
                //visa_request.Contact__c = contId;
                visa_request.Attendee_Type__c = attendeeType;
                visa_request.FirstName__c = firstName;
                visa_request.LastName__c = lastName;
                visa_request.Gender__c = gender;
                visa_request.ContactEmail__c = email;
                visa_request.Passport_Number__c = passport;
                visa_request.CountryOfBirth__c = countryOfBirth;
                visa_request.Company_or_Organization__c = company;
                visa_request.Accommodation_Paid_by__c = accommodationPaidBy;
                visa_request.Title__c = jobTitle;
                visa_request.Office_phone__c = phone; //ToDo: Pratik to confirm if the mapping is correct
                visa_request.Org_paying_for_your_travel__c = orgPayingForTravel;
                visa_request.mailing_Address1__c = street;
                visa_request.mailing_Address_2__c = addLine2;
                visa_request.City__c = city;
                visa_request.State__c = state;
                visa_request.Country__c = country;
                visa_request.Zipcode__c = zip;
                visa_request.Register_Event__c = true;
                if(String.isNotBlank(dateOfBirth)){
                   visa_request.DateofBirth__c = dateOfBirth.contains('/') ? Date.parse(dateOfBirth) : Date.valueOf(dateOfBirth);
                }

                SObjectAccessDecision visaRequestSecurityDecision = Security.stripInaccessible(AccessType.CREATABLE, new List<Visa_Request__c>{
                        visa_request
                });
                insert visaRequestSecurityDecision.getRecords();

                status = 'success';
            }
        } catch (Exception e) {
            System.debug('Exception: ' + e + ', Message: ' + e.getMessage() + ', Line Number: ' + e.getLineNumber() + '\n' + e.getStackTraceString());
            errorMessage = 'Exception: ' + e + ', Message: ' + e.getMessage() + ', Line Number: ' + e.getLineNumber() + '\n' + e.getStackTraceString();
            APIRequestLog.updateApiRequestLog(apiId, 'Error: ' + e.getMessage() + ' at line: ' + e.getLineNumber());
            if (e.getMessage().contains('No event registration found')) {
                status = 'Not Registered';
                sendNotRegisteredEmail(apiId, firstName, lastName, email, event);
            } else if(e.getMessage().contains('DUPLICATES_DETECTED')){
                status = 'Duplicate';
            } else {
                sendLogEmail(requestBody, errorMessage, status);
            }
            //res.statusCode = 400;
        }
        return status;
    }

    global static void sendLogEmail(String requestBody, String errorMessage, String status) {
        String emailBody = 'Hi there, <br/> <br/> We have a new submission from Visa Request Form. <br/> Please find below details of the submission<br/><br/>';
        emailBody += 'Response: ' + status;

        if (errorMessage != null && errorMessage != '') {
            emailBody += '<br/> <br/> ' + errorMessage + '<br/>';
        }
        requestBody = requestBody.replaceAll('" : "', ' : ');
        requestBody = requestBody.replaceAll('", "', '<br>');
        requestBody = requestBody.replace('{"', '<br>');
        requestBody = requestBody.replace('"}', '<br>');
        emailBody += requestBody;


        Id orgWideEmailAddress = Utility.getOrgWideEmailAddress();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = Label.Visa_Request_Form_Submission_Recipients.split(';');
        mail.setOrgWideEmailAddressId(orgWideEmailAddress);
        mail.setToAddresses(toAddresses);
        mail.setSubject('Visa Request Form Submission');
        mail.setHtmlBody(emailBody);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                mail
        });
    }

    public static void sendNotRegisteredEmail(String apiId, String firstName, String lastName, String email, String event) {
        try {

            Event__c e = [SELECT Id, Event_Registration_URL__c FROM Event__c WHERE Id = :event];


            String emailBody = Label.Visa_Request_Form_Submission_Not_Registered_Email;

            emailBody = emailBody.replace('[Name]', firstName + ' ' + lastName);
            emailBody = emailBody.replace('[RegistrationURL]', e.Event_Registration_URL__c);

            Id orgWideEmailAddress = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'visaletters@linuxfoundation.org' LIMIT 1].Id;
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new List<String>{
                    email
            };
            mail.setOrgWideEmailAddressId(orgWideEmailAddress);
            mail.setToAddresses(toAddresses);
            mail.setSubject('There was an error with your visa letter request submission');
            mail.setHtmlBody(emailBody);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                    mail
            });
        } catch (Exception e) {
            APIRequestLog.updateApiRequestLog(apiId, 'Error: ' + e.getMessage() + ' at line: ' + e.getLineNumber());
        }
    }

}