force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Total_Approved_Travel_Funds__c.field-meta.xml
<CustomField>
    <fullName>Total_Approved_Travel_Funds__c</fullName>
    <description>Should calculate from Travel Fund Request</description>
    <label>Total Approved Travel Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Total_Paid_Travel_Funds__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_Travel_Funds__c</fullName>
    <label>Total Paid Travel Funds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/Travel_Fund_Request__c.object-meta.xml
<CustomObject>
    <label>Travel Fund Request</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Fund Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approved_Amount__c</fullName>
    <label>Approved Amount</label>
    <summarizedField>Travel_Fund_Request_Line_Item__c.Cost__c</summarizedField>
    <summaryFilterItems>
        <field>Travel_Fund_Request_Line_Item__c.Line_Status__c</field>
        <operation>equals</operation>
        <value>Approved</value>
    </summaryFilterItems>
    <summaryForeignKey>Travel_Fund_Request_Line_Item__c.Travel_Fund_Request__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Travel Fund Requests</relationshipLabel>
    <relationshipName>Travel_Fund_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Travel_Fund_Request__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <label>Total Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RollUpTriggerHandler.cls
public class RollUpTriggerHandler {
    
    public static void rollupHelper(List<Travel_Fund_Request__c> travelFundRequest){
         List<RollUpSummaryUtility.fieldDefinition> fieldDefinitions = 
            new List<RollUpSummaryUtility.fieldDefinition> {                
                new RollUpSummaryUtility.fieldDefinition('SUM', 'Approved_Amount__c', 'Total_Approved_Travel_Funds__c'),
                new RollUpSummaryUtility.fieldDefinition('SUM', 'Total_Amount_Paid__c', 'Total_Paid_Travel_Funds__c')
                    };
                        
        RollUpSummaryUtility.rollUpTrigger(fieldDefinitions, travelFundRequest,'Travel_Fund_Request__c', 'Event__c', 'Event__c', '');
    }
}