force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Registrations__c.field-meta.xml
<CustomField>
    <fullName>Event_Registrations__c</fullName>
    <label>Event Registrations</label>
    <summaryForeignKey>Event_Registrations__c.Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/Event_Registrations__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registrations__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/fields/Cvent_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Cvent_Registration_Status__c</fullName>
    <label>Cvent Registration Status</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registrations__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/Visa_Request__c.object-meta.xml
<CustomObject>
    <label>Visa Request</label>
    <nameField>
        <label>Visa Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visa Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visa_Request__c/fields/Accommodation_Paid_by__c.field-meta.xml
<CustomField>
    <fullName>Accommodation_Paid_by__c</fullName>
    <label>Accommodation Paid by</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delegate</fullName>
            </value>
            <value>
                <fullName>Linux Foundation</fullName>
            </value>
            <value>
                <fullName>The Linux Foundation</fullName>
            </value>
            <value>
                <fullName>Delegate&apos;s Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Company_or_Organization__c.field-meta.xml
<CustomField>
    <fullName>Company_or_Organization__c</fullName>
    <label>Company or Organization</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visa Requests</relationshipLabel>
    <relationshipName>Visa_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Visa Requests</relationshipLabel>
    <relationshipName>Visa_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Org_paying_for_your_travel__c.field-meta.xml
<CustomField>
    <fullName>Org_paying_for_your_travel__c</fullName>
    <label>Org paying for your travel</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visa_Request__c/fields/Registered__c.field-meta.xml
<CustomField>
    <fullName>Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VisaRequestTriggerHandler.cls
public class VisaRequestTriggerHandler implements ITriggerHandler {
    public static void BeforeInsert(List<SObject> triggerNew){
        contactInsertIfEmailPresent((List<Visa_Request__c>) triggerNew);
        validateContactRegistration((List<Visa_Request__c>) triggerNew);
        updateVisaOrgpay((List<Visa_Request__c>) triggerNew, null);
    }
    public static void BeforeUpdate(Map<Id, Sobject> newMap, Map<Id, Sobject> oldMap) {
        updateVisaOrgpay((List<Visa_Request__c>) newMap.values(),(Map<Id, Visa_Request__c>) oldMap);
        
    }    
    public static void BeforeDelete(Map<Id, Sobject> oldMap) {
        //call before delete actions
    } 
    
    public static void AfterInsert(Map<Id, SObject> newMap){
        //call onAfterInsert delete actions
        
        
    }   
    public static void AfterUpdate(Map<Id, SObject> newMap, Map<Id, Sobject> oldMap){      
        
    }
    
    public static void AfterDelete(Map<Id, Sobject> oldMap) {
    }
    
    
    public static void AfterUnDelete(Map<Id, Sobject> newMap) {
        //call after undelete actions
    } 
    
    public Boolean IsDisabled(){
        return false;
    }
    
    public static void validateContactRegistration(List<Visa_Request__c> triggerNew){
        List<Visa_Request__c> visaReq =  new List<Visa_Request__c>();
        Set<Id> contactSet = new Set<ID>();
        Set<Id> eventIds = new Set<Id>();
        for(Visa_Request__c vReq: triggerNew){
            visaReq.add(vReq);
            eventIds.add(vReq.Event__c);
            contactSet.add(vReq.Contact__c);
            
        }
        
        if(!contactSet.IsEmpty()){
            List<Event_Registrations__c> eventRegistrationList = [SELECT Contact__c,Event__c,Cvent_Registration_Status__c FROM Event_Registrations__c WHERE 
                                                                  Event__c IN :eventIds AND Cvent_Registration_Status__c != 'Cancelled' AND 
                                                                  Contact__c IN :contactSet];
            Map<Id,Set<Id>> eventContactSet =new  Map<Id,Set<Id>>();
            for(Event_Registrations__c er :eventRegistrationList){
                if(!eventContactSet.containsKey(er.Event__c)){
                    eventContactSet.put(er.Event__c,new Set<Id>());
                }
                eventContactSet.get(er.Event__c).add(er.Contact__c);
            }
            for(Visa_Request__c vReq:visaReq){
                if(eventContactSet.containsKey(vReq.Event__c) && eventContactSet.get(vReq.Event__c).contains(vReq.Contact__c)){
                    vReq.Registered__c = TRUE;
                }
                else{
                    vReq.Registered__c = FALSE;
                    vReq.addError('No event registration found');
                }
                
            }
            
        }
    }
    
    public static void contactInsertIfEmailPresent(List<Visa_Request__c> triggerNew){
        ContactInsertUtilityClass uc = new ContactInsertUtilityClass();
        uc.contactInsert(triggerNew);
    }
    
    public static void updateVisaOrgpay(List<Visa_Request__c> newMap,Map<Id, Visa_Request__c> oldMap){
        for(Visa_Request__c visaReq : newMap){
            System.debug('New MAps' +visaReq.Company_or_Organization__c);
            if(string.isNotBlank(visaReq.Company_or_Organization__c) && (visaReq.Accommodation_Paid_by__c == 'Delegate' || visaReq.Accommodation_Paid_by__c == 'Delegate\'s Company') && string.ISBLANK(visaReq.Org_paying_for_your_travel__c)){
                visaReq.Org_paying_for_your_travel__c = visaReq.Company_or_Organization__c;
                
            }
        }    
    }

}