force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Accept_Travel_Fund__c.field-meta.xml
<CustomField>
    <fullName>Accept_Travel_Fund__c</fullName>
    <defaultValue>(&quot;Yes&quot;)</defaultValue>
    <label>Accept Travel Fund</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <inlineHelpText>Indicates if the project has Membership, Crowdfunding (e.g. LFX Funding), or both. Note that a project may have membership requirements that do not have any fees or funding associated with them. In that case, &apos;Membership&apos; is still selected for this field.</inlineHelpText>
    <label>Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Membership</fullName>
            </value>
            <value>
                <fullName>Crowdfunding</fullName>
            </value>
            <value>
                <fullName>Alternate Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TravelFundRequestRestTest.cls
/********************************************************
 * Created by: Martand Atrey @ CloudRoute Solutions
 * Created Date: 14-01-2020.
 * Description: TravelFundRequestRestTest
 * LastModifiedBy: Harshad Kuhite @Proxima
 ********************************************************/
@isTest
public class TravelFundRequestRestTest {
    
    // test setup method
    @testSetup static void setup() {
        Project__c parentProject = new Project__c();
        parentProject.Name = 'Parent Project';
        parentProject.Slug__c = 'test_parent_slug';
        parentProject.Status__c = 'Active';
        parentProject.Funding__c = 'Funded';
        parentProject.Model__c = 'Membership';
        insert parentProject;

        TestDataUtils.createProject(true, 'The Linux Foundation', 'Membership', 'Linux Foundation', 'Planned');

        Event__c evt = TestDataUtils.createEvent(false, 'testEventName', 'Unfunded' , 'Non-LF Event', 'Planned');
        evt.BillFromProject__c = parentProject.Id;
        insert evt; 
    }
    
    // test success Travel Fund Request
    @isTest
    static void sendSuccessRequest() {
        RestResponse res = new RestResponse();
        Event__c evt = [Select Id,Name From Event__c Where Name='testEventName' Limit 1];
        evt.Accept_Travel_Fund__c = 'Yes';
        update evt;

        RestRequest request = new RestRequest();
        request.requestUri ='https://linuxfoundation--stage.cs36.my.salesforce.com/services/apexrest/travelFundRequest/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('{ "event": "' + evt.Id + '","firstName": "Martand", "lastName": "Atrey", "emailAddress": "martand.a+test889@cloudroute.in", "CompanyName": "CloudRoute", "receivedFunds": "No", "socialLink": "testLInk", "reasonToAttend": " TestDesc", "travellingFrom": "INdia", "group": "LGBTQIA+,Woman,Person of Color,Person with Disability,Other", "numOfNights": "2", "estimateCost": "2", "attendingBehalfofComp": "Yes", "writingBlog": "Yes", "otherDescription": "otherDescription", "otherEventName": "otherEventName", "otherEventLocation": "otherEventLocation", "orgPaying": "orgPaying", "expenses": [{ "Name": "Royal Orchid Hotel", "Type": "Hotel", "Value": "500" }, { "Name": "AirAsia", "Type": "Air", "Value": "300" }, { "Name": "Oberoi", "Type": "Hotel", "Value": "150" } ] }');
        RestContext.request = request;
        RestContext.response = res;
        TravelFundRequestRest.processForm();
        System.debug(RestContext.response + '====> res');
     }
    
    // test exception Travel Fund Request
    @isTest
    static void sendErrorRequest() {
        RestResponse res = new RestResponse();
        Event__c evt = [Select Id,Name From Event__c Where Name='testEventName' Limit 1];
        evt.Accept_Travel_Fund__c = 'Yes';
        update evt;

        RestRequest request = new RestRequest();
        request.requestUri ='https://linuxfoundation--stage.cs36.my.salesforce.com/services/apexrest/travelFundRequest/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('{ "event": "' + evt.Id + '","firstName": "Harshad", "lastName": "Kuhite", "emailAddress": "harshad.kuhite", "CompanyName": "Proxima", "receivedFunds": "No", "socialLink": "testLInk", "reasonToAttend": " TestDesc", "travellingFrom": "INdia", "group": "LGBTQ,Woman,Person of Color,Person with Disability,Other", "numOfNights": "2", "estimateCost": "2", "attendingBehalfofComp": "Yes", "writingBlog": "Yes", "otherDescription": "otherDescription", "otherEventName": "otherEventName", "otherEventLocation": "otherEventLocation", "orgPaying": "orgPaying", "expenses": [{ "Name": "Royal Orchid Hotel", "Type": "Hotel", "Value": "500" }, { "Name": "AirAsia", "Type": "Air", "Value": "300" }, { "Name": "Oberoi", "Type": "Hotel", "Value": "150" } ] }');
        RestContext.request = request;
        RestContext.response = res;
        TravelFundRequestRest.processForm();
        System.debug(RestContext.response + '====> res');
    }

    // test Travel Fund Request without Passing Event ID
    @isTest
    static void sendRequestWithoutEventID() {
        RestResponse res = new RestResponse();
        RestRequest request = new RestRequest();
        request.requestUri ='https://linuxfoundation--stage.cs36.my.salesforce.com/services/apexrest/travelFundRequest/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('{ "otherDescription":"Test Description","CompanyName": "CloudRoute", "receivedFunds": "No", "socialLink": "testLInk", "reasonToAttend": " TestDesc", "travellingFrom": "INdia", "group": "LGBTQ,Woman,Person of Color,Person with Disability,Other", "numOfNights": "2", "estimateCost": "2", "attendingBehalfofComp": "Yes", "writingBlog": "Yes", "expenses": [{ "Name": "Royal Orchid Hotel", "Type": "Hotel", "Value": "500" }, { "Name": "AirAsia", "Type": "Air", "Value": "300" }, { "Name": "Oberoi", "Type": "Hotel", "Value": "150" } ] }');
        RestContext.request = request;
        RestContext.response = res;
        TravelFundRequestRest.processForm();
        System.debug(RestContext.response + '====> res');   
    }
    
    // test Travel Fund Request by Passing Event where Accept Travel Fund is False
    @isTest
    static void sendRequestWithEventAcceptTravelFundFalse() {
        Event__c evt = [Select Id,Name From Event__c Where Name='testEventName' Limit 1];
        evt.Accept_Travel_Fund__c = 'False';
        update evt;
		RestResponse res = new RestResponse();
        RestRequest request = new RestRequest();
        request.requestUri ='https://linuxfoundation--stage.cs36.my.salesforce.com/services/apexrest/travelFundRequest/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('{ "event": "' + evt.Id + '","firstName": "Martand", "emailAddress": "martand.a+test889@cloudroute.in", "CompanyName": "CloudRoute", "receivedFunds": "No", "socialLink": "testLInk", "reasonToAttend": " TestDesc", "travellingFrom": "INdia", "group": "LGBTQ,Woman,Person of Color,Person with Disability,Other", "numOfNights": "2", "estimateCost": "2", "attendingBehalfofComp": "Yes", "writingBlog": "Yes", "expenses": [{ "Name": "Royal Orchid Hotel", "Type": "Hotel", "Value": "500" }, { "Name": "AirAsia", "Type": "Air", "Value": "300" }, { "Name": "Oberoi", "Type": "Hotel", "Value": "150" } ] }');
        RestContext.request = request;
        RestContext.response = res;
        TravelFundRequestRest.processForm();
        System.debug(RestContext.response + '====> res');
    }
	
    // test Travel Fund Request by Sending Dummy Event ID
    @isTest
    static void sendRequestWithDummyEventID() {      
		RestResponse res = new RestResponse();
        RestRequest request = new RestRequest();
        request.requestUri ='https://linuxfoundation--stage.cs36.my.salesforce.com/services/apexrest/travelFundRequest/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('{ "event": "dummyeventid","firstName": "Martand", "emailAddress": "martand.a+test889@cloudroute.in", "CompanyName": "CloudRoute", "receivedFunds": "No", "socialLink": "testLInk", "reasonToAttend": " TestDesc", "travellingFrom": "INdia", "group": "LGBTQ,Woman,Person of Color,Person with Disability,Other", "numOfNights": "2", "estimateCost": "2", "attendingBehalfofComp": "Yes", "writingBlog": "Yes", "expenses": [{ "Name": "Royal Orchid Hotel", "Type": "Hotel", "Value": "500" }, { "Name": "AirAsia", "Type": "Air", "Value": "300" }, { "Name": "Oberoi", "Type": "Hotel", "Value": "150" } ] }');
        RestContext.request = request;
        RestContext.response = res;
        TravelFundRequestRest.processForm();
        System.debug(RestContext.response + '====> res');
    }
 
    // test Travel Fund Request without Passing Last Name
    @isTest
    static void sendRequestWithoutLastName() {
        Event__c evt = [Select Id,Name From Event__c Where Name='testEventName' Limit 1];
        evt.Accept_Travel_Fund__c = 'Yes';
        update evt;
		
        RestResponse res = new RestResponse();
		RestRequest request = new RestRequest();
        request.requestUri ='https://linuxfoundation--stage.cs36.my.salesforce.com/services/apexrest/travelFundRequest/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('{ "event": "' + evt.Id + '","firstName": "Martand", "CompanyName": "CloudRoute", "emailAddress": "martand.a+test889@cloudroute.in","receivedFunds": "No", "socialLink": "testLInk", "reasonToAttend": " TestDesc", "travellingFrom": "INdia", "group": "LGBTQ,Woman,Person of Color,Person with Disability,Other", "numOfNights": "2", "estimateCost": "2", "attendingBehalfofComp": "Yes", "writingBlog": "Yes", "expenses": [{ "Name": "Royal Orchid Hotel", "Type": "Hotel", "Value": "500" }, { "Name": "AirAsia", "Type": "Air", "Value": "300" }, { "Name": "Oberoi", "Type": "Hotel", "Value": "150" } ] }');
        RestContext.request = request;
        RestContext.response = res;
        TravelFundRequestRest.processForm();
        System.debug(RestContext.response + '====> res');
    }

    // test Travel Fund Request without Passing Email Address
    @isTest
    static void sendRequestWithoutEmailAddress() {
 		Event__c evt = [Select Id,Name From Event__c Where Name='testEventName' Limit 1];
        evt.Accept_Travel_Fund__c = 'Yes';
        update evt;
		RestResponse res = new RestResponse();
        RestRequest request = new RestRequest();
        request.requestUri ='https://linuxfoundation--stage.cs36.my.salesforce.com/services/apexrest/travelFundRequest/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('{ "event": "' + evt.Id + '","firstName": "Martand", "CompanyName": "CloudRoute", "lastName": "Atrey","receivedFunds": "No", "socialLink": "testLInk", "reasonToAttend": " TestDesc", "travellingFrom": "INdia", "group": "LGBTQ,Woman,Person of Color,Person with Disability,Other", "numOfNights": "2", "estimateCost": "2", "attendingBehalfofComp": "Yes", "writingBlog": "Yes", "expenses": [{ "Name": "Royal Orchid Hotel", "Type": "Hotel", "Value": "500" }, { "Name": "AirAsia", "Type": "Air", "Value": "300" }, { "Name": "Oberoi", "Type": "Hotel", "Value": "150" } ] }');
        RestContext.request = request;
        RestContext.response = res;
        TravelFundRequestRest.processForm();
        System.debug(RestContext.response + '====> res');
    }
}