force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <label>Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Netsuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_ID__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Netsuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Netsuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Sugar_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Sugar_Event_ID__c</fullName>
    <externalId>true</externalId>
    <label>Sugar Event ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/Product_Details__c.object-meta.xml
<CustomObject>
    <label>Product Details</label>
    <nameField>
        <label>Product Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Details__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Product Details</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Error__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Error__c</fullName>
    <label>NetSuite Error</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Netsuite_ID__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_ID__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>NS Item ID</inlineHelpText>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Name_Override__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Name_Override__c</fullName>
    <label>NetSuite Name Override</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NetSuite_Sync__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NetSuite Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Income_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Income_GL_Account__c</fullName>
    <label>NS Income GL Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Income_GL_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
            <value>
                <fullName>Straight Line</fullName>
                <isActive>false</isActive>
                <label>Straight Line</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Skip_60_Char_Limit__c.field-meta.xml
<CustomField>
    <fullName>Skip_60_Char_Limit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip 60 Char Limit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Details__c/fields/Tax_Class__c.field-meta.xml
<CustomField>
    <fullName>Tax_Class__c</fullName>
    <defaultValue>&quot;T1&quot;</defaultValue>
    <label>Tax Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Details__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/NetSuite_ID__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_ID__c</fullName>
    <label>NetSuite ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product_Details__c.field-meta.xml
<CustomField>
    <fullName>Product_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Details</label>
    <referenceTo>Product_Details__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Product_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Deferred_Revenue_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>284</fullName>
        <label>Deferred Revenue : Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>282</fullName>
        <label>Deferred Revenue : Deferred Revenue - Membership</label>
    </customValue>
    <customValue>
        <fullName>4494</fullName>
        <label>Deferred Revenue : Deferred Revenue - Directed Funds</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Other</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Membership</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Membership</label>
    </customValue>
    <masterLabel>NetSuite Deferred Revenue Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NetSuite_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Events</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Training</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Training (Linux Labs)</label>
    </customValue>
    <masterLabel>NetSuite Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CloneEvents.cls
//////////// TEST CLASS - CloneEvents_Test ////////////////

global with sharing class CloneEvents{
    @AuraEnabled
    WebService static String clone_method(Id evtId){
    
        //Id evnt_Id = Id.valueOf(evtId);
        String clonedEvt_Id;
        Event__c eventRecordToClone = new Event__c();
        Event__c clonedEvent = new Event__c();
        List<Product_Details__c> clonedProdDetailList = new List<Product_Details__c>();
        
        // FETCH ALL FIELD FROM EVENT
        Map<String, Schema.SObjectField> schemaFieldMapEVENT = Schema.SObjectType.Event__c.fields.getMap();
        List<String> listOfEventFieldNames = new List<String>();
        for(String sso : schemaFieldMapEVENT.keyset()){
           listOfEventFieldNames.add(sso);
        }
        String eventFieldNames = String.join(listOfEventFieldNames,',');
        // FETCH ALL FIELD FROM PRODUCT DETAIL
        Map<String, Schema.SObjectField> schemaFieldMapProductDetail = Schema.SObjectType.Product_Details__c.fields.getMap();
        List<String> listOfproDetailFieldNames = new List<String>();
        for(String sso : schemaFieldMapProductDetail.keyset()){
           listOfproDetailFieldNames.add(sso);
        }
        
        String proDetailFieldNames = String.join(listOfproDetailFieldNames, ',');
        String qury;                                                                         
        
        qury = 'SELECT '+ eventFieldNames + ' , (Select '+ proDetailFieldNames +' FROM Product_Details__r WHERE Status__c != \'Inactive\') FROM Event__c WHERE Id = :evtId';
        
        system.debug('____qury___'+qury);
        
        if(qury!=null || qury!='')
            eventRecordToClone = Database.query(qury);
            
        system.debug('___eventRecordToClone____'+eventRecordToClone);
        
        try{
            if(eventRecordToClone!=null){
                clonedEvent = eventRecordToClone.clone(false, false, false, false);
                clonedEvent.Event_Name__c = eventRecordToClone.Event_Name__c + ' - Clone';
                clonedEvent.Name = eventRecordToClone.Name + ' - Clone';  
                clonedEvent.Status__c = 'Planned';    
                clonedEvent.Netsuite_Sync__c=False;   
                clonedEvent.NetSuite_Class__c='';
                clonedEvent.Job_Code__c='';
                clonedEvent.NS_Department__c='';
                clonedEvent.NS_Deferred_Revenue_Account__c='';
                clonedEvent.NS_Income_GL_Account__c='';
                clonedEvent.NS_Revenue_Schedule__c='';
                clonedEvent.Sugar_Event_ID__c = null;
                clonedEvent.Email_Sent__c = false;
                //don't copy any fields that starts with Cvent_Event_
                for(string fieldName : schemaFieldMapEVENT.keyset()){
                    system.debug('Processing record '+fieldName );                    
                    if(fieldName.startsWithIgnoreCase('Cvent_Event_') && schemaFieldMapEVENT.get(fieldName).getDescribe().isUpdateable())
                    {
                        if(schemaFieldMapEVENT.get(fieldName).getDescribe().getType() == Schema.DisplayType.BOOLEAN)
                            clonedEvent.put(fieldName,false);
                        else
                         clonedEvent.put(fieldName,null);
                    }
                   
                }
            }                               
            
            system.debug('__before___clonedEvent___'+clonedEvent);
            insert clonedEvent;
            system.debug('__after___clonedEvent___'+clonedEvent);
            
            if(eventRecordToClone.Product_Details__r.size()>0){
                for(Product_Details__c pd : eventRecordToClone.Product_Details__r){
                    Product_Details__c clonedProd = new Product_Details__c();
                    clonedProd = pd.clone(false,false,false,false);
                    clonedProd.Event__c = clonedEvent.Id;
                    clonedProd.Status__c = 'Inactive';
                    clonedProd.NetSuite_Error__c= '';
                    clonedProd.NetSuite_Class__c= '';
                    clonedProd.Job_Code__c= '';
                    clonedProd.NS_Department__c= '';
                    clonedProd.NS_Deferred_Revenue_Account__c= '';
                    clonedProd.NS_Income_GL_Account__c= '';
                    clonedProd.NS_Revenue_Schedule__c= '';
                    clonedProd.NetSuite_Name_Override__c= '';
                    clonedProd.Tax_Class__c= '';
                    clonedProd.Netsuite_ID__c= '';
                    clonedProd.Skip_60_Char_Limit__c = true;
                    clonedProd.NetSuite_Sync__c=False;
                    clonedProdDetailList.add(clonedProd);
                }
            }
            
            if(clonedProdDetailList!=null && clonedProdDetailList.size()>0)
                insert clonedProdDetailList;
                
            system.debug('____clonedProdDetailList____'+clonedProdDetailList);
            system.debug('____clonedEvent__Id___'+clonedEvent.Id);
        }
        Catch(Exception ae){ 
            system.debug('In exception' + ae.getMessage()); 
              clonedEvt_Id  = ae.getMessage();
            return clonedEvt_Id;
        }        
        clonedEvt_Id= String.valueOf(clonedEvent.Id);
            
        return clonedEvt_Id;
    }
    
}