force-app/main/default/objects/EMS__c/EMS__c.object-meta.xml
<CustomObject>
    <label>EMS</label>
    <nameField>
        <label>EMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS__c/fields/EMS_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Number__c</fullName>
    <label>EMS Number</label>
    <length>31</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>EMS</relationshipLabel>
    <relationshipName>EMS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Netsuite_Job_Code_Error__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Job_Code_Error__c</fullName>
    <label>Netsuite Job Code Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Netsuite_Job_Code_Id__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Job_Code_Id__c</fullName>
    <label>Netsuite Job Code Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/NS_Class__c.field-meta.xml
<CustomField>
    <fullName>NS_Class__c</fullName>
    <defaultValue>&quot;3&quot;</defaultValue>
    <label>NS Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <defaultValue>&quot;284&quot;</defaultValue>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <defaultValue>&quot;2&quot;</defaultValue>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <defaultValue>&quot;6&quot;</defaultValue>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Revenue_Schedule</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EMS__c/fields/SubsidiaryID__c.field-meta.xml
<CustomField>
    <fullName>SubsidiaryID__c</fullName>
    <formula>Bill_From__r.Subsidiary_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SubsidiaryID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Endpoints__c/Endpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Endpoints</label>
</CustomObject>

force-app/main/default/objects/Endpoints__c/fields/Nlauth_Account__c.field-meta.xml
<CustomField>
    <fullName>Nlauth_Account__c</fullName>
    <label>Nlauth_Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Endpoints__c/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <label>Realm</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Endpoints__c/fields/Script_Id__c.field-meta.xml
<CustomField>
    <fullName>Script_Id__c</fullName>
    <label>Script Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/EMS_Number__c.field-meta.xml
<CustomField>
    <fullName>EMS_Number__c</fullName>
    <label>EMS Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Job_Code__c.field-meta.xml
<CustomField>
    <fullName>Job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Deferred_Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>NS_Deferred_Revenue_Account__c</fullName>
    <label>NS Deferred Revenue Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Deferred_Revenue_Account</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/NS_Revenue_Schedule__c.field-meta.xml
<CustomField>
    <fullName>NS_Revenue_Schedule__c</fullName>
    <label>NS Revenue Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>Straight Line</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>Directed Fund</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/job_Code__c.field-meta.xml
<CustomField>
    <fullName>job_Code__c</fullName>
    <label>Job Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NetSuite_Class__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Class__c</fullName>
    <label>NetSuite Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/NS_Department__c.field-meta.xml
<CustomField>
    <fullName>NS_Department__c</fullName>
    <label>NS Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NetSuite_Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Subsidiary_ID__c.field-meta.xml
<CustomField>
    <fullName>Subsidiary_ID__c</fullName>
    <label>Subsidiary ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/NetSuite_Deferred_Revenue_Account.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>284</fullName>
        <label>Deferred Revenue : Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>282</fullName>
        <label>Deferred Revenue : Deferred Revenue - Membership</label>
    </customValue>
    <customValue>
        <fullName>4494</fullName>
        <label>Deferred Revenue : Deferred Revenue - Directed Funds</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Other</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Other</label>
    </customValue>
    <customValue>
        <fullName>Deferred Revenue - Membership</fullName>
        <isActive>false</isActive>
        <label>Deferred Revenue - Membership</label>
    </customValue>
    <masterLabel>NetSuite Deferred Revenue Account</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NetSuite_Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Events</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Sales</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Training</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Training (Linux Labs)</label>
    </customValue>
    <masterLabel>NetSuite Department</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/NetSuite_Revenue_Schedule.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>6</fullName>
        <label>Straight Line</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>Directed Fund</label>
    </customValue>
    <customValue>
        <fullName>7164</fullName>
        <label>CP Services</label>
    </customValue>
    <masterLabel>NetSuite Revenue Schedule</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EMSCodeHelper.cls
public class EMSCodeHelper implements Queueable, Database.AllowsCallouts {
    public String recordId;
    public EMS__c emsRecord;
    
    public static Endpoints__c settings{
        get{
            if(settings == null){
                List<Endpoints__c> endPointObj = new List<Endpoints__c>([SELECT Name, Endpoint__c, Password__c, User_Id__c,
                 Nlauth_Account__c, Access_Token__c, Consumer_Key__c, Consumer_Secret__c, Realm__c, Token_Secret__c, Script_Id__c
                 FROM Endpoints__c WHERE name = 'For EMS Code To NS']);         
                if (endPointObj.size() > 0) {
                    settings = endPointObj[0];
                }
            }
            return settings;
        }
        set;
    }

    public EMSCodeHelper(String id){
        recordId = id;
        List<EMS__c> emsList = [SELECT Id, EMS_Number__c, Netsuite_Job_Code_Id__c, SubsidiaryID__c, NS_Class__c, Netsuite_Job_Code_Error__c, Event__c,
         Event__r.BillFromProject__r.Subsidiary_ID__c, Event__r.BillFromProject__r.NetSuite_Class__c
         FROM EMS__c WHERE Id =: recordId];
        if (emsList.size() > 0) {
            emsRecord = emsList[0];
        }
    }

    public void execute(QueueableContext context) {
        if (emsRecord != null) {
            try{
                if (settings != null) {
                String body = createRequestJSON(); // create json body
                
                HttpRequest httpRequestObject = new HttpRequest();
                httpRequestObject.setMethod('POST');

                if(String.isNotBlank(body)){
                    httpRequestObject.setBody(body);
                }
                httpRequestObject.setHeader('Content-Type', 'application/json');

                Map<String, String> urlParams = new Map<String, String>();
                urlParams.put('script', settings.Script_Id__c);

                httpRequestObject = NetSuiteIntegrationHelper.addEndpointAndAuthHeader(httpRequestObject, settings, urlParams);

                Http http = new Http();
                HttpResponse response = http.send(httpRequestObject);

                System.debug('Response ==>' + response.getBody());
                emsRecord.NetSuite_Job_Code_Error__c = null;
                if(response.getStatusCode() == 200 || response.getStatusCode() == 201) {
                    ResponseWrapper successWrapper = (ResponseWrapper)JSON.deserialize(response.getBody() , ResponseWrapper.class);
                    System.debug(successWrapper);
                    if (successWrapper.success == true && successWrapper.id != null) {
                        emsRecord.NetSuite_Job_Code_Id__c = successWrapper.id;
                        if (emsRecord.Event__c != null) {
                            Event__c emsEvent = [SELECT Id, Job_Code__c, NS_Department__c, NS_Deferred_Revenue_Account__c, NS_Revenue_Schedule__c   FROM Event__c WHERE Id =: emsRecord.Event__c];
                            emsEvent.Job_Code__c = successWrapper.id;
                            emsEvent.EMS_Number__c = emsRecord.EMS_Number__c;
                            emsEvent.NS_Department__c = '2'; //NS Department = Events
                            emsEvent.NS_Deferred_Revenue_Account__c = '284'; //NS Deferred Revenue Account = Deferred Revenue : Deferred Revenue - Other
                            emsEvent.NS_Revenue_Schedule__c = '6'; //NS Revenue Schedule = Straight Line
                            update emsEvent;
                        }
                    }
                    else {
                        emsRecord.NetSuite_Job_Code_Error__c ='NetSuite Job Code Sync Failed: ' + response.getBody();
                    }
                }else{
                    ResponseErrorWrapper errorWrapper = (ResponseErrorWrapper)JSON.deserialize(response.getBody() , ResponseErrorWrapper.class);
                    System.debug(errorWrapper);
                    emsRecord.NetSuite_Job_Code_Error__c ='NetSuite Job Code Sync Failed: ' + errorWrapper.error.message;
                }
                update emsRecord;

                }
            }
            catch (Exception ex) {
                emsRecord.NetSuite_Job_Code_Error__c = 'Exception Caught: ' + ex.getMessage();
                update emsRecord;
            }
        }
    }
    
    public String createRequestJSON() {
        Map<String, Object> jsonMappingObject = new Map<String, Object>();

        jsonMappingObject.put('name', emsRecord.EMS_Number__c);
        jsonMappingObject.put('subsidiary', emsRecord.Event__r.BillFromProject__r.Subsidiary_ID__c);
        jsonMappingObject.put('class', emsRecord.Event__r.BillFromProject__r.NetSuite_Class__c);
        jsonMappingObject.put('jobType', 7); //'Project Event'); 

        String jsonString = JSON.serialize(jsonMappingObject);       
        return jsonString;
    }


    public class ResponseWrapper {
        public String id {get; set;}
        public Boolean success {get; set;}
        public String error {get; set;}
    }

    public class ResponseErrorWrapper {
        public ResponseError error {get; set;}
    }

    public class ResponseError {
        public String code {get; set;}
        public String message {get; set;}
    }
}