force-app/main/default/objects/EMS__c/EMS__c.object-meta.xml
<CustomObject>
    <label>EMS</label>
    <nameField>
        <label>EMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EMS__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>EMS (Bill To Account)</relationshipLabel>
    <relationshipName>EMS1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>EMS</relationshipLabel>
    <relationshipName>EMS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EMS__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Off</fullName>
            </value>
            <value>
                <fullName>Retainer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>This custom object contains all information related to LF Events, Project Event and LF managed events.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/BillFromProject__c.field-meta.xml
<CustomField>
    <fullName>BillFromProject__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bill From Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>Project__c.Funding__c</field>
            <operation>equals</operation>
            <value>Funded</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LF Event</fullName>
            </value>
            <value>
                <fullName>Project Event</fullName>
            </value>
            <value>
                <fullName>3rd Party Event</fullName>
            </value>
            <value>
                <fullName>Non-LF Event</fullName>
            </value>
            <value>
                <fullName>Migrated Data</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>Event_Location_Country__c</fullName>
    <label>Event Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bonaire S.E.S.</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Custom object for all Linux Foundation projects.</description>
    <label>Project</label>
    <nameField>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Indicates the type of entity the project is established as. If you&apos;re debating between Unofficial Subproject and Subproject, note that Subproject is the more common answer.</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subproject</fullName>
            </value>
            <value>
                <fullName>Incorporated Entity</fullName>
            </value>
            <value>
                <fullName>Series LLC</fullName>
            </value>
            <value>
                <fullName>Unofficial Subproject</fullName>
            </value>
            <value>
                <fullName>Internal Allocation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <inlineHelpText>Indicates if this project has its own funding, if it does not have funding, or if it gets its funding from its Parent Project. If this project gets funding from its grandparent project, select Unfunded.</inlineHelpText>
    <label>Funding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Unfunded</fullName>
            </value>
            <value>
                <fullName>Supported by Parent Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Parent_Project__c.field-meta.xml
<CustomField>
    <fullName>Parent_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Incorporated Entity, Series LLC, or Subproject with which this project is associated. For example, a Series LLC entity may have a legal parent of LF Projects, LLC, but be associated with the parent project LF AI Foundation.</inlineHelpText>
    <label>Parent Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Child Projects</relationshipLabel>
    <relationshipName>Child_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <description>Back-end field needed to indicate whether this project has any child projects nested below it (via the Parent Project lookup field). If so, this is a Project Group. If not, this is a Project. This field is automatically updated; users should not set this field manually.</description>
    <inlineHelpText>Back-end field needed to indicate whether this project has any child projects nested below it. If so, this is a Project Group. If not, this is a Project.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
                <default>true</default>
                <label>Project</label>
            </value>
            <value>
                <fullName>Project Group</fullName>
            </value>
            <value>
                <fullName>LF Supported</fullName>
                <isActive>false</isActive>
                <label>LF Supported</label>
            </value>
            <value>
                <fullName>Member Project</fullName>
                <isActive>false</isActive>
                <label>Member Project</label>
            </value>
            <value>
                <fullName>Member Sub-Project</fullName>
                <isActive>false</isActive>
                <label>Member Sub-Project</label>
            </value>
            <value>
                <fullName>Non-Member Project</fullName>
                <isActive>false</isActive>
                <label>Non-Member Project</label>
            </value>
            <value>
                <fullName>Preformation</fullName>
                <isActive>false</isActive>
                <label>Preformation</label>
            </value>
            <value>
                <fullName>Public Domain Project</fullName>
                <isActive>false</isActive>
                <label>Public Domain Project</label>
            </value>
            <value>
                <fullName>Standalone</fullName>
                <isActive>false</isActive>
                <label>Standalone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>The slug is used for external integrations, like Auto Join, the PCC, and Insights. The value of this field should never change once it&apos;s set.</inlineHelpText>
    <label>Slug</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sunset</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventTriggerHandlerTest.cls
/********************************************************
 * Created by: Martand Atrey @ CloudRoute Solutions
 * Created Date: 15-11-2019.
 * Description: EventTriggerHandlerTest
 * Modified - April 2021 @Cloudroute Solutions
 ********************************************************/
@isTest
public class EventTriggerHandlerTest{
	/**
	 * TestSetup inserting required data for test class
	 */
	@TestSetup
	static void createTestData(){
		Project__c project = TestDataUtils.createProject(true, 'The Linux Foundation', 'Event', 'Directed Fund', 'Planned');
		project.Status__c = 'Active';
		project.Funding__c = 'Funded';
		update project;
	}

	/**
	 * Test UseCase for Not Creating EMS On LF Event Insertion
	 */
	@isTest
	public static void noEMSCreationForLFEvent_Test(){

		Test.startTest();
		Project__c project = [SELECT Id
		                      FROM Project__c
		                      WHERE Name = 'The Linux Foundation'];
		Event__c evt = TestDataUtils.createEvent(false, 'Test Event', 'Unfunded', 'LF Event', 'Planned');
		evt.BillFromProject__c = project.Id;
        evt.Event_Location_Country__c = 'United Kingdom';
		insert evt;
		Test.stopTest();

		//Asserts
		System.assertEquals(0, [SELECT count()
		                        From EMS__c ],'No Record should return');
		delete evt;
	}

	/**
	 * Test UseCase for Creating EMS On Project Event Insertion
	 */
	@isTest
	public static void emsCreationForProjectEventOnInsert_Test(){
		Test.startTest();
		Project__c project = [SELECT Id
		                      FROM Project__c
		                      WHERE Name = 'The Linux Foundation'];
		Event__c evt = new Event__c(Name = 'Test Event', Category__c = 'Project Event');
		evt.BillFromProject__c = project.Id;
        evt.Event_Location_Country__c = 'United Kingdom';
		insert evt;
		Test.stopTest();
		System.assertEquals(1, [SELECT count()
		                        From EMS__c ],'List must contain 1 record');
	}

	/**
	 * test method for automateEMSCreation on Updation of event
	 */
	@isTest
	public static void automateEMSCreationOnUpdate_Test(){
		Test.startTest();
		Project__c project = [SELECT Id
		                      FROM Project__c
		                      WHERE Name = 'The Linux Foundation'];
		Event__c evt = TestDataUtils.createEvent(false, 'Test Event', 'Unfunded', 'LF Event', 'Planned');
		evt.BillFromProject__c = project.Id;
        evt.Event_Location_Country__c = 'United Kingdom';
		insert evt;
		evt.Category__c = 'Project Event';
		update evt;
		Test.stopTest();
		System.assertEquals(1, [SELECT count()
		                        From EMS__c ],'List must contain 1 record');
	}

	/**
	 * test method for updateEms
	 */
	@isTest
	public static void updateEms_Test(){
		Test.startTest();
		ID projectAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Project Account').getRecordTypeId();
		Account account = new Account(Name = 'The Linux Foundation', RecordTypeId = projectAccountRecordTypeId);
		insert account;
		Project__c parentProject = [SELECT Id
		                            FROM Project__c
		                            WHERE Name = 'The Linux Foundation'];
		parentProject.Project_Type__c = 'Project Group';
        parentProject.Slug__c = 'parentproject';
		update parentProject;

		Project__c project = TestDataUtils.createProject(false, 'TestProject', 'Event', 'Directed Fund', 'Planned');
        project.Slug__c = 'test_slug';
		project.Status__c = 'Active';
		project.Funding__c = 'Funded';
		project.Parent_Project__c = parentProject.Id;
		insert project;

		Event__c evt = new Event__c(Name = 'Test Ecvent', Category__c = 'Project Event');
		evt.BillFromProject__c = project.Id;
        evt.Event_Location_Country__c = 'United States';
		insert evt;
		evt.BillFromProject__c = parentProject.Id;
		update evt;
		Test.stopTest();
		//AssertsTest.stopTest();
		System.assertEquals(account.Id, [SELECT Bill_To_Account__c
		                                 From EMS__c
		                                 LIMIT 1].Bill_To_Account__c,'AccountId should be \''+account.Id+'\'');
	}
}